### ISSUE TITLE
Error using Anowon's card draw ability.

### ISSUE THREAD

**Issue by jayzz911** [magefree/mage#10192]
Had an error in a commander game. I had anowon on the field and a mindcrank. Attacked one of my opponents and progenitus got milled. I'm not sure if that's why it happened but here is the stacktrace regardless.

Stacktrace:
FATAL 2023-04-09 00:28:15,486 Game exception gameId: fd75425a-110c-4d40-baa2-60a66b4f0964                                =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.SortedSet
	at mage.abilities.common.DrawCardWatcher.watch(DrawCardTriggeredAbility.java:118)
	at mage.watchers.Watchers.watch(Watchers.java:34)
	at mage.game.GameState.handleEvent(GameState.java:833)
	at mage.game.GameImpl.fireEvent(GameImpl.java:3142)
	at mage.actions.MageDrawAction.drawCard(MageDrawAction.java:93)
	at mage.actions.MageDrawAction.doAction(MageDrawAction.java:58)
	at mage.game.GameImpl.doAction(GameImpl.java:3461)
	at mage.players.PlayerImpl.drawCards(PlayerImpl.java:676)
	at mage.cards.a.AnowonTheRuinThiefEffect.apply(AnowonTheRuinThief.java:137)
	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:151)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:86)
	at mage.game.GameImpl.resolve(GameImpl.java:1657)
	at mage.game.GameImpl.playPriority(GameImpl.java:1583)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:125)
	at mage.game.GameImpl.playTurn(GameImpl.java:1056)
	at mage.game.GameImpl.play(GameImpl.java:966)
	at mage.game.GameImpl.start(GameImpl.java:942)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2023-04-09 00:28:15,501 
Stack before error 0: 

                                                                  =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
FATAL 2023-04-09 00:57:42,219 Game exception gameId: fd75425a-110c-4d40-baa2-60a66b4f0964                                =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.SortedSet
	at mage.abilities.common.DrawCardWatcher.watch(DrawCardTriggeredAbility.java:118)
	at mage.watchers.Watchers.watch(Watchers.java:34)
	at mage.game.GameState.handleEvent(GameState.java:833)
	at mage.game.GameImpl.fireEvent(GameImpl.java:3142)
	at mage.actions.MageDrawAction.drawCard(MageDrawAction.java:93)
	at mage.actions.MageDrawAction.doAction(MageDrawAction.java:58)
	at mage.game.GameImpl.doAction(GameImpl.java:3461)
	at mage.players.PlayerImpl.drawCards(PlayerImpl.java:676)
	at mage.cards.a.AnowonTheRuinThiefEffect.apply(AnowonTheRuinThief.java:137)
	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:151)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:86)
	at mage.game.GameImpl.resolve(GameImpl.java:1657)
	at mage.game.GameImpl.playPriority(GameImpl.java:1583)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:125)
	at mage.game.GameImpl.playTurn(GameImpl.java:1056)
	at mage.game.GameImpl.playExtraTurns(GameImpl.java:1015)
	at mage.game.GameImpl.play(GameImpl.java:970)
	at mage.game.GameImpl.start(GameImpl.java:942)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2023-04-09 00:57:42,220 
Stack before error 1: 
stack ability (Whenever one or more Rogues you control deal combat damage to a player, that player mills a card for each 1 damage dealt to them. If the player mills at least one creature card this way, you draw a card.)
 =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
FATAL 2023-04-09 00:58:32,399 Game exception gameId: fd75425a-110c-4d40-baa2-60a66b4f0964                                =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.SortedSet
	at mage.abilities.common.DrawCardWatcher.watch(DrawCardTriggeredAbility.java:118)
	at mage.watchers.Watchers.watch(Watchers.java:34)
	at mage.game.GameState.handleEvent(GameState.java:833)
	at mage.game.GameImpl.fireEvent(GameImpl.java:3142)
	at mage.actions.MageDrawAction.drawCard(MageDrawAction.java:93)
	at mage.actions.MageDrawAction.doAction(MageDrawAction.java:58)
	at mage.game.GameImpl.doAction(GameImpl.java:3461)
	at mage.players.PlayerImpl.drawCards(PlayerImpl.java:676)
	at mage.cards.a.AnowonTheRuinThiefEffect.apply(AnowonTheRuinThief.java:137)
	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:151)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:86)
	at mage.game.GameImpl.resolve(GameImpl.java:1657)
	at mage.game.GameImpl.playPriority(GameImpl.java:1583)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:125)
	at mage.game.GameImpl.playTurn(GameImpl.java:1056)
	at mage.game.GameImpl.playExtraTurns(GameImpl.java:1015)
	at mage.game.GameImpl.play(GameImpl.java:970)
	at mage.game.GameImpl.start(GameImpl.java:942)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2023-04-09 00:58:32,400 
Stack before error 3: 
stack ability (Whenever an opponent loses life, that player mills that many cards.)
stack ability (Whenever one or more Rogues you control deal combat damage to a player, that player mills a card for each 1 damage dealt to them. If the player mills at least one creature card this way, you draw a card.)
stack ability (Whenever an opponent loses life, that player mills that many cards.)
 =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
FATAL 2023-04-09 00:59:21,294 Game exception gameId: fd75425a-110c-4d40-baa2-60a66b4f0964                                =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
java.lang.ClassCastException
INFO  2023-04-09 00:59:21,295 
Stack before error 3: 
stack ability (Whenever an opponent loses life, that player mills that many cards.)
stack ability (Whenever an opponent loses life, that player mills that many cards.)
stack ability (Whenever one or more Rogues you control deal combat damage to a player, that player mills a card for each 1 damage dealt to them. If the player mills at least one creature card this way, you draw a card.)
 =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
FATAL 2023-04-09 00:59:34,745 Game exception gameId: fd75425a-110c-4d40-baa2-60a66b4f0964                                =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
java.lang.ClassCastException
INFO  2023-04-09 00:59:34,746 
Stack before error 4: 
stack ability (Whenever one or more Rogues you control deal combat damage to a player, that player mills a card for each 1 damage dealt to them. If the player mills at least one creature card this way, you draw a card.)
stack ability (Whenever an opponent loses life, that player mills that many cards.)
stack ability (Whenever an opponent loses life, that player mills that many cards.)
stack ability (Whenever an opponent loses life, that player mills that many cards.)
 =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
FATAL 2023-04-09 01:01:09,049 Game exception gameId: fd75425a-110c-4d40-baa2-60a66b4f0964                                =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority 
java.lang.ClassCastException
INFO  2023-04-09 01:01:09,049 
Stack before error 1: 
stack ability (Whenever one or more Rogues you control deal combat damage to a player, that player mills a card for each 1 damage dealt to them. If the player mills at least one creature card this way, you draw a card.)
 =>[GAME fd75425a-110c-4d40-baa2-60a66b4f0964] GameImpl.playPriority

**Comment by JayDi85** [comment]
Fixed in f7b32cadd72e445e533dcf0ee561e74eb51f2cbc
