### ISSUE TITLE
Cannot connect to local server after GNU Linux/Debian system update + app update

### ISSUE THREAD

**Issue by mbideau** [magefree/mage#10297]
Hi,

Thank you for this amazing project that already gave me hundred of ours of joy (and pain) :smiley: 

The exception I get when I try to connect to local server through the mage-client :

```
❯ INFO  2023-04-30 09:56:17,089 Starting MAGE client version 1.4.52-V3-beta8 (build: 2023-04-21 07:41)                     =>[main] MageFrame.main 
INFO  2023-04-30 09:56:17,091 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2023-04-30 09:56:17,092 Default charset: UTF-8                                                                     =>[main] MageFrame.main 
INFO  2023-04-30 09:56:17,249 Custom (or bundled) Java certificate file (cacerts) file found                             =>[AWT-EventQueue-0] MageFrame.<init> 
FATAL 2023-04-30 09:56:17,456 MAGE Client UI error                                                                       =>[Basic L&F File Loading Thread] ..truncated..
INFO  2023-04-30 09:56:18,097 Using GUI theme: Default                                                                   =>[AWT-EventQueue-0] PreferencesDialog.getCurrentTheme 
INFO  2023-04-30 09:56:18,111 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-04-30 09:56:18,537 Images: search broken files...                                                             =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2023-04-30 09:56:18,789 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2023-04-30 09:56:19,938 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2023-04-30 09:56:19,978 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2023-04-30 09:56:19,987 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2023-04-30 09:56:19,989 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2023-04-30 09:56:19,990 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
WARN  2023-04-30 09:56:20,456 SystemTray is not supported                                                                =>[AWT-EventQueue-0] MageTray.install 
INFO  2023-04-30 09:56:20,631 Client start up time: 3 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2023-04-30 09:56:57,943 Connect: connecting to server localhost:17171                                              =>[SwingWorker-pool-3-thread-3] SessionImpl$5.work 
WARN  2023-04-30 09:56:58,014 Cannot connect                                                                             =>[SwingWorker-pool-3-thread-2] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:429)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://192.168.121.1:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=java]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createClientSocket(SocketClientInvoker.java:175)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1220)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
Caused by: java.lang.ExceptionInInitializerError
	at org.jboss.remoting.serialization.impl.java.JavaSerializationManager.createOutput(JavaSerializationManager.java:63)
	at org.jboss.remoting.marshal.serializable.SerializableMarshaller.getMarshallingStream(SerializableMarshaller.java:89)
	at org.jboss.remoting.marshal.serializable.SerializableMarshaller.getMarshallingStream(SerializableMarshaller.java:72)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createOutputStream(ClientSocketWrapper.java:230)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createStreams(ClientSocketWrapper.java:188)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.<init>(ClientSocketWrapper.java:67)
	... 23 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private void java.io.ObjectOutputStream.clear() accessible: module java.base does not "opens java.io" to unnamed module @4015e7ec
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.jboss.remoting.serialization.impl.java.ClearableObjectOutputStream.getDeclaredMethod(ClearableObjectOutputStream.java:88)
	at org.jboss.remoting.serialization.impl.java.ClearableObjectOutputStream.<clinit>(ClearableObjectOutputStream.java:53)
	... 29 more
INFO  2023-04-30 09:56:58,033 Disconnecting DONE                                                                         =>[SwingWorker-pool-3-thread-2] SessionImpl.disconnect 
INFO  2023-04-30 09:56:58,034 Disconnected from user mode                                                                =>[SwingWorker-pool-3-thread-2] MageFrame.disconnected 
ERROR 2023-04-30 09:57:20,266 java.io.IOException: Server returned HTTP response code: 403 for URL: http://XMage.de/files/server-list.txt =>[AWT-EventQueue-0] ConnectDialog.chooseAndSetServerSettingsFromOther 
java.io.IOException: Server returned HTTP response code: 403 for URL: http://XMage.de/files/server-list.txt
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at mage.client.dialog.ConnectDialog.chooseAndSetServerSettingsFromOther(ConnectDialog.java:153)
	at mage.client.dialog.ConnectDialog.btnFindOtherActionPerformed(ConnectDialog.java:844)
	at mage.client.dialog.ConnectDialog.access$1200(ConnectDialog.java:35)
	at mage.client.dialog.ConnectDialog$13.actionPerformed(ConnectDialog.java:413)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:174)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:89)
	at mage.client.dialog.ConnectDialog.showDialog(ConnectDialog.java:83)
	at mage.client.MageFrame.lambda$new$2(MageFrame.java:359)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
ERROR 2023-04-30 09:57:30,339 java.io.IOException: Server returned HTTP response code: 403 for URL: http://XMage.de/files/server-list.txt =>[AWT-EventQueue-0] ConnectDialog.chooseAndSetServerSettingsFromOther 
java.io.IOException: Server returned HTTP response code: 403 for URL: http://XMage.de/files/server-list.txt
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at mage.client.dialog.ConnectDialog.chooseAndSetServerSettingsFromOther(ConnectDialog.java:153)
	at mage.client.dialog.ConnectDialog.btnFindOtherActionPerformed(ConnectDialog.java:844)
	at mage.client.dialog.ConnectDialog.access$1200(ConnectDialog.java:35)
	at mage.client.dialog.ConnectDialog$13.actionPerformed(ConnectDialog.java:413)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:174)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:89)
	at mage.client.dialog.ConnectDialog.showDialog(ConnectDialog.java:83)
	at mage.client.MageFrame.lambda$new$2(MageFrame.java:359)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO  2023-04-30 09:57:36,099 Connect: connecting to server localhost:17171                                              =>[SwingWorker-pool-3-thread-5] SessionImpl$5.work 
WARN  2023-04-30 09:57:36,101 Cannot connect                                                                             =>[SwingWorker-pool-3-thread-4] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:429)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://192.168.121.1:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=java]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createClientSocket(SocketClientInvoker.java:175)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1220)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.remoting.serialization.impl.java.ClearableObjectOutputStream
	at org.jboss.remoting.serialization.impl.java.JavaSerializationManager.createOutput(JavaSerializationManager.java:63)
	at org.jboss.remoting.marshal.serializable.SerializableMarshaller.getMarshallingStream(SerializableMarshaller.java:89)
	at org.jboss.remoting.marshal.serializable.SerializableMarshaller.getMarshallingStream(SerializableMarshaller.java:72)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createOutputStream(ClientSocketWrapper.java:230)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createStreams(ClientSocketWrapper.java:188)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.<init>(ClientSocketWrapper.java:67)
	... 23 more
INFO  2023-04-30 09:57:36,119 Disconnecting DONE                                                                         =>[SwingWorker-pool-3-thread-4] SessionImpl.disconnect 
INFO  2023-04-30 09:57:36,119 Disconnected from user mode                                                                =>[SwingWorker-pool-3-thread-4] MageFrame.disconnected 
```

The server run just fine :

```
❯ sh startServer.sh 
INFO  2023-04-30 09:55:18,533 Starting MAGE server version 1.4.52-V3-beta8 (build: 2023-04-21 07:41)                     =>[main] Main.main 
INFO  2023-04-30 09:55:18,535 Logging level: INFO                                                                        =>[main] Main.main 
INFO  2023-04-30 09:55:18,535 Default charset: UTF-8                                                                     =>[main] Main.main 
INFO  2023-04-30 09:55:18,537 Reading configuration from path=config/config.xml                                          =>[main] Main.main 
INFO  2023-04-30 09:55:18,726 Loading database...                                                                        =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-04-30 09:55:19,012 Done.                                                                                      =>[main] Main.main 
INFO  2023-04-30 09:55:19,012 Loading extension packages...                                                              =>[main] Main.main 
INFO  2023-04-30 09:55:19,013 Done.                                                                                      =>[main] Main.main 
INFO  2023-04-30 09:55:19,013 Loading cards...                                                                           =>[main] Main.main 
INFO  2023-04-30 09:55:26,544 Done.                                                                                      =>[main] Main.main 
INFO  2023-04-30 09:55:26,545 Updating user stats DB...                                                                  =>[main] Main.main 
INFO  2023-04-30 09:55:26,632 Done.                                                                                      =>[main] Main.main 
INFO  2023-04-30 09:55:26,731 Config - max seconds idle: 600                                                             =>[main] Main.main 
INFO  2023-04-30 09:55:26,731 Config - max game threads: 10                                                              =>[main] Main.main 
INFO  2023-04-30 09:55:26,731 Config - max AI opponents: 15                                                              =>[main] Main.main 
INFO  2023-04-30 09:55:26,732 Config - min usr name le.: 3                                                               =>[main] Main.main 
INFO  2023-04-30 09:55:26,732 Config - max usr name le.: 14                                                              =>[main] Main.main 
INFO  2023-04-30 09:55:26,733 Config - min pswrd length: 8                                                               =>[main] Main.main 
INFO  2023-04-30 09:55:26,733 Config - max pswrd length: 100                                                             =>[main] Main.main 
INFO  2023-04-30 09:55:26,733 Config - inv.usr name pat: [^a-z0-9_]                                                      =>[main] Main.main 
INFO  2023-04-30 09:55:26,733 Config - save game active: false                                                           =>[main] Main.main 
INFO  2023-04-30 09:55:26,733 Config - backlog size    : 200                                                             =>[main] Main.main 
INFO  2023-04-30 09:55:26,733 Config - lease period    : 5000                                                            =>[main] Main.main 
INFO  2023-04-30 09:55:26,733 Config - sock wrt timeout: 10000                                                           =>[main] Main.main 
INFO  2023-04-30 09:55:26,734 Config - max pool size   : 300                                                             =>[main] Main.main 
INFO  2023-04-30 09:55:26,734 Config - num accp.threads: 2                                                               =>[main] Main.main 
INFO  2023-04-30 09:55:26,734 Config - second.bind port: -1                                                              =>[main] Main.main 
INFO  2023-04-30 09:55:26,734 Config - auth. activated : false                                                           =>[main] Main.main 
INFO  2023-04-30 09:55:26,734 Config - mailgun api key :                                                                 =>[main] Main.main 
INFO  2023-04-30 09:55:26,735 Config - mailgun domain  :                                                                 =>[main] Main.main 
INFO  2023-04-30 09:55:26,735 Config - mail smtp Host  :                                                                 =>[main] Main.main 
INFO  2023-04-30 09:55:26,735 Config - mail smtpPort   :                                                                 =>[main] Main.main 
INFO  2023-04-30 09:55:26,735 Config - mail user       :                                                                 =>[main] Main.main 
INFO  2023-04-30 09:55:26,735 Config - mail passw. len.: 0                                                               =>[main] Main.main 
INFO  2023-04-30 09:55:26,735 Config - mail from addre.:                                                                 =>[main] Main.main 
INFO  2023-04-30 09:55:26,735 Config - google account  :                                                                 =>[main] Main.main 
INFO  2023-04-30 09:55:26,736 Loaded game types: 16, tourneys: 17, players: 3, cubes: 48, decks: 51                      =>[main] Main.main 
INFO  2023-04-30 09:55:26,830 Started MAGE server - listening on 0.0.0.0:17171/?serializationtype=java&maxPoolSize=300   =>[main] Main.main 
```

Before the system update and app update everything was running fine.

I think this issue is related to #6197 and more precisely with #6514 and #6531

Thank you very much for any help and futur fixes.

If you want me to test something just ask.

Best regards

**Comment by JayDi85** [comment]
> java.lang.NoClassDefFoundError: Could not initialize class org.jboss.remoting.serialization.impl.java.ClearableObjectOutputStream

Can be related to serialization problem, so something wrong with different client/server/java versions. Be careful -- launcher run apps by java 1.8 (java folder in the launcher), but command line tools uses default system java.

You are running server by command line. Make sure client app runs same way and both server and client app uses same java versions. If you run task manager then must see two java app with same path to executable file but with different params.

**Comment by mbideau** [comment]
Hi @JayDi85 ,
Thank you very much for your feedback.
Thanks to your hint about the java binary used being not the same depending on the way to start client and server, I forced the use of the java one packed with the xmage package and it worked just fine :tada: 

For the record, below are my modified version of the launchers I use that works perfectly on every of my Linuxes ...

Client
```
❯ cat /opt/xmage/xmage/mage-client/startClient.sh 
#!/bin/sh

TMPDIR=/opt/xmage/tmp
TMP=$TMPDIR
TEMP=$TMPDIR
export TMPDIR
export TMP
export TEMP
LC_ALL=C
export LC_ALL

PATH="$(realpath '../../java/jre1.8.0_201/bin'):$PATH"
command -v java
export PATH

java -Djava.io.tmpdir=$TMPDIR -Djava.net.preferIPv4Stack=true -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -jar ./lib/mage-client-1.4.50.jar &
```

Server
```
❯ cat /opt/xmage/xmage/mage-server/startServer.sh 
#!/bin/sh

TMPDIR=/opt/xmage/tmp
TMP=$TMPDIR
TEMP=$TMPDIR
export TMPDIR
export TMP
export TEMP
LC_ALL=C
export LC_ALL

PATH="$(realpath '../../java/jre1.8.0_201/bin'):$PATH"
command -v java
export PATH

java -Djava.io.tmpdir=$TMPDIR -Djava.net.preferIPv4Stack=true -Xms256M -Xmx512M -Dfile.encoding=UTF-8 -Djava.security.policy=./config/security.policy -Dlog4j.configuration=file:./config/log4j.properties -jar ./lib/mage-server-1.4.50.jar
```

I use a different temporary directory because my _/tmp_ partition is mounted with `noexec` option.

I export the `C` language cause, in case of crash or errors, I get the messages in english which are better suited to search on the Internet.

I just added the modification of the path to prepend the path to the java binary packaged with xmage (those lines saved my issue).

And I have added the temp directory option in the java command argument and also force to use the IPv4 network stack to prevent any IPv6 issue.

That's it.

What is cumbersome is that I need to backup that file and restore it after every update ...

May be I should dig into the code and create an issue+PR to offer to save those modifications directly in the source ...

Anyway thank you again.

You can clause the bug if you want.

Best regards

**Comment by JayDi85** [comment]
`xmage` folder clean up on each update (except images folder), so you must put your custom scripts to launcher's folder or any other place. Just change current directory in it:
- client app must run from `..\xmage\mage-client`
- server app must run from `..\xmage\mage-server`

**Comment by mbideau** [comment]
@JayDi85 thank you, I moved my start scripts in the `xmage` parent folder and added a _path change_ in the begining of the script.
