### ISSUE TITLE
ConcurrentModificationException in Whirlwind Denial

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#10427]
Opponent cast [[Whirlwind Denial]]. Two of my things are about to be countered (a spell and an ability) - I decline to pay the first one, and this happened

```Game exception occurred: 

java.util.ConcurrentModificationException
Server version: 1.4.52-V4-beta2 (build: 2023-05-12 14:27)
Stack trace:
java.util.ArrayDeque$DeqSpliterator.forEachRemaining(ArrayDeque.java:957)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
mage.cards.w.WhirlwindDenialEffect.apply(WhirlwindDenial.java:61)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:186)
mage.game.stack.Spell.resolve(Spell.java:275)
mage.game.GameImpl.resolve(GameImpl.java:1690)
mage.game.GameImpl.playPriority(GameImpl.java:1615)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:125)
mage.game.GameImpl.playTurn(GameImpl.java:1087)
mage.game.GameImpl.play(GameImpl.java:997)
mage.game.GameImpl.start(GameImpl.java:973)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)```

**Comment by alexander-novo** [comment]
I don't know much about this Java exception, but it kind of looks like the stack is being modified (spell is being countered) as it's being iterated through. I don't know about Java, but this isn't allowed in languages like C++.

**Comment by xenohedron** [comment]
The effect needs to be reimplemented to comply with this ruling, rather than trying to iterate through the stack and counter each unpaid individually:

As Whirlwind Denial resolves, first the opponent whose turn it is (or, if it's your turn, the next opponent in turn order) chooses which spells and/or abilities to pay for, then pays that amount. Then each other opponent in turn order does the same. Then all spells and abilities that weren't paid for are countered at the same time.
(2020-01-24)

**Comment by JayDi85** [comment]
ConcurrentModificationException is a [popular and complex bug](https://github.com/magefree/mage/issues?q=is%3Aissue+is%3Aopen+ConcurrentModificationException), it can be related to wrong `applyEffects` or `processAction` calls from another effect or card too.

**Comment by JayDi85** [comment]
Another example of `ConcurrentModificationException` with [[Awaken the Sleeper]]:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
    	at java.util.ArrayList$Itr.next(ArrayList.java:859)
    	at mage.cards.a.AwakenTheSleeperEffect.apply(AwakenTheSleeper.java:76)
    	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
    	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:186)
    	at mage.game.stack.Spell.resolve(Spell.java:275)
    	at mage.game.GameImpl.resolve(GameImpl.java:1690)
    	at mage.game.GameImpl.playPriority(GameImpl.java:1615)
    	at mage.game.turn.Step.priority(Step.java:61)
    	at mage.game.turn.Phase.playStep(Phase.java:184)
    	at mage.game.turn.Phase.play(Phase.java:89)
    	at mage.game.turn.Turn.play(Turn.java:125)
    	at mage.game.GameImpl.playTurn(GameImpl.java:1087)
    	at mage.game.GameImpl.play(GameImpl.java:997)
    	at mage.game.GameImpl.start(GameImpl.java:973)
    	at mage.server.game.GameWorker.call(GameWorker.java:34)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```
