### ISSUE TITLE
Error while downloading Card Images

### ISSUE THREAD

**Issue by Incarceron** [magefree/mage#1074]
I get this error when I try to update the last 1000 or so magic cards.

```
Suppressed: java.nio.file.NoSuchFileException: C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip\AVR
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
        at java.nio.file.Files.createDirectory(Unknown Source)
        at net.java.truevfs.driver.file.FileController.make(FileController.java:202)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$make$1.apply(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$make$1.apply(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.make(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.access.TFile.mkdir(TFile.java:2127)
        at net.java.truevfs.access.TFile.mkdirs(TFile.java:2104)
        at org.mage.plugins.card.images.DownloadPictures$DownloadTask.run(DownloadPictures.java:529)
        ... 3 more
    Suppressed: java.nio.file.NoSuchFileException: C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip\AVR
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkAccess(Unknown Source)
        at net.java.truevfs.driver.file.FileController.checkAccess(FileController.java:101)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
        ... 8 more
    Suppressed: java.nio.file.NoSuchFileException: C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip\AVR\Zealous Conscripts.full.jpg
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkAccess(Unknown Source)
        at net.java.truevfs.driver.file.FileController.checkAccess(FileController.java:101)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.checkAccess(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.access.TFile.exists(TFile.java:1670)
        at org.mage.plugins.card.images.DownloadPictures$DownloadTask.run(DownloadPictures.java:528)
        ... 3 more
    Suppressed: java.nio.file.NoSuchFileException: C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip\AVR
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
        at java.nio.file.Files.createDirectory(Unknown Source)
        at net.java.truevfs.driver.file.FileController.make(FileController.java:202)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$make$1.apply(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$make$1.apply(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.make(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.access.TFile.mkdir(TFile.java:2127)
        at net.java.truevfs.access.TFile.mkdirs(TFile.java:2104)
        at org.mage.plugins.card.images.DownloadPictures$DownloadTask.run(DownloadPictures.java:529)
        ... 3 more
    Suppressed: java.nio.file.NoSuchFileException: C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip\AVR
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkAccess(Unknown Source)
        at net.java.truevfs.driver.file.FileController.checkAccess(FileController.java:101)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
        ... 8 more
    Suppressed: java.nio.file.NoSuchFileException: C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip\AVR\Zealous Strike.full.jpg
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.checkAccess(Unknown Source)
        at net.java.truevfs.driver.file.FileController.checkAccess(FileController.java:101)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.checkAccess(FalsePositiveArchiveController.scala:74)
        at net.java.truevfs.access.TFile.exists(TFile.java:1670)
        at org.mage.plugins.card.images.DownloadPictures$DownloadTask.run(DownloadPictures.java:528)
        ... 3 more
    Suppressed: java.nio.file.NoSuchFileException: C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip\AVR
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
        at java.nio.file.Files.createDirectory(Unknown Source)
        at net.java.truevfs.driver.file.FileController.make(FileController.java:202)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$make$1.apply(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$make$1.apply(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
        at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.make(FalsePositiveArchiveController.scala:128)
        at net.java.truevfs.access.TFile.mkdir(TFile.java:2127)
        at net.java.truevfs.access.TFile.mkdirs(TFile.java:2104)
        at org.mage.plugins.card.images.DownloadPictures$DownloadTask.run(DownloadPictures.java:529)
        ... 3 more
```

**Comment by LevelX2** [comment]
Sometimes the zip archives are damaged and the image files can't be saved.
So test if you 
1) quit xmage
2) delete C:\Users\unfre_000\Desktop\XMage Launcher\xmage\mage-client\plugins\images\AVR.zip file.
3) Start xmage and start image download.
and check after taht, if the AVR images are available.
If so, it was probably a damaged zip file.
Probabaly the damaged zip files also have a file size of 0.

Please report the results if you try this.

**Comment by Incarceron** [comment]
I'm still getting errors. Is there a torrent or something where I can download all the cards rather than through the xmage client?

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
