### ISSUE TITLE
GUI error on hovering over a card.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#10888]
So this was not gamebreaking, but on hovering hover a [[Captive Audience]] that had one ability used with the hint from #10860, I did have the rules box barely of the right height to see the top half of the hint, and there was the following error in the client console. I retried after a second trigger (so hint did change), and there was no problem with two .

Seems not critical, but maybe there is more issues relative to that so figured I'll post an issue about it.
 
```
FATAL 2023-08-19 14:07:18,821 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException: 0
	at javax.swing.text.BoxView.getOffset(BoxView.java:1101)
	at javax.swing.text.BoxView.childAllocation(BoxView.java:695)
	at javax.swing.text.CompositeView.getChildAllocation(CompositeView.java:232)
	at javax.swing.text.BoxView.getChildAllocation(BoxView.java:453)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.calculateViewPosition(BasicTextUI.java:1999)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.layoutContainer(BasicTextUI.java:1975)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validate(Container.java:1633)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
```

**Comment by Susucre** [comment]
Ok could reproduce:
![image](https://github.com/magefree/mage/assets/34709007/7ecc0fa7-a6df-4591-9556-60d8bd001e1a)

**Comment by Susucre** [comment]
With two used modes, no issue. This is strange.
![image](https://github.com/magefree/mage/assets/34709007/e6fb6dd7-5b48-47f5-970a-a25436c98997)

**Comment by JayDi85** [comment]
Can't reproduce any errors in current version. Text bug related to design - card popup dialog can't show too long texts. Nothing to do with it. Maybe scrollbars can help but it hard task for UX.

![shot_231126_220851](https://github.com/magefree/mage/assets/8344157/0b11f084-13f2-441f-8cfe-fa22d779efae)
![shot_231126_220930](https://github.com/magefree/mage/assets/8344157/b666853e-1c1e-4d3f-9fc2-a596269a7a8e)
![shot_231126_220906](https://github.com/magefree/mage/assets/8344157/74656f2b-7196-44cd-9f62-adc18e3561ad)
![shot_231126_220834](https://github.com/magefree/mage/assets/8344157/0ce1764c-1c58-43e8-920b-ea121f0c71a1)
