### ISSUE TITLE
Commander games can contains commander cards without init code call?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11081]
Old and popular bug from a server with missing `CommanderInfoWatcher`:
```
java.lang.Throwable
	at mage.watchers.Watchers.get(Watchers.java:51)
    	at mage.watchers.Watchers.get(Watchers.java:43)
    	at mage.game.GameState.getWatcher(GameState.java:643)
    	at mage.game.GameCommanderImpl.checkStateBasedActions(GameCommanderImpl.java:248)
    	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2080)
    	at mage.game.turn.EndPhase.playStep(EndPhase.java:39)
    	at mage.game.turn.Phase.play(Phase.java:90)
    	at mage.game.turn.Turn.play(Turn.java:137)
    	at mage.game.GameImpl.playTurn(GameImpl.java:1095)
    	at mage.game.GameImpl.play(GameImpl.java:1002)
    	at mage.game.GameImpl.start(GameImpl.java:978)
    	at mage.server.game.GameWorker.call(GameWorker.java:34)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

Each commander card must be init with special code, see `initCommander`. That's code adds `CommanderInfoWatcher` and assign it with a card. But there are possible use cases with missing watcher, e.g. commander card doesn't init at the start of the game. Error state: game contains card's id in the player's commanders list, but card's watcher was missed.

I don't know the real reason. What can be buggy:
* MDFC or other double faced cards as a commander;
* partner card as a commander;
* card as an oathbreaker spell;
* something adds cards to the commanders list or something removes cards from a game forever;
* leave/lose player;
* all above but after game restart with [[Karn Liberated]].

**Comment by JayDi85** [comment]
Fixed in related commits, see comment from https://github.com/magefree/mage/pull/11628#issuecomment-1891164141
