### ISSUE TITLE
NPE error without game view updated properly

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11201]
@JayDi85 seems related to the recent network changes

Reported on Discord by user Teka
> Got the same error (Susucr note: responded to another NPE error a few days before), but happened after a timeout and reconnect, cliect didnt/show load the field from every player and game froze for the current playing player(couldnt press done)

![image](https://github.com/magefree/mage/assets/34709007/b3b91a69-0c32-4116-93e6-b1a2b0c4c5ff)

```java
java.lang.NullPointerException
	at mage.client.game.GamePanel.updateGame(GamePanel.java:915)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:717)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:711)
	at mage.client.game.GamePanel.inform(GamePanel.java:1665)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:380)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
FATAL 2023-09-23 22:47:44,827 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.NullPointerException
	at mage.client.game.GamePanel.updateGame(GamePanel.java:915)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:717)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:347)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:172)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:89)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1249)
	at mage.client.MageFrame.showError(MageFrame.java:1527)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:661)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
FATAL 2023-09-23 22:47:44,875 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.NullPointerException
	at mage.client.game.GamePanel.updateGame(GamePanel.java:915)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:717)
	at mage.client.game.GamePanel.endMessage(GamePanel.java:1670)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:231)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:172)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:89)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1249)
	at mage.client.MageFrame.showError(MageFrame.java:1527)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:661)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:172)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:89)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1249)
	at mage.client.MageFrame.showError(MageFrame.java:1527)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:661)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by JayDi85** [comment]
Miss avatars panels related to miss ccGameStarted event after reconnect. All that npe errors after reconnects depends on miss players data. It's old bug.

**Comment by Susucre** [comment]
Alright, was not sure and wanted to make that NPE visible on github.
