### ISSUE TITLE
Deck generation throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1128]
I tried to generate a {B}{U} Magic Origins deck
Singletons = OFF
Artifacts = ON
Non-Basic Lands = ON

```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.set(ArrayList.java:444)
	at mage.client.deck.generator.DeckGeneratorPool.getFixedSpells(DeckGeneratorPool.java:396)
	at mage.client.deck.generator.DeckGeneratorPool.calculateSpellColorPercentages(DeckGeneratorPool.java:229)
	at mage.client.deck.generator.DeckGenerator.generateLands(DeckGenerator.java:248)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:173)
	at mage.client.deck.generator.DeckGenerator.buildDeck(DeckGenerator.java:98)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:66)
	at mage.client.table.NewPlayerPanel.generateDeck(NewPlayerPanel.java:97)
```

**Comment by Simown** [comment]
I saw this last night too but haven't provided a fix for it yet. It happens for single sets when not enough cards are found in the chosen colors in the first iteration and when it comes to fill the holes in a generated deck it tries to add more cards than have been found. 

I'll investigate and hopefully get a fix in later today.

**Comment by Simown** [comment]
Should be fixed now. Can you confirm and then I'll close it?

**Comment by LevelX2** [comment]
I created some Origins decks and had no bug. 
I close the issue.
