### ISSUE TITLE
beta.xmage.today crashes a lot recently

### ISSUE THREAD

**Issue by CozyDoomer** [magefree/mage#11285]
The interval varies quite a lot but in my experience, it happens roughly every few minutes to 2 hours.

People in the in-game chat are saying it happens when a near-infinite amount of triggers are created (e.g. storm with way more than 20 triggers) but I have no evidence for this.
I do know however that recently the game has been almost unplayable due to the crashes so I'd like to help where I can.

@JayDi85 do you have anything in your logs?
Also not sure if this came up already - I couldn't find any issues on this except maybe [#10656](https://github.com/magefree/mage/issues/10656).

**Comment by JayDi85** [comment]
There only two candidates:
1. Commander cards with miss init code (details in #11081). That error can freeze game and run infinite errors logs until server's restart;
2. Transformable cards with too much calls of game cycle:
It's a daybound/nightbound cards like [[Child of the Pack]] that can cause too much calls of `checkStateBasedActions -> transform` in the games. If you put that cards to the battlefield then it will dramatically increase cpu usage and `applyEffects` calls, see attached screenshot.

![shot_231009_084729](https://github.com/magefree/mage/assets/8344157/5c3a8eb5-2f54-44bb-a60c-55e29da32172)

![shot_231009_085259](https://github.com/magefree/mage/assets/8344157/970ba43b-71b8-4e26-9476-9253ed780b00)

**Comment by jeffwadsworth** [comment]
Is the following GPT analysis correct?  If so, the state check may be superfluous.

### Handling in a Game State Engine:

1. **Global State Variable**: You'll need a global variable, say `dayNightState`, which can have three possible values: "None", "Day", and "Night". The game begins with the value set to "None".

2. **Spell Count**: Maintain a counter for each player that keeps track of the number of spells they've cast during their own turn. This can be reset to 0 at the beginning of each player's turn.

3. **Transition Logic**: At the beginning of each player's end step, check the spell count of that player:

   - If it's 0 and the current `dayNightState` is "Day", set `dayNightState` to "Night".
   - If it's 2 or more and the current `dayNightState` is "Night", set `dayNightState` to "Day".
   - In any other case, do nothing.

4. **Card Transformation**: Based on the `dayNightState`, transform all relevant Daybound/Nightbound cards on the battlefield:

   - If transitioning to "Night", all Daybound cards transform to their Nightbound side.
   - If transitioning to "Day", all Nightbound cards transform to their Daybound side.

5. **No Continuous Checks**: You only need to check the spell count and the transition logic at specific times, not continuously. This is mainly at the beginning of each player's end step, so you aren't overloading your application with constant checks.

6. **Integration with Other Mechanics**: Ensure that the Daybound/Nightbound mechanic interacts appropriately with other mechanics, like transforming cards or other game states. Ensure that triggered abilities or replacement effects that rely on the day/night cycle are checked whenever the `dayNightState` changes.

7. **Edge Cases and Complexities**: Like any game mechanic, there might be additional rules or card-specific effects that need special handling. Always refer to the most recent official rules or rulings when implementing in an engine.

Remember, when building game state engines, modularity and clear structure are key. Each piece of logic should be isolated enough that it can be modified, debugged, or expanded without causing cascading changes or bugs across the entire system.

**Comment by whispy** [comment]
+1, the server crashes all of the time. Is there a bounty we can put to get this fixed?

**Comment by JayDi85** [comment]
There are added new global features like Prototype mechanics (#11249), so prepare for more unstable times until this whole things stabilises.

**Comment by ssk97** [comment]
> There are added new global features like Prototype mechanics (#11249), so prepare for more unstable times until this whole things stabilises.

I don't really see how Prototype could cause a server crash, worst case would be a game crash that doesn't touch the rest of the server, right? Unless the single boolean added to each permanent somehow is too much extra data...

**Comment by JayDi85** [comment]
> worst case would be a game crash that doesn't touch the rest of the server, right?

Nope. All server restarts related to the memory overflow error: java's garbage collector (GC) can't clean and free objects due [circular references between game states or other game objects](https://stackoverflow.com/a/18350729/1276632). So one broken game can eats all server's memory and crash whole server. Under the hood: xmage uses thread's pool to process games and you [can't limit memory usage for specific thread/game](https://stackoverflow.com/a/6600076/1276632).

The main problem of memory overflow errors -- it's hard to catch and repeat. It must be a combo of two things:
* bugged code with generating shared objects between game states;
* infinite loop that can generate a large number of calls of the problem code.

Well, whole xmage code base can generates such "shared" objects, but it's ok in 99% due game lifecycle. On game ends it will be closed and all game's memory will be free anyway. But inifinite/freeze game doesn't ends and eats memory by time.

There are possible another use cases like infinite number of objects like AI and mana variations calculation, AI and infinite choose dialogs, infinite number of tokens (no more actual), etc. But it's more easy to catch.

**Comment by JayDi85** [comment]
The main "problem" of new big features -- it adds new batch of possible bad combos or use cases to generate such infinite loops and freezes. So players can find out new steps to reproduce it on the server.

**Comment by JayDi85** [comment]
One of the use case from #9302:
> Putting 100s of abilities on the stack at once will crash the server
> Easiest way to reproduce, add 10-30 [[Sharding Sphinx]] to your board and a [[Platinum Angel]] to the AI so they won't lose the game.
> When damage is deal this will put a few hundred triggers from the Sharing Sphinx on the board. This will cause the server to lock up a large amount of RAM (20 Sphinxes will lock up ~450MB of ram). This ram can't be CG'ed away until the stack empties.

**Comment by ShadowKayoto** [comment]
I'd also like to chime in that this should be the most urgent issue to look into and address. No amount of coding efforts on this project matter if no one can actually enjoy what's been created and maintained all this time, which is currently the case.

Is there any way to identify and prevent some of these cases from occurring? It looks like you have metrics and call stacks available, so figuring out the most frequent causes should be possible, and then prioritizing the fixes from there.

Like @whispy mentioned already, I'm also willing to donate towards the goal of getting the server stabilized.

**Comment by JayDi85** [comment]
Load tests can be useful to find problems with the cards or AI. Also it allows to test cards and server's stability.

As example:
* start local server;
* open `LoadTest` file and setup testing cards by:
  * `TEST_AI_RANDOM_DECK_SETS`, 
  * `TEST_AI_CUSTOM_DECK_PATH_1`, 
  * `TEST_AI_CUSTOM_DECK_PATH_2`
* setup games amount to run by `gamesAmount`;
* run unit test `test_TwoAIPlayGame_Multiple`
* wait final results;
* if you see a problem/slow game, then you can repeat it by manual random sid in `singleGameSID`;

![shot_231011_151841](https://github.com/magefree/mage/assets/8344157/fe7b8a89-bae5-4c08-ae25-93eaab2e0ca1)


![shot_231011_150253](https://github.com/magefree/mage/assets/8344157/e9b39c3c-3570-484a-b1ef-bf16ea589852)

**Comment by JayDi85** [comment]
Main memory problem fixed, so server must be more stable. See details here: https://github.com/magefree/mage/issues/9302#issuecomment-1762853919. But there are still todos and check for next updates.

**Comment by JayDi85** [comment]
One of the unknown use case with 90% CPU freeze:
Constructed - Legacy | DaddyGreen, Urzasdestiny [quit] | Two Player Duel |

AddCountersSourceEffect and some triggers:

![shot_231014_225008](https://github.com/magefree/mage/assets/8344157/34cc601f-3ea4-436b-b1aa-069bb5466fc6)
![shot_231014_223948](https://github.com/magefree/mage/assets/8344157/633fc524-90c2-47ef-98ff-f62647c9a971)
![shot_231014_230957](https://github.com/magefree/mage/assets/8344157/0bbe57ad-2332-4cb4-9939-637f44e514b9)

Empty stack and permanents on battlefield (except lands, I'm not sure that it's a moment of high CPU or after it):
* [[CityOfTraitors]]
* [[GrimLavamancer]] with one boost counter on it
* [[DragonsRageChanneler]]
* [[DelverOfSecrets]]
* [[ChromeMox]]

**Comment by xenohedron** [comment]
Thanks for your deep research and improvements @JayDi85 , great work

**Comment by JayDi85** [comment]
Another one possible use case from a problem game:
* [[Rite of Replication]] on the stack
* [[Ancient Greenwarden]] on the battlefield as 160+ tokens and active triggers/effects
* [[Primal Vigor]] on battlefield as 9 active token and counter triggers/effects
* [[Nyxbloom Ancient]]

**Comment by jeffwadsworth** [comment]
@JayDi85 I could have sworn I saw that "test_TwoAIPlayGame_Multiple" test in the test folder in the past, but now I can't find it.

**Comment by JayDi85** [comment]
@jeffwadsworth It ignored by default. Mage.Verify project -> LoadTest.java -> test_TwoAIPlayGame_Multiple

**Comment by Susucre** [comment]
@JayDi85 an user on the Discord reported a crash of the beta server.
The reported situation was 500 [[Ramos  Dragon Engine]] then triggering them all by casting a multicolored spell.

**Comment by JayDi85** [comment]
Last crash from that game with high CPU usage: [Not CDEH/ No infinite combo] Martin - azert - B24M - vsdiaz
![shot_231128_184452](https://github.com/magefree/mage/assets/8344157/f2cb8750-576b-4faf-a504-b9de1ceda0a8)

Don't know the real battlefield situation or steps to reproduce, but CPU "stack" looks very strange cause `LookAtTopCardOfLibraryAnyTimeEffect` is `ContinuousEffect` -- it applies on every game cycle. BUT it calls a network code to send data to users (`fireUpdatePlayersEvent`):
![shot_231128_191411](https://github.com/magefree/mage/assets/8344157/b8aff157-e9fc-4cfe-b2bb-8317da5d8272)
![shot_231128_191459](https://github.com/magefree/mage/assets/8344157/c4b25192-e4e4-4d6f-a9d1-bdd6390719cb)

I think it was a workaround to force a user update (in old days reveals/lookat windows may miss on choose dialog). That broken code must be removed from all places, not only continues effects.

**Comment by JayDi85** [comment]
Just interesting screenshot with good and bad games example:

![shot_231128_194358](https://github.com/magefree/mage/assets/8344157/bd9cd7cb-e0b7-469e-b305-40aab25be55c)

**Comment by JayDi85** [comment]
well, it's can be a real cheater/troll now -- crashed server on main phase of turn 1 (T1M1) with 300 replacement effects and 500 permanents on battlefield

GAME started 5234893d-a6e0-4ed7-baf3-2840f39599cf [] **icarus - oranges**

Freeze on choose `chooseReplacementEffect` with 230 effects to choose:
![shot_231129_034327](https://github.com/magefree/mage/assets/8344157/c4607b52-3241-4d08-8055-075605b10ac1)

3 auto-selected choices by user: [[Ancient Greenwarden]], [[Nyxbloom Ancient]] and [[Primal Vigor]]
![shot_231129_033018](https://github.com/magefree/mage/assets/8344157/76f6aa03-b678-4800-aa18-c7955c34a4cd)

1 spell on stack: [[Mythos of Illuna]]
![shot_231129_033416](https://github.com/magefree/mage/assets/8344157/b585560f-462f-4cff-b201-4605dc17661c)

~500 permanents on battlefield:
![shot_231129_033337](https://github.com/magefree/mage/assets/8344157/555dbaf8-3fa4-47d4-a7f8-3f59a0e64fdd)
![shot_231129_033344](https://github.com/magefree/mage/assets/8344157/4ef83c4c-3aca-4043-92fa-be6b623bb9f4)
![shot_231129_033351](https://github.com/magefree/mage/assets/8344157/0f540f1b-7561-40cb-9ae2-19a865143907)

**Comment by JayDi85** [comment]
Yes, it's a real troll, played 1 vs 1 game from same computer, but with two diff clients. From USA, IP address recorded too.

**Comment by JayDi85** [comment]
Another use case with infinite game freeze on mana calculations -- only 25 permanents on battlefield, but something do an explosive {any} mana growth in available mana calculation. It must have additional limits for such use cases:

![shot_231129_094002](https://github.com/magefree/mage/assets/8344157/9dfda7d5-f5d4-4d55-af2a-33b6e764aa63)
![shot_231129_093820](https://github.com/magefree/mage/assets/8344157/f7c279ad-0d10-4364-a72d-03ff467f1ca9)
![shot_231129_093435](https://github.com/magefree/mage/assets/8344157/7fcc6536-b512-437e-8d7a-8d7cebefb71a)

**Comment by JayDi85** [comment]
Another interesting catch: some users was able to run macro feature (it's outdated and disabled feature to repeat same user actions on server side, e.g. combo recording). Fixed by ebaa92c537205acb27f44fa5cfc8dd85ab2345d4

**Comment by JayDi85** [comment]
Server stats from last week: ~7 restarts per day

**Comment by JayDi85** [comment]
Found two use cases for crash protection tests in old reddit’s topic:
https://www.reddit.com/r/XMage/comments/ikroo7/i_love_when_i_get_spectators/

Must be checked and implemented as unit tests:

1 - tokens:
> The main deck is OmniTell, that is: Legacy Show and Tell into Omniscience to cast stuff for free, but I've built a version that basically exists as a gun, and the ammo is whatever is in my sideboard.

> So the part that crashes the client is to play Opalescence turning all Enchantments into creatures, then playing a Dual Nature to get tokens of creatures (enchantments) and Doubling Seasons to double the number of tokens. However, when Dual Nature enters the battlefield, Opalescence makes it a creature, so it triggers itself. That means there are two Dual Natures. When I play Doubling Season, two Dual Nature triggers go onto the stack, trying to each place a token copy of Doubling Season. After some number of these resolve the next Dual Nature trigger to resolve places token Doubling Seasons doubled for every other token. This makes it grow very very quickly in number, as it basically creates 2^N + N tokens for each Dual Nature trigger to resolve where N is the number of Doubling Seasons. So for two plays of Doubling Season (which is where the game lags hard and locks up) this is about 2^2059 tokens, each a 5/5 creature token copy of Doubling Season.

2 - triggers:
> If one were to use this deck in real life, you can easily keep track of the number of tokens and just put some piece of paper to represent it, right?

> Wrong.

> I also have included in the deck Grip of Chaos, which will be copied a large number of times. Then if I were to happen to play a spell which targets a creature, ALL of those triggers go onto the stack and EACH one triggers ALL of them. In a tournament, this means you have to call over a judge to resolve them, and they would be very disappointed in me.

**Comment by JayDi85** [comment]
TODO:
* [ ] find and replace inner classes to static (possible memory leaks). ~50 places to fix IntelliJ. Inspection settings example to find it:
![shot_240215_212541](https://github.com/magefree/mage/assets/8344157/60fd5f1c-a878-488b-ac0d-2c1f04a42cda)

**Comment by xenohedron** [comment]
> TODO: find and replace inner classes to static (possible memory leaks). ~50 places to fix.

I'm starting to work on this

**Comment by xenohedron** [comment]
> TODO: find and replace inner classes to static (possible memory leaks). ~50 places to fix.

Most addressed, see #11798 and #11810

**Comment by JayDi85** [comment]
Looks like java 8 under docker has some bugs and [generate memory “leaks” too by inner tools like GC, native threads, etc](https://stackoverflow.com/questions/52607839/unexplained-extra-memory-consumed-by-docker-running-java-process). Maybe it will be fixed after [migrate to newer java someday](https://github.com/magefree/mage/issues/6197).

So current workaround: leave more free memory for the system and docker. Example:
- hardware: 8 GB;
- docker’s container memory limit: 7000 GB;
- java’s app memory limit: 6500 GB.

**Comment by JayDi85** [comment]
Last crashes was due constant memory leaks without cpu usage or objects overflow. And there is a new suspect - network library with buggy finalizers (source of the some leaks). Maybe new server session code can cause it and require some fixes: #11527

**Comment by JayDi85** [comment]
Intermediate report after more researches and memory dumps analysing from last weeks (server with disabled AI):
1. [x] Memory leaks by games (e.g. too many game states) -- no, it's not actual any more. No freeze games, no infinite game states generation;
2. [x] Memory leaks by another code (e.g. third party library, see [prev comment](https://github.com/magefree/mage/issues/11285#issuecomment-1979838104)) -- no, it's not actual. It has some potentially leaked traces but it's too small (few KBs, not MBs or GBs);
3. [x] 100% CPU usage like infinite transform -- no, it's not actual. Transform bug exists, but real games and server can do nothing with it. There were only few use cases with high CPU usage (maybe related to transform, maybe related to another heavy calculations), but it last for few minutes without any consequences (no crashes, no memory overuse);

But I found very perspective problem:
* [ ] Real memory "leaks" come from java's Garbage Collector (GC). For unknown reason GC forget to clean old gen objects and it raises by time until memory overflow (more work time -- more new gen objects moved to old gen and keeps in memory).

Server's memory usage example:
![shot_240315_205747](https://github.com/magefree/mage/assets/8344157/93912c12-da69-4048-8c55-c0014de54726)

GC works example - it ignore most of the heap (old gen objects) until manually GC call (new and old gen objects clean):
![shot_240315_202309](https://github.com/magefree/mage/assets/8344157/fa3e4971-add2-4608-b704-401a29067851)

No memory leaks after manual GC call:
![shot_240315_201918](https://github.com/magefree/mage/assets/8344157/62ec107f-3c20-46b3-9fe7-e4d4418171a8)

Here is [related SO topic](https://stackoverflow.com/questions/25885826/java-gcold-generation-becomes-larger-and-larger-and-cannot-be-reclaimed) with possible solutions for such problem. Experiments with the server will continue. Looks like it coming to finish.

**Comment by JayDi85** [comment]
BTW server with 30 active games uses less than 500 MB after 12 hours uptime -- it's related to low hardware requirements and good/stable performance.

![shot_240315_212003](https://github.com/magefree/mage/assets/8344157/05a8f8e9-3d67-4cc3-ab2c-d3cddb7f5d02)

**Comment by JayDi85** [comment]
![dharma-lost](https://github.com/magefree/mage/assets/8344157/582dfb6c-5301-4f57-85cc-d28b971a8c58)

**Comment by JayDi85** [comment]
No more memory crashes, so server live longer to catch worse bugs like empty players list and no started games from #5358.

Real reason: infinite code freeze in string replace (!!!) and server's data lock, so all other code waiting data unlock. It's critical error and contains two independent problems.

TODO:
* [ ] infinite string replacement - need research and unit tests for proof (is it possible to freeze it by some texts);
* [ ] bad fields/class lock logic, so GameView's generating freeze can block a whole server -- need research, maybe no needs in some sync fields/methods, maybe need some copy code instead lock/sync. See additional task with richman draft below, can be related (original source of the problem).

Combo of both problems can broke whole server (no out of memory, so it must be manually restarted only):
![shot_240321_102026](https://github.com/magefree/mage/assets/8344157/50a0b81c-5671-48c4-bee0-2152fba84d8d)

Example of infinite freeze and 100% CPU in `GainAbilityAttachedEffect` with `formatRule` usage:
![shot_240321_031315](https://github.com/magefree/mage/assets/8344157/8f9ff692-596d-469d-876b-58a84a75956b)
![shot_240321_030806](https://github.com/magefree/mage/assets/8344157/eb3199fc-691b-46da-b0d8-9ee755effb0f)

Example of infinite freeze and 100% CPU in `getReminderText`:
![shot_240321_102423](https://github.com/magefree/mage/assets/8344157/b6f06f23-adde-42a7-a7f3-e58af2c65ff9)
![shot_240321_102525](https://github.com/magefree/mage/assets/8344157/4e7dab3b-eafd-4890-b3f6-0b59c7b83349)


TODO:
* [ ] There were multiple `RichManBoosterDraft` while freeze, maybe related

![shot_240321_030523](https://github.com/magefree/mage/assets/8344157/f08e2933-aa8a-4f13-aad6-d856503a9c42)

It stuck at pick cards:
![shot_240321_103124](https://github.com/magefree/mage/assets/8344157/c02c55ba-813f-4784-b9ca-c7e830485e0d)

It can continue on player quit or submit/autosubmit only (maybe notify calls miss in some use cases/places):
![shot_240321_103109](https://github.com/magefree/mage/assets/8344157/0f2bc608-65a4-4623-9eed-1dc7865932cf)
![shot_240321_103052](https://github.com/magefree/mage/assets/8344157/305cb706-78c6-454c-93cd-3c89b1d492ff)

**Comment by JayDi85** [comment]
* [ ] rare ghost game threads problem: response waiting code can go to infinite (if all players disconnected without concede and game thread stuck on waiting someone, e.g. due network problems). Must use protection timeout to continue in game thread or must improve server health check to find and close such ghost games. There are additional threads with player timers (it can stop game on timeout) but it looks bad and must be removed someday (4 players game creates 5 threads: 1 for game and 4 for each timers).
```
"GAME fca08133-9c87-4295-8dc7-e489e80b51bb" - Thread t@8602
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <3b530b5d> (a mage.player.human.PlayerResponse)
	at java.lang.Object.wait(Object.java:502)
	at mage.player.human.HumanPlayer.waitForResponse(HumanPlayer.java:322)
	at mage.player.human.HumanPlayer.priority(HumanPlayer.java:1316)
	at mage.game.GameImpl.playPriority(GameImpl.java:1668)
	at mage.game.turn.Step.priority(Step.java:67)
	at mage.game.turn.Phase.playStep(Phase.java:205)
	at mage.game.turn.Phase.play(Phase.java:91)
	at mage.game.turn.Turn.play(Turn.java:137)
	at mage.game.GameImpl.playTurn(GameImpl.java:1131)
	at mage.game.GameImpl.play(GameImpl.java:1038)
	at mage.game.GameImpl.start(GameImpl.java:1014)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at mage.server.game.GameWorker.call(GameWorker.java:15)
```

**Comment by JayDi85** [comment]
* [ ] Infinite mana combos from mana triggers can potentially go to 100% CPU usage and crash. Must research [[Basalt Monolith]] with cards like [[Kinnan, Bonder Prodigy]] (other examples on [reddit[(https://www.reddit.com/r/mtgfinance/comments/fy1e1i/kinnan_makes_basalt_monolith_go_infinite_with/)).

**Comment by JayDi85** [comment]
* [ ] detached games problem

Each server game works in game thread (`GameWorker`) and must be processed from start to end by that thread. All errors must be processed inside. But some code can cause it to quit without real game finish. That's game will be detached (it will be store in active games list until server restart, but nothing works with it).

Table health check must find and delete it, but it can't -- maybe due active/connected game's players. Server example: ~2% of all games keep active.

Two possible solutions:
* good: health check must close that games;
* bad: health check must start new game thread and continue to execute that game;

It's not critical bug -- just showing that some errors/bugs occurred and must be researched.

**Comment by JayDi85** [comment]
* [ ] something miss in tourney stats: -1 in active (like [detached games](https://github.com/magefree/mage/issues/11285#issuecomment-2076362715) but for tourney?)

![shot_240428_044655](https://github.com/magefree/mage/assets/8344157/317f9977-59e3-4041-b9e1-7f11fc741ce1)
![shot_240428_044720](https://github.com/magefree/mage/assets/8344157/21d4526b-3bc4-4a45-b49f-f8a7dd32d106)

**Comment by JayDi85** [comment]
* [ ] client take too much time for disconnect sometime

After one of the few updates disconnect process starting to freeze sometime for 5-10 seconds for unknown reason (connect to public server, do nothing and try to disconnect). Maybe related to wrong synchronized usage on busy server from [above comments]

(https://github.com/magefree/mage/issues/11285#issuecomment-2044515400).
![shot_240428_045705](https://github.com/magefree/mage/assets/8344157/b755822b-731e-4408-aed2-d218cb16dacd)

**Comment by JayDi85** [comment]
* [ ] multiple instance of [[Energy Refractor]] cause 100% CPU usage forever
