### ISSUE TITLE
Effects with aura/equipment re-attach code must check spell ability

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11328]
Original server side error with [[Halvar, God of Battle]]:
```
java.lang.NullPointerException
	at mage.cards.h.HalvarGodOfBattleEffect.apply(HalvarGodOfBattle.java:131)
    	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
    	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:183)
    	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:167)
    	at mage.game.stack.StackAbility.resolve(StackAbility.java:87)
    	at mage.game.GameImpl.resolve(GameImpl.java:1729)
    	at mage.game.GameImpl.playPriority(GameImpl.java:1654)
```

Bugged code:
![shot_231021_171350](https://github.com/magefree/mage/assets/8344157/24d399c4-e65c-4258-97b9-3c0567fe8d08)

Possible reason: land somehow becomes an aura and attached to a permanent, so another code with aura re-attach effect catch the error. Can't find any cards with aura + land types in the same side, but there are two potential DFC cards like [[Dowsing Dagger]] and [[Journey to Eternity]].

Possible fix: add SpellAbility() check on null or attachment check on not land

If someone can find workable use case for unit test then it will be good. But bugged code must be fixed anyway. There are ~16 use cases with same code style, search by `.getSpellAbility().getTargets().get(0)`:
![shot_231021_171045](https://github.com/magefree/mage/assets/8344157/6bde243b-00c3-4eb2-9d67-649ef3deed8c)

**Comment by xenohedron** [comment]
See also #9583, the correct handling would be to get the target from the EnchantAbility, part of a larger rework
