### ISSUE TITLE
Second side of DFC card can lost watcher init code (Temple of Power)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11329]
Interesting server side logs for second side of [[Ojer Axonil, Deepest Might]] -- Temple of Power side lost their watcher while stay in library:
```
java.lang.Throwable
	at mage.watchers.Watchers.get(Watchers.java:51)
    	at mage.game.GameState.getWatcher(GameState.java:639)
    	at mage.cards.t.TempleOfPowerHint.getText(TempleOfPower.java:93)
    	at mage.util.CardUtil.getCardRulesWithAdditionalInfo(CardUtil.java:1197)
    	at mage.cards.CardImpl.getRules(CardImpl.java:220)
    	at mage.view.CardView.<init>(CardView.java:418)
    	at mage.view.CardView.<init>(CardView.java:270)
    	at mage.view.CardView.<init>(CardView.java:152)
    	at mage.view.CardView.<init>(CardView.java:524)
    	at mage.view.CardsView.<init>(CardsView.java:61)
    	at mage.server.game.GameController.lambda$target$18(GameController.java:840)
    	at mage.server.game.GameController.perform(GameController.java:1001)
    	at mage.server.game.GameController.perform(GameController.java:994)
    	at mage.server.game.GameController.target(GameController.java:833)
    	at mage.server.game.GameController.lambda$init$3aa0d15c$2(GameController.java:193)
    	at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
    	at mage.game.events.PlayerQueryEventSource.target(PlayerQueryEventSource.java:74)
    	at mage.game.GameImpl.fireSelectTargetEvent(GameImpl.java:2925)
    	at mage.player.human.HumanPlayer.chooseTarget(HumanPlayer.java:844)
    	at mage.target.common.TargetCardInLibrary.choose(TargetCardInLibrary.java:84)
    	at mage.players.PlayerImpl.searchLibrary(PlayerImpl.java:2803)
    	at mage.players.PlayerImpl.searchLibrary(PlayerImpl.java:2725)
    	at mage.abilities.effects.common.search.SearchLibraryPutInHandEffect.apply(SearchLibraryPutInHandEffect.java:54)
    	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
    	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:186)
    	at mage.game.stack.Spell.resolve(Spell.java:294)
    	at mage.game.GameImpl.resolve(GameImpl.java:1729)
    	at mage.game.GameImpl.playPriority(GameImpl.java:1654)
````

But original card has good ability/watcher code. So there are possible bugs with second side init or another use case:
![shot_231021_174709](https://github.com/magefree/mage/assets/8344157/d2c75aa3-1abf-45dd-8b71-2772b7ca6034)

**Comment by Susucre** [comment]
Just a random thought, when are we adding watchers for cards in command zone? Do we properly add back side watchers from there?

**Comment by JayDi85** [comment]
Watchers are global, added one time per card on start of the game (game init). Each watcher has a scope: game scope (one watcher class per game) and card scope (one watcher + card id per game).

**Comment by Susucre** [comment]
could somehow the watcher being added on a back face ability not be registered?

**Comment by JayDi85** [comment]
If so then it’s a bug. Each card side must be initialized on start of the game. There is one exception — the outside cards. They added and init on first usage.

**Comment by JayDi85** [comment]
Well, another possible research - copy card code. Its gives new id for the card sides, so it can lost card scope watchers. Hmm. Its can be a real bug.

**Comment by JayDi85** [comment]
Original reason: watcher added with ability init, not a card. E.g. watcher from a second side will be added after transform resolve. Its a weird and can generate other hidden bugs for cards with watchers.
