### ISSUE TITLE
Network: some user commands must be synced (GameController->sendPlayerAction, related to ConcurrentModificationException)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11460]
From #11458 and #11437, related to random `ConcurrentModificationException` errors and other random bugs (e.g. with undo/rollback usage).

Original problem: 
* game executes by one thread (GAME xxx) but almost all user commands executes by another thread (CALL xxx) at random time. So if command thread changes game data (example: undo/rollback) the it can broke game in random time (user can call it in the middle of the slow game calculation and raise `ConcurrentModificationException`).

Recommended fixes:
* move game changes commands to GAME thread (example: undo) -- need sync code, see `asyncWantConcede` and `asyncWantCheat`, maybe needs in more easy sync code (there are too much client commands);
* keep other commands in original thread (example: updates of user skip settings -- it keep data inside game object, but it's hard to catch concurrent modification with it unlike the game changes from a previous point);

**Comment by JayDi85** [comment]
ConcurrentModificationException error example:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
    	at java.util.ArrayList$Itr.next(ArrayList.java:859)
    	at mage.abilities.effects.ContinuousEffects.preventedByRuleModification(ContinuousEffects.java:790)
    	at mage.game.GameState.replaceEvent(GameState.java:908)
    	at mage.game.GameState.replaceEvent(GameState.java:904)
    	at mage.game.GameImpl.replaceEvent(GameImpl.java:3286)
    	at mage.players.PlayerImpl.canLose(PlayerImpl.java:2589)
    	at mage.players.PlayerImpl.lost(PlayerImpl.java:2563)
    	at mage.players.PlayerImpl.concede(PlayerImpl.java:2483)
    	at mage.game.GameImpl.concede(GameImpl.java:1533)
    	at mage.server.game.GameController.sendPlayerAction(GameController.java:571)
    	at mage.server.game.GameManagerImpl.sendPlayerAction(GameManagerImpl.java:127)
    	at mage.server.MageServerImpl.lambda$null$39(MageServerImpl.java:826)
    	at java.util.Optional.ifPresent(Optional.java:159)
    	at mage.server.MageServerImpl.lambda$sendPlayerAction$40(MageServerImpl.java:824)
    	at mage.server.MageServerImpl.lambda$execute$69(MageServerImpl.java:1159)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```
