### ISSUE TITLE
Server's Error: Nullpointer Exception

### ISSUE THREAD

**Issue by Elucos90** [magefree/mage#11481]
Downloaded Xmage and redownloaded it after getting non stops pop-ups of Nullpointer Exception; here's some of the log:

	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:198)
	at mage.client.dialog.MageDialog.show(MageDialog.java:109)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:115)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1253)
	at mage.client.MageFrame.showError(MageFrame.java:1531)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:664)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:198)
	at mage.client.dialog.MageDialog.show(MageDialog.java:109)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:115)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1253)
	at mage.client.MageFrame.showError(MageFrame.java:1531)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:664)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:198)
	at mage.client.dialog.MageDialog.show(MageDialog.java:109)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:115)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1253)
	at mage.client.MageFrame.showError(MageFrame.java:1531)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:664)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:198)
	at mage.client.dialog.MageDialog.show(MageDialog.java:109)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:115)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1253)
	at mage.client.MageFrame.showError(MageFrame.java:1531)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:664)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$2(CallbackClientImpl.java:468)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:198)
	at mage.client.dialog.MageDialog.show(MageDialog.java:109)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:115)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:81)

Please help.

**Comment by JayDi85** [comment]
Whats error it say?

**Comment by xenohedron** [comment]
Another player in XDHS is reporting constant server error NPE, when spectating another game. Not even fixed by launching new client.

**Comment by xenohedron** [comment]
Seems to be an issue for all spectating

**Comment by Elucos90** [comment]
So it's not only me?

**Comment by JayDi85** [comment]
@Elucos90 yes, game watching fixed with today’s update. If you catch another error then report new issue.
