### ISSUE TITLE
Network: miss data, random disconnects, empty deck, not started game/trouney empty battlefield, instant loose, etc (report it here)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11526]
Report here all new network and connection related bugs

**Comment by catman123456** [comment]
Playing with [[Zhulodok, Void Gorger]] and its keeps disconnecting

![image](https://github.com/magefree/mage/assets/64045003/5e0e7413-a544-46e8-8dc4-5e3d87e80c4e)

 

INFO  2023-12-13 08:55:26,846 Starting MAGE server version 1.4.52-V7-beta3 (build: 2023-12-09 14:28)                     =>[main] Main.main 
INFO  2023-12-13 08:55:26,849 Logging level: INFO                                                                        =>[main] Main.main 
INFO  2023-12-13 08:55:26,849 Default charset: windows-1252                                                              =>[main] Main.main 
INFO  2023-12-13 08:55:26,851 Reading configuration from path=config\config.xml                                          =>[main] Main.main 
INFO  2023-12-13 08:55:27,075 Loading database...                                                                        =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,042 Database stats:                                                                            =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,043  - sets: 487                                                                               =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,043  - cards: 69708                                                                            =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,044  - tokens: 1747                                                                            =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,044  - emblems: 111                                                                            =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,044  - planes: 21                                                                              =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,044  - dungeons: 3                                                                             =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2023-12-13 08:55:36,044 Done.                                                                                      =>[main] Main.main 
INFO  2023-12-13 08:55:36,045 Loading extension packages...                                                              =>[main] Main.main 
INFO  2023-12-13 08:55:36,045 Done.                                                                                      =>[main] Main.main 
INFO  2023-12-13 08:55:36,046 Loading cards...                                                                           =>[main] Main.main 
INFO  2023-12-13 08:55:49,792 Done.                                                                                      =>[main] Main.main 
INFO  2023-12-13 08:55:49,793 Updating user stats DB...                                                                  =>[main] Main.main 
INFO  2023-12-13 08:55:50,034 Done.                                                                                      =>[main] Main.main 
INFO  2023-12-13 08:55:50,517 Config - max seconds idle: 600                                                             =>[main] Main.main 
INFO  2023-12-13 08:55:50,517 Config - max game threads: 10                                                              =>[main] Main.main 
INFO  2023-12-13 08:55:50,517 Config - max AI opponents: 15                                                              =>[main] Main.main 
INFO  2023-12-13 08:55:50,517 Config - min usr name le.: 3                                                               =>[main] Main.main 
INFO  2023-12-13 08:55:50,517 Config - max usr name le.: 14                                                              =>[main] Main.main 
INFO  2023-12-13 08:55:50,517 Config - min pswrd length: 8                                                               =>[main] Main.main 
INFO  2023-12-13 08:55:50,517 Config - max pswrd length: 100                                                             =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - inv.usr name pat: [^a-z0-9_]                                                      =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - save game active: false                                                           =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - backlog size    : 200                                                             =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - lease period    : 5000                                                            =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - sock wrt timeout: 10000                                                           =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - max pool size   : 300                                                             =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - num accp.threads: 2                                                               =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - second.bind port: -1                                                              =>[main] Main.main 
INFO  2023-12-13 08:55:50,518 Config - users registration: false                                                         =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - users anon: true                                                                  =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - mailgun api key :                                                                 =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - mailgun domain  :                                                                 =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - mail smtp Host  :                                                                 =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - mail smtpPort   :                                                                 =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - mail user       :                                                                 =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - mail passw. len.: 0                                                               =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - mail from addre.:                                                                 =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Config - google account  :                                                                 =>[main] Main.main 
INFO  2023-12-13 08:55:50,519 Loaded game types: 16, tourneys: 21, players: 3, cubes: 49, decks: 51                      =>[main] Main.main 
INFO  2023-12-13 08:55:56,743 Started MAGE server - listening on 0.0.0.0:17171/?serializationtype=java&maxPoolSize=300   =>[main] Main.main 
INFO  2023-12-13 09:03:58,241 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3ue8mu-9          =>[WorkerThread#1[192.168.0.11:54168]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:05:41,943 MATCH started [Game] a16f57a3-6758-49d7-bcac-d9b1a5536628 (catman123456)                   =>[CALL main-41] TableController.lambda$startMatch$7 
INFO  2023-12-13 09:05:42,024 GAME started 11883a01-9a5c-4e55-84c1-23843e140169 [Game] catman123456 - Computer 4 - Computer 2 - Computer 3 =>[CALL main-41] TableController.startGame 
INFO  2023-12-13 09:10:27,353 LOST CONNECTION - catman123456 [Match: 1 ] at 192.168.0.11, sessionId: 5c4o0b-767syp-lq3u3q73-1-lq3ue8mu-9 =>[Timer-0] Main$MageServerConnectionListener.handleConnectionException 
INFO  2023-12-13 09:10:29,849 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3ummvd-h, restoreSessionId 5c4o0b-767syp-lq3u3q73-1-lq3ue8mu-9 =>[WorkerThread#1[192.168.0.11:54503]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:10:49,846 LOST CONNECTION - catman123456 [Match: 1 ] at 192.168.0.11, sessionId: 5c4o0b-767syp-lq3u3q73-1-lq3ummvd-h =>[Timer-0] Main$MageServerConnectionListener.handleConnectionException 
INFO  2023-12-13 09:11:08,407 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3ungmn-p, restoreSessionId 5c4o0b-767syp-lq3u3q73-1-lq3ummvd-h =>[WorkerThread#5[192.168.0.11:54540]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:11:19,899 LOST CONNECTION - catman123456 [Match: 1 ] at 192.168.0.11, sessionId: 5c4o0b-767syp-lq3u3q73-1-lq3ungmn-p =>[Timer-0] Main$MageServerConnectionListener.handleConnectionException 
INFO  2023-12-13 09:11:25,318 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3untod-w, restoreSessionId 5c4o0b-767syp-lq3u3q73-1-lq3ungmn-p =>[WorkerThread#4[192.168.0.11:54561]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:11:45,317 LOST CONNECTION - catman123456 [Match: 1 ] at 192.168.0.11, sessionId: 5c4o0b-767syp-lq3u3q73-1-lq3untod-w =>[Timer-0] Main$MageServerConnectionListener.handleConnectionException 
INFO  2023-12-13 09:11:50,788 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3uodbv-14, restoreSessionId 5c4o0b-767syp-lq3u3q73-1-lq3untod-w =>[WorkerThread#3[192.168.0.11:54584]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:12:15,363 LOST CONNECTION - catman123456 [Match: 1 ] at 192.168.0.11, sessionId: 5c4o0b-767syp-lq3u3q73-1-lq3uodbv-14 =>[Timer-0] Main$MageServerConnectionListener.handleConnectionException 
INFO  2023-12-13 09:12:29,348 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3up731-1b, restoreSessionId 5c4o0b-767syp-lq3u3q73-1-lq3uodbv-14 =>[WorkerThread#4[192.168.0.11:54618]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:12:45,414 LOST CONNECTION - catman123456 [Match: 1 ] at 192.168.0.11, sessionId: 5c4o0b-767syp-lq3u3q73-1-lq3up731-1b =>[Timer-0] Main$MageServerConnectionListener.handleConnectionException 
INFO  2023-12-13 09:12:49,207 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3upmem-1i, restoreSessionId 5c4o0b-767syp-lq3u3q73-1-lq3up731-1b =>[WorkerThread#5[192.168.0.11:54640]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:13:09,798 Disconnecting another user instance for catman123456 (reason:  (session reconnect))        =>[WorkerThread#2[192.168.0.11:54663]] Session.connectUserHandling 
INFO  2023-12-13 09:13:09,800 catman123456 connected to server by sessionId 5c4o0b-767syp-lq3u3q73-1-lq3uq2ap-1p, restoreSessionId 5c4o0b-767syp-lq3u3q73-1-lq3upmem-1i =>[WorkerThread#2[192.168.0.11:54663]] SessionManagerImpl.connectUser 
INFO  2023-12-13 09:13:29,806 LOST CONNECTION - catman123456 [Match: 1 ] at 192.168.0.11, sessionId: 5c4o0b-767syp-lq3u3q73-1-lq3uq2ap-1p =>[Timer-0] Main$MageServerConnectionListener.handleConnectionException

**Comment by JayDi85** [comment]
@catman123456 

1. Are other games works fine with local server?
2. Can you show client logs too?

**Comment by JayDi85** [comment]
Catch while testing another bugs: 
* [x] if you try to create multiple tourneys and games then game can be freeze forever (not started). Must be researched (is it miss client message or a server side freeze).

**Comment by rgoes** [comment]
Hello, I am getting a lot of random disconnections. I have attached the client log for your analysis. One time it was disconnecting about every 30 seconds and reconnecting. But normally it freezes and I have to restart the client. Than it works for about 5 minutes and freezes again. Thank you for your amazing job. I love the platform. :)

	at java.util.TimerThread.run(Timer.java:505)
INFO  2025-11-01 01:03:18,595 Disconnected from client side                                                              =>[Thread-112] MageFrame.disconnected 
INFO  2025-11-01 01:03:18,595 Disconnecting...                                                                           =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2025-11-01 01:03:31,703 Disconnecting DONE                                                                         =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2025-11-01 01:03:31,703 Disconnected from server side                                                              =>[AWT-EventQueue-0] MageFrame.disconnected 
INFO  2025-11-01 01:03:41,629 Connect: trying to restore old session for user rgoest                                     =>[AWT-EventQueue-0] SessionHandler.connect 
INFO  2025-11-01 01:03:41,630 Connect: connecting to server beta.xmage.today:17171                                       =>[SwingWorker-pool-4-thread-4] SessionImpl$5.work 
INFO  2025-11-01 01:03:43,800 Connect: DONE                                                                              =>[SwingWorker-pool-4-thread-4] SessionImpl$5.work 
INFO  2025-11-01 01:03:43,801 Logging: as username rgoest to server beta.xmage.today:17171                               =>[SwingWorker-pool-4-thread-6] SessionImpl$4.work 
INFO  2025-11-01 01:03:46,259 Logging: DONE                                                                              =>[SwingWorker-pool-4-thread-6] SessionImpl$4.work 
INFO  2025-11-01 01:03:48,660 Game 9b1d1d07-22fa-4e09-827d-dfaaa51a6566 started for player 6137f5c8-6ec0-4346-b9f8-4e8d77e17dc8 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
WARN  2025-11-01 01:03:49,657 Found miss game data, requesting latest info... (possible reason: reconnect)               =>[AWT-EventQueue-0] CallbackClientImpl.lambda$onCallback$2 
INFO  2025-11-01 01:14:02,740 Ending game...                                                                             =>[AWT-EventQueue-0] FeedbackPanel.lambda$null$0 
INFO  2025-11-01 01:15:57,673 Connect: lost connection to server.                                                        =>[Thread-158] SessionImpl$MageClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
	at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
	at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
	at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
	at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
INFO  2025-11-01 01:15:57,674 Disconnected from client side                                                              =>[Thread-158] MageFrame.disconnected 
INFO  2025-11-01 01:15:57,674 Disconnecting...                                                                           =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2025-11-01 01:16:18,601 Disconnecting DONE                                                                         =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2025-11-01 01:16:18,601 Disconnected from server side                                                              =>[AWT-EventQueue-0] MageFrame.disconnected 
INFO  2025-11-01 01:16:20,709 Connect: trying to restore old session for user rgoest                                     =>[AWT-EventQueue-0] SessionHandler.connect 
INFO  2025-11-01 01:16:20,710 Connect: connecting to server beta.xmage.today:17171                                       =>[SwingWorker-pool-4-thread-4] SessionImpl$5.work 
WARN  2025-11-01 01:16:50,711 Cannot connect                                                                             =>[AWT-EventQueue-0] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:447)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:107)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:103)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.InvocationFailureException: Socket timed out.  Waited 26518 milliseconds for response while calling on InvokerLocator [bisocket://beta.xmage.today:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=java]; nested exception is: 
	java.net.SocketTimeoutException: Read timed out
	at org.jboss.remoting.transport.socket.SocketClientInvoker.handleException(SocketClientInvoker.java:137)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.handleOtherException(MicroSocketClientInvoker.java:1104)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:966)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2641)
	at java.io.ObjectInputStream$BlockDataInputStream.readBlockHeader(ObjectInputStream.java:2835)
	at java.io.ObjectInputStream$BlockDataInputStream.refill(ObjectInputStream.java:2905)
	at java.io.ObjectInputStream$BlockDataInputStream.read(ObjectInputStream.java:2977)
	at java.io.ObjectInputStream.read(ObjectInputStream.java:902)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.readVersion(MicroSocketClientInvoker.java:1366)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:920)
	... 15 more
INFO  2025-11-01 01:16:50,716 Disconnecting DONE                                                                         =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2025-11-01 01:16:50,717 Disconnected from server side                                                              =>[AWT-EventQueue-0] MageFrame.disconnected 
INFO  2025-11-01 01:16:55,011 Connect: trying to restore old session for user rgoest                                     =>[SwingWorker-pool-4-thread-6] SessionHandler.connect 
INFO  2025-11-01 01:16:55,012 Connect: connecting to server beta.xmage.today:17171                                       =>[SwingWorker-pool-4-thread-7] SessionImpl$5.work 
WARN  2025-11-01 01:17:25,014 Cannot connect                                                                             =>[SwingWorker-pool-4-thread-6] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:447)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:107)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:103)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://beta.xmage.today:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=java]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createClientSocket(SocketClientInvoker.java:175)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1220)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2663)
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2679)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at org.jboss.remoting.loading.ObjectInputStreamWithClassLoader.<init>(ObjectInputStreamWithClassLoader.java:100)
	at org.jboss.remoting.serialization.impl.java.JavaSerializationManager.createInput(JavaSerializationManager.java:54)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:75)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:58)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createInputStream(ClientSocketWrapper.java:206)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createStreams(ClientSocketWrapper.java:189)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.<init>(ClientSocketWrapper.java:67)
	... 21 more
INFO  2025-11-01 01:17:25,016 Disconnecting DONE                                                                         =>[SwingWorker-pool-4-thread-6] SessionImpl.connectStop 
INFO  2025-11-01 01:17:25,016 Disconnected from client side                                                              =>[SwingWorker-pool-4-thread-6] MageFrame.disconnected 
INFO  2025-11-01 01:17:34,300 Connect: trying to restore old session for user rgoest                                     =>[SwingWorker-pool-4-thread-8] SessionHandler.connect 
INFO  2025-11-01 01:17:34,301 Connect: connecting to server beta.xmage.today:17171                                       =>[SwingWorker-pool-4-thread-2] SessionImpl$5.work 
INFO  2025-11-01 01:17:36,504 Connect: DONE                                                                              =>[SwingWorker-pool-4-thread-2] SessionImpl$5.work 
INFO  2025-11-01 01:17:36,504 Logging: as username rgoest to server beta.xmage.today:17171                               =>[SwingWorker-pool-4-thread-9] SessionImpl$4.work 
INFO  2025-11-01 01:17:39,441 Logging: DONE                                                                              =>[SwingWorker-pool-4-thread-9] SessionImpl$4.work 
INFO  2025-11-01 01:19:43,530 Disconnecting...                                                                           =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2025-11-01 01:19:43,532 Disconnecting DONE                                                                         =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2025-11-01 01:19:43,532 Disconnected from server side                                                              =>[AWT-EventQueue-0] MageFrame.disconnected 
INFO  2025-11-01 01:19:50,434 Connect: trying to restore old session for user rgoest                                     =>[SwingWorker-pool-4-thread-7] SessionHandler.connect 
INFO  2025-11-01 01:19:50,435 Connect: connecting to server beta.xmage.today:17171                                       =>[SwingWorker-pool-4-thread-4] SessionImpl$5.work 
INFO  2025-11-01 01:19:51,890 Connect: DONE                                                                              =>[SwingWorker-pool-4-thread-4] SessionImpl$5.work 
INFO  2025-11-01 01:19:51,890 Logging: as username rgoest to server beta.xmage.today:17171                               =>[SwingWorker-pool-4-thread-6] SessionImpl$4.work 
INFO  2025-11-01 01:19:55,193 Logging: DONE                                                                              =>[SwingWorker-pool-4-thread-6] SessionImpl$4.work 
INFO  2025-11-01 01:26:11,215 Game 18e90e76-5917-4e77-8fe6-3b9dc3fd6407 started for player b78e953a-cf5c-4c2f-a1b9-d4c6e63e118e =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
FATAL 2025-11-01 01:27:44,233 Connection error: other                                                                    =>[SwingWorker-pool-4-thread-10] SessionImpl.handleThrowable 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy9.roomGetAllTables(Unknown Source)
	at mage.remote.SessionImpl.getTables(SessionImpl.jav
INFO  2025-11-01 03:01:58,960 Connect: DONE                                                                              =>[SwingWorker-pool-4-thread-10] SessionImpl$5.work 
INFO  2025-11-01 03:01:58,960 Logging: as username rgoest to server beta.xmage.today:17171                               =>[SwingWorker-pool-4-thread-2] SessionImpl$4.work 
INFO  2025-11-01 03:02:02,536 Connect: lost connection to server.                                                        =>[Thread-40] SessionImpl$MageClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
	at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
	at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
	at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
	at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
ERROR 2025-11-01 03:02:12,894 Can't receive server state before other data (possible reason: unstable network): message 1 - MESSAGE - CHATMESSAGE =>[ThreadPool(2)-1] SessionImpl$CallbackHandler.handleCallback 
INFO  2025-11-01 03:03:50,840 Starting MAGE CLIENT version: 1.4.58-V1 (build: 2025-10-06 20:20)                          =>[main] MageFrame.main 
INFO  2025-11-01 03:03:50,841 Java version: 1.8.0_201                                                                    =>[main] MageFrame.main 
INFO  2025-11-01 03:03:50,841 Logging level: INFO

**Comment by JayDi85** [comment]
Make sure your proxy/vpn do not have sleep timeout. Also mobile wifi/internet can go sleep or disconnect time by time due bad network or energy save mode (both in your machine or mobile). Stable connection is very important for xmage. Xmage can’t silently restore connection like web browsers or other online apps.
