### ISSUE TITLE
Fatal client UI error (html text rendering)

### ISSUE THREAD

**Issue by ssk97** [magefree/mage#11612]
[message.txt](https://github.com/magefree/mage/files/13847310/message.txt)

![image](https://github.com/magefree/mage/assets/8648826/111fbe82-2fa8-42ef-a5b6-9e052101ef7c)

Reporting for another player, occurred right as Thundering Tanadon was attempted to be played from hand during precombat main phase. Note the [[Dormant Grove]] having triggered in the game log. The client then locked up and no actions were able to be taken. Opening a new client and reconnecting fixed the issue.

The tournament included [[Future Sight]] and [[Spellbook]] emblems for all players but they don't seem related to the issue.

**Comment by JayDi85** [comment]
Something wrong with editor pane and html text drawing (game logs, chats, card hint in text mode, etc).

Stack trace from attached file:

```
FATAL 2024-01-05 16:20:43,884 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
javax.swing.text.StateInvariantError: GlyphView: Stale view: javax.swing.text.BadLocationException: Invalid location
	at javax.swing.text.GlyphView.getText(GlyphView.java:137)
	at javax.swing.text.GlyphPainter1.getSpan(GlyphPainter1.java:60)
	at javax.swing.text.GlyphView.getPreferredSpan(GlyphView.java:592)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:732)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
	at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:270)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
```

**Comment by JayDi85** [comment]
for info it's not html related -- it's about edt thread and game components update outside of the swing thread -- xmage redraw battlefield on battlefield resize -- if it's starting the same time as game update income then can cause such errors (one of the example -- another example card dragging while game update income and many other use cases)

**Comment by matoro** [comment]
so this would also be fixed by https://github.com/magefree/mage/pull/14819 ?

**Comment by JayDi85** [comment]
Yes, it's partly fix some non swing threads usage, but not all. Like long living #11285 to collect stability/crashes bugs.
