### ISSUE TITLE
Launcher issue

### ISSUE THREAD

**Issue by SilentWraith** [magefree/mage#1161]
When I try to launch the client, an empty black box appears.
Then, when I try to check the version it reads:"
Reading config from http://xmage.de/xmage/config.json/config.json
Error reading config from http://xmage.de/xmage/config.json/config.json
Possible causes:  Site is offline or internet connection is unavailable."
Can someone help?

**Comment by LevelX2** [comment]
Remove the config.json from your xmage home setting in the launcher settings.

**Comment by LJSparks** [comment]
I'm having the same issue, but when i check the version it reads:
"You are running the latest version of Xmage" 


(xmage_launcher.log)

ERROR 2015-08-08 22:47:25,721 Error staring process                                                                      =>[AWT-EventQueue-0] Utilities.launchProcess
java.io.IOException: Cannot run program "C:\Users\Lillian\Desktop\XMage\java\jre1.7.0_75\bin\java" (in directory "C:\Users\Lillian\Desktop\XMage\xmage\mage-client"): CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.xmage.launcher.Utilities.launchProcess(Utilities.java:142)
	at com.xmage.launcher.Utilities.launchClientProcess(Utilities.java:101)
	at com.xmage.launcher.XMageLauncher.handleClient(XMageLauncher.java:380)
	at com.xmage.launcher.XMageLauncher.access$300(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$4.actionPerformed(XMageLauncher.java:223)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 43 more

**Comment by mtgburchmtg** [comment]
levelx2. I am having the same problem as silentwraith. my xmage home setting in the launcher settings says "http://xmage.de/xmage" and it doesn't say config.json at all under the home setting. Please help. I want to play magic.

**Comment by LevelX2** [comment]
What exactly is written to the text box?

**Comment by cader9** [comment]
Im having the same problem, when i try to launch xmage it says 
"Error reading config from http://xmage.de/xmage/config.json
Possible causes:  Site is offline or internet connection is unavailable."
any  help would be appreciated.

**Comment by LevelX2** [comment]
Web server was offline. It's online again now.

**Comment by MrBeef23** [comment]
I am having the same problem. I try to launch, it says
Reading config from http://xmage.de/xmage/config.json/config.json
Error reading config from http://xmage.de/xmage/config.json/config.json
Possible causes:  Site is offline or internet connection is unavailable.
My xmage home is http://xmage.de/xmage
What's the problem?

**Comment by LevelX2** [comment]
It should be  http://xmage.de/xmage/config.json
instead of http://xmage.de/xmage/config.json/config.json
so do remove /config.json at the end of your custom xmage home setting.

**Comment by MrBeef23** [comment]
I did that, and it still fails to read:
Reading config from http://xmage.de/xmage/config.json
Error reading config from http://xmage.de/xmage/config.json
Possible causes:  Site is offline or internet connection is unavailable.
