### ISSUE TITLE
Suddenly cannot connect to Localhost

### ISSUE THREAD

**Issue by KithekHunter** [magefree/mage#11758]
Randomly this week I was suddenly unable to connect to the localhost on Xmage to play against AI. I have been using Xmage for months with zero issues and then suddenly I cannot connect to the localhost. 

I can connect to the BETA server no problem but not the localhost (which is what I primarily use for deck testing).

The error messages I am receiving in the client window: 

INFO  2024-02-04 11:47:13,708 Connect: connecting to server localhost:17171                                              =>[SwingWorker-pool-4-thread-7] SessionImpl$5.work 
WARN  2024-02-04 11:47:34,896 Cannot connect                                                                             =>[SwingWorker-pool-4-thread-6] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:449)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:105)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:101)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://192.168.40.111:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=java]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
INFO  2024-02-04 11:47:34,897 Disconnecting DONE                                                                         =>[SwingWorker-pool-4-thread-6] SessionImpl.connectStop 
INFO  2024-02-04 11:47:34,897 Disconnected from client side                                                              =>[SwingWorker-pool-4-thread-6] MageFrame.disconnected 

I've been looking around to see if anyone is having the same issues but the topics are so spread out and years apart that it's hard for me to apply solutions when most people just "reinstall fixed it for me". I have already deleted all files and re-downloaded and installed Xmage and it hasn't fixed this issue. Any help would be greatly appreciated.

**Comment by JayDi85** [comment]
Have you had any successful connection attempts to localhost at all (after machine restart and local server run)?

**Comment by JayDi85** [comment]
Try to use 127.0.0.1 instead localhost address

**Comment by KithekHunter** [comment]
> Have you had any successful connection attempts to localhost at all (after machine restart and local server run)?

Prior to about 3 days ago I was able to connect fine. Since then I have had zero successful connections to localhost at all. Including after restarts of the PC and deleting all xmage files, re-downloading, and re-installing.

**Comment by KithekHunter** [comment]
> Try to use 127.0.0.1 instead localhost address

INFO  2024-02-04 13:24:45,662 Connect: connecting to server 127.0.0.1:17171                                              =>[SwingWorker-pool-4-thread-3] SessionImpl$5.work 
FATAL 2024-02-04 13:28:26,152 Connect: unknown IO error                                                                  =>[SwingWorker-pool-4-thread-2] SessionImpl.doRemoteWorkAndHandleErrors 
java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.jboss.remoting.transport.bisocket.BisocketServerInvoker$2.run(BisocketServerInvoker.java:403)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.remoting.transport.bisocket.BisocketServerInvoker.createControlConnection(BisocketServerInvoker.java:395)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:459)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.addCallbackListener(Client.java:2153)
	at org.jboss.remoting.Client.addListener(Client.java:1258)
	at org.jboss.remoting.Client.addListener(Client.java:1144)
	at org.jboss.remoting.Client.addListener(Client.java:1127)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:456)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:105)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:101)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2024-02-04 13:28:26,155 Disconnecting...                                                                           =>[SwingWorker-pool-4-thread-2] SessionImpl.connectStop 
INFO  2024-02-04 13:28:26,181 Disconnecting DONE                                                                         =>[SwingWorker-pool-4-thread-2] SessionImpl.connectStop 
INFO  2024-02-04 13:28:26,181 Disconnected from client side                                                              =>[SwingWorker-pool-4-thread-2] MageFrame.disconnected 

this is what I get when trying to use 127.0.0.1

**Comment by JayDi85** [comment]
1.

Open command line and enter:
* ping local host
* ping 127.0.0.1

Copy ping results here and write your OS (Windows, Linux or MAC).

2.

Open xmage/mage-server/config/config.xml in text editor and make sure it contains:
* server serverAddress="0.0.0.0"
If not then change to it and try again.

**Comment by KithekHunter** [comment]
ping results: 

Pinging DESKTOP-PILK4S0 [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

C:\Users\kithi>ping 127.0.0.1

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

server config:

    <server serverAddress="0.0.0.0"
            serverName="mage-server"
            port="17171"
            secondaryBindPort="-1"
            backlogSize="200"
            numAcceptThreads="2"
            maxPoolSize="300"
            leasePeriod="5000"
            socketWriteTimeout="10000"
            maxGameThreads="10"
            maxSecondsIdle="600"
            minUserNameLength="3"
            maxUserNameLength="14"
            invalidUserNamePattern="[^a-z0-9_]"
            minPasswordLength="8"
            maxPasswordLength="100"
            maxAiOpponents="15"
            saveGameActivated="false"
            authenticationActivated="false"
            googleAccount=""
            mailgunApiKey=""
            mailgunDomain=""
            mailSmtpHost=""
            mailSmtpPort=""
            mailUser=""
            mailPassword=""
            mailFromAddress=""
    />
    
    windows OS

**Comment by JayDi85** [comment]
Run local server and show latest logs from it: is it really running and waiting connection

**Comment by KithekHunter** [comment]
> Run local server and show latest logs from it: is it really running and waiting connection

INFO  2024-02-04 13:53:52,506 Started MAGE server - listening on 0.0.0.0:17171/?serializationtype=java&maxPoolSize=300   =>[main] Main.main 

is what the server window says

**Comment by JayDi85** [comment]
Ok, the last one thing — run client and show starting logs here (1-3 lines from it)

**Comment by KithekHunter** [comment]
> Ok, the last one thing — run client and show starting logs here (1-3 lines from it)

Feb 04, 2024 2:05:51 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2024-02-04 14:05:51,138 Starting MAGE client version 1.4.52-V7-beta7 (build: 2024-01-30 18:53)                     =>[main] MageFrame.main 
INFO  2024-02-04 14:05:51,139 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2024-02-04 14:05:51,139 Default charset: UTF-8                                                                     =>[main] MageFrame.main 
INFO  2024-02-04 14:05:51,324 Custom (or bundled) Java certificate file (cacerts) file found                             =>[AWT-EventQueue-0] MageFrame.<init> 

first few lines from client upon startup

**Comment by JayDi85** [comment]
Well, I can't see any problems with settings. It can be firewall or other third party software.

Close all xmage apps (make sure no java.exe apps in task manager). Move whole files (launcher, xmage, java and other files) to new folder like d:\games\xmage2\ and run server/client -- windows firewall must ask you again about network access.

**Comment by ssk97** [comment]
> WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

Possibly that's the problem? Try running xmage in administrator mode maybe? Just guessing here.

**Comment by JayDi85** [comment]
Nope, its a standard error on new machines (error with java settings store). Admin access needs to run from Program Files or another read only folders and it will be “visible” as miss launcher updates and broken images download.

**Comment by KithekHunter** [comment]
I checked my firewall and antivirus settings, even turned them off and still unable to connect. Continuously says server is likely offline. I can connect to BETA just fine, still. 

Its incredibly frustrating seeing as though I've been using localhost just fine for months. Its pretty much the only thing I use Xmage for.

**Comment by JayDi85** [comment]
* Run notepad as admin
* Open file: `C:\Windows\System32\drivers\etc\hosts`
* Make sure it contains line: `127.0.0.1 localhost`
* Save and restart server and client

![shot_240205_003751](https://github.com/magefree/mage/assets/8344157/084abd8e-244b-4a01-beef-c586c866438d)

**Comment by JayDi85** [comment]
If not helps then add additional line to it like: `127.0.0.1 myxmage`, restart client/server and connect as myxmage instead localhost.

**Comment by KithekHunter** [comment]
> If not helps then add additional line to it like: `127.0.0.1 myxmage`, restart client/server and connect as myxmage instead localhost.

INFO  2024-02-04 15:01:44,577 Connect: connecting to server myxmage:17171                                                =>[SwingWorker-pool-4-thread-3] SessionImpl$5.work 
FATAL 2024-02-04 15:05:26,509 Connect: unknown IO error                                                                  =>[SwingWorker-pool-4-thread-2] SessionImpl.doRemoteWorkAndHandleErrors 
java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.jboss.remoting.transport.bisocket.BisocketServerInvoker$2.run(BisocketServerInvoker.java:403)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.remoting.transport.bisocket.BisocketServerInvoker.createControlConnection(BisocketServerInvoker.java:395)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:459)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.addCallbackListener(Client.java:2153)
	at org.jboss.remoting.Client.addListener(Client.java:1258)
	at org.jboss.remoting.Client.addListener(Client.java:1144)
	at org.jboss.remoting.Client.addListener(Client.java:1127)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:456)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:105)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:101)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2024-02-04 15:05:26,512 Disconnecting...                                                                           =>[SwingWorker-pool-4-thread-2] SessionImpl.connectStop 
INFO  2024-02-04 15:05:26,538 Disconnecting DONE                                                                         =>[SwingWorker-pool-4-thread-2] SessionImpl.connectStop 
INFO  2024-02-04 15:05:26,539 Disconnected from client side                                                              =>[SwingWorker-pool-4-thread-2] MageFrame.disconnected 

I try that and it waits for 4-5 mins and then displays that with "timed out"

**Comment by JayDi85** [comment]
Ok, the last one magic:
* run command line as admin;
* enter: `netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 precedence=51 label=4 store=persistent`
* restart client and server.

**Comment by KithekHunter** [comment]
> Ok, the last one magic:
> 
>     * run command line as admin;
> 
>     * enter: `netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 precedence=51 label=4 store=persistent`
> 
>     * restart client and server.

Ran the command line, got the "Ok." response. Restarted Xmage and got the exact same error as posted above when trying to connect to "myxmage"

**Comment by JayDi85** [comment]
You must restart server too

**Comment by KithekHunter** [comment]
> You must restart server too

Still nothing. Restarted everything and still cannot connect.

**Comment by JayDi85** [comment]
Well, then nothing to do with it.
