### ISSUE TITLE
ConcurrentModificationException when drafting with 7 madbot, after deck construction before entering game

### ISSUE THREAD

**Issue by phughk** [magefree/mage#11848]
When playing a draft (Booster Draft Elimination, 3x Alpha) at a table of 8 (self + 7 madbot), the games start without me being able to join my table.

Instead of joining my game table, I am presented the tournament status window where I can spectate games. I can watch other games, but I cannot watch my own.

The following stack trace appears in the logs.

Steps to reproduce:
1. Start Booster Draft Elimination with 7 madbot (level 2)
2. Draft as normal
3. Construct deck as normal
4. Submit Deck
5. <BUG> Haven't joined table. Cannot join table. Cannot watch own game.

Expected:
5. Player joins the table where they are playing

```
INFO  2024-02-24 10:57:32,401 Client start up time: 13 seconds                                                           =>[AWT-EventQueue-0] MageFrame.lambda$new$3 
INFO  2024-02-24 11:06:56,418 Connect: trying to restore old session for user hugh                                       =>[SwingWorker-pool-3-thread-2] SessionHandler.connect 
INFO  2024-02-24 11:06:56,422 Connect: connecting to server localhost:17171                                              =>[SwingWorker-pool-3-thread-3] SessionImpl$5.work 
INFO  2024-02-24 11:06:56,712 Connect: DONE                                                                              =>[SwingWorker-pool-3-thread-3] SessionImpl$5.work 
INFO  2024-02-24 11:06:56,713 Logging: as username hugh to server localhost:17171                                        =>[SwingWorker-pool-3-thread-4] SessionImpl$4.work 
INFO  2024-02-24 11:06:57,735 Logging: DONE                                                                              =>[SwingWorker-pool-3-thread-4] SessionImpl$4.work 
INFO  2024-02-24 11:07:49,382 Tournament d0719722-d872-40d8-828a-437e77ae9718 started for player 028d17a2-e564-4487-b50a-be46c81a8ceb =>[AWT-EventQueue-0] CallbackClientImpl.tournamentStarted 
INFO  2024-02-24 11:07:49,468 Draft f832a2e9-8e41-4010-85e5-f6ff0fa9397b started for player 028d17a2-e564-4487-b50a-be46c81a8ceb =>[AWT-EventQueue-0] CallbackClientImpl.draftStarted 
INFO  2024-02-24 11:11:22,655 Game ee533703-d7c5-4457-a972-6df740336774 started for player 028d17a2-e564-4487-b50a-be46c81a8ceb =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
INFO  2024-02-24 11:22:08,110 Ending game...                                                                             =>[AWT-EventQueue-0] FeedbackPanel.lambda$null$0 
INFO  2024-02-24 11:22:44,405 Tournament 1ce8b94d-fb2a-4892-ae68-ccd54ddd927f started for player bcc9ebfe-4ad4-4eff-9bf9-c2570f22f97c =>[AWT-EventQueue-0] CallbackClientImpl.tournamentStarted 
INFO  2024-02-24 11:22:44,558 Draft 418df02c-cb15-4994-88d8-3d61790ffdba started for player bcc9ebfe-4ad4-4eff-9bf9-c2570f22f97c =>[AWT-EventQueue-0] CallbackClientImpl.draftStarted 
FATAL 2024-02-24 11:31:00,237 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at mage.client.cards.CardsList.drawCards(CardsList.java:271)
	at mage.client.cards.CardsList.loadCards(CardsList.java:474)
	at mage.client.cards.CardsList.loadCards(CardsList.java:466)
	at mage.client.cards.CardsList.loadCards(CardsList.java:253)
	at mage.client.draft.DraftPanel.loadCardsToPickedCardsArea(DraftPanel.java:416)
	at mage.client.draft.DraftPanel.lambda$loadBooster$52a9c88f$2(DraftPanel.java:367)
	at mage.client.util.EventDispatcher.fireEvent(EventDispatcher.java:30)
	at mage.client.cards.CardEventSource.fireEvent(CardEventSource.java:58)
	at mage.client.cards.CardEventSource.fireEvent(CardEventSource.java:38)
	at mage.client.draft.DraftGrid.lambda$new$2fe10b0c$1(DraftGrid.java:73)
	at mage.client.util.EventDispatcher.fireEvent(EventDispatcher.java:30)
	at mage.client.cards.CardEventSource.fireEvent(CardEventSource.java:58)
	at mage.client.plugins.adapters.MageActionCallback.mouseClicked(MageActionCallback.java:140)
	at org.mage.card.arcane.CardPanel.mouseClicked(CardPanel.java:624)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
INFO  2024-02-24 11:34:22,030 Watching game bfbecb35-b08c-4be3-86f0-4f591174e208                                         =>[AWT-EventQueue-0] TournamentPanel$1.actionPerformed 
INFO  2024-02-24 11:34:22,198 Watching game bfbecb35-b08c-4be3-86f0-4f591174e208                                         =>[AWT-EventQueue-0] CallbackClientImpl.watchGame 
INFO  2024-02-24 11:34:32,562 Watching game 846786d3-e55a-4417-b98d-f54989866dc8                                         =>[AWT-EventQueue-0] TournamentPanel$1.actionPerformed 
INFO  2024-02-24 11:34:33,328 Watching game 846786d3-e55a-4417-b98d-f54989866dc8                                         =>[AWT-EventQueue-0] TournamentPanel$1.actionPerformed 
INFO  2024-02-24 11:34:33,878 Watching game 846786d3-e55a-4417-b98d-f54989866dc8                                         =>[AWT-EventQueue-0] TournamentPanel$1.actionPerformed 
INFO  2024-02-24 11:34:34,078 Watching game 846786d3-e55a-4417-b98d-f54989866dc8                                         =>[AWT-EventQueue-0] TournamentPanel$1.actionPerformed 
INFO  2024-02-24 11:34:34,212 Watching game 846786d3-e55a-4417-b98d-f54989866dc8                                         =>[AWT-EventQueue-0] TournamentPanel$1.actionPerformed 
```

**Comment by phughk** [comment]
Feel free to assign to me

**Comment by JayDi85** [comment]
something wrong on client side lead to error on game start, so no game gui -- but if you try to quite and login then there is will be new user and you can't join as old one.

solution: close app with keep session (wait for me) and reconnect again -- it allow to join failed game in few minutes, e.g. on client crash or disconnect.
