### ISSUE TITLE
Java 9: NoSuchMethodException waiting for player response in duel

### ISSUE THREAD

**Issue by phughk** [magefree/mage#11856]
When compiling server and client, and then launching server and client using OpenJDK Java 9.0.4, and starting a 2 player game against a madbot, the following error occurs in the logs

```
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceElement(int)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2432)
        at mage.util.TraceHelper.<clinit>(DebugUtil.java:55)
        at mage.util.DebugUtil.getMethodNameWithSource(DebugUtil.java:40)
        at mage.player.human.HumanPlayer.waitForResponse(HumanPlayer.java:315)
        at mage.player.human.HumanPlayer.chooseMulligan(HumanPlayer.java:386)
        at mage.game.mulligan.Mulligan.executeMulliganPhase(Mulligan.java:55)
        at mage.game.mulligan.LondonMulligan.executeMulliganPhase(LondonMulligan.java:54)
        at mage.game.GameImpl.init(GameImpl.java:1286)
        at mage.game.TwoPlayerDuel.init(TwoPlayerDuel.java:35)
        at mage.game.GameImpl.start(GameImpl.java:989)
        at mage.server.game.GameWorker.call(GameWorker.java:34)
        at mage.server.game.GameWorker.call(GameWorker.java:15)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at mage.util.TraceHelper.getMethodNameWithSource(DebugUtil.java:74)
        at mage.util.DebugUtil.getMethodNameWithSource(DebugUtil.java:40)
        at mage.player.human.HumanPlayer.waitForResponse(HumanPlayer.java:315)
        at mage.player.human.HumanPlayer.chooseMulligan(HumanPlayer.java:386)
        at mage.game.mulligan.Mulligan.executeMulliganPhase(Mulligan.java:55)
        at mage.game.mulligan.LondonMulligan.executeMulliganPhase(LondonMulligan.java:54)
        at mage.game.GameImpl.init(GameImpl.java:1286)
        at mage.game.TwoPlayerDuel.init(TwoPlayerDuel.java:35)
        at mage.game.GameImpl.start(GameImpl.java:989)
        at mage.server.game.GameWorker.call(GameWorker.java:34)
        at mage.server.game.GameWorker.call(GameWorker.java:15)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

This ticket is related to #6197

**Comment by JayDi85** [comment]
Real reason: java 9+ [replaced getStackTraceElement with new class StackWalker](https://stackoverflow.com/questions/53866372/reflection-api-is-throwing-no-such-method-exception-while-migrating-to-java-9), so current debug tool fail to find source code method to print in log.

It’s not a critical code so can be fixed by error ignoring and returning text like “unsupport in java 9+”. After full java 17 migration it can be returned.

![IMG_9763](https://github.com/magefree/mage/assets/8344157/6847208d-5169-44b8-a827-d252eb98081b)
