### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jayzz911** [magefree/mage#11870]
Seems a little unclear but whenever im testing a deck against 3 (level 2) bots and i play a terastodon, I get an exception:

FATAL 2024-02-27 22:12:46,146 GameWorker system error [0f90bfa0-6301-4360-b5bf-3d8686548092 - Commander Free For All; T27.M1; active: Jayzz911; stack: 1 (top: Cast Terastodon)]: java.lang.OutOfMemoryError: GC overhead limit exceeded =>[GAME 0f90bfa0-6301-4360-b5bf-3d8686548092] GameWorker.call 
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1750)
	at java.util.HashMap.putVal(HashMap.java:631)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at mage.abilities.mana.ActivatedManaAbilityImpl.getProducableManaTypes(ActivatedManaAbilityImpl.java:115)
	at mage.MageObjectImpl.getFrameColor(MageObjectImpl.java:229)
	at mage.game.permanent.PermanentCard.copyFromCard(PermanentCard.java:122)
	at mage.game.permanent.PermanentCard.reset(PermanentCard.java:97)
	at mage.game.permanent.Battlefield.reset(Battlefield.java:37)
	at mage.game.GameState.applyEffects(GameState.java:670)
	at mage.game.GameImpl.applyEffects(GameImpl.java:1880)
	at mage.game.GameImpl.playPriority(GameImpl.java:1655)
	at mage.game.turn.Step.priority(Step.java:67)
	at mage.game.turn.Phase.playStep(Phase.java:204)
	at mage.game.turn.Phase.play(Phase.java:90)
	at mage.game.turn.Turn.play(Turn.java:137)
	at mage.game.GameImpl.playTurn(GameImpl.java:1117)
	at mage.game.GameImpl.play(GameImpl.java:1024)
	at mage.game.GameImpl.start(GameImpl.java:1000)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at mage.server.game.GameWorker.call(GameWorker.java:15)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

 Let me know if you need any additional info.

**Comment by jayzz911** [comment]
I have allocated 8GBs out of my 32GBs of ram and the client indicates 1,3GB used. (I know this is the server but I don't know what the usage is there).

**Comment by JayDi85** [comment]
Show battlefield screenshot
 [[Terastodon]]

**Comment by jayzz911** [comment]
Sure thing

![Field](https://github.com/magefree/mage/assets/17490574/7ae457bb-9beb-411a-8363-7ccb1c3d0b4b)
![Client console](https://github.com/magefree/mage/assets/17490574/db08f8f2-aa83-4ec2-851b-6b5e6ef9372b)

**Comment by jayzz911** [comment]
Let mo know if you need something else

**Comment by JayDi85** [comment]
Try to increase server memory too (same launcher param but for server field). Maybe it can help. Use 2 GB as example.

**Comment by jayzz911** [comment]
I did but it made no difference

**Comment by jayzz911** [comment]
![image](https://github.com/magefree/mage/assets/17490574/058d0909-3224-42d6-a268-49425375964e)
At 4 gigs of the server and after knocking out the other 2 bots I got to the part where you pick targets but it still crashed before i got to pick one
