### ISSUE TITLE
XMage Client Console Blank

### ISSUE THREAD

**Issue by LJSparks** [magefree/mage#1190]
Got Java up n' running.
Dl'd and installed Xmage
Open Client and....
[Blank] many, many mins of  [Blank]

I'm having the same issue as with #1161, but when i check the version it reads:
"You are running the latest version of Xmage"

(xmage_launcher.log)

ERROR 2015-08-08 22:47:25,721 Error staring process =>[AWT-EventQueue-0] Utilities.launchProcess
java.io.IOException: Cannot run program "C:\Users\Lillian\Desktop\XMage\java\jre1.7.0_75\bin\java" (in directory "C:\Users\Lillian\Desktop\XMage\xmage\mage-client"): CreateProcess error=267, The directory name is invalid
at java.lang.ProcessBuilder.start(Unknown Source)
at com.xmage.launcher.Utilities.launchProcess(Utilities.java:142)
at com.xmage.launcher.Utilities.launchClientProcess(Utilities.java:101)
at com.xmage.launcher.XMageLauncher.handleClient(XMageLauncher.java:380)
at com.xmage.launcher.XMageLauncher.access$300(XMageLauncher.java:58)
at com.xmage.launcher.XMageLauncher$4.actionPerformed(XMageLauncher.java:223)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
at java.lang.ProcessImpl.create(Native Method)
at java.lang.ProcessImpl.(Unknown Source)
at java.lang.ProcessImpl.start(Unknown Source)
... 43 more
 Help?

**Comment by LJSparks** [comment]
I have gotten it exempt threw the firewall. but made no difference.

**Comment by hanasu** [comment]
It sounds like your Java path is incorrect. First, if you go to C:\Users\Lillian\Desktop\XMage\java\jre1.7.0_75\bin\java is there anything actually there? Do you see a java.exe? Try to uninstall all versions of Java and install the latest (version 8 update 60) here: http://www.java.com/en/download/. If that does not help try setting your path manually using this guide: http://java.com/en/download/help/path.xml

**Comment by Zerrisx** [comment]
This looks to be resolved and/or obsolete
