### ISSUE TITLE
Error setting up client lease upon performing connect - Ubuntu

### ISSUE THREAD

**Issue by LeonHammerla** [magefree/mage#11954]
Trying to host localhost server:

OS: Ubuntu 20.04

Main Java Version is Java 11

For starting Server and Client i use a secondary Java 8 Version, for that i changed startClient and startServer .sh scripts:

```
#!/bin/sh

PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/:$PATH java -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -jar ./lib/mage-client-1.4.50.jar &
```

```
#!/bin/sh

PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/:$PATH java -Xms256M -Xmx512M -Dfile.encoding=UTF-8 -Djava.security.policy=./config/security.policy -Dlog4j.configuration=file:./config/log4j.properties -jar ./lib/mage-server-1.4.50.jar

```

Error:

```
Connect: connecting to server localhost:17171                                              =>[SwingWorker-pool-3-thread-3] SessionImpl$5.work 
WARN  2024-03-17 01:02:54,685 Cannot connect                                                                             =>[SwingWorker-pool-3-thread-2] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:415)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.InvocationFailureException: Socket timed out.  Waited 29993 milliseconds for response while calling on InvokerLocator [bisocket://172.17.0.1:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=jboss]; nested exception is: 
	java.net.SocketTimeoutException: Read timed out
	at org.jboss.remoting.transport.socket.SocketClientInvoker.handleException(SocketClientInvoker.java:137)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.handleOtherException(MicroSocketClientInvoker.java:1104)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:966)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.jboss.serial.io.JBossObjectInputStream.read(JBossObjectInputStream.java:193)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.readVersion(MicroSocketClientInvoker.java:1366)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:920)

```

**Comment by JayDi85** [comment]
> 172.17.0.1

Is it real server machine address? Describe your machine/network configuration for client and server apps running (is it diff/same machines, are there router, what’s type of network, etc).
