### ISSUE TITLE
Some errors from server logs

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12131]
1. Concurrent modification exception
> FATAL 2024-03-16 05:46:03,951 GameWorker system error [83e9ee0e-ed2c-4288-8767-4c645fc9494d - Two Player Duel; T26.CL; active: MichaelAngello; stack: 0]: java.util.ConcurrentModificationException =>[GAME 83e9ee0e-ed2c-4288-8767-4c645fc9494d] GameWorker.call 
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1503)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1501)
        at mage.util.CardUtil.deepCopyHashMap(CardUtil.java:1870)
        at mage.util.CardUtil.deepCopyObject(CardUtil.java:1809)
        at mage.game.GameState.<init>(GameState.java:176)
        at mage.game.GameState.copy(GameState.java:284)
        at mage.game.GameImpl.rollbackTurnsExecution(GameImpl.java:3905)
        at mage.game.GameImpl.playTurn(GameImpl.java:1111)
        at mage.game.GameImpl.play(GameImpl.java:1027)
        at mage.game.GameImpl.start(GameImpl.java:1003)
        at mage.server.game.GameWorker.call(GameWorker.java:34)
        at mage.server.game.GameWorker.call(GameWorker.java:15)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

2. Ability without sourceId (repeated many times in quick succession)
> WARN  2024-03-27 19:58:27,257 Ability without sourceId:If it would be dealt damage or destroyed, remove a shield counter from it instead. =>[GAME 19c66886-16a1-4c4c-b7dd-e06fc3518204] ContinuousEffects.getControllerOfSourceId 
WARN  2024-03-27 19:58:27,258 Ability without sourceId:If a permanent with a stun counter would become untapped, remove one from it instead. =>[GAME 19c66886-16a1-4c4c-b7dd-e06fc3518204] ContinuousEffects.getControllerOfSourceId 
WARN  2024-03-27 19:58:27,259 Ability without sourceId:If a creature with a finality counter on it would die, exile it instead. =>[GAME 19c66886-16a1-4c4c-b7dd-e06fc3518204] ContinuousEffects.getControllerOfSourceId 

3. Session callback exception (there are a few similar to this)
> WARN  2024-03-30 10:43:01,136 SESSION CALLBACK EXCEPTION - java.io.IOException: Connection is closed, userId 8f98b531-ce32-4292-97c4-61a454de4e18, messageId: 107 =>[CALL main-26396] Session.fireCallback 
org.jboss.remoting.callback.HandleCallbackException: Error handling callback
        at org.jboss.remoting.callback.ServerInvokerCallbackHandler.handleCallback(ServerInvokerCallbackHandler.java:866)
        at org.jboss.remoting.callback.ServerInvokerCallbackHandler.handleCallbackOneway(ServerInvokerCallbackHandler.java:728)
        at mage.server.Session.fireCallback(Session.java:441)
        at mage.server.User.lambda$fireCallback$0(User.java:260)
        at java.util.Optional.ifPresent(Optional.java:159)
        at mage.server.User.fireCallback(User.java:259)
        at mage.server.draft.DraftSession.lambda$update$0(DraftSession.java:75)
        at java.util.Optional.ifPresent(Optional.java:159)
        at mage.server.draft.DraftSession.update(DraftSession.java:75)
        at mage.server.draft.DraftController.updateDraft(DraftController.java:209)
        at mage.server.draft.DraftController.lambda$init$3aa0d15c$1(DraftController.java:51)
        at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
        at mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:60)
        at mage.game.draft.DraftImpl.fireUpdatePlayersEvent(DraftImpl.java:300)
        at mage.game.draft.BoosterDraft.start(BoosterDraft.java:33)
        at mage.server.draft.DraftController.startDraft(DraftController.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://192.168.43.50:55875/callback?callbackServerHost=192.168.43.50&callbackServerPort=55875&callbackServerProtocol=bisocket&isCallbackServer=true]

4. Error that required reconnect to continue
> WARN  2024-03-30 11:44:59,595 Game frozen in waitResponseOpen for 30 secs. User: Delirium; reason: something wrong with your priority on priority - HumanPlayer.java:1316; game: 2720fc64-9a49-4a94-94d7-3450bedf7425, Two Player Duel; T22.M1; active: Delirium; stack: 0 =>[CALL main-27020] HumanPlayer.waitResponseOpen

**Comment by JayDi85** [comment]
1. Improved in non release;
2. Must be research and fixed with unit tests (maybe some existing tests can generate it already);
3. It’s ok use case with user connection , improved in 46b5780e91c2409944a254e68a9e626cf4c20201;
4. It’s ok use case with user connection.

**Comment by Susucre** [comment]
2. The current setup for those replacement effects is without Source, so it is expected they don't have sourceId.
That's why I introduce a fake emblem as source in the Radiation counter PR. #12087
If we want to ensure all abilities always have a source, we need other fake emblems for Stun Counter ability, Shield Counter ability & Fatality Counter ability.
