### ISSUE TITLE
Client-side error on watching a game and trying to look at the back face of a dfc

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12225]
I was watching a game, there was a flipped [[Ajani, Nacatl Avenger]], I did click on the button to see the other face, and that did cause the following error:

```FATAL 2024-05-05 15:41:01,466 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.ClassCastException: mage.view.CardView cannot be cast to mage.view.PermanentView
	at org.mage.card.arcane.CardPanel.getOriginalPermanent(CardPanel.java:839)
	at mage.client.game.BattlefieldPanel.update(BattlefieldPanel.java:159)
	at mage.client.game.PlayAreaPanel.update(PlayAreaPanel.java:532)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:884)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:785)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:773)
	at mage.client.game.GamePanel.inform(GamePanel.java:1770)
	at mage.client.remote.CallbackClientImpl.lambda$onCallback$2(CallbackClientImpl.java:412)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	```

**Comment by Warahar** [comment]
I believe I had the same issue when playing a game. I'm not 100% sure this started the bug, but I believe I was looking at the back of a 2 faced card. When I got the error I was in my upkeep. I still had priority and could tap lands and attempt to cast spells, but I was stuck in my upkeep phase without the option to pass to the next phase. Starting a new client cleared the issue and I rejoined the game normally. 

"Error type: General error - ClassCastException

Client version: 1.4.55-V3 (build: 2024-12-16 20:14)
Java version: 1.8.0_201
Default charset: UTF-8

mage.view.CardView cannot be cast to mage.view.PermanentView

Stack trace:
org.mage.card.arcane.CardPanel.getOriginalPermanent(CardPanel.java:838)
mage.client.game.BattlefieldPanel.update(BattlefieldPanel.java:185)
mage.client.game.PlayAreaPanel.update(PlayAreaPanel.java:515)
mage.client.game.GamePanel.updateGame(GamePanel.java:1170)
mage.client.game.GamePanel.updateGame(GamePanel.java:1071)
mage.client.game.GamePanel.select(GamePanel.java:2075)
mage.client.remote.CallbackClientImpl.lambda$onCallback$2(CallbackClientImpl.java:302)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
java.awt.EventQueue.access$500(EventQueue.java:97)
and other 11 lines"
