### ISSUE TITLE
Unable connect to server. Server is not responding \ Server is likely offline

### ISSUE THREAD

**Issue by wwwmagnottait** [magefree/mage#12235]
Hi all!
Are anyone encountering server connection problem in these days?!
Since yesterday afternoon I got some problems using Xmage. After a commander game, Xmage freezes for a while, then I was unable to connect to the server (beta.xmage.today, Port: 17171). I tried today, and again I get always the same error message:
- Unable connect to server. Server is not responding
OR
- Unable connect to server. Server is likely offline

My Java version is 1.8.0_201
My XMage version is: 1.4.51-dev (both latest versions available)

Before to post I searched on this forum to find a solution: tried all the fixes suggested here: https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/?onetap_auto=true&one_tap=true
moreover I disabled Windows Firewall, disabled IPv6 in my network, updated Java, forced update on XMage,
Nothing solve my issue, still persistent!
PS If i run Server, I can correctly connect to localhost: I played some test games with bot and it works. Ping  to beta.xmage.today works. Xmage Update works.
Any suggestions?! Many thanks :)

**Comment by wwwmagnottait** [comment]
if it helps, this is my last mageclient.log of today:

WARN  2024-05-08 11:57:00,817 Cannot connect                                                                             =>[SwingWorker-pool-4-thread-6] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:449)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:105)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:101)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://beta.xmage.today:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=java]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
INFO  2024-05-08 11:57:00,817 Disconnecting DONE                                                                         =>[SwingWorker-pool-4-thread-6] SessionImpl.connectStop 
INFO  2024-05-08 11:57:00,817 Disconnected from client side                                                              =>[SwingWorker-pool-4-thread-6] MageFrame.disconnected

**Comment by JayDi85** [comment]
Hi. It's server problems, not your. In normal use case it must auto-restart
in 10-30 minutes on problems. I can manually restart it later in 1 hour.

Is it works now?

**Comment by wwwmagnottait** [comment]
> Hi. It's server problems, not your. In normal use case it must auto-restart in 10-30 minutes on problems. I can manually restart it later in 1 hour. Is it works now?

sadly, no :(
I restarted Pc several times, as well as XMage...tried last time one min ago, nothing. 
Error Message: Unable connect to server. Server is not responding

**Comment by JayDi85** [comment]
server restarted, must work fine now

**Comment by wwwmagnottait** [comment]
> server restarted, must work fine now

YEPPP! Now it works...thanks! :)
