### ISSUE TITLE
UI Crash when tapping lands

### ISSUE THREAD

**Issue by johannes-wolf** [magefree/mage#12257]
The following exception happens very often (at least every 3-4 games) when tapping mana (fast?):
```
FATAL 2024-05-19 13:37:28,245 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException: 2
	at javax.swing.text.CompositeView.getView(CompositeView.java:160)
	at javax.swing.text.FlowView$FlowStrategy.createView(FlowView.java:662)
	at javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:520)
	at javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:477)
	at javax.swing.text.FlowView.layout(FlowView.java:201)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:334)
	at javax.swing.text.BoxView.layout(BoxView.java:709)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:334)
	at javax.swing.text.BoxView.layout(BoxView.java:709)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:334)
	at javax.swing.text.BoxView.layout(BoxView.java:709)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:334)
	at javax.swing.text.BoxView.layout(BoxView.java:709)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1046)
	at javax.swing.text.DefaultCaret.repaintNewCaret(DefaultCaret.java:1308)
	at javax.swing.text.DefaultCaret$1.run(DefaultCaret.java:1287)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

After that the UI won't recover and you have to restart the whole client.

**Comment by JayDi85** [comment]
Are you changed a size settings (main menu - preferences) in that buggy games?

**Comment by JayDi85** [comment]
I think it can be related to popup card hint and game update.

Go to preferences and try to change popup speed to lower or bigger values (0 will disable it). Example 1: increase to 1000 ms, so you can fast click on mana payments without popup. Example 2: decrease to 50 ms , so you will see popup window immediately.

**Comment by johannes-wolf** [comment]
> I think it can be related to popup card hint and game update.
> 
> Go to preferences and try to change popup speed to lower or bigger values (0 will disable it). Example 1: increase to 1000 ms, so you can fast click on mana payments without popup. Example 2: decrease to 50 ms , so you will see popup window immediately.

I will try that and repot if it helps.

**Comment by johannes-wolf** [comment]
Increasing those delays does not help, the client still crashes from time to time when tapping permanents.

**Comment by JayDi85** [comment]
Ref for dev: https://stackoverflow.com/questions/47397453/awt-eventqueue-0-java-lang-arrayindexoutofboundsexception-value-program-stil

Error message contains a caret rendering call (it’s a cursor in text fields):
![IMG_0431](https://github.com/magefree/mage/assets/8344157/fd285d92-d891-4431-8d61-043d64c39897)

So error can be related to editable text field manipulation - for active game it can be a game chat or choose dialog with search filter. Maybe related to selectable text in game logs too. Error reason: GUI change from non swing thread and broke it.

Possible reproducible steps: while writing message, selecting text or searching - game catch update (opponent priority end). Or you move a battlefield scrolls and immediately go to writing message or selection logs.

@johannes-wolf try to ignore chat and game history (do not clicks on it, do not write, do not select, do not scroll history). If it helps then that’s the reason.
