### ISSUE TITLE
Cards with TargetsCountAdjuster must process empty and multiple targets (Extraordinary Journey error)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#12424]
`TargetsCountAdjuster` added multiple instances of the blueprint target (example: exile up to X target creatures) and can add 0 targets on X = 0. All related cards/effects must support such use case.

Error on [[Extraordinary Journey]]:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at mage.cards.e.ExtraordinaryJourneyEffect.apply(ExtraordinaryJourney.java:84)
	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:218)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:202)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:205)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:85)
	at mage.game.GameImpl.resolve(GameImpl.java:1766)
	at mage.game.GameImpl.playPriority(GameImpl.java:1689)
	at mage.game.turn.Step.priority(Step.java:67)
	at mage.game.turn.Phase.playStep(Phase.java:205)
	at mage.game.turn.Phase.play(Phase.java:91)
	at mage.game.turn.Turn.play(Turn.java:137)
```

TODO:
* [ ] Cards with `TargetsCountAdjuster` and `XTargetsCountAdjuster` must be reviewed - it's possible a wrong usage of `TargetsCountAdjuster`. Example: card's effect use first target and wait min/max values in it -- not multiple instances of target.
  * [ ] support of multiple targets is required;
  * [ ] support of empty targets is optional (see below);
* [ ] If it's hard to control `TargetsCountAdjuster` usage then `TargetsCountAdjuster` must add one target on count = 0 and up to usages. Another solution: support two settings -- change target instances or change max amount of single target.

Search code:
* `new TargetsCountAdjuster`
* `new XTargetsCountAdjuster`

Bugged code in card:
![shot_240607_074803](https://github.com/magefree/mage/assets/8344157/fb83d5a3-bc9c-426e-9c08-efc20acc2639)

Bugged code in TargetsCountAdjuster:
![shot_240607_074409](https://github.com/magefree/mage/assets/8344157/345e88fe-5342-4f42-a8fb-9b6be38c6703)

**Comment by ssk97** [comment]
Huh, I think I can just get rid of the if condition there and always add the target. Only a couple of the old adjusters had a count check like that.

**Comment by xenohedron** [comment]
Sounds reasonable to just remove that check and always add the target.
