### ISSUE TITLE
Random deck generation error handling missing

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1242]
If not enough cards for deck generation are available no error message is shown. (BFZ)
If no basic lands are included no error masic is shown. (DTK)

**Comment by Simown** [comment]
It tries much harder to produce a deck than it did, but there should be an error message if it fails. Basic lands shouldn't be an issue though, as they are retrieved from the block if none are available in the set. I'll have a look at that.

**Comment by Simown** [comment]
There was a bug in getting basic lands which caused an IndexOutOfBoundsException which I've fixed, always displayed an error message though. Can you provide some steps to reproduce the "not enough cards" error?

**Comment by LevelX2** [comment]
> Can you provide some steps to reproduce the "not enough cards" not showing an error?

I simply tried to generate a deck for the Battle for Zendikar set to do some random testing.

**Comment by Simown** [comment]
Right, sure. Was it no error message or IndexOutOfBounds message? Both issues for me have shown a dialog with IndexOutOfBounds rather than IllegalStateException (which should be shown). I'm fixing that up now. No idea why you aren't seeing the dialog though.

![Error](http://i.imgur.com/QTaJkud.png)

**Comment by LevelX2** [comment]
I'm getting no dialog to the client only the following exception the client log:

java.lang.IllegalStateException: Not enough cards to generate deck.
	at mage.client.deck.generator.DeckGenerator.generateSpells(DeckGenerator.java:227)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:171)
	at mage.client.deck.generator.DeckGenerator.buildDeck(DeckGenerator.java:98)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:66)
	at mage.client.table.NewPlayerPanel.generateDeck(NewPlayerPanel.java:97)
	at mage.client.table.NewPlayerPanel.btnGenerateActionPerformed(NewPlayerPanel.java:220)
	at mage.client.table.NewPlayerPanel.access$100(NewPlayerPanel.java:49)
	at mage.client.table.NewPlayerPanel$2.actionPerformed(NewPlayerPanel.java:165)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)

**Comment by Simown** [comment]
I don't have control about when the dialog is shown in this bit of code, if I throw an exception it will display in a dialog in the client.  That is the correct error message shown in the console for not enough cards. Regardless, I see the dialog. Wonder if other people can? Since my latest commit is it any better?

**Comment by Simown** [comment]
Was fixed a while ago
