### ISSUE TITLE
Game error on usage Satoru, the Infiltrator with triggered ability

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#12462]
Game error on usage [[Satoru, the Infiltrator]] -- can't processing triggered ability on stack. Without details, only error:

ERROR 2024-06-12 16:40:09,375 getSpellOrLKIStack got non-spell id mage.game.stack.StackAbility correlating to non-spell object stack ability (When {t>
java.lang.Throwable
        at mage.game.GameImpl.getSpellOrLKIStack(GameImpl.java:718)
        at mage.cards.s.SatoruTheInfiltratorTriggeredAbility.checkTrigger(SatoruTheInfiltrator.java:104)
        at mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:243)
        at mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:108)
        at mage.game.GameState.handleEvent(GameState.java:1006)
        at mage.game.GameState.handleSimultaneousEvent(GameState.java:825)
        at mage.game.GameState.processAction(GameState.java:679)
        at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:251)
        at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:205)
        at mage.game.stack.Spell.resolve(Spell.java:309)
        at mage.game.GameImpl.resolve(GameImpl.java:1766)
        at mage.game.GameImpl.playPriority(GameImpl.java:1689)

**Comment by JayDi85** [comment]
Same error but for `KickerAbility`

>
ERROR 2024-06-12 09:52:15,210 getSpellOrLKIStack got non-spell id mage.game.stack.StackAbility correlating to non-spell object stack ability (When yo>
java.lang.Throwable
        at mage.game.GameImpl.getSpellOrLKIStack(GameImpl.java:718)
        at mage.abilities.keyword.KickerAbility.getSpellKickedCountStrict(KickerAbility.java:283)
        at mage.abilities.keyword.KickerAbility.getSpellKickedCount(KickerAbility.java:276)
        at mage.abilities.condition.common.KickedCondition.apply(KickedCondition.java:28)
        at mage.abilities.decorator.ConditionalInterveningIfTriggeredAbility.checkInterveningIfClause(ConditionalInterveningIfTriggeredAbility.java:5>
        at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:184)
        at mage.game.stack.StackAbility.resolve(StackAbility.java:85)
        at mage.game.GameImpl.resolve(GameImpl.java:1766)
        at mage.game.GameImpl.playPriority(GameImpl.java:1689)
        at mage.game.turn.Step.priority(Step.java:67)
        at mage.game.turn.Phase.playStep(Phase.java:205)
        at mage.game.turn.Phase.play(Phase.java:91)
        at mage.game.turn.Turn.play(Turn.java:137)
        at mage.game.GameImpl.playTurn(GameImpl.java:1123)

**Comment by jeffwadsworth** [comment]
`// At this point, we have at least one event matching
        // "Whenever {this} and/or one or more other nontoken creatures enter the battlefield under your control"
        // Now to check that none were cast using mana
        for (ZoneChangeEvent zce : moved) {
            Spell spell = game.getSpellOrLKIStack(zce.getTargetId());
            if (spell != null && spell.getStackAbility().getManaCostsToPay().getUsedManaToPay().count() > 0) {
                return false; // found one that was cast using mana, so no triggering.
            }
        }
        return true; // all relevant permanents passed the spell mana check, so triggering.`
