### ISSUE TITLE
Game exception occurred: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by MadMoses666** [magefree/mage#1246]
Can't post this on the slightlymagic forums ("too spammy"), so here:

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.4v0
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
java.util.ArrayList$Itr.next(ArrayList.java:851)
mage.game.GameState.addAbility(GameState.java:745)
mage.game.GameState.addAbility(GameState.java:707)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:285)
mage.abilities.keyword.TransformAbility.transform(TransformAbility.java:93)
mage.abilities.keyword.TransformEffect.apply(TransformAbility.java:134)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:113)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:861)
mage.game.GameState.applyEffects(GameState.java:541)
mage.game.GameImpl.applyEffects(GameImpl.java:1300)
mage.game.GameImpl.playPriority(GameImpl.java:1207)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:796)
mage.game.GameImpl.play(GameImpl.java:710)
mage.game.GameImpl.start(GameImpl.java:677)
mage.server.game.GameWorker.call(GameWorker.java:61)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

Keep up the great work! Nice to see the new mulligan already implemented!

**Comment by LevelX2** [comment]
What happened (something was transformed?) exactly in the game before the error was shown?

**Comment by LevelX2** [comment]
Somehow the list of watchers belonging to an ability is modified while the an object gains this ability. Not clear to me why this happens.


	at mage.game.GameState.addAbility(GameState.java:745)
	at mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:304)
	at mage.abilities.effects.common.continuous.GainAbilityPairedEffect.apply(GainAbilityPairedEffect.java:72)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:113)
  
  at mage.game.GameState.addAbility(GameState.java:745)
	at mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:304)
	at mage.abilities.effects.common.continuous.GainAbilityAttachedEffect.apply(GainAbilityAttachedEffect.java:120)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:113)
  
  at mage.game.GameState.addAbility(GameState.java:745)
	at mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:304)
	at mage.abilities.effects.common.continuous.GainAbilityPairedEffect.apply(GainAbilityPairedEffect.java:72)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:113)
	
	at mage.game.GameState.addAbility(GameState.java:745)
	at mage.game.GameState.addOtherAbility(GameState.java:873)
	at mage.sets.fatereforged.GainAbilitySpellsEffect.apply(SoulfireGrandMaster.java:140)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:113)

**Comment by MadMoses666** [comment]
>What happened (something was transformed?) exactly in the game before the error was shown?

We played Innistrad draft. AFAIK I didn't have any transforming cards out, but my opponent had Screeching Bat and Thraben Sentry. The Screeching Bat had already transformed and attacked. I think the error occurred on my next turn, when I attacked and sacrificed my Selfless Cathar, triggering the Thraben Sentry's transformation.

**Comment by LevelX2** [comment]
LevelX: Fixed with the 1.4.4v1 Server version active on the public servers.
