### ISSUE TITLE
Ulalek, Fused Atrocity disconneting

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#12470]
When I cast [[Ulalek, Fused Atrocity]] the game disconnents. 

![image](https://github.com/magefree/mage/assets/64045003/b471dc6c-36e1-4cb6-9f79-9cb5dc3b8c9a)

Server console
INFO  2024-06-14 02:51:31,665 GAME started 87d1799b-7b51-42f1-b023-65ec6533d5d2 [Game] catman123456 - Computer 2 - Computer 3 - Computer 4 =>[CALL main-102] TableController.startGame 
FATAL 2024-06-14 03:00:01,160 GameWorker system error [87d1799b-7b51-42f1-b023-65ec6533d5d2 - Commander Free For All; T28.M1; active: catman123456; stack: 1 (top: stack ability (Whenever {this} or another land enters the battlefield under your control, if you ...)]: java.lang.OutOfMemoryError: GC overhead limit exceeded =>[GAME 87d1799b-7b51-42f1-b023-65ec6533d5d2] GameWorker.call 
java.lang.OutOfMemoryError: GC overhead limit exceeded
INFO  2024-06-14 03:00:01,165 CLIENT DISCONNECTED - catman123456 [Match: 1 ] at 192.168.0.12, sessionId: 5c4o0c-smywmo-lxdb01nl-1-lxdyjahh-h =>[WorkerThread#11[192.168.0.12:61967]] Main$MageServerConnectionListener.handleConnectionException 
FATAL 2024-06-14 03:00:01,170 Game session game quit exception null                                                      =>[CALL main-126] GameSessionPlayer.lambda$quitGame$12 

Client console
INFO  2024-06-14 02:51:31,997 Game 87d1799b-7b51-42f1-b023-65ec6533d5d2 started for player 915f2b4e-b91f-4959-8727-dd4474a5aa1d =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
INFO  2024-06-14 02:59:55,592 Connect: lost connection to server.                                                        =>[Thread-1882] SessionImpl$MageClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
	at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
	at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
	at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
	at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
INFO  2024-06-14 02:59:55,593 Disconnected from client side                                                              =>[Thread-1882] MageFrame.disconnected 
INFO  2024-06-14 03:00:01,183 Disconnecting...                                                                           =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2024-06-14 03:00:01,184 Disconnecting DONE                                                                         =>[AWT-EventQueue-0] SessionImpl.connectStop 
INFO  2024-06-14 03:00:01,184 Disconnected from server side                                                              =>[AWT-EventQueue-0] MageFrame.disconnected

**Comment by catman123456** [comment]
[mageclient.log](https://github.com/user-attachments/files/15833036/mageclient.log)

**Comment by JayDi85** [comment]
Make sure launcher - settings - java - options - server has a good memory limit settings like -xmx1000m. Old launcher has 256 mb limit, it can be too low.

**Comment by catman123456** [comment]
> Make sure launcher - settings - java - options - server has a good memory limit settings like -xmx1000m. Old launcher has 256 mb limit, it can be too low.

The memory limit is 3751 mb but I'll increased it and see if that works

![image](https://github.com/magefree/mage/assets/64045003/d2981a31-5a03-4fe2-82c0-f0eeaa7fa4eb)

**Comment by catman123456** [comment]
Its still happens
![image](https://github.com/magefree/mage/assets/64045003/ac22dc59-7731-4717-b8db-2a857c39854c)

**Comment by JayDi85** [comment]
It’s about server settings. Anyway it’s a bug.

![IMG_0520](https://github.com/magefree/mage/assets/8344157/a000b64c-439c-4226-8b4a-b1301e8a04ec)
