### ISSUE TITLE
ConcurrentModificationException prevents rollback

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#12502]
Stack trace:

```
FATAL 2024-06-21 11:41:59,537 GameWorker system error [64f39870-f70c-4d31-a805-f9b0eba20c79 - Commander Free For All; T15.CL; active: Computer 4; stack: 0]: java.util.ConcurrentModificationException =>[GAME 64f39870-f70c-4d31-a805-f9b0eba20c79] GameWorker.call 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at mage.util.CardUtil.deepCopyHashMap(CardUtil.java:1891)
	at mage.util.CardUtil.deepCopyObject(CardUtil.java:1830)
	at mage.game.GameState.<init>(GameState.java:179)
	at mage.game.GameState.copy(GameState.java:290)
	at mage.game.GameImpl.rollbackTurnsExecution(GameImpl.java:3950)
	at mage.game.GameImpl.playTurn(GameImpl.java:1152)
	at mage.game.GameImpl.play(GameImpl.java:1068)
	at mage.game.GameImpl.start(GameImpl.java:1044)
	at mage.server.game.GameWorker.call(GameWorker.java:35)
	at mage.server.game.GameWorker.call(GameWorker.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jeffwadsworth** [comment]
Probably should use ConcurrentHashMap instead of HashMap.

**Comment by JayDi85** [comment]
Nope, concurrent hash map just hide the problem, not fix it. It’s related to data changes from non game thread (must be restricted). #11285 contains many linked commits with related fixes and examples.

Current error stack shows consequences, not the real reason (source of the changes). Nothing to do with it.
