### ISSUE TITLE
Unable to run the server on an ARM-based Mac

### ISSUE THREAD

**Issue by Bmorr1123** [magefree/mage#12598]
Unable to run the server on an ARM-based Mac. Received the following error:
```
Caused by: java.lang.Exception: No native library found for os.name=Mac, os.arch=aarch64, paths=[/Users/user/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[sqlite-jdbc-3.32.3.2.jar:na]
	... 52 common frames omitted
```

I got it working by changing `sqlite-jdbc` from version `3.32.3.2` to version `3.32.3.3` 

Solution from the sqlite-jdbc repository:
https://github.com/xerial/sqlite-jdbc/issues/562#issuecomment-741265278

**Comment by JayDi85** [comment]
fixed in c272a825c012ccaee138453bde018919abb7b47e
