### ISSUE TITLE
ERROR ON STARTUP CLIENT

### ISSUE THREAD

**Issue by foxtaco94** [magefree/mage#12787]
Hi i downloaded the last version 1.4.53-dev (2024-08-16 15-45), but now when i try to launch the client i have this error

> FATAL 2024-09-02 17:20:49,234 Critical error on start up, app will be closed: REV                                        =>[AWT-EventQueue-0] MageFrame.lambda$main$9 
java.lang.NoSuchFieldError: REV
	at mage.cards.c.Chainsaw.<clinit>(Chainsaw.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:191)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:58)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:21)
	at mage.client.MageFrame.<init>(MageFrame.java:263)
	at mage.client.MageFrame.lambda$main$9(MageFrame.java:1464)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I try to download the full version but continues to give me the error.

What can i do?

Thank you

**Comment by JayDi85** [comment]
Interesting error.

1. Close all java.exe apps by task manager or restart computer.
2. Open mage_launcher_folder/xmage/mage-client/db/ and delete all files inside it;
3. Run launcher and press Update button to re-download all files;
4. Run client from a launcher and report results here.

**Comment by foxtaco94** [comment]
Thank you JayDi85, i do every step and now it works again.
