### ISSUE TITLE
Not Able to Download Symbols or Images

### ISSUE THREAD

**Issue by TrickiWiard** [magefree/mage#12997]
Keep getting these errors whenever I try to install symbols

WARN  2024-10-13 23:39:44,378 Download: AFR-U - unknown error for network resource https://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=AFR&size=small&rarity=U - java.net.ConnectException: Connection refused: connect =>[XMAGE symbols downloader - 5] Downloader$DownloadCallback.onMessage 
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at mage.client.remote.XmageURLConnection.connect(XmageURLConnection.java:170)
	at org.mage.plugins.card.dl.Downloader$DownloadCallback.onMessage(Downloader.java:177)
	at org.mage.plugins.card.dl.Downloader$DownloadCallback.onMessage(Downloader.java:128)
	at org.jetlang.channels.ChannelSubscription$1.run(ChannelSubscription.java:31)
	at org.jetlang.core.BatchExecutorImpl.execute(BatchExecutorImpl.java:11)
	at org.jetlang.fibers.PoolFiber.flush(PoolFiber.java:82)
	at org.jetlang.fibers.PoolFiber.access$100(PoolFiber.java:21)
	at org.jetlang.fibers.PoolFiber$1.run(PoolFiber.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	
And these errors for downloading card images

ERROR 2024-10-13 23:46:45,134 java.net.ConnectException: Connection refused: connect                                     =>[Thread-22] XmageURLConnection.downloadText 
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at mage.client.remote.XmageURLConnection.connect(XmageURLConnection.java:170)
	at mage.client.remote.XmageURLConnection.downloadText(XmageURLConnection.java:294)
	at org.mage.plugins.card.dl.sources.ScryfallImageSource.prepareBulkData(ScryfallImageSource.java:337)
	at org.mage.plugins.card.dl.sources.ScryfallImageSource.prepareDownloadList(ScryfallImageSource.java:250)
	at org.mage.plugins.card.images.DownloadPicturesService.run(DownloadPicturesService.java:660)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2024-10-13 23:46:45,135 Can't get bulk info from scryfall api https://api.scryfall.com/bulk-data/all-cards         =>[Thread-22] ScryfallImageSource.prepareBulkData 

Also finding that I continually get this error on startup within the client:

ERROR 2024-10-13 23:39:15,170 java.net.ConnectException: Connection refused: connect                                     =>[SwingWorker-pool-4-thread-2] XmageURLConnection.downloadText 
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at mage.client.remote.XmageURLConnection.connect(XmageURLConnection.java:170)
	at mage.client.remote.XmageURLConnection.downloadText(XmageURLConnection.java:294)
	at mage.client.dialog.WhatsNewDialog$1.doInBackground(WhatsNewDialog.java:87)
	at mage.client.dialog.WhatsNewDialog$1.doInBackground(WhatsNewDialog.java:81)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)	
	
I've followed the FAQ reddit post to the best of my ability, but still am unsure why this is happening. This happened after the most recent update as well.

**Comment by JayDi85** [comment]
Something wrong with your connection. Try two possible solutions:
1. Run client - main menu - Preferences - Network - make sure no proxy settings enabled;
2. Close all client and server apps (all java.exe) and move launcher folder with all files inside to new place. After run you will be asked about network access again (if it was blocked by your firewall).

**Comment by TrickiWiard** [comment]
It ended up downloading after I did the first fix, thank you!
