### ISSUE TITLE
Server Crash xmage.de 2015-10-08

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1306]
Unclear what is causing this.

```
FATAL 2015-10-08 00:03:58,666 Game exception                                                                             =>[GAME e7e576a9-590d-4e6f-9975-110f58c364e1] GameImpl.playPriority
mage.MageException: Iterated player priority after game exception too often, game ends!
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:819)
    at mage.game.GameImpl.play(GameImpl.java:733)
    at mage.game.GameImpl.start(GameImpl.java:700)
    at mage.server.game.GameWorker.call(GameWorker.java:61)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

```
FATAL 2015-10-08 03:33:13,981 Game exception gameId: 9545403d-d043-44a5-a393-88e21cb33fe0                                =>[GAME 9545403d-d043-44a5-a393-88e21cb33fe0] GameImpl.playPriority
java.lang.NullPointerException
    at mage.view.CardView.<init>(CardView.java:159)
    at mage.view.CardView.<init>(CardView.java:145)
    at mage.view.CardView.<init>(CardView.java:123)
    at mage.view.PlayerView.<init>(PlayerView.java:115)
    at mage.view.GameView.<init>(GameView.java:94)
    at mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:239)
    at mage.server.game.GameSessionWatcher.update(GameSessionWatcher.java:80)
    at mage.server.game.GameController.updateGame(GameController.java:758)
    at mage.server.game.GameController.access$000(GameController.java:97)
    at mage.server.game.GameController$1.event(GameController.java:166)
    at mage.server.game.GameController$1.event(GameController.java:158)
    at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:56)
    at mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:66)
    at mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:2077)
    at mage.game.GameImpl.playPriority(GameImpl.java:1283)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:819)
    at mage.game.GameImpl.play(GameImpl.java:733)
    at mage.game.GameImpl.start(GameImpl.java:700)
    at mage.server.game.GameWorker.call(GameWorker.java:61)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

```
312: DEBUG 2015-10-08 00:00:30,196 AbilityImpl.resolve: object: Planar Chaos                                                  =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
313: DEBUG 2015-10-08 00:00:30,196 AbilityImpl.resolve: effect returned false -that player flips a coin. If he or she loses the flip, counter that spell =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
898: DEBUG 2015-10-08 00:00:35,544 792ac1ca-1fed-4a36-85c3-76e8b2184cbb 22:42:19 Game e999aa8b-aeeb-4d1e-80c0-ecab60d8650a [stetsVerneint, Katana, Merez, Glex] =>[pool-8-thread-1] TableManager.debugServerState
982: DEBUG 2015-10-08 00:00:35,551 e999aa8b-aeeb-4d1e-80c0-ecab60d8650a [stetsVerneint(Left=N) Katana(Left=N) Merez(Left=N) Glex(Left=N) ] =>[pool-8-thread-1] TableManager.debugServerState
3549: DEBUG 2015-10-08 00:07:46,336 AbilityImpl.resolve: object: Starke of Rath                                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
3550: DEBUG 2015-10-08 00:07:46,337 AbilityImpl.resolve: effect returned false -Destroy target artifact or creature. That permanent's controller gains control of {this} =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
3551: FATAL 2015-10-08 00:07:46,337 Game exception gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.playPriority
3675: DEBUG 2015-10-08 00:08:15,242 AbilityImpl.resolve: object: Starke of Rath                                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
3676: DEBUG 2015-10-08 00:08:15,242 AbilityImpl.resolve: effect returned false -Destroy target artifact or creature. That permanent's controller gains control of {this} =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
3677: FATAL 2015-10-08 00:08:15,243 Game exception gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.playPriority
4711: DEBUG 2015-10-08 00:11:13,894 AbilityImpl.resolve: object: Planar Chaos                                                  =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
4712: DEBUG 2015-10-08 00:11:13,894 AbilityImpl.resolve: effect returned false -that player flips a coin. If he or she loses the flip, counter that spell =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
4972: DEBUG 2015-10-08 00:11:46,741 AbilityImpl.resolve: object: Planar Chaos                                                  =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
4973: DEBUG 2015-10-08 00:11:46,741 AbilityImpl.resolve: effect returned false -that player flips a coin. If he or she loses the flip, counter that spell =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
5116: FATAL 2015-10-08 00:12:06,851 Game exception gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.playPriority
5256: DEBUG 2015-10-08 00:12:46,179 Game over for player Id: e888db7f-3566-4b66-8e71-939b3cf2a430 gameId e999aa8b-aeeb-4d1e-80c0-ecab60d8650a =>[CALL main-44535] GameImpl.gameOver
5258: DEBUG 2015-10-08 00:12:46,180 stetsVerneint has lost gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                        =>[CALL main-44535] PlayerImpl.lostForced
5560: DEBUG 2015-10-08 00:13:45,239 AbilityImpl.resolve: object: Starke of Rath                                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
5561: DEBUG 2015-10-08 00:13:45,239 AbilityImpl.resolve: effect returned false -Destroy target artifact or creature. That permanent's controller gains control of {this} =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] AbilityImpl.resolve
5562: FATAL 2015-10-08 00:13:45,240 Game exception gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.playPriority
5712: DEBUG 2015-10-08 00:14:20,806 -- kill game session of gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                       =>[CALL main-44421] User.remove
6741: DEBUG 2015-10-08 00:14:58,506 792ac1ca-1fed-4a36-85c3-76e8b2184cbb 22:42:19 Game e999aa8b-aeeb-4d1e-80c0-ecab60d8650a [Katana, Merez, Glex] =>[pool-8-thread-1] TableManager.debugServerState
6792: DEBUG 2015-10-08 00:14:58,511 e999aa8b-aeeb-4d1e-80c0-ecab60d8650a [stetsVerneint(Left=Y) Katana(Left=N) Merez(Left=N) Glex(Left=N) ] =>[pool-8-thread-1] TableManager.debugServerState
8208: FATAL 2015-10-08 00:17:59,788 Game exception gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.playPriority
8589: DEBUG 2015-10-08 00:18:52,217 Player Glex concedes game e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                             =>[CALL main-42240] GameImpl.concede
8590: DEBUG 2015-10-08 00:18:52,218 Game over for player Id: 8c8607ec-6e92-46f1-b476-063cf881f958 gameId e999aa8b-aeeb-4d1e-80c0-ecab60d8650a =>[CALL main-42240] GameImpl.gameOver
8592: DEBUG 2015-10-08 00:18:52,218 Glex has lost gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                 =>[CALL main-42240] PlayerImpl.lostForced
8607: FATAL 2015-10-08 00:18:55,767 Game exception gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.playPriority
8720: DEBUG 2015-10-08 00:19:19,045 Player Glex concedes game e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                             =>[CALL main-44541] GameImpl.concede
8721: DEBUG 2015-10-08 00:19:19,046 Game over for player Id: 8c8607ec-6e92-46f1-b476-063cf881f958 gameId e999aa8b-aeeb-4d1e-80c0-ecab60d8650a =>[CALL main-44541] GameImpl.gameOver
8723: DEBUG 2015-10-08 00:19:19,047 Glex has lost gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                 =>[CALL main-44541] PlayerImpl.lostForced
8786: DEBUG 2015-10-08 00:19:26,743 Player Merez concedes game e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                            =>[CALL main-45371] GameImpl.concede
8787: DEBUG 2015-10-08 00:19:26,744 Game over for player Id: 8c166800-a44b-41f5-b27b-126b50abd87b gameId e999aa8b-aeeb-4d1e-80c0-ecab60d8650a =>[CALL main-45371] GameImpl.gameOver
8789: DEBUG 2015-10-08 00:19:26,744 END of gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                        =>[CALL main-45371] GameImpl.end
8790: DEBUG 2015-10-08 00:19:26,744 Player Katana has won gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                         =>[CALL main-45371] GameImpl.checkIfGameIsOver
8793: DEBUG 2015-10-08 00:19:26,745 Merez has lost gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[CALL main-45371] PlayerImpl.lostForced
8794: DEBUG 2015-10-08 00:19:26,747 Katana has won gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a                                =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.findWinnersAndLosers
8795: INFO  2015-10-08 00:19:26,747 GAME END  gameId: e999aa8b-aeeb-4d1e-80c0-ecab60d8650a [Merez => L] - [Glex => L] - [Katana => W] - [stetsVerneint => LQ] =>[GAME e999aa8b-aeeb-4d1e-80c0-ecab60d8650a] GameImpl.play
```

```
28206: INFO  2015-10-08 01:10:22,871 GAME started 6e1112c7-100d-474f-847d-dc444175469e [] Long - Thoughtsneezer                 =>[GAME 12174c87-b6f5-456f-86b9-0356779b0a28] TableController.startGame
28209: DEBUG 2015-10-08 01:10:23,562 Player Long 44ef35d2-07bc-4588-b0d5-5cb515c4196e has joined gameId: 6e1112c7-100d-474f-847d-dc444175469e =>[CALL main-48222] GameController.join
28210: DEBUG 2015-10-08 01:10:23,712 Player Thoughtsneezer bc4b1d7b-c086-483f-82c5-4573defdfca2 has joined gameId: 6e1112c7-100d-474f-847d-dc444175469e =>[CALL main-48222] GameController.join
28211: DEBUG 2015-10-08 01:10:23,714 GAME WORKER started gameId 6e1112c7-100d-474f-847d-dc444175469e                            =>[GAME main-48426] GameWorker.call
28342: FATAL 2015-10-08 01:11:01,626 Game exception gameId: 6e1112c7-100d-474f-847d-dc444175469e                                =>[GAME 6e1112c7-100d-474f-847d-dc444175469e] GameImpl.playPriority
28450: FATAL 2015-10-08 01:11:21,096 Game exception gameId: 6e1112c7-100d-474f-847d-dc444175469e                                =>[GAME 6e1112c7-100d-474f-847d-dc444175469e] GameImpl.playPriority
28599: FATAL 2015-10-08 01:11:38,715 Game exception gameId: 6e1112c7-100d-474f-847d-dc444175469e                                =>[GAME 6e1112c7-100d-474f-847d-dc444175469e] GameImpl.playPriority
28770: FATAL 2015-10-08 01:12:17,831 Game exception gameId: 6e1112c7-100d-474f-847d-dc444175469e                                =>[GAME 6e1112c7-100d-474f-847d-dc444175469e] GameImpl.playPriority
28811: DEBUG 2015-10-08 01:12:25,656 Player Thoughtsneezer concedes game 6e1112c7-100d-474f-847d-dc444175469e                   =>[CALL main-48497] GameImpl.concede
28812: DEBUG 2015-10-08 01:12:25,657 Game over for player Id: bc4b1d7b-c086-483f-82c5-4573defdfca2 gameId 6e1112c7-100d-474f-847d-dc444175469e =>[CALL main-48497] GameImpl.gameOver
28814: DEBUG 2015-10-08 01:12:25,657 END of gameId: 6e1112c7-100d-474f-847d-dc444175469e                                        =>[CALL main-48497] GameImpl.end
28815: DEBUG 2015-10-08 01:12:25,657 Player Long has won gameId: 6e1112c7-100d-474f-847d-dc444175469e                           =>[CALL main-48497] GameImpl.checkIfGameIsOver
28818: DEBUG 2015-10-08 01:12:25,658 Thoughtsneezer has lost gameId: 6e1112c7-100d-474f-847d-dc444175469e                       =>[CALL main-48497] PlayerImpl.lostForced
28819: DEBUG 2015-10-08 01:12:25,658 Long has won gameId: 6e1112c7-100d-474f-847d-dc444175469e                                  =>[GAME 6e1112c7-100d-474f-847d-dc444175469e] GameImpl.findWinnersAndLosers
28820: INFO  2015-10-08 01:12:25,659 GAME END  gameId: 6e1112c7-100d-474f-847d-dc444175469e [Thoughtsneezer => L] - [Long => W] =>[GAME 6e1112c7-100d-474f-847d-dc444175469e] GameImpl.play
```

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated.
