### ISSUE TITLE
XMage can't run from folders with non-ascii names

### ISSUE THREAD

**Issue by mbideau** [magefree/mage#13121]
Related #7025

Error example:
```
Error type: CLIENT - unhandled error in GUI - InvalidPathException
Client version: 1.4.55-V2 (build: 2024-12-01 17:48)

Malformed input or input contains unmappable characters: /home/mbideau/T��l��chargements

Stack trace:
sun.nio.fs.UnixPath.encode(UnixPath.java:147)
sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
java.nio.file.Paths.get(Paths.java:84)
sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:490)
javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run0(BasicDirectoryModel.java:239)
javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run(BasicDirectoryModel.java:228)
```

**Comment by JayDi85** [comment]
1.
Run client by launcher and look at startup logs (black window) -- if must show `Default charset: UTF-8`:
![shot_241207_145901](https://github.com/user-attachments/assets/d4f98bf9-3974-4452-8cbf-5fb6ea9adeb5)

If it show another value then go to "launcher - settings - java - client options" and insert ` -Dfile.encoding=UTF-8 ` in any place (don't forget about spaces). Example:
* `-Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Xmx2000m`

2.
If it doesn't help then move all xmage files (with launcher folder) to another place like `D:\games\x` (don't use desktop, documents, download or program files).

**Comment by mbideau** [comment]
Hi, thank you for your quick reply, but I already have `-Dfile.encoding=UTF-8` in my launcher command.
See the full log below:
```sh
❯ sh startClient.sh 
/usr/lib/jvm/java-8-openjdk-amd64/bin/java
openjdk version "1.8.0_402"
OpenJDK Runtime Environment (build 1.8.0_402-8u402-ga-2-b06)
OpenJDK 64-Bit Server VM (build 25.402-b06, mixed mode)
INFO  2024-12-09 11:39:44,174 Starting MAGE CLIENT version: 1.4.55-V2 (build: 2024-12-01 17:48)                          =>[main] MageFrame.main 
INFO  2024-12-09 11:39:44,176 Java version: 1.8.0_402                                                                    =>[main] MageFrame.main 
INFO  2024-12-09 11:39:44,177 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2024-12-09 11:39:44,177 Default charset: UTF-8                                                                     =>[main] MageFrame.main 
INFO  2024-12-09 11:39:44,407 Custom (or bundled) Java certificate file (cacerts) file found                             =>[AWT-EventQueue-1] MageFrame.<init> 
INFO  2024-12-09 11:39:44,537 Using GUI theme: Default                                                                   =>[AWT-EventQueue-1] PreferencesDialog.loadTheme 
INFO  2024-12-09 11:39:44,565 Loading database...                                                                        =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,687 Database stats:                                                                            =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,687  - sets: 513                                                                               =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,687  - cards: 75858                                                                            =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,687  - tokens: 2032                                                                            =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,687  - emblems: 123                                                                            =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,687  - planes: 21                                                                              =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,688  - dungeons: 3                                                                             =>[AWT-EventQueue-1] RepositoryUtil.bootstrapLocalDb 
INFO  2024-12-09 11:39:47,702 Images: search broken files...                                                             =>[AWT-EventQueue-1] MageFrame.<init> 
INFO  2024-12-09 11:39:47,781 Loading sets and formats...                                                                =>[AWT-EventQueue-1] MageFrame.bootstrapSetsAndFormats 
INFO  2024-12-09 11:39:57,416 Symbols: loading...                                                                        =>[AWT-EventQueue-1] ManaSymbols.loadImages 
INFO  2024-12-09 11:39:58,358 Symbols: done                                                                              =>[AWT-EventQueue-1] ManaSymbols.loadImages 
INFO  2024-12-09 11:39:58,364 Loading plugins...                                                                         =>[AWT-EventQueue-1] Plugins.loadPlugins 
INFO  2024-12-09 11:39:58,409 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-1] CounterPluginImpl.newPlugin 
INFO  2024-12-09 11:39:58,418 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-1] CardPluginImpl.newPlugin 
INFO  2024-12-09 11:39:58,422 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-1] ThemePluginImpl.newPlugin 
INFO  2024-12-09 11:39:58,422 Done.                                                                                      =>[AWT-EventQueue-1] Plugins.loadPlugins 
ERROR 2024-12-09 11:39:58,859 JavaFX is not supported by your system. What's new page will be disabled.                  =>[AWT-EventQueue-1] MageFrame.<init> 
java.lang.UnsupportedClassVersionError: javafx/beans/value/ChangeListener has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at mage.client.MageFrame.<init>(MageFrame.java:312)
	at mage.client.MageFrame.lambda$main$12(MageFrame.java:1580)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
WARN  2024-12-09 11:39:59,222 SystemTray is not supported                                                                =>[AWT-EventQueue-1] MageTray.install 
INFO  2024-12-09 11:39:59,370 Client start up time: 15 seconds                                                           =>[AWT-EventQueue-1] MageFrame.lambda$new$1 
FATAL 2024-12-09 11:41:03,671 MAGE Client UI error                                                                       =>[Basic L&F File Loading Thread] EDTExceptionHandler.handle 
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/mbideau/T��l��chargements
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
	at javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:490)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run0(BasicDirectoryModel.java:239)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run(BasicDirectoryModel.java:228)
```

My launcher is the following script:
```sh
❯ cat startClient.sh | grep -v '^#'

set -e

cd "$(dirname "$0")/xmage/mage-client"

TMPDIR=/opt/xmage/tmp
TMP=$TMPDIR
TEMP=$TMPDIR
export TMPDIR
export TMP
export TEMP
LC_ALL=C
export LC_ALL

PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH"
command -v java
export PATH
java -version

java -Djava.io.tmpdir=$TMPDIR -Xms512m -Xmx2048m -Dfile.encoding=UTF-8 -jar ./lib/mage-client-1.4.55.jar
```

Thanks for your time helping me.

Best regards

**Comment by JayDi85** [comment]
Try add additional java command to the launch script:
* `-Dsun.jnu.encoding=UTF-8`

**Comment by mbideau** [comment]
That's it ! No more errors !
`-Dsun.jnu.encoding=UTF-8` did the trick !
Thanks a lot :heart:
