### ISSUE TITLE
Client doesn't start

### ISSUE THREAD

**Issue by darkyndy** [magefree/mage#1415]
I updated today, info when starting:
> XMage folder:  D:\
> XMage Launcher version installed:  0.3.4
> XMage Launcher version available:  0.3.4
> Java version installed:  1.7.0_75
> Java version available:  1.7.0_75
> XMage version installed:  1.4.5v0 (2015-11-21)
> XMage version available:  1.4.5v0 (2015-11-21)

And when I start client I get:
~~~
INFO  2015-12-10 22:11:17,801 Starting MAGE client version 1.4.5v0                                                       =>[main] MageFrame.main 
INFO  2015-12-10 22:11:17,801 Logging level: INFO                                                                        =>[main] MageFrame.main 
org.h2.jdbc.JdbcSQLException: IO Exception: "Closing" [90028-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:367)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1362)
	at org.h2.engine.Database.openDatabase(Database.java:296)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:252)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:184)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:440)
	at com.j256.ormlite.table.TableUtils.createTable(TableUtils.java:220)
	at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:61)
	at mage.cards.repository.RepositoryUtil.isDatabaseObsolete(RepositoryUtil.java:21)
	at mage.cards.repository.ExpansionRepository.<init>(ExpansionRepository.java:41)
	at mage.cards.repository.ExpansionRepository.<clinit>(ExpansionRepository.java:23)
	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:52)
	at mage.client.MageFrame.<init>(MageFrame.java:236)
	at mage.client.MageFrame$21.run(MageFrame.java:1210)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: File corrupted in chunk 15, expected page length =< 384, got 86708482 [1.4.187/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.Page$PageChildren.read(Page.java:1042)
	at org.h2.mvstore.MVStore.readPageChunkReferences(MVStore.java:1294)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1239)
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1224)
	at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1183)
	at org.h2.mvstore.MVStore.storeNowTry(MVStore.java:981)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:973)
	at org.h2.mvstore.MVStore.commitAndSave(MVStore.java:962)
	at org.h2.mvstore.MVStore.commit(MVStore.java:923)
	at org.h2.mvstore.db.TransactionStore.close(TransactionStore.java:217)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:346)
	... 39 more
FATAL 2015-12-10 22:11:24,927 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.cards.repository.ExpansionRepository.getSetCodes(ExpansionRepository.java:64)
	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:52)
	at mage.client.MageFrame.<init>(MageFrame.java:236)
	at mage.client.MageFrame$21.run(MageFrame.java:1210)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

~~~

**Comment by LevelX2** [comment]
>>> File corrupted in chunk 15, expected page length =< 384, got 86708482 [1.4.187/6]

Looks like a damage of your harddisk/storage medium.
Validate your storage medium and if needed reinstall xmage.

**Comment by darkyndy** [comment]
Thanks, I will try to re-install.
