### ISSUE TITLE
Xmage disconnects me a lot

### ISSUE THREAD

**Issue by SeekerPS** [magefree/mage#1440]
Well, i'm tired of xmage disconnecting me of almost every game.  it happens on all servers i connect, this is what appears on the console:

ene 03, 2016 11:01:56 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2016-01-03 11:01:56,464 Starting MAGE client version 1.4.6v0                                                       =>[main] MageFrame.main 
INFO  2016-01-03 11:01:56,470 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2016-01-03 11:02:10,071 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-01-03 11:02:10,461 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2016-01-03 11:02:10,511 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-01-03 11:02:18,075 Card pool load time: 4 seconds                                                             =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2016-01-03 11:02:28,014 Card images checking time: 9 seconds                                                       =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2016-01-03 11:02:58,582 Check download images (total cards: 24921, total tokens: 541) => Missing images: 36        =>[AWT-EventQueue-0] DownloadPictures.getNeededCards 
INFO  2016-01-03 11:03:00,825 Client start up time: 64 seconds                                                           =>[AWT-EventQueue-0] MageFrame$6.run 
INFO  2016-01-03 11:03:04,222 Trying to connect as SeekerPS to XMAGE server at xmage.de:17171                            =>[AWT-EventQueue-0] SessionImpl.connect 
INFO  2016-01-03 11:03:05,619 Connected as SeekerPS to MAGE server at xmage.de:17171                                     =>[AWT-EventQueue-0] SessionImpl.connect 
INFO  2016-01-03 12:13:26,017 connection to server lost - Could not connect to server!                                   =>[Thread-452] SessionImpl$ClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
	at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
	at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
	at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
	at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
INFO  2016-01-03 12:13:26,024 RECONNECT - Connected: true                                                                =>[Thread-452] SessionImpl.reconnect 
INFO  2016-01-03 12:13:26,025 DISCONNECTED (NO Event Dispatch Thread)                                                    =>[Thread-452] MageFrame.disconnected 
INFO  2016-01-03 12:13:35,876 DISCONNECT (still connected)                                                               =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-01-03 12:13:36,112 Disconnected ...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-01-03 12:13:37,303 DISCONNECTED (Event Dispatch Thread)                                                       =>[AWT-EventQueue-0] MageFrame.disconnected 
INFO  2016-01-03 12:13:39,396 Trying to connect as SeekerPS to XMAGE server at xmage.de:17171                            =>[AWT-EventQueue-0] SessionImpl.connect 
INFO  2016-01-03 12:13:40,328 Connected as SeekerPS to MAGE server at xmage.de:17171                                     =>[AWT-EventQueue-0] SessionImpl.connect 
INFO  2016-01-03 12:14:16,563 Joining table 8f1bfc98-51c8-43a1-9461-0a50819b9131                                         =>[AWT-EventQueue-0] TablesPanel$1.actionPerformed 
INFO  2016-01-03 12:14:29,386 Game fc40681e-76db-4e62-928a-0210b44f81a9 started for player d21e9a14-57b8-486c-9eab-e0d5fb7ef358 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
WARN  2016-01-03 12:19:48,776 message out of sequence - ignoringMessageId = 369 method = gameInform                      =>[AWT-EventQueue-0] CallbackClientImpl$1.run 
INFO  2016-01-03 12:21:37,825 Ending game...                                                                             =>[pool-9-thread-1] FeedbackPanel$1.run 
INFO  2016-01-03 12:22:32,709 Game 22b7a9af-da23-4f4a-8e98-d023643f084b started for player d21e9a14-57b8-486c-9eab-e0d5fb7ef358 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
WARN  2016-01-03 12:30:31,444 ignoring message from later source: 956, text=Precombat Main - Waiting for <font color='#20B2AA'>OliverH</font> =>[AWT-EventQueue-0] FeedbackPanel.getFeedback 
INFO  2016-01-03 12:36:17,081 Ending game...                                                                             =>[pool-9-thread-1] FeedbackPanel$1.run 
INFO  2016-01-03 12:36:20,642 Joining table 52ade34d-e42b-4428-9ef3-e2fe5481c29a                                         =>[AWT-EventQueue-0] TablesPanel$1.actionPerformed 
INFO  2016-01-03 12:36:36,248 Game 3d133bca-9ffb-4f6e-92af-20612ed3630a started for player 9188664d-2adb-49e1-84fe-c85ec31662a6 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
INFO  2016-01-03 12:39:36,561 connection to server lost - Could not connect to server!                                   =>[Thread-10578] SessionImpl$ClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
	at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
	at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
	at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
	at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
INFO  2016-01-03 12:39:36,562 RECONNECT - Connected: true                                                                =>[Thread-10578] SessionImpl.reconnect 
INFO  2016-01-03 12:39:36,563 DISCONNECTED (NO Event Dispatch Thread)                                                    =>[Thread-10578] MageFrame.disconnected 
ERROR 2016-01-03 12:40:25,600 Ping failed: SeekerPS Session: 5c4o14-c6hwl3-iiyq943e-1-iiysrx38-e to MAGE server at xmage.de:17171 =>[pool-1-thread-1] SessionImpl.ping 
FATAL 2016-01-03 12:40:25,600 Server error                                                                               =>[pool-1-thread-1] SessionImpl.handleMageException 
mage.MageException: Ping failed
	at mage.remote.SessionImpl.ping(SessionImpl.java:1417)
	at mage.client.MageFrame$2.run(MageFrame.java:260)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
INFO  2016-01-03 12:40:25,600 DISCONNECT (still connected)                                                               =>[pool-1-thread-1] SessionImpl.disconnect 
INFO  2016-01-03 12:40:48,837 Disconnected ...                                                                           =>[pool-1-thread-1] SessionImpl.disconnect 
INFO  2016-01-03 12:40:48,837 DISCONNECTED (NO Event Dispatch Thread)                                                    =>[pool-1-thread-1] MageFrame.disconnected 
INFO  2016-01-03 12:40:50,757 Trying to connect as SeekerPS to XMAGE server at xmage.de:17171                            =>[AWT-EventQueue-0] SessionImpl.connect 
INFO  2016-01-03 12:40:52,898 Connected as SeekerPS to MAGE server at xmage.de:17171                                     =>[AWT-EventQueue-0] SessionImpl.connect 
INFO  2016-01-03 12:40:56,815 Game 3d133bca-9ffb-4f6e-92af-20612ed3630a started for player 9188664d-2adb-49e1-84fe-c85ec31662a6 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
INFO  2016-01-03 12:40:59,926 DISCONNECT (still connected)                                                               =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-01-03 12:41:01,095 Disconnected ...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-01-03 12:41:01,095 DISCONNECTED (Event Dispatch Thread)                                                       =>[AWT-EventQueue-0] MageFrame.disconnected 
INFO  2016-01-03 12:41:14,890 Trying to connect as SeekerPS to XMAGE server at xmage.de:17171                            =>[SwingWorker-pool-4-thread-2] SessionImpl.connect 
INFO  2016-01-03 12:41:15,868 Connected as SeekerPS to MAGE server at xmage.de:17171                                     =>[SwingWorker-pool-4-thread-2] SessionImpl.connect 
INFO  2016-01-03 12:41:23,419 DISCONNECT (still connected)                                                               =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-01-03 12:41:24,397 Disconnected ...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-01-03 12:41:24,397 DISCONNECTED (Event Dispatch Thread)                                                       =>[AWT-EventQueue-0] MageFrame.disconnected

**Comment by Sixftrabbit** [comment]
Yeah, I couldn't connect at all tonight

Jan 18, 2016 10:33:25 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2016-01-18 22:33:25,605 Starting MAGE client version 1.4.7v1                                                       =>[main] MageFrame.main 
INFO  2016-01-18 22:33:25,608 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2016-01-18 22:33:27,665 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-01-18 22:33:27,716 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2016-01-18 22:33:27,722 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-01-18 22:33:30,657 Card pool load time: 2 seconds                                                             =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2016-01-18 22:33:31,495 Card images checking time: 0 seconds                                                       =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2016-01-18 22:33:34,402 Client start up time: 8 seconds                                                            =>[AWT-EventQueue-0] MageFrame$6.run 
INFO  2016-01-18 22:33:34,406 Trying to connect to XMAGE server at xmage.woogerworks.info:17171                          =>[AWT-EventQueue-0] SessionImpl$5.run 
WARN  2016-01-18 22:33:53,445 Cannot connect                                                                             =>[AWT-EventQueue-0] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.run(SessionImpl.java:403)
	at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:136)
	at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:281)
	at mage.remote.SessionImpl.connect(SessionImpl.java:239)
	at mage.client.MageFrame.connect(MageFrame.java:729)
	at mage.client.MageFrame.performConnect(MageFrame.java:771)
	at mage.client.MageFrame.autoConnect(MageFrame.java:742)
	at mage.client.MageFrame$6.run(MageFrame.java:356)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 23 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://xmage.woogerworks.info:17171/?serializationtype=jboss]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 25 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createClientSocket(SocketClientInvoker.java:175)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1220)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 28 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.jboss.serial.io.JBossObjectInputStream.checkSignature(JBossObjectInputStream.java:110)
	at org.jboss.serial.io.JBossObjectInputStream.<init>(JBossObjectInputStream.java:94)
	at org.jboss.remoting.serialization.impl.jboss.JBossSerializationManager.createInput(JBossSerializationManager.java:64)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:75)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:58)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createInputStream(ClientSocketWrapper.java:206)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createStreams(ClientSocketWrapper.java:189)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.<init>(ClientSocketWrapper.java:67)
	... 35 more
FATAL 2016-01-18 22:33:59,738 Error disconnecting ...                                                                    =>[AWT-EventQueue-0] SessionImpl.disconnect 
java.lang.Exception: Can not remove callback listener as remoting client is not connected to server.
	at org.jboss.remoting.Client.removeListener(Client.java:1466)
	at mage.remote.SessionImpl.disconnect(SessionImpl.java:502)
	at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:428)
	at mage.remote.SessionImpl.connect(SessionImpl.java:239)
	at mage.client.MageFrame.connect(MageFrame.java:729)
	at mage.client.MageFrame.performConnect(MageFrame.java:771)
	at mage.client.MageFrame.autoConnect(MageFrame.java:742)
	at mage.client.MageFrame$6.run(MageFrame.java:356)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
INFO  2016-01-18 22:33:59,740 Disconnected ...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-01-18 22:33:59,741 DISCONNECTED (Event Dispatch Thread)                                                       =>[AWT-EventQueue-0] MageFrame.disconnected

**Comment by fireshoes** [comment]
woogerworks crashed tonight. You should be able to connect to xmage.de by clicking the Find server button and selecting it from the list.
