### ISSUE TITLE
First time running issues after compilation (client and server)

### ISSUE THREAD

**Issue by Mike-NetCode** [magefree/mage#1455]
Hi.

So I got latest repo which I was able to compile but not run. Neither client nor server but I'm getting two different exceptions. I assume that there is something wrong with my configuration if it works on your machines. Please guide me.

Client:

```
ERROR 2016-01-11 03:08:57,452 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadImages 
ERROR 2016-01-11 03:08:57,453 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2016-01-11 03:08:57,738 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-01-11 03:08:57,781 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2016-01-11 03:08:57,785 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
FATAL 2016-01-11 03:08:58,620 java.io.StreamCorruptedException: invalid stream header: 00000000                          =>[AWT-EventQueue-0] Plugins.getGamesPlayed 
FATAL 2016-01-11 03:08:58,620                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.RuntimeException: mage.interfaces.PluginException: java.io.StreamCorruptedException: invalid stream header: 00000000
	at mage.client.plugins.impl.Plugins.getGamesPlayed(Plugins.java:143)
	at mage.client.MageFrame.<init>(MageFrame.java:337)
	at mage.client.MageFrame$21.run(MageFrame.java:1210)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: mage.interfaces.PluginException: java.io.StreamCorruptedException: invalid stream header: 00000000
	at org.mage.plugins.counter.CounterPluginImpl.getGamePlayed(CounterPluginImpl.java:138)
	at mage.client.plugins.impl.Plugins.getGamesPlayed(Plugins.java:140)
	... 16 more
Caused by: java.io.StreamCorruptedException: invalid stream header: 00000000
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at org.mage.plugins.counter.CounterPluginImpl.getGamePlayed(CounterPluginImpl.java:126)
	... 17 more
```

Server:
```
INFO  2016-01-11 03:13:46,696 Loading cards...                                                                           =>[main] Main.main
Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file mage/sets/magic2012/Divination
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at mage.util.ClassScanner.findClasses(ClassScanner.java:95)
	at mage.util.ClassScanner.findClasses(ClassScanner.java:74)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:66)
	at mage.server.Main.main(Main.java:120)
```

**Comment by menocar** [comment]
It appears something is going wrong around compilation. Not sure about your environment but in case you are using NetBeans IDE, did you uncheck "Compile On Save" in the Build > Compile menu? When it's checked I got weird errors caused by inconsistent build state.

**Comment by Mike-NetCode** [comment]
Sorry for not giving sufficient information. It's Win7, JDK 1.8, Netbeans 8.0.2. Maven 3.0.5
Building with dependencies is successful (after cleaning and rebuilding). I unchecked those options in each project but no luck. Thanks

**Comment by LevelX2** [comment]
You can use JDK 1.8. I'm using maven 3.3.1 (did not update for a long time I guess)
I have no problems with the current version.
Builds and runs without any problem on my system.

**Comment by Mike-NetCode** [comment]
I assumed it works on your machines. My knowledge is too limited to be able to resolve this myself, I guess I'll have to stay aside. darn :(

**Comment by Mike-NetCode** [comment]
Perhaps you can say something about this error? (Mage.Framework)

```
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project mage: MavenReportException: Error while generating Javadoc:
Exit code: 1 - C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:60: error: reference not found
* @see mage.abilities.keyword.LevelAbility#getRule()
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:106: warning: no @param for game
Abilities<ManaAbility> getAvailableManaAbilities(Zone zone, Game game);
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:118: error: reference not found
* @see mage.abilities.effects.ContinuousEffects#asThough(java.util.UUID, mage.constants.AsThoughEffectType, mage.game.Game)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:121: warning - Tag @see: can't find asThough(java.util.UUID, mage.constants.AsThoughEffectType, mage.game.Game) in mage.abilities.effects.ContinuousEffects
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:137: error: reference not found
* @see mage.cards.CardImpl#checkTriggers(mage.constants.Zone, mage.game.events.GameEvent, mage.game.Game)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:138: error: reference not found
* @see mage.game.permanent.PermanentImpl#checkTriggers(mage.game.events.GameEvent, mage.game.Game)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:139: error: reference not found
* @see mage.game.permanent.PermanentCard#checkPermanentOnlyTriggers(mage.game.events.ZoneChangeEvent, mage.game.Game)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:141: warning - Tag @see: can't find checkTriggers(mage.constants.Zone, mage.game.events.GameEvent, mage.game.Game) in mage.cards.CardImpl
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:141: warning - Tag @see: can't find checkTriggers(mage.game.events.GameEvent, mage.game.Game) in mage.game.permanent.PermanentImpl
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:141: warning - Tag @see: can't find checkPermanentOnlyTriggers(mage.game.events.ZoneChangeEvent, mage.game.Game) in mage.game.permanent.PermanentCard
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:148: error: reference not found
* @see mage.game.permanent.PermanentImpl#hasProtectionFrom(mage.MageObject)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:149: error: reference not found
* @see mage.players.PlayerImpl#hasProtectionFrom(mage.MageObject)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:150: error: reference not found
* @see mage.players.PlayerImpl#canDamage(mage.MageObject)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:152: warning - Tag @see: can't find hasProtectionFrom(mage.MageObject) in mage.game.permanent.PermanentImpl
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:152: warning - Tag @see: can't find hasProtectionFrom(mage.MageObject) in mage.players.PlayerImpl
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:152: warning - Tag @see: can't find canDamage(mage.MageObject) in mage.players.PlayerImpl
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:168: warning: no description for @param
* @param controllerId
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:170: error: reference not found
* @see mage.cards.CardImpl#setControllerId(java.util.UUID)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:175: warning - Tag @see: can't find setControllerId(java.util.UUID) in mage.cards.CardImpl
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:180: warning: no description for @param
* @param sourceId
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:200: warning: no description for @param
* @param abilityId
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:201: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:210: warning: no description for @param
* @param abilityId
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:211: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:222: warning: no description for @param
* @param ability
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:223: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:230: warning: no description for @param
* @param ability
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:231: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:239: warning: no description for @param
* @param abilities
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:247: warning: no description for @param
* @param classObject
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Abilities.java:256: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilitiesImpl.java:49: warning: no description for @param
* @param <T>
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:226: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:271: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:278: warning: no description for @param
* @param choice
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:285: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:292: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:312: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:319: warning: no description for @param
* @param source
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:320: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:364: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:372: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:395: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:413: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:414: warning: no description for @param
* @param source
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:415: warning: no description for @param
* @param event
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:416: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:425: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:426: warning: no description for @param
* @param source
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:427: warning: no description for @param
* @param event
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:428: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:436: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:445: warning: no description for @param
* @param ruleAtTheTop
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:453: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:462: warning: no description for @param
* @param worksFaceDown
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:469: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:479: warning: no description for @param
* @param ruleVisible
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:487: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:497: warning: no description for @param
* @param ruleAdditionalCostsVisible
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:515: warning: no description for @param
* @param abilityWord
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:523: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:524: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:543: warning: no description for @param
* @param mageObject
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:544: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:553: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:554: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:565: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\Ability.java:566: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:504: warning: no description for @param
* @param controller
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:506: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:533: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:534: warning: no description for @param
* @param noMana
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:535: warning: no description for @param
* @param controller
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:672: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:925: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:926: warning: no description for @param
* @param source
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\AbilityImpl.java:927: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\TriggeredAbility.java:47: warning: no description for @param
* @param event
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\TriggeredAbility.java:48: warning: no description for @param
* @param game
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\TriggeredAbility.java:49: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\SpecialActions.java:49: warning: no description for @param
* @param controllerId
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\SpecialActions.java:52: warning: no description for @return
* @return
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\BeginningOfDrawTriggeredAbility.java:52: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\BeginningOfDrawTriggeredAbility.java:53: warning: no description for @param
* @param targetController
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\BeginningOfDrawTriggeredAbility.java:54: warning: no description for @param
* @param isOptional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:55: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:64: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:65: warning: no description for @param
* @param optional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:73: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:74: warning: no description for @param
* @param optional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:75: warning: no description for @param
* @param opponentController
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:83: warning: no description for @param
* @param zone
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:84: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:85: warning: no description for @param
* @param optional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:86: warning: no description for @param
* @param opponentController
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:93: warning: no description for @param
* @param zone
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:94: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:96: warning: no description for @param
* @param optional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\CreatureEntersBattlefieldTriggeredAbility.java:97: warning: no description for @param
* @param opponentController
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\EntersBattlefieldAbility.java:53: warning: no description for @param
* @param optional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\EntersBattlefieldAbility.java:71: warning: no description for @param
* @param optional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\EntersBattlefieldAllTriggeredAbility.java:56: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\EntersBattlefieldAllTriggeredAbility.java:57: warning: no description for @param
* @param filter
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\EntersBattlefieldControlledTriggeredAbility.java:50: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\EntersBattlefieldControlledTriggeredAbility.java:51: warning: no description for @param
* @param filter
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\SpellCastOpponentTriggeredAbility.java:64: warning: no description for @param
* @param zone
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\SpellCastOpponentTriggeredAbility.java:65: warning: no description for @param
* @param effect
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\SpellCastOpponentTriggeredAbility.java:66: warning: no description for @param
* @param filter
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\common\SpellCastOpponentTriggeredAbility.java:67: warning: no description for @param
* @param optional
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\condition\common\PermanentsOnTheBattlefieldCondition.java:40: error: reference not found
* @see #Controls(mage.filter.Filter)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\condition\common\PermanentsOnTheBattlefieldCondition.java:41: error: reference not found
* @see #Controls(mage.filter.Filter, mage.abilities.condition.Condition)
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\condition\common\PermanentsOnTheBattlefieldCondition.java:57: error: reference not found
* {@link #ControlsPermanent(mage.filter.FilterPermanent, mage.abilities.condition.common.ControlsPermanent.CountType, int)}
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\condition\common\TransformedCondition.java:51: error: invalid use of @return
* @return true if the condition is true, false if the condition is false
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\effects\CostModificationEffect.java:48: error: reference not found
* Called by the {@link ContinuousEffects#costModification(java.util.UUID, mage.abilities.Ability, mage.game.Game) ContinuousEffects.costModification}
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\AttacksThisTurnMarkerAbility.java:39: error: no tag name after @
* You should use {@see AttacksIfAbleTargetEffect} for real effect.
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\BlocksThisTurnMarkerAbility.java:39: error: no tag name after @
* You should use {@see BlocksIfAbleTargetEffect} for real effect.
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\LevelerCardBuilder.java:134: error: @param name not found
* @param card
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\ReboundAbility.java:51: error: reference not found
* call to apply. This is because of how the {@link ReboundEffect} works. It
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\ReboundAbility.java:54: error: self-closing element not allowed
* <p/>
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\ReboundAbility.java:56: error: self-closing element not allowed
* <p/>
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\ReboundAbility.java:63: error: self-closing element not allowed
* <p/>
^
C:\Programming\Java\mage\Mage\src\main\java\mage\abilities\keyword\ReboundAbility.java:67: error: self-closing element not allowed
* <p/>
^
C:\Programming\Java\mage\Mage\src\main\java\mage\filter\predicate\Predicate.java:46: error: reference not found
* <li>The computation is <i>consistent with equals</i>; that is, {@link Objects#equal
^
C:\Programming\Java\mage\Mage\src\main\java\mage\game\GameImpl.java:2391: error: malformed HTML
* matter, if not, then Map<UUID, Map<Zone, Card>> should be used instead).
^
C:\Programming\Java\mage\Mage\src\main\java\mage\game\GameImpl.java:2391: error: malformed HTML
* matter, if not, then Map<UUID, Map<Zone, Card>> should be used instead).
^
C:\Programming\Java\mage\Mage\src\main\java\mage\game\GameImpl.java:2391: error: bad use of '>'
* matter, if not, then Map<UUID, Map<Zone, Card>> should be used instead).
^
C:\Programming\Java\mage\Mage\src\main\java\mage\game\GameImpl.java:2391: error: bad use of '>'
* matter, if not, then Map<UUID, Map<Zone, Card>> should be used instead).
^
C:\Programming\Java\mage\Mage\src\main\java\mage\players\Library.java:74: error: malformed HTML
* Don't use this directly. Use <player.shuffleLibrary(game)> instead.
^
C:\Programming\Java\mage\Mage\src\main\java\mage\players\Library.java:74: error: bad use of '>'
* Don't use this directly. Use <player.shuffleLibrary(game)> instead.
^
C:\Programming\Java\mage\Mage\src\main\java\mage\players\Player.java:750: error: unknown tag: Cards
* @return Set<Cards> that were successful moved to graveyard
^
C:\Programming\Java\mage\Mage\src\main\java\mage\players\PlayerImpl.java:2655: error: reference not found
* @see mage.server.GameSessionPlayer#getGameView()
^
C:\Programming\Java\mage\Mage\src\main\java\mage\target\TargetImpl.java:558: error: bad use of '>'
* group of targets of the ability with a target tag > 0.
^
C:\Programming\Java\mage\Mage\src\main\java\mage\util\CardUtil.java:452: error: bad use of '>'
* Converts an integer number to string Numbers > 20 will be returned as
^
C:\Programming\Java\mage\Mage\src\main\java\mage\util\CardUtil.java:464: error: bad use of '>'
* Numbers > 20 will be returned as digits
^

Command line was: "C:\Program Files\Java\jdk1.8.0_40\jre\..\bin\javadoc.exe" @options @packages

Refer to the generated Javadoc files in 'C:\Programming\Java\mage\Mage\target\apidocs' dir.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

After correcting the problems, you can resume the build with the command
  mvn <goals> -rf :mage
```

**Comment by LevelX2** [comment]
Smells like a maven problem to me.

Try to uninstall the manual installed maven version.
I guess you don't need to install maven explicit as long as you only use the common actions. 
I don't think you need more.

**Comment by Mike-NetCode** [comment]
I reverted maven version to NetBean's bundled (3.0.5) yet same result. I must be really unlucky with my environment!

**Comment by rollergo11** [comment]
Delete all of the repo files and re-clone. I had an issue similar to this but it sorted itself out when I recloned

**Comment by Mike-NetCode** [comment]
Heh. It worked! Thanks :-)

**Comment by LevelX2** [comment]
Good to know.
