### ISSUE TITLE
UnknownHostException on client startup - OSX 10.11.2

### ISSUE THREAD

**Issue by shawnwall** [magefree/mage#1523]
Using the latest version of xmage, installed by launcher, I'm getting the following on startClient. I was getting the same UnknownHostException before using scutil to set a hostname, and it was using a local fiosrouter based address for my machine. I'm currently not even at the same physical location but am getting the same error.

When running xmage on a windows 10 virtualbox VM on the same mac, it works, so it appears this is related to osx networking.

```
org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: wall: wall: nodename nor servname provided, or not known" [90028-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:287)
	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:268)
	at org.h2.server.TcpServer.getURL(TcpServer.java:201)
	at org.h2.tools.Server.start(Server.java:475)
	at org.h2.engine.Database.startServer(Database.java:780)
	at org.h2.engine.Database.open(Database.java:636)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:187)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:252)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:184)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:440)
	at com.j256.ormlite.table.TableUtils.createTable(TableUtils.java:220)
	at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:61)
	at mage.cards.repository.RepositoryUtil.isDatabaseObsolete(RepositoryUtil.java:21)
	at mage.cards.repository.ExpansionRepository.<init>(ExpansionRepository.java:41)
	at mage.cards.repository.ExpansionRepository.<clinit>(ExpansionRepository.java:23)
	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:54)
	at mage.client.MageFrame.<init>(MageFrame.java:237)
	at mage.client.MageFrame$21.run(MageFrame.java:1213)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.net.UnknownHostException: wall: wall: nodename nor servname provided, or not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:266)
	... 42 more
Caused by: java.net.UnknownHostException: wall: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
	... 43 more
FATAL 2016-02-09 09:29:41,475 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.cards.repository.ExpansionRepository.getSetCodes(ExpansionRepository.java:64)
	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:54)
	at mage.client.MageFrame.<init>(MageFrame.java:237)
	at mage.client.MageFrame$21.run(MageFrame.java:1213)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by LevelX2** [comment]
This is a bug in the JDK 7 for OSX as noted in [1] (login required) and more recently on [2]

The workaround is to add the name of the machine to your `/etc/hosts` file, e.g.

	127.0.0.1 MacBook

**Comment by takenp** [comment]
It's resolved me a problem with client start on Linux just adding the name of the local machine the client was looking for (PuppyLinux in my case) to /etc/hosts as @LevelX2 reffered. thx alot!
