### ISSUE TITLE
blank client, also don't know the home link

### ISSUE THREAD

**Issue by masonro** [magefree/mage#1524]
xmage_launcher.log
ERROR 2016-02-09 09:18:38,570 Invalid config from http://xmage.info/xmage/config.json                                    =>[AWT-EventQueue-0] XMageLauncher.getConfig
org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.xmage.launcher.Utilities.readJsonFromUrl(Utilities.java:83)
	at com.xmage.launcher.XMageLauncher.getConfig(XMageLauncher.java:492)
	at com.xmage.launcher.XMageLauncher.access$1000(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$14.run(XMageLauncher.java:474)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
ERROR 2016-02-09 09:20:19,933 Invalid config from http://xmage.info/xmage/config.json                                    =>[AWT-EventQueue-0] XMageLauncher.getConfig
org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.xmage.launcher.Utilities.readJsonFromUrl(Utilities.java:83)
	at com.xmage.launcher.XMageLauncher.getConfig(XMageLauncher.java:492)
	at com.xmage.launcher.XMageLauncher.access$1000(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$14.run(XMageLauncher.java:474)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
ERROR 2016-02-09 09:20:21,349 Invalid config from http://xmage.info/xmage/config.json                                    =>[AWT-EventQueue-0] XMageLauncher.getConfig
org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.xmage.launcher.Utilities.readJsonFromUrl(Utilities.java:83)
	at com.xmage.launcher.XMageLauncher.getConfig(XMageLauncher.java:492)
	at com.xmage.launcher.XMageLauncher.handleCheckUpdates(XMageLauncher.java:420)
	at com.xmage.launcher.XMageLauncher.access$600(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$8.actionPerformed(XMageLauncher.java:295)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)

**Comment by masonro** [comment]
What Do I put for the link?
It's updated, but not showing up

**Comment by LevelX2** [comment]
You need to set it to:

`http://xmage.de/xmage`
