### ISSUE TITLE
issue downloading images from Magiccards.info

### ISSUE THREAD

**Issue by William-Shadowruby** [magefree/mage#1539]
When downloading from Magiccards.info an error happens for each card. While the UI provides no indication of failure.

ERROR 2016-02-17 14:05:23,680 java.net.SocketException: Unexpected end of file from server                               =>[pool-7-thread-9] DownloadPictures$DownloadTask.run 
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at org.mage.plugins.card.images.DownloadPictures$DownloadTask.run(DownloadPictures.java:575)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by LevelX2** [comment]
Fixed beyond 1.4.8v1

**Comment by guifig** [comment]
It's not, though. I just tested it:

![capturar](https://cloud.githubusercontent.com/assets/17275479/13248871/a8f82816-d9ff-11e5-879c-16ee0a9b05a7.PNG)

**Comment by Zekvyrin** [comment]
Happened to me as well in 1.4.9v1

I've tried it in both Windows 7 & Linux Mint (had issues in both), and on 2 different networks (home & work)

**Comment by fireshoes** [comment]
There was another fix for this applied yesterday, which will be available with the next update.

**Comment by rkfg** [comment]
Or you may try the beta branch (change it in settings), I occasionally compile it and this particular fix is already there.
