### ISSUE TITLE
NPE instead of sideboarding after finishing a round

### ISSUE THREAD

**Issue by rkfg** [magefree/mage#1565]
Several message boxes with message "java.lang.NullPointerException" and "null" pop up after winning or losing a game. I'm using Debian stretch, compiled the game from git.

```java
FATAL 2016-02-26 12:37:31,948 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.NullPointerException
	at mage.client.cards.CardGrid.drawCards(CardGrid.java:143)
	at mage.client.cards.CardGrid.loadCards(CardGrid.java:123)
	at mage.client.deckeditor.CardSelector.filterCards(CardSelector.java:405)
	at mage.client.deckeditor.CardSelector.switchToGrid(CardSelector.java:205)
	at mage.client.deckeditor.DeckEditorPanel.showDeckEditor(DeckEditorPanel.java:173)
	at mage.client.deckeditor.DeckEditorPane.show(DeckEditorPane.java:89)
	at mage.client.MageFrame.showDeckEditor(MageFrame.java:1128)
	at mage.client.remote.CallbackClientImpl.sideboard(CallbackClientImpl.java:490)
	at mage.client.remote.CallbackClientImpl$1.run(CallbackClientImpl.java:325)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:139)
	at mage.client.dialog.MageDialog.show(MageDialog.java:82)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at javax.swing.JComponent.setVisible(Unknown Source)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:88)
	at mage.client.dialog.GameEndDialog.showDialog(GameEndDialog.java:146)
	at mage.client.MageFrame.showGameEndDialog(MageFrame.java:744)
	at mage.client.remote.CallbackClientImpl$1.run(CallbackClientImpl.java:285)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
FATAL 2016-02-26 12:37:32,132 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.NullPointerException
	at mage.client.cards.CardGrid.drawCards(CardGrid.java:143)
	at mage.client.deckeditor.CardSelector.componentResized(CardSelector.java:1197)
	at java.awt.AWTEventMulticaster.componentResized(Unknown Source)
	at java.awt.AWTEventMulticaster.componentResized(Unknown Source)
	at java.awt.Component.processComponentEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:141)
	at mage.client.dialog.MageDialog.show(MageDialog.java:82)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at javax.swing.JComponent.setVisible(Unknown Source)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:88)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:110)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1140)
	at mage.client.MageFrame.showError(MageFrame.java:1383)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:499)
	at mage.client.remote.CallbackClientImpl.access$600(CallbackClientImpl.java:69)
	at mage.client.remote.CallbackClientImpl$1.run(CallbackClientImpl.java:378)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:139)
	at mage.client.dialog.MageDialog.show(MageDialog.java:82)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at javax.swing.JComponent.setVisible(Unknown Source)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:88)
	at mage.client.dialog.GameEndDialog.showDialog(GameEndDialog.java:146)
	at mage.client.MageFrame.showGameEndDialog(MageFrame.java:744)
	at mage.client.remote.CallbackClientImpl$1.run(CallbackClientImpl.java:285)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
FATAL 2016-02-26 12:37:32,146                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.cards.CardGrid.drawCards(CardGrid.java:143)
	at mage.client.deckeditor.CardSelector.componentMoved(CardSelector.java:1204)
	at java.awt.AWTEventMulticaster.componentMoved(Unknown Source)
	at java.awt.AWTEventMulticaster.componentMoved(Unknown Source)
	at java.awt.Component.processComponentEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:141)
	at mage.client.dialog.MageDialog.show(MageDialog.java:82)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at javax.swing.JComponent.setVisible(Unknown Source)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:88)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:110)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1140)
	at mage.client.MageFrame.showError(MageFrame.java:1383)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:499)
	at mage.client.remote.CallbackClientImpl.access$600(CallbackClientImpl.java:69)
	at mage.client.remote.CallbackClientImpl$1.run(CallbackClientImpl.java:378)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
FATAL 2016-02-26 12:37:32,172                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.cards.CardGrid.drawCards(CardGrid.java:143)
	at mage.client.deckeditor.CardSelector.componentResized(CardSelector.java:1197)
	at java.awt.AWTEventMulticaster.componentResized(Unknown Source)
	at java.awt.AWTEventMulticaster.componentResized(Unknown Source)
	at java.awt.Component.processComponentEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at mage.client.util.EDTExceptionHandler.handle(EDTExceptionHandler.java:51)
	at mage.client.util.EDTExceptionHandler.uncaughtException(EDTExceptionHandler.java:45)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
FATAL 2016-02-26 12:37:32,344                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.cards.CardGrid.drawCards(CardGrid.java:143)
	at mage.client.deckeditor.CardSelector.componentResized(CardSelector.java:1197)
	at java.awt.AWTEventMulticaster.componentResized(Unknown Source)
	at java.awt.Component.processComponentEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at mage.client.util.EDTExceptionHandler.handle(EDTExceptionHandler.java:51)
	at mage.client.util.EDTExceptionHandler.uncaughtException(EDTExceptionHandler.java:45)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at mage.client.util.EDTExceptionHandler.handle(EDTExceptionHandler.java:51)
	at mage.client.util.EDTExceptionHandler.uncaughtException(EDTExceptionHandler.java:45)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
FATAL 2016-02-26 12:37:32,373                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.cards.CardGrid.drawCards(CardGrid.java:143)
	at mage.client.deckeditor.CardSelector.componentResized(CardSelector.java:1197)
	at java.awt.AWTEventMulticaster.componentResized(Unknown Source)
	at java.awt.Component.processComponentEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at mage.client.util.EDTExceptionHandler.handle(EDTExceptionHandler.java:51)
	at mage.client.util.EDTExceptionHandler.uncaughtException(EDTExceptionHandler.java:45)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at mage.client.util.EDTExceptionHandler.handle(EDTExceptionHandler.java:51)
	at mage.client.util.EDTExceptionHandler.uncaughtException(EDTExceptionHandler.java:45)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at mage.client.util.EDTExceptionHandler.handle(EDTExceptionHandler.java:51)
	at mage.client.util.EDTExceptionHandler.uncaughtException(EDTExceptionHandler.java:45)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
INFO  2016-02-26 12:37:39,669 Ending game...                                                                             =>[pool-14-thread-1] FeedbackPanel$1.run 
```

**Comment by rkfg** [comment]
This patch seems to fix it (premature mode switch when the deck editor isn't fully initialized):
```diff
diff --git a/Mage.Client/src/main/java/mage/client/deckeditor/DeckEditorPanel.java b/Mage.Client/src/main/java/mage/client/deckeditor/DeckEditorPanel.java
index f7420e2..e0a1fae 100644
--- a/Mage.Client/src/main/java/mage/client/deckeditor/DeckEditorPanel.java
+++ b/Mage.Client/src/main/java/mage/client/deckeditor/DeckEditorPanel.java
@@ -170,7 +170,6 @@ public class DeckEditorPanel extends javax.swing.JPanel {
                     this.cardSelector.loadSideboard(new ArrayList<>(deck.getSideboard()), this.bigCard);
                 }
                 // TODO: take from preferences
-                this.cardSelector.switchToGrid();
 
                 this.btnExit.setVisible(false);
                 this.btnImport.setVisible(false);
```
