### ISSUE TITLE
Xmage is not found

### ISSUE THREAD

**Issue by Aguythatswantshisproblemstobesolved** [magefree/mage#2037]
Recently i started having some problems with xmage, so i decided to reinstall it. The problem is that when i tried to reinstall the game, the launcher kept on trying to install it and stopped working. So i downloaded it manually and now the launcher keeps saying the program is not there.

**Comment by LevelX2** [comment]
In the directory you start the launcher from is a launcher log file with messages that show problems during installation and execution. Maybe you check this first.

**Comment by Aguythatswantshisproblemstobesolved** [comment]
Well, the log file is here:
ERROR 2016-06-26 16:42:56,019 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] DownloadTask.download
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.xmage.launcher.Downloader.connect(Downloader.java:27)
	at com.xmage.launcher.DownloadTask.download(DownloadTask.java:64)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:779)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2016-06-26 16:43:01,791 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] DownloadTask.download
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.xmage.launcher.Downloader.connect(Downloader.java:27)
	at com.xmage.launcher.DownloadTask.download(DownloadTask.java:64)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:785)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2016-06-26 16:52:27,715 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateXMage
java.io.EOFException: Truncated ZIP entry: mage-client/lib/trove4j-3.0.3.jar
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.drainCurrentEntryData(ZipArchiveInputStream.java:619)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.closeEntry(ZipArchiveInputStream.java:583)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:193)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:338)
	at com.xmage.launcher.DownloadTask.unzip(DownloadTask.java:208)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:798)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2016-06-26 17:27:28,237 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] DownloadTask.download
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.xmage.launcher.Downloader.connect(Downloader.java:27)
	at com.xmage.launcher.DownloadTask.download(DownloadTask.java:64)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:779)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2016-06-26 17:27:30,765 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] DownloadTask.download
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.xmage.launcher.Downloader.connect(Downloader.java:27)
	at com.xmage.launcher.DownloadTask.download(DownloadTask.java:64)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:785)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2016-06-26 17:35:05,319 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateXMage
java.io.EOFException: Truncated ZIP entry: mage-client/lib/mage-client-1.4.12.jar
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.drainCurrentEntryData(ZipArchiveInputStream.java:619)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.closeEntry(ZipArchiveInputStream.java:583)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:193)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:338)
	at com.xmage.launcher.DownloadTask.unzip(DownloadTask.java:208)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:798)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
