### ISSUE TITLE
Game crashes if Gisela is on the battlefield but not Bruna

### ISSUE THREAD

**Issue by michaelstephendavies** [magefree/mage#2064]
Note: This is against the AI.

If I cast Gisela while Bruna is not on the battlefield, then at the beginning of my upkeep her meld ability goes on the stack (I think this is wrong because of the "intervening if" clause?). If I let it resolve, the game crashes. On the client I get:

```
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends!
Server version: 1.4.13v0
mage.game.GameImpl.playPriority(GameImpl.java:1343)
mage.game.turn.EndPhase.playStep(EndPhase.java:67)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:852)
mage.game.GameImpl.play(GameImpl.java:766)
mage.game.GameImpl.start(GameImpl.java:733)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)
```

And on the server:
```
FATAL 2016-07-11 22:29:24,352 Game exception gameId: 68a6545e-e576-45ee-abda-6b256dc24349
=>[GAME 68a6545e-e576-45ee-abda-6b256dc24349] GameImpl.playPriority
java.lang.NullPointerException
        at mage.abilities.effects.common.MeldEffect.apply(MeldEffect.java:94)
        at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:197)
        at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:100)
        at mage.game.stack.StackAbility.resolve(StackAbility.java:105)
        at mage.game.GameImpl.resolve(GameImpl.java:1370)
        at mage.game.GameImpl.playPriority(GameImpl.java:1321)
        at mage.game.turn.EndPhase.playStep(EndPhase.java:67)
        at mage.game.turn.Phase.play(Phase.java:115)
        at mage.game.turn.Turn.play(Turn.java:152)
        at mage.game.GameImpl.playTurn(GameImpl.java:852)
        at mage.game.GameImpl.play(GameImpl.java:766)
        at mage.game.GameImpl.start(GameImpl.java:733)
        at mage.server.game.GameWorker.call(GameWorker.java:60)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

(the offending line is [here](https://github.com/magefree/mage/blob/e1b3428a391daaf8e88e95ca549762dcffb6edec/Mage/src/main/java/mage/abilities/effects/common/MeldEffect.java#L94))

If I cast Bruna first, then Gisela on a later turn then they meld just fine.

I haven't tried this with the other meld pairs but I assume they have the same problem.

EDIT: So I investigated a bit, [here](https://github.com/magefree/mage/blob/e1b3428a391daaf8e88e95ca549762dcffb6edec/Mage/src/main/java/mage/abilities/condition/common/MeldCondition.java#L57) you try to check for a creature with the appropriate name, but I think it's just checking that you own and control any creature. You'd need to add a `NamePredicate` to check the actual name, like [Marauding Maulhorn](https://github.com/magefree/mage/blob/18b98edbc6f6b261ee0d28a94e4b0c176b4e2727/Mage.Sets/src/mage/sets/magic2014/MaraudingMaulhorn.java).

**Comment by quercitron** [comment]
You are right, the problem was that NamePredicate was not used in the condition. The issue is fixed.
Thanks!
