### ISSUE TITLE
ClassFormatError when starting the server

### ISSUE THREAD

**Issue by Dilnu** [magefree/mage#2111]
Hi, I'm trying to run the server at head and I'm getting an error. To be clear before posting this bug I redownloaded the entire project from scratch.

The full error is below. Further investigation showed that this was occurring with cards from a few specific sets including the dark. A full list of the failing cards is also below. There are a few recurring error messages mostly relating to FilterPermanent and Target Permanent.

The internet seems to think this is usually caused by an error in the maven dependencies, often when depending on javaee-api but I didn't see any mention of that in the code base.
```
Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mage.sets.ajanivsnicolbolas.AgonizingDemise.<clinit>(AgonizingDemise.java:56)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at mage.util.ClassScanner.findClassesInJar(ClassScanner.java:126)
	at mage.util.ClassScanner.findClasses(ClassScanner.java:79)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:66)
	at mage.server.Main.main(Main.java:116)
```
The cards that fail to load and the associated errors are here:
```
mage.sets.thedark.AshesToAshes
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.BogRats
Absent Code attribute in method that is not native or abstract in class file mage/sets/thedark/BogRats
mage.sets.thedark.CityOfShadows
Absent Code attribute in method that is not native or abstract in class file mage/target/TargetPermanent
mage.sets.thedark.DanceOfMany
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.DarkHeartOfTheWood
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.DustToDust
Absent Code attribute in method that is not native or abstract in class file mage/sets/thedark/DustToDust
mage.sets.thedark.EaterOfTheDead
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterImpl
mage.sets.thedark.Exorcist
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.Fissure
Absent Code attribute in method that is not native or abstract in class file mage/sets/thedark/Fissure
mage.sets.thedark.Flood
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.GoblinCaves
Absent Code attribute in method that is not native or abstract in class file mage/target/TargetPermanent
mage.sets.thedark.GoblinDiggingTeam
Absent Code attribute in method that is not native or abstract in class file mage/sets/thedark/GoblinDiggingTeam
mage.sets.thedark.GoblinsOfTheFlarg
Absent Code attribute in method that is not native or abstract in class file mage/sets/thedark/GoblinsOfTheFlarg
mage.sets.thedark.GoblinWizard
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterImpl
mage.sets.thedark.GraveRobbers
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterImpl
mage.sets.thedark.HiddenPath
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.HolyLight
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.Inferno
Absent Code attribute in method that is not native or abstract in class file mage/sets/thedark/Inferno
mage.sets.thedark.ManaVortex
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.MerfolkAssassin
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.OrcGeneral
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.PeopleOfTheWoods
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.Preacher
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.PreventDamageToSourceByCardTypeEffect
Absent Code attribute in method that is not native or abstract in class file mage/abilities/effects/ContinuousEffectImpl
mage.sets.thedark.PutBasicForestOnBattlefieldEffect
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterImpl
mage.sets.thedark.RagMan
Absent Code attribute in method that is not native or abstract in class file mage/sets/thedark/RagMan
mage.sets.thedark.RagManDiscardEffect
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterImpl
mage.sets.thedark.Riptide
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.SavaenElves
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.SkullOfOrm
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterImpl
mage.sets.thedark.SunkenCity
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.TivadarsCrusade
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.Venom
Absent Code attribute in method that is not native or abstract in class file mage/target/TargetPermanent
mage.sets.thedark.WaterWurm
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.WitchHunter
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.thedark.WordOfBinding
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.pdsslivers.AcidicSliver
Absent Code attribute in method that is not native or abstract in class file mage/filter/FilterPermanent
mage.sets.pdsslivers.AphettoDredging
```

**Comment by drmDev** [comment]
This almost always means you need to do a full clean and rebuild with Maven. Go to your XMage repository directory on a command prompt and enter 
mvn clean install -DskipTests

See the Developer Getting Started guide for info on Maven and how to install it locally if needed:
https://github.com/magefree/mage/wiki/Developer-Getting-Started#maven

**Comment by Dilnu** [comment]
That seems to have fixed it, thanks for the advice.
