### ISSUE TITLE
Spell Queller dying after exiled spell is processed and he leaves battlefield

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2126]
Bugs reported on forums:

1) "When the card that was exiled by Spell Queller leaves the exile zone(using a processor like Ulamog's Nullifier), then Spell Queller dies [???]. Then an error is thrown and game goes back to start of phase. "

2) "...SpellQueller exiled my Nissa, Vastwood Seeker. Next turn he processed Nissa with Wasteland Strangler and killed my Tireless Tracker. I then cast Quarantine Field, targeting Spell Queller and Wasteland Strangler. That's when the error message occurred.  (fatal exception)"

Seems they both are related to 
1) Spell Queller exiles a spell with his ETB ability
2) That spell in exile is processed by a processor such as Wasteland Strangler
3) When Spell Queller is removed from the battlefield, the errors occurs.

**Comment by drmDev** [comment]
adding tests to try to reproduce...

**Comment by drmDev** [comment]
Fatal Exception stack trace:

FATAL [2016-07-29 15:51 [06:643]] GameImpl[main]: Game exception gameId: 14bc22bc-787a-4abb-a87d-faee1bd25d32
java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:713)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
	at mage.sets.eldritchmoon.SpellQuellerLeavesEffect.apply(SpellQueller.java:160)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:197)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:100)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:105)
	at mage.game.GameImpl.resolve(GameImpl.java:1370)
	at mage.game.GameImpl.playPriority(GameImpl.java:1321)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:152)
	at mage.game.GameImpl.playTurn(GameImpl.java:852)
	at mage.game.GameImpl.play(GameImpl.java:766)
	at mage.game.GameImpl.start(GameImpl.java:733)
	at org.mage.test.serverside.base.impl.CardTestPlayerAPIImpl.execute(CardTestPlayerAPIImpl.java:186)
	at org.mage.test.cards.single.emn.SpellQuellerTest.testExiledSpellProcessedThenQuellerDies(SpellQuellerTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
FATAL [2016-07-29 15:51 [06:664]] GameImpl[main]: Game exception 
mage.MageException: Error in testclass
	at mage.game.GameImpl.playPriority(GameImpl.java:1349)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:152)
	at mage.game.GameImpl.playTurn(GameImpl.java:852)
	at mage.game.GameImpl.play(GameImpl.java:766)
	at mage.game.GameImpl.start(GameImpl.java:733)
	at org.mage.test.serverside.base.impl.CardTestPlayerAPIImpl.execute(CardTestPlayerAPIImpl.java:186)
	at org.mage.test.cards.single.emn.SpellQuellerTest.testExiledSpellProcessedThenQuellerDies(SpellQuellerTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)

**Comment by drmDev** [comment]
Fixed with latest commit
