### ISSUE TITLE
Bane of Progress causes NPE

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2271]
```
FATAL 2016-09-12 03:52:06,135 Game exception gameId: b987d198-5f3c-4067-877a-d02ef4ee676f                                =>[GAME b987d198-5f3c-4067-877a-d02ef4ee676f] GameImpl.playPriority
java.lang.NullPointerException
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:227)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.game.permanent.PermanentCard.moveToZone(PermanentCard.java:162)
	at mage.cards.CardImpl.moveToZone(CardImpl.java:337)
	at mage.game.permanent.PermanentImpl.destroy(PermanentImpl.java:959)
	at mage.sets.commander2013.BaneOfProgressEffect.apply(BaneOfProgress.java:101)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:197)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:100)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:106)
	at mage.game.GameImpl.resolve(GameImpl.java:1368)
	at mage.game.GameImpl.playPriority(GameImpl.java:1319)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:152)
	at mage.game.GameImpl.playTurn(GameImpl.java:852)
	at mage.game.GameImpl.play(GameImpl.java:766)
	at mage.game.GameImpl.start(GameImpl.java:733)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by LevelX2** [comment]
Another example:

```
java.lang.NullPointerException
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:227)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.game.permanent.PermanentCard.moveToZone(PermanentCard.java:162)
	at mage.cards.CardImpl.moveToZone(CardImpl.java:337)
	at mage.game.permanent.PermanentImpl.destroy(PermanentImpl.java:959)
	at mage.sets.commander2013.DecreeOfPainEffect.apply(DecreeOfPain.java:99)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:197)
	at mage.game.stack.Spell.resolve(Spell.java:215)
	at mage.game.GameImpl.resolve(GameImpl.java:1368)
	at mage.game.GameImpl.playPriority(GameImpl.java:1319)
```

**Comment by Dilnu** [comment]
Sorry about this, I added https://github.com/magefree/mage/pull/2273 to fix this edge case, and added another bit of code for the same situation. I hadn't thought about tokens at all and I certainly hadn't considered this edge case. This bug shouldn't occur any longer.
