### ISSUE TITLE
CardView creates null pointer exception 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2272]
taken from from xmage.de server log

```
java.lang.NullPointerException
    at mage.view.CardView.<init>(CardView.java:168)
    at mage.view.CardView.<init>(CardView.java:153)
    at mage.view.CardView.<init>(CardView.java:131)
    at mage.view.PlayerView.<init>(PlayerView.java:128)
    at mage.view.GameView.<init>(GameView.java:95)
    at mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:239)
    at mage.server.game.GameSessionPlayer.select(GameSessionPlayer.java:103)
    at mage.server.game.GameController$18.execute(GameController.java:868)
    at mage.server.game.GameController.perform(GameController.java:1019)
    at mage.server.game.GameController.perform(GameController.java:1012)
    at mage.server.game.GameController.select(GameController.java:865)
    at mage.server.game.GameController.access$1100(GameController.java:97)
    at mage.server.game.GameController$2.event(GameController.java:240)
    at mage.server.game.GameController$2.event(GameController.java:224)
    at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:56)
    at mage.game.events.PlayerQueryEventSource.select(PlayerQueryEventSource.java:67)
    at mage.game.GameImpl.firePriorityEvent(GameImpl.java:1990)
    at mage.player.human.HumanPlayer.priority(HumanPlayer.java:679)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ingmargoudt** [comment]
line that causes a null reference: player.getLibrary().getFromTop() , this is then passed down to CardView

**Comment by drmDev** [comment]
might be resolved with some of the recent commits that did massive overhauls?

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.
