### ISSUE TITLE
Xmage Launcher Issue "Xmage not found"

### ISSUE THREAD

**Issue by slovenhjelm** [magefree/mage#2323]
I donloaded a new version of xmage today, 1.4.15v3 (2016-09-18). the launcher started giving me the error message:  "XMage not found", and when i check the xmage folder, i dont have xmage launcher and xmage server folders.

i have tried changing the "read only" option on the parent folder, create a new folder, re-download xmage.jar. i have also tried redownload java and a reboot of PC, nothing worked.

log:

ERROR 2016-09-18 16:56:14,712 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateXMage
java.io.EOFException: Truncated ZIP entry: mage-client/lib/swingx-1.6.1.jar
    at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.drainCurrentEntryData(ZipArchiveInputStream.java:619)
    at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.closeEntry(ZipArchiveInputStream.java:583)
    at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:193)
    at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:338)
    at com.xmage.launcher.DownloadTask.unzip(DownloadTask.java:208)
    at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:798)
    at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
    at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by Horadrik** [comment]
I'm having the same problem. Xmage was installed on computer and was working normally (Windows 10) , then it said that it needed to update, it entered in a loop and kept need to update. Always showing that xmage was not found.

Reading config from http://xmage.de/xmage/config.json
XMage folder:  C:\Users\Rodrigo\Desktop\Xmage\mage-master
XMage Launcher version installed:  0.3.8
XMage Launcher version available:  0.3.8
Java version installed:  
Java version available:  1.8.0_102
Java not found
XMage version installed:  
XMage version available:  1.4.15v4 (2016-09-19)
XMage not found
Downloading Java from http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jre-8u102-windows-x64.tar.gz
Installing Java ...Done
Downloading XMage from http://bit.ly/xmage_1_4_15v4o
Installing XMage ...Java version installed:  1.8.0_102
Java version available:  1.8.0_102
XMage version installed:  
XMage version available:  1.4.15v4 (2016-09-19)
XMage not found


Tried everything I could, reinstall and etcetera

**Comment by nishizu** [comment]
Same issues but the error pointed to another file

win 10
Java 1.8.0_102
xlauncher 0.3.8
xmage 1.4.15v4

INFO  2016-09-21 15:46:17,405 Detected screen DPI: 96                                                                    =>[main] Config.<clinit>
ERROR 2016-09-21 15:48:49,767 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateXMage
java.io.EOFException: Truncated ZIP entry: mage-server/lib/commons-logging-1.1.1.jar
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.drainCurrentEntryData(ZipArchiveInputStream.java:619)
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.closeEntry(ZipArchiveInputStream.java:583)
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:193)
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:338)
        at com.xmage.launcher.DownloadTask.unzip(DownloadTask.java:208)
        at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:798)
        at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
        at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by AedenGB** [comment]
Same issue here and I definitely have java installed. I'm on a windows 10 Dell XPS 15.

Here's my log:

Reading config from http://xmage.de/xmage/config.json
XMage folder:  C:\Users\scruf\Dropbox\Documents\Aeden's Stuff\MTG\xmage
XMage Launcher version installed:  0.3.8
XMage Launcher version available:  0.3.8
Java version installed:  
Java version available:  1.8.0_102
Java not found
XMage version installed:  
XMage version available:  1.4.16v3 (2016-10-09)
XMage not found
Downloading Java from http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jre-8u102-windows-x64.tar.gz
Installing Java ...Done
Downloading XMage from http://bit.ly/xmage_1_4_16v3o
Installing XMage ...Java version installed:  1.8.0_102
Java version available:  1.8.0_102
XMage version installed:  
XMage version available:  1.4.16v3 (2016-10-09)
XMage not found

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
