### ISSUE TITLE
[KLD] Janjeet Sentry cannot be cast.

### ISSUE THREAD

**Issue by brodee** [magefree/mage#2353]
it causes server side errors:
Exception in thread "CALL main-67" java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at mage.server.ChatManager.leaveChat(ChatManager.java:75)
	at mage.server.MageServerImpl$14.execute(MageServerImpl.java:562)
	at mage.server.MageServerImpl$53.run(MageServerImpl.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

and the client reports:
WARN  2016-09-20 21:54:41,409 message out of sequence - ignoringMessageId = 29 method = gameInform                       =>[AWT-EventQueue-0] CallbackClientImpl$1.run 
FATAL 2016-09-20 21:54:46,820 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,822 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,823 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,823 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,824 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,830 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2016-09-20 21:54:46,834 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
..... infinite loop

**Comment by brodee** [comment]
missed the dup https://github.com/magefree/mage/issues/2331
