### ISSUE TITLE
AI cant use MorphAbility

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2366]
java.util.concurrent.ExecutionException: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:493)
    at mage.player.ai.ComputerPlayer7.calculatePreCombatActions(ComputerPlayer7.java:171)
    at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:110)
    at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:86)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:586)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:608)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:483)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:480)
    ... 4 more
java.util.concurrent.ExecutionException: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:493)
    at mage.player.ai.ComputerPlayer7.calculatePostCombatActions(ComputerPlayer7.java:212)
    at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:146)
    at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:86)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:586)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:608)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:483)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:480)
    ... 4 more
java.util.concurrent.ExecutionException: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:493)
    at mage.player.ai.ComputerPlayer7.calculatePreCombatActions(ComputerPlayer7.java:171)
    at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:110)
    at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:86)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:586)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:608)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:483)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:480)
    ... 4 more
java.util.concurrent.ExecutionException: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:493)
    at mage.player.ai.ComputerPlayer7.calculatePostCombatActions(ComputerPlayer7.java:212)
    at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:146)
    at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:86)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:586)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:608)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:483)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:480)
    ... 4 more
java.util.concurrent.ExecutionException: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:493)
    at mage.player.ai.ComputerPlayer7.calculatePreCombatActions(ComputerPlayer7.java:171)
    at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:110)
    at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:86)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:586)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:608)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:483)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:480)
    ... 4 more
java.util.concurrent.ExecutionException: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:493)
    at mage.player.ai.ComputerPlayer7.calculatePostCombatActions(ComputerPlayer7.java:212)
    at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:146)
    at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:86)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: mage.abilities.keyword.MorphAbility cannot be cast to mage.abilities.ActivatedAbility
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:586)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:608)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:330)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:483)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:480)
    ... 4 more

**Comment by Zerrisx** [comment]
Fairly sure this is resolved, given the AI now can (and does) cast morphs and then un-morph them.
