### ISSUE TITLE
Flashback + Buyback produce StackOverflowError 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2367]
It would still go to exile. The relevant rule:

702.33a Flashback appears on some instants and sorceries. It represents two static abilities: one that functions while the card is in a players graveyard and another that functions while the card is on the stack. Flashback [cost] means You may cast this card from your graveyard by paying [cost] rather than paying its mana cost and If the flashback cost was paid, exile this card instead of putting it anywhere else any time it would leave the stack. Casting a spell using its flashback ability follows the rules for paying alternative costs in rules 601.2b and 601.2fh.

```
FATAL 2016-09-22 01:10:01,203 GameWorker general error [c7beac28-9a3d-42d2-9f31-7a20b8ff49fb] java.lang.StackOverflowError =>[GAME c7beac28-9a3d-42d2-9f31-7a20b8ff49fb] GameWorker.call
java.lang.StackOverflowError
	at mage.cards.CardImpl.moveToExile(CardImpl.java:374)
	at mage.cards.CardImpl.moveToExile(CardImpl.java:366)
	at mage.players.PlayerImpl.moveCardToExileWithInfo(PlayerImpl.java:3381)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3186)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3123)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3114)
	at mage.abilities.keyword.FlashbackReplacementEffect.replaceEvent(FlashbackAbility.java:277)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.cards.CardImpl.moveToZone(CardImpl.java:352)
	at mage.abilities.keyword.BuybackEffect.replaceEvent(BuybackAbility.java:207)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.cards.CardImpl.moveToExile(CardImpl.java:374)
	at mage.cards.CardImpl.moveToExile(CardImpl.java:366)
	at mage.players.PlayerImpl.moveCardToExileWithInfo(PlayerImpl.java:3381)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3186)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3123)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3114)
	at mage.abilities.keyword.FlashbackReplacementEffect.replaceEvent(FlashbackAbility.java:277)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.cards.CardImpl.moveToZone(CardImpl.java:352)
	at mage.abilities.keyword.BuybackEffect.replaceEvent(BuybackAbility.java:207)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.cards.CardImpl.moveToExile(CardImpl.java:374)
	at mage.cards.CardImpl.moveToExile(CardImpl.java:366)
	at mage.players.PlayerImpl.moveCardToExileWithInfo(PlayerImpl.java:3381)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3186)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3123)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3114)
	at mage.abilities.keyword.FlashbackReplacementEffect.replaceEvent(FlashbackAbility.java:277)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.cards.CardImpl.moveToZone(CardImpl.java:352)
	at mage.abilities.keyword.BuybackEffect.replaceEvent(BuybackAbility.java:207)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.cards.CardImpl.moveToExile(CardImpl.java:374)
	at mage.cards.CardImpl.moveToExile(CardImpl.java:366)
	at mage.players.PlayerImpl.moveCardToExileWithInfo(PlayerImpl.java:3381)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3186)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3123)
	at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3114)
	at mage.abilities.keyword.FlashbackReplacementEffect.replaceEvent(FlashbackAbility.java:277)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
	at mage.game.ZonesHandler.moveCards(ZonesHandler.java:56)
	at mage.game.ZonesHandler.moveCard(ZonesHandler.java:37)
	at mage.cards.CardImpl.moveToZone(CardImpl.java:352)
	at mage.abilities.keyword.BuybackEffect.replaceEvent(BuybackAbility.java:207)
	at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:857)
	at mage.game.GameState.replaceEvent(GameState.java:679)
	at mage.game.GameState.replaceEvent(GameState.java:672)
	at mage.game.GameImpl.replaceEvent(GameImpl.java:2342)
	at mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:213)
...
```

**Comment by LevelX2** [comment]
Fixed.
