### ISSUE TITLE
User manager exception

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2369]
FATAL 2016-09-22 12:20:12,078 User manager exception
java.lang.NullPointerException
    at mage.game.Table.toProto(Table.java:317)
    at mage.server.record.TableRecorderImpl.record(TableRecorderImpl.java:18)
    at mage.game.Table.setState(Table.java:246)
    at mage.game.Table.endTournament(Table.java:127)
    at mage.server.TableController.endTournament(TableController.java:685)
    at mage.server.TableManager.endTournament(TableManager.java:304)
    at mage.server.tournament.TournamentController.endTournament(TournamentController.java:239)
    at mage.server.tournament.TournamentController.access$600(TournamentController.java:69)
    at mage.server.tournament.TournamentController$1.event(TournamentController.java:108)
    at mage.server.tournament.TournamentController$1.event(TournamentController.java:90)
    at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:56)
    at mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:62)
    at mage.game.tournament.TournamentImpl.construct(TournamentImpl.java:396)
    at mage.tournament.BoosterDraftSwissTournament.nextStep(BoosterDraftSwissTournament.java:76)
    at mage.server.TableController.endDraft(TableController.java:840)
    at mage.server.TableManager.endDraft(TableManager.java:298)
    at mage.server.draft.DraftController.endDraft(DraftController.java:200)
    at mage.server.draft.DraftController.abortDraft(DraftController.java:264)
    at mage.server.tournament.TournamentController.abortDraftTournament(TournamentController.java:433)
    at mage.server.tournament.TournamentController.quit(TournamentController.java:363)
    at mage.server.tournament.TournamentManager.quit(TournamentManager.java:68)
    at mage.server.User.remove(User.java:381)
    at mage.server.UserManager$2.run(UserManager.java:145)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by drmDev** [comment]
I know there's been some recent changes to UserManager and thread handling. Not sure if this is still ongoing?

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.
