### ISSUE TITLE
ConcurrentModificationException during library copy

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2370]
```
FATAL 2016-09-22 18:41:10,342 Game exception gameId: ebc97f6a-e7dd-4f83-a430-4a6eb9b741a7                                =>[GAME ebc97f6a-e7dd-4f83-a430-4a6eb9b741a7] GameImpl.playPriority
java.util.ConcurrentModificationException
    at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:643)
    at mage.players.Library.<init>(Library.java:66)
    at mage.players.Library.copy(Library.java:162)
    at mage.players.PlayerImpl.<init>(PlayerImpl.java:272)
    at mage.player.human.HumanPlayer.<init>(HumanPlayer.java:136)
    at mage.player.human.HumanPlayer.copy(HumanPlayer.java:1453)
    at mage.player.human.HumanPlayer.copy(HumanPlayer.java:103)
    at mage.players.Players.<init>(Players.java:45)
    at mage.players.Players.copy(Players.java:60)
    at mage.game.GameState.<init>(GameState.java:154)
    at mage.game.GameState.copy(GameState.java:241)
    at mage.game.GameStates.save(GameStates.java:54)
    at mage.game.GameImpl.saveState(GameImpl.java:577)
    at mage.game.GameImpl.bookmarkState(GameImpl.java:660)
    at mage.players.PlayerImpl.playAbility(PlayerImpl.java:1115)
    at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1199)
    at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1246)
    at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1256)
    at mage.player.human.HumanPlayer.priority(HumanPlayer.java:716)
    at mage.game.GameImpl.playPriority(GameImpl.java:1298)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:152)
    at mage.game.GameImpl.playTurn(GameImpl.java:852)
    at mage.game.GameImpl.play(GameImpl.java:766)
    at mage.game.GameImpl.start(GameImpl.java:733)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.
