### ISSUE TITLE
Error importing from clipboard in deck editor

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2402]
I have not been able to import from clipboard since it was implemented. I noticed this error gets thrown when trying to do it.

INFO  2016-09-29 00:42:27,832 1          =>[AWT-EventQueue-0] DeckEditorPanel$10.actionPerformed 
FATAL 2016-09-29 00:42:27,834 MAGE Client UI error             =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.awt.IllegalComponentStateException: contentPane cannot be set to null.
	at javax.swing.JRootPane.setContentPane(JRootPane.java:621)
	at javax.swing.JDialog.setContentPane(JDialog.java:1047)
	at mage.client.deckeditor.DeckImportFromClipboardDialog.<init>(DeckImportFromClipboardDialog.java:20)
	at mage.client.deckeditor.DeckEditorPanel.btnImportFromClipboardActionPerformed(DeckEditorPanel.java:739)
	at mage.client.deckeditor.DeckEditorPanel.access$2100(DeckEditorPanel.java:78)
	at mage.client.deckeditor.DeckEditorPanel$10.actionPerformed(DeckEditorPanel.java:603)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by spjspj** [comment]
Fixed with #2435 hopefully.
