### ISSUE TITLE
java.net.SocketException when attempting to log in to server

### ISSUE THREAD

**Issue by Okiesmokie** [magefree/mage#2475]
I've been constantly getting exceptions when trying to log in to most servers.  It connects to the server fine, but gets a SocketException when attempting to log in.

Console Log:

INFO  2016-10-17 06:37:54,095 Trying to connect to XMAGE server at xmage.de:17171                                        =>[SwingWorker-pool-4-thread-5] SessionImpl$5.run 
INFO  2016-10-17 06:37:55,503 Connected to MAGE server at xmage.de:17171                                                 =>[SwingWorker-pool-4-thread-5] SessionImpl$5.run 
INFO  2016-10-17 06:37:55,503 Trying to log-in as Okiesmokie to XMAGE server at xmage.de:17171                           =>[SwingWorker-pool-4-thread-5] SessionImpl$4.run 
FATAL 2016-10-17 06:38:04,770 error                                                                                      =>[SwingWorker-pool-4-thread-5] RegularObjectPersister.writeSlotWithMethod 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithMethod(RegularObjectPersister.java:120)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:86)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ArrayPersister.saveObjectArray(ArrayPersister.java:110)
    at org.jboss.serial.persister.ArrayPersister.writeData(ArrayPersister.java:101)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.io.JBossObjectOutputStream.writeObjectOverride(JBossObjectOutputStream.java:181)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
    at org.jboss.remoting.serialization.impl.jboss.JBossSerializationManager.sendObject(JBossSerializationManager.java:133)
    at org.jboss.remoting.marshal.serializable.SerializableMarshaller.write(SerializableMarshaller.java:120)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.versionedWrite(MicroSocketClientInvoker.java:1347)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:885)
    at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
    at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
    at org.jboss.remoting.Client.invoke(Client.java:2084)
    at org.jboss.remoting.Client.invoke(Client.java:879)
    at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
    at com.sun.proxy.$Proxy8.getMissingCardsData(Unknown Source)
    at mage.remote.SessionImpl.updateDatabase(SessionImpl.java:414)
    at mage.remote.SessionImpl.access$600(SessionImpl.java:68)
    at mage.remote.SessionImpl$4.run(SessionImpl.java:233)
    at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:113)
    at mage.remote.SessionImpl.connect(SessionImpl.java:216)
    at mage.client.SessionHandler.connect(SessionHandler.java:48)
    at mage.client.MageFrame.connect(MageFrame.java:819)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:411)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:401)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at org.jboss.remoting.transport.socket.TimedOutputStream.write(TimedOutputStream.java:122)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
    at java.io.DataOutputStream.writeBoolean(DataOutputStream.java:139)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeBoolean(DataContainer.java:234)
    at org.jboss.serial.util.StringUtil.saveString(StringUtil.java:71)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.saveImmutable(DataContainer.java:295)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:149)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ObjectOutputStreamProxy.writeObjectOverride(ObjectOutputStreamProxy.java:60)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
    at java.util.ArrayList.writeObject(ArrayList.java:762)
    ... 50 more
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithMethod(RegularObjectPersister.java:120)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:86)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ArrayPersister.saveObjectArray(ArrayPersister.java:110)
    at org.jboss.serial.persister.ArrayPersister.writeData(ArrayPersister.java:101)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.io.JBossObjectOutputStream.writeObjectOverride(JBossObjectOutputStream.java:181)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
    at org.jboss.remoting.serialization.impl.jboss.JBossSerializationManager.sendObject(JBossSerializationManager.java:133)
    at org.jboss.remoting.marshal.serializable.SerializableMarshaller.write(SerializableMarshaller.java:120)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.versionedWrite(MicroSocketClientInvoker.java:1347)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:885)
    at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
    at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
    at org.jboss.remoting.Client.invoke(Client.java:2084)
    at org.jboss.remoting.Client.invoke(Client.java:879)
    at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
    at com.sun.proxy.$Proxy8.getMissingCardsData(Unknown Source)
    at mage.remote.SessionImpl.updateDatabase(SessionImpl.java:414)
    at mage.remote.SessionImpl.access$600(SessionImpl.java:68)
    at mage.remote.SessionImpl$4.run(SessionImpl.java:233)
    at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:113)
    at mage.remote.SessionImpl.connect(SessionImpl.java:216)
    at mage.client.SessionHandler.connect(SessionHandler.java:48)
    at mage.client.MageFrame.connect(MageFrame.java:819)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:411)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:401)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at org.jboss.remoting.transport.socket.TimedOutputStream.write(TimedOutputStream.java:122)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
    at java.io.DataOutputStream.writeBoolean(DataOutputStream.java:139)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeBoolean(DataContainer.java:234)
    at org.jboss.serial.util.StringUtil.saveString(StringUtil.java:71)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.saveImmutable(DataContainer.java:295)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:149)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ObjectOutputStreamProxy.writeObjectOverride(ObjectOutputStreamProxy.java:60)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
    at java.util.ArrayList.writeObject(ArrayList.java:762)
    ... 50 more
FATAL 2016-10-17 06:38:04,808 Update Players Task error                                                                  =>[AWT-EventQueue-0] ConnectDialog$ConnectTask.done 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at javax.swing.SwingWorker.get(SwingWorker.java:612)
    at mage.client.dialog.ConnectDialog$ConnectTask.done(ConnectDialog.java:418)
    at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
    at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at mage.client.dialog.MageDialog.startModal(MageDialog.java:139)
    at mage.client.dialog.MageDialog.show(MageDialog.java:82)
    at java.awt.Component.show(Component.java:1671)
    at java.awt.Component.setVisible(Component.java:1623)
    at javax.swing.JComponent.setVisible(JComponent.java:2644)
    at mage.client.dialog.MageDialog.setVisible(MageDialog.java:88)
    at mage.client.dialog.ConnectDialog.showDialog(ConnectDialog.java:129)
    at mage.client.MageFrame.btnConnectActionPerformed(MageFrame.java:1061)
    at mage.client.MageFrame.access$1300(MageFrame.java:159)
    at mage.client.MageFrame$12.actionPerformed(MageFrame.java:939)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
    at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:123)
    at mage.remote.SessionImpl.connect(SessionImpl.java:216)
    at mage.client.SessionHandler.connect(SessionHandler.java:48)
    at mage.client.MageFrame.connect(MageFrame.java:819)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:411)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:401)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by goesta** [comment]
Is this still a problem or can we close the issue?
