### ISSUE TITLE
Draft NPE with card with variant art

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2478]
I am implementing new cubes and got these 2 errors when a card (Order of the Ebon Hand) with variant art was generated in a booster pack. The draft froze and did not continue.

`FATAL 2016-10-17 19:46:25,772 Error loading card: mage.cards.o.OrderOfTheEbonHand                                        =>[CALL main-57] CardImpl.createCard
java.lang.ClassNotFoundException: mage.cards.o.OrderOfTheEbonHand
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:260)
    at mage.cards.CardImpl.createCard(CardImpl.java:171)
    at mage.cards.repository.CardInfo.getCard(CardInfo.java:203)
    at mage.game.draft.DraftCube.createBooster(DraftCube.java:119)
    at mage.game.draft.DraftImpl.openBooster(DraftImpl.java:236)
    at mage.game.draft.BoosterDraft.start(BoosterDraft.java:47)
    at mage.server.draft.DraftController.startDraft(DraftController.java:176)
    at mage.server.draft.DraftController.access$400(DraftController.java:54)
    at mage.server.draft.DraftController$3.run(DraftController.java:162)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

`Exception in thread "CALL main-57" java.lang.NullPointerException
    at mage.player.ai.ComputerPlayer.pickCard(ComputerPlayer.java:1823)
    at mage.game.draft.DraftImpl.pickCards(DraftImpl.java:254)
    at mage.game.draft.BoosterDraft.start(BoosterDraft.java:48)
    at mage.server.draft.DraftController.startDraft(DraftController.java:176)
    at mage.server.draft.DraftController.access$400(DraftController.java:54)
    at mage.server.draft.DraftController$3.run(DraftController.java:162)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by fireshoes** [comment]
Repeated the errors on another card with alt-art (Order of Leitbur).


```FATAL 2016-10-17 20:17:40,429 Error loading card: mage.cards.o.OrderOfLeitbur                                            =>[CALL main-111] CardImpl.createCard
java.lang.ClassNotFoundException: mage.cards.o.OrderOfLeitbur
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at mage.cards.CardImpl.createCard(CardImpl.java:171)
	at mage.cards.repository.CardInfo.getCard(CardInfo.java:203)
	at mage.game.draft.DraftCube.createBooster(DraftCube.java:119)
	at mage.game.draft.DraftImpl.openBooster(DraftImpl.java:236)
	at mage.game.draft.BoosterDraft.start(BoosterDraft.java:47)
	at mage.server.draft.DraftController.startDraft(DraftController.java:176)
	at mage.server.draft.DraftController.access$400(DraftController.java:54)
	at mage.server.draft.DraftController$3.run(DraftController.java:162)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by JOAC69** [comment]
The problem is the class names for those cards have a 1 on the end : mage.cards.o.OrderOfTheEbonHand1 and mage.cards.o.OrderOfLeitbur1. Maybe try rebuilding your client and server DB files.

**Comment by JOAC69** [comment]
BTW - I will be fixing the classes this week to get rid of the # at end of card class names that were multiples (variant art). However, it should work as it is now just somehow your DB might be off. If the DB is fine then I'll check to see if it is stripping the number before class load.

**Comment by drmDev** [comment]
Is this issue still unresolved?

**Comment by drmDev** [comment]
I'm assuming at this point from what it sounds like, this issue should be resolved. I'll re-open if not (been 3 weeks without any update )
