### ISSUE TITLE
Unable to connect to server. Server likely offline

### ISSUE THREAD

**Issue by nottaran** [magefree/mage#2497]
This is the first time it's happened to me. I played just fine yesterday and today I try to play and nothing.

I click on startmagewin7 then the whole thing pops up, I click on connect and it tells me this "Unable to connect to server. Server likely offline"

How can I fix this?

```
oct. 25, 2016 6:40:36 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2016-10-25 06:40:36,328 Starting MAGE client version 1.4.12v0                                                      =>[main] MageFrame.main 
INFO  2016-10-25 06:40:36,331 Logging level: INFO                                                                        =>[main] MageFrame.main 
ERROR 2016-10-25 06:40:37,380 Couldn't rename mana symbols!                                                              =>[AWT-EventQueue-0] ManaSymbols.renameSymbols 
INFO  2016-10-25 06:40:38,009 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-10-25 06:40:38,074 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2016-10-25 06:40:38,084 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-10-25 06:40:40,966 Card pool load time: 1 seconds                                                             =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2016-10-25 06:40:41,112 Card images checking time: 0 seconds                                                       =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2016-10-25 06:40:44,133 Client start up time: 7 seconds                                                            =>[AWT-EventQueue-0] MageFrame$6.run 
INFO  2016-10-25 06:40:44,140 Trying to connect to XMAGE server at xmage.de:17171                                        =>[AWT-EventQueue-0] SessionImpl$5.run 
WARN  2016-10-25 06:41:05,402 Cannot connect                                                                             =>[AWT-EventQueue-0] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
    at org.jboss.remoting.Client.connect(Client.java:1928)
    at org.jboss.remoting.Client.connect(Client.java:737)
    at mage.remote.SessionImpl$5.run(SessionImpl.java:403)
    at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:136)
    at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:281)
    at mage.remote.SessionImpl.connect(SessionImpl.java:239)
    at mage.client.MageFrame.connect(MageFrame.java:755)
    at mage.client.MageFrame.performConnect(MageFrame.java:799)
    at mage.client.MageFrame.autoConnect(MageFrame.java:768)
    at mage.client.MageFrame$6.run(MageFrame.java:379)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$300(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.Exception: Error setting up client lease
    at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
    at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
    at org.jboss.remoting.Client.connect(Client.java:1924)
    ... 23 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://xmage.de:17171/?serializationtype=jboss]
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
    at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
    at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
    at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
    ... 25 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
    at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
    at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
    ... 28 more
FATAL 2016-10-25 06:41:08,820 Error disconnecting ...                                                                    =>[AWT-EventQueue-0] SessionImpl.disconnect 
java.lang.Exception: Can not remove callback listener as remoting client is not connected to server.
    at org.jboss.remoting.Client.removeListener(Client.java:1466)
    at mage.remote.SessionImpl.disconnect(SessionImpl.java:502)
    at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:428)
    at mage.remote.SessionImpl.connect(SessionImpl.java:239)
    at mage.client.MageFrame.connect(MageFrame.java:755)
    at mage.client.MageFrame.performConnect(MageFrame.java:799)
    at mage.client.MageFrame.autoConnect(MageFrame.java:768)
    at mage.client.MageFrame$6.run(MageFrame.java:379)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$300(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
INFO  2016-10-25 06:41:08,820 Disconnected ...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2016-10-25 06:41:08,820 DISCONNECTED (Event Dispatch Thread)                                                       =>[AWT-EventQueue-0] MageFrame.disconnected 
```

**Comment by goesta** [comment]
Is this still a problem or can we close this issue?
