### ISSUE TITLE
NPE on Disconnect (no window prompt for disconnect)

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2548]
Got disconnected twice tonight, but no window popped up to say I was disconnected. This NPE was in the log. Not sure if from the no window part or just the disconnect in general.
```INFO  2016-11-01 23:55:23,075 DISCONNECTED (Event Dispatch Thread)                                                       =>[AWT-EventQueue-0] MageFrame.disconnected 
FATAL 2016-11-01 23:55:23,205 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.MageFrame$24.run(MageFrame.java:1423)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by LevelX2** [comment]
But does the reconnect window still appear sometimes?

I remember I did some changes to the reconnect process, but this behavior was not intended.

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.
