### ISSUE TITLE
Client UI goes completely crazy (Win 10)

### ISSUE THREAD

**Issue by Averethel** [magefree/mage#2611]
Occasionally the UI goes completely nuts while playing on windows. The elements start to resize randomly and move to random places on the screen. It is impossible to continue the game while this happens.

This is what I found in the log file:
```
FATAL 2016-11-20 17:26:32,691 MAGE Client UI error                                                                       =>[Thread-1] EDTExceptionHandler.handle 
net.java.truevfs.kernel.spec.FsSyncException: zip:file:/D:/Users/ksakw_000/Downloads/xmage/mage-client/plugins/images/OGW.thumb.zip!/
	at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:357)
	at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:349)
	at scala.Option.foreach(Option.scala:257)
	at net.java.truevfs.kernel.impl.TargetArchiveController.close(TargetArchiveController.scala:349)
	at net.java.truevfs.kernel.impl.TargetArchiveController.sync(TargetArchiveController.scala:253)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$ResourceController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.ResourceController$class.sync(ResourceController.scala:70)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$CacheController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.CacheController$class.sync(CacheController.scala:116)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$SyncController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.SyncController$class.doSync(SyncController.scala:172)
	at net.java.truevfs.kernel.impl.SyncController$class.sync(SyncController.scala:149)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$LockController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply$mcV$sp(LockController.scala:96)
	at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply(LockController.scala:96)
	at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply(LockController.scala:96)
	at net.java.truevfs.kernel.impl.LockingStrategy.apply(LockingStrategy.scala:84)
	at net.java.truevfs.kernel.impl.LockController$class.sync(LockController.scala:96)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.ArchiveControllerAdapter.sync(ArchiveControllerAdapter.scala:37)
	at net.java.truevfs.comp.zipdriver.AbstractKeyController.sync(AbstractKeyController.java:147)
	at net.java.truevfs.kernel.spec.FsDecoratingController.sync(FsDecoratingController.java:117)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.sync(FalsePositiveArchiveController.scala:157)
	at net.java.truevfs.kernel.spec.FsControllerSyncVisitor.visit(FsControllerSyncVisitor.java:49)
	at net.java.truevfs.kernel.spec.FsControllerSyncVisitor.visit(FsControllerSyncVisitor.java:22)
	at net.java.truevfs.kernel.spec.FsAbstractManager$1AssembleExceptionVisitor.visit(FsAbstractManager.java:34)
	at net.java.truevfs.kernel.spec.FsAbstractManager$1AssembleExceptionVisitor.visit(FsAbstractManager.java:30)
	at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$accept$3.apply(DefaultManager.scala:95)
	at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$accept$3.apply(DefaultManager.scala:95)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at net.java.truevfs.kernel.impl.DefaultManager.accept(DefaultManager.scala:95)
	at net.java.truevfs.kernel.spec.FsAbstractManager.sync(FsAbstractManager.java:39)
	at net.java.truevfs.kernel.impl.DefaultManager.sync(DefaultManager.scala:87)
	at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$1.apply$mcV$sp(DefaultManager.scala:37)
	at net.java.truevfs.kernel.impl.ShutdownFuse$$anonfun$net$java$truevfs$kernel$impl$ShutdownFuse$$onDisarm$2.apply$mcV$sp(ShutdownFuse.scala:55)
	at net.java.truevfs.kernel.impl.ShutdownFuse.net$java$truevfs$kernel$impl$ShutdownFuse$$onCondition(ShutdownFuse.scala:61)
	at net.java.truevfs.kernel.impl.ShutdownFuse.net$java$truevfs$kernel$impl$ShutdownFuse$$onDisarm(ShutdownFuse.scala:53)
	at net.java.truevfs.kernel.impl.ShutdownFuse$$anon$1.run(ShutdownFuse.scala:29)
	Suppressed: net.java.truevfs.kernel.spec.FsSyncException: zip:file:/D:/Users/ksakw_000/Downloads/xmage/mage-client/plugins/images/KLD.thumb.zip!/
		... 41 more
	Caused by: java.nio.file.AccessDeniedException: D:\Users\ksakw_000\Downloads\xmage\mage-client\plugins\images\KLD.thumb.zip
		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
		at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
		at java.nio.file.Files.newOutputStream(Unknown Source)
		at net.java.truevfs.driver.file.FileOutputSocket$1Stream.<init>(FileOutputSocket.java:240)
		at net.java.truevfs.driver.file.FileOutputSocket.stream(FileOutputSocket.java:254)
		at net.java.truecommons.cio.IoSockets$OutputAdapter.stream(IoSockets.java:84)
		at net.java.truecommons.io.Streams.copy(Streams.java:82)
		at net.java.truecommons.cio.IoSockets.copy(IoSockets.java:43)
		at net.java.truevfs.driver.file.FileOutputSocket.close(FileOutputSocket.java:163)
		at net.java.truevfs.driver.file.FileOutputSocket$1Stream.close(FileOutputSocket.java:248)
		at net.java.truecommons.io.DecoratingOutputStream.close(DecoratingOutputStream.java:56)
		at net.java.truevfs.comp.zip.AbstractZipOutputStream.close(AbstractZipOutputStream.java:681)
		at net.java.truevfs.comp.zipdriver.ZipOutputService.close(ZipOutputService.java:272)
		at net.java.truevfs.kernel.spec.cio.MultiplexingOutputService.close(MultiplexingOutputService.java:155)
		at net.java.truecommons.cio.DecoratingOutputService.close(DecoratingOutputService.java:32)
		at net.java.truevfs.kernel.impl.DisconnectingOutputService.net$java$truevfs$kernel$impl$CheckedCloseable$$super$close(DisconnectingOutputService.scala:28)
		at net.java.truevfs.kernel.impl.CheckedCloseable$class.close(CheckedCloseable.scala:25)
		at net.java.truevfs.kernel.impl.DisconnectingOutputService.close(DisconnectingOutputService.scala:28)
		at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply$mcV$sp(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.LockOn$.apply(LockOn.scala:23)
		at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
		at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
		at net.java.truevfs.kernel.impl.LockOutputService.close(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:351)
		... 40 more
Caused by: java.nio.file.AccessDeniedException: D:\Users\ksakw_000\Downloads\xmage\mage-client\plugins\images\OGW.thumb.zip
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.nio.file.Files.newOutputStream(Unknown Source)
	at net.java.truevfs.driver.file.FileOutputSocket$1Stream.<init>(FileOutputSocket.java:240)
	at net.java.truevfs.driver.file.FileOutputSocket.stream(FileOutputSocket.java:254)
	at net.java.truecommons.cio.IoSockets$OutputAdapter.stream(IoSockets.java:84)
	at net.java.truecommons.io.Streams.copy(Streams.java:82)
	at net.java.truecommons.cio.IoSockets.copy(IoSockets.java:43)
	at net.java.truevfs.driver.file.FileOutputSocket.close(FileOutputSocket.java:163)
	at net.java.truevfs.driver.file.FileOutputSocket$1Stream.close(FileOutputSocket.java:248)
	at net.java.truecommons.io.DecoratingOutputStream.close(DecoratingOutputStream.java:56)
	at net.java.truevfs.comp.zip.AbstractZipOutputStream.close(AbstractZipOutputStream.java:681)
	at net.java.truevfs.comp.zipdriver.ZipOutputService.close(ZipOutputService.java:272)
	at net.java.truevfs.kernel.spec.cio.MultiplexingOutputService.close(MultiplexingOutputService.java:155)
	at net.java.truecommons.cio.DecoratingOutputService.close(DecoratingOutputService.java:32)
	at net.java.truevfs.kernel.impl.DisconnectingOutputService.net$java$truevfs$kernel$impl$CheckedCloseable$$super$close(DisconnectingOutputService.scala:28)
	at net.java.truevfs.kernel.impl.CheckedCloseable$class.close(CheckedCloseable.scala:25)
	at net.java.truevfs.kernel.impl.DisconnectingOutputService.close(DisconnectingOutputService.scala:28)
	at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply$mcV$sp(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.LockOn$.apply(LockOn.scala:23)
	at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
	at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
	at net.java.truevfs.kernel.impl.LockOutputService.close(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:351)
	... 40 more
```
The file that is referred to in the exception message is on the drive and does not seem to be corrupted (i.e. I can open it without any problems).

**Comment by Averethel** [comment]
Here's a log from another occurrence. It happened after deleting and redownloading all the symbols:

```
FATAL 2016-11-20 17:48:58,600 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.cards.repository.ExpansionRepository.getSetCodes(ExpansionRepository.java:64)
	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:53)
	at mage.client.MageFrame.<init>(MageFrame.java:291)
	at mage.client.MageFrame$22.run(MageFrame.java:1296)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

and a screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/144707/20464724/200cd3f2-af4d-11e6-8307-8aac33a14fda.png)

As reported before elements keep jumping in random places on the screen.
If you need any more details, please let me know - I'm happy to provide them.

**Comment by JRHerlehy** [comment]
This is related to Issue #1514 and has been known for a while.

From what I have seen with my own issues, this seems to due more with Java, Win10, and/or video drivers.

**Comment by drmDev** [comment]
We have a parent issue on this ongoing problem #1514 as mentioned above. I've marked this as a duplicate, but your information from here will be included on the parent issue ^
