### ISSUE TITLE
Frequent server disconnects and Null Ref Exceptions

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3021]
While trying to test some cards on localhost server, I'm running into these exceptions all the time. I have not been able to successfully stay connected to localhost even long enough to start a test game. I'll try to dig into this more, but I suspect it was from changes in a recent commit (perhaps @ingmargoudt change to Optionals ? )

```
INFO  2017-03-24 20:59:11,784 escplan9 connected to server                                                               =>[WorkerThread#3[192.168.0.3:57144]] SessionManager.connectUser
DEBUG 2017-03-24 20:59:11,784 - userId:    null                                                                          =>[WorkerThread#3[192.168.0.3:57144]] SessionManager.connectUser
DEBUG 2017-03-24 20:59:11,784 - sessionId: 5c4o03-b6vnrk-j0ojrmc8-1-j0ojskk3-e                                           =>[WorkerThread#3[192.168.0.3:57144]] SessionManager.connectUser
DEBUG 2017-03-24 20:59:11,784 - host:      192.168.0.3                                                                   =>[WorkerThread#3[192.168.0.3:57144]] SessionManager.connectUser
ERROR 2017-03-24 20:59:11,788 User with name escplan9 could not be found                                                 =>[WorkerThread#3[192.168.0.3:57144]] UserManager.getUserByName
Exception in thread "CALL main-39" java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at mage.server.UserManager.getUser(UserManager.java:70)
	at mage.server.ChatSession.join(ChatSession.java:64)
	at mage.server.ChatManager.joinChat(ChatManager.java:65)
	at mage.server.MageServerImpl.lambda$joinChat$6(MageServerImpl.java:534)
	at mage.server.MageServerImpl.lambda$execute$48(MageServerImpl.java:1203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
DEBUG 2017-03-24 20:59:51,316 DISCONNECT  Disconnected - sessionId: 5c4o03-b6vnrk-j0ojrmc8-1-j0ojskk3-e                  =>[WorkerThread#2[192.168.0.3:57147]] SessionManager.disconnect
DEBUG 2017-03-24 20:59:51,316 SESSION LOCK SET sessionId: 5c4o03-b6vnrk-j0ojrmc8-1-j0ojskk3-e                            =>[WorkerThread#2[192.168.0.3:57147]] Session.kill
DEBUG 2017-03-24 20:59:51,316 SESSION LOCK UNLOCK sessionId: 5c4o03-b6vnrk-j0ojrmc8-1-j0ojskk3-e                         =>[WorkerThread#2[192.168.0.3:57147]] Session.kill
ERROR 2017-03-24 20:59:51,319 Session with sessionId 5c4o03-b6vnrk-j0ojrmc8-1-j0ojskk3-e is not found                    =>[WorkerThread#3[192.168.0.3:57144]] SessionManager.getSession
ERROR 2017-03-24 20:59:51,320 Session not found : 5c4o03-b6vnrk-j0ojrmc8-1-j0ojskk3-e                                    =>[WorkerThread#3[192.168.0.3:57144]] Main$ClientConnectionListener.handleConnectionException
```

**Comment by drmDev** [comment]
Above was the server log messages, in the client log I see this:

```
INFO  2017-03-24 21:05:12,509 Connected to MAGE server at localhost:17171                                                =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2017-03-24 21:05:12,509 Trying to log-in as escplan9 to XMAGE server at localhost:17171                            =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
INFO  2017-03-24 21:05:12,587 Logged-in as escplan9 to MAGE server at localhost:17171                                    =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
FATAL 2017-03-24 21:05:30,212 Communication error                                                                        =>[AWT-EventQueue-0] SessionImpl.handleThrowable 
java.lang.NullPointerException
	at mage.server.MageServerImpl.handleException(MageServerImpl.java:1043)
	at mage.server.MageServerImpl.executeWithResult(MageServerImpl.java:1231)
	at mage.server.MageServerImpl.createTable(MageServerImpl.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	at com.sun.proxy.$Proxy8.createTable(Unknown Source)
	at mage.remote.SessionImpl.createTable(SessionImpl.java:1049)
	at mage.client.SessionHandler.createTable(SessionHandler.java:233)
	at mage.client.table.TablesPanel.btnQuickStartActionPerformed(TablesPanel.java:1204)
	at mage.client.table.TablesPanel.lambda$initComponents$26(TablesPanel.java:1060)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by drmDev** [comment]
I know @jeffwadsworth mentioned he's running into a lot more NREs and disconnects as well. Jeff - are these the same errors you're seeing?

**Comment by jeffwadsworth** [comment]
Yes.  I reverted a commit accidentally due to my local testing that I stupidly made part of the master.  Anyway, it may involve the one I made the comment on so I will test that in a separate branch.

**Comment by drmDev** [comment]
I confirmed this is the commit where the NRE starts to occur:
https://github.com/magefree/mage/commit/25752f913e69186b90262a97d45081cf4331835a

**Comment by jeffwadsworth** [comment]
Let's let @ingmargoudt check it out.  Fine with me.  Also, if someone could revert my "revert", that would be grand.  b4a60555fcd098c8bb960e71f76e0e1e618aa050

**Comment by drmDev** [comment]
With @ingmargoudt recent commit, it resolved this issue for me. Now I only have an issue when connecting to test server using two clients. I'll create a separate issue for that.
