### ISSUE TITLE
Cannot create game with 2 clients on test server

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3024]
In testing out a possible bugged card, I have two clients launched to connect to my localhost server in debug mode. 

I run the mage-client project for the first client and it connects and displays the lobby fine with my logged in name there (escplan9).

With the client launched from my regular XMage install, I appear to connect and it displays the lobby, but no players in it (should show both escplan9 and drmDev here). I see this message in the logs:

INFO  2017-03-25 11:59:58,251 Connected to MAGE server at localhost:17171                                                =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2017-03-25 11:59:58,251 Trying to log-in as drmDev to XMAGE server at localhost:17171                              =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
INFO  2017-03-25 11:59:58,283 Logged-in as drmDev to MAGE server at localhost:17171                                      =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
FATAL 2017-03-25 12:00:02,690 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ClassCastException: java.util.Optional cannot be cast to java.util.UUID
	at com.sun.proxy.$Proxy8.getRoomChatId(Unknown Source)
	at mage.remote.SessionImpl.getRoomChatId(SessionImpl.java:606)
	at mage.client.SessionHandler.getRoomChatId(SessionHandler.java:259)
	at mage.client.table.TablesPanel.showTables(TablesPanel.java:483)
	at mage.client.table.TablesPane.showTables(TablesPane.java:77)
	at mage.client.MageFrame.showGames(MageFrame.java:1021)
	at mage.client.dialog.ConnectDialog$ConnectTask.done(ConnectDialog.java:432)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:134)
	at mage.client.dialog.MageDialog.show(MageDialog.java:82)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:88)
	at mage.client.dialog.ConnectDialog.showDialog(ConnectDialog.java:123)
	at mage.client.MageFrame.lambda$new$2(MageFrame.java:320)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by drmDev** [comment]
However, I am able to have 2 clients connect to the server fine by running the mage-client project twice to launch the client from there. May just be a syncing issue of some sort between the current version of the mage-client (from my installed version of XMage)

**Comment by drmDev** [comment]
Pretty sure this is just me being an idiot - just needed two instances of the mage-client project run to be able to connect.

**Comment by spjspj** [comment]
Sounds like something has changed slightly in the client server interface
