### ISSUE TITLE
ConcurrentModificationException during GameImpl.checkStateBasedActions (from xmage.de server log)

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#3168]
```
FATAL 2017-04-18 09:39:34,274 Game exception gameId: bdd4cbbe-0e29-4d93-8354-d59df680f5ad                                =>[GAME bdd4cbbe-0e29-4d93-8354-d59df680f5ad] GameImpl.playPriority
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:324)
	at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:305)
	at mage.game.GameImpl.checkStateBasedActions(GameImpl.java:1943)
	at mage.game.GameCommanderImpl.checkStateBasedActions(GameCommanderImpl.java:200)
	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1562)
	at mage.game.GameImpl.playPriority(GameImpl.java:1259)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:819)
	at mage.game.GameImpl.play(GameImpl.java:728)
	at mage.game.GameImpl.start(GameImpl.java:692)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeffwadsworth** [comment]
Is this just related to Commander games?

**Comment by LevelX2** [comment]
Don't know.
It was at least a multiplayer game:
INFO  2017-04-18 09:03:04,397 GAME started bdd4cbbe-0e29-4d93-8354-d59df680f5ad [casual] ShiDZ - dsubs - Leethoof - Riven_Skull =>[CALL main-3290] TableController.startGame

**Comment by LevelX2** [comment]
Maybe it's caused somehow by the change to stream handling.

**Comment by magenoxx** [comment]
I found the cause: (it's not commander but multiplayer specific)
It can be seen from logs and from call hierarchy, GameImpl:2298 removes permanents from battlefield at the same time while another player plays priority iterating through the same battlefield object from gameState.

If it's duel then no remove happens due to:
`
if (checkIfGameIsOver()) {
    // no need to remove objects if only one player is left so the game is over
    return;
}
`

**Comment by ingmargoudt** [comment]
A stream does not cause a concurrentModificationException more than a regular forloop or iterator. It is caused by multiple threads accessing and mutating the same collection

**Comment by LevelX2** [comment]
I guess this problem can be the cause that permanents of quit/dead players stay on the battlefield.
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20299&start=60#p211691

Any idea how to fix?

**Comment by magenoxx** [comment]
Yes, looks like it's the same cause.

**Comment by magenoxx** [comment]
It's not so easy fix since requires adding locking (and not only for battlefield but exile, effects, etc.) that should be done carefully. And the risk is to lock something forever so game won't be able to continue.
I may look into it but with lowest priority.

**Comment by magenoxx** [comment]
There is another option that is to use:
http://docs.oracle.com/javase/6/docs/api/java/util/concurrent/CopyOnWriteArrayList.html
but as Javadoc says it may cost you memory.

**Comment by LevelX2** [comment]
If it's only used if a player > 2 is removed from a muliplayer game it shouldn't happen so much often, so probably memory usage is tolerable.

**Comment by magenoxx** [comment]
If we use CopyOnWriteArrayList then it will be so for all games modes. Or do you suggest to have for all arrays in the gameState logic like:
if players > 2
  array = new CopyOnWriteArrayList
else 
  array = new ArrayList
and similar for maps.

**Comment by ingmargoudt** [comment]
Also: 
http://stackoverflow.com/questions/17016747/linkedhashmap-concurrentmodificationexception-error

I *assume* a linkedhashset is used to determine the neighbours of a Player in a game, correct?

**Comment by LevelX2** [comment]
> Or do you suggest to have for all arrays in the gameState logic like

No, thought it would work more like copy the objects before doing the action. But this can't work.
So maybe your suggestion is a possible solution.

But I thought about another solution. The problem is caused by a player that concedes and the removing of the objects of the player is done in an other thread than the main game thread. So we should only flag the player as conceded (104.3a A player can concede the game at any time. A player who concedes leaves the game immediately. He or she loses the game.)  and also add an action to a new list named e.g. gameActionsToDoFromOtherThreads and add an entry (removePlayer + playerId).
The main game thread checks this list in it's priority iteration (and/or befoer checkStateBasedActions or more often) and executes the action in the main game thread.

So it should be prevented to get a ConcurrentModification exception.

**Comment by magenoxx** [comment]
@LevelX2 I like the idea

**Comment by ingmargoudt** [comment]
@LevelX2 I like that idea too, flag it and clean up after the game.

**Comment by magenoxx** [comment]
@ingmargoudt LevelX2 suggests even better, to have marked data removed by GameThread as state based effect (so since it's in the same thread, no concurrent access) - this way no need to wait until game ends

**Comment by ingmargoudt** [comment]
ah yes :)

**Comment by JayDi85** [comment]
Real reason: miss copy code in game and player objects, so AI in game simulations was able to access to the same objects (example: cards list, lki). Improved in 1664ee01cf30af2e85d725d63f22808ffdf2d61f. So must be fine now.
