### ISSUE TITLE
Mage Client UI error NPE

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#3197]
This fired off 28 times in less than a second playing a match today on the dev client. It occurred 18 seconds after my 1 vs 1 Amonkhet sealed tournament started, so I suppose something in the deck editor for sealed deck building.

`FATAL 2017-04-20 10:45:28,985 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.cards.DragCardGrid.updateSelectionDrag(DragCardGrid.java:1166)
	at mage.client.cards.DragCardGrid.access$200(DragCardGrid.java:39)
	at mage.client.cards.DragCardGrid$10.mouseDragged(DragCardGrid.java:799)
	at java.awt.Component.processMouseMotionEvent(Component.java:6573)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3340)
	at java.awt.Component.processEvent(Component.java:6294)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4550)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by drmDev** [comment]
Can be "fixed" by adding a null check on `selectionDragStartCards` in `updateSelectionDrag` but only deals with the symptom of the problem. Not sure how it would ever be null from a quick glance in the code (though I have not spent much time on UI here and am not a UI guy by any means)

**Comment by JayDi85** [comment]
No more actual
