### ISSUE TITLE
Null source in triggerAbility method

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#322]
WARN  [2013-09-04 13:44 [09:189]] PlayerImpl[pool-2-thread-20]: Null source in triggerAbility method
FATAL [2013-09-04 13:44 [09:190]] GameImpl[pool-2-thread-20]: Game exception 
java.lang.IllegalArgumentException: source TriggeredAbility  must not be null
	at mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:848)
	at mage.game.GameImpl.checkTriggered(GameImpl.java:1150)
	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1125)
	at mage.game.GameImpl.playPriority(GameImpl.java:896)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:198)
	at mage.game.turn.EndPhase.playStep(EndPhase.java:65)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:132)
	at mage.game.GameImpl.playTurn(GameImpl.java:581)
	at mage.game.GameImpl.play(GameImpl.java:554)
	at mage.game.GameImpl.start(GameImpl.java:521)
	at mage.game.GameImpl.start(GameImpl.java:511)
	at mage.server.game.GameWorker.call(GameWorker.java:58)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)

**Comment by LevelX2** [comment]
Fixed weeks ago.
