### ISSUE TITLE
Gideon's Intervention not allowing card selection and freezes game

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3322]
Gideon's Intervention is giving no card selection and an error:null which prevents the game from progressing.

http://i.imgur.com/URnhDgU.jpg

`FATAL 2017-05-06 16:55:34,370 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException
java.lang.NullPointerException
   at java.util.TreeMap.getEntry(TreeMap.java:347)
   at java.util.TreeMap.containsKey(TreeMap.java:232)
   at java.util.TreeSet.contains(TreeSet.java:234)
   at mage.choices.ChoiceImpl.setChoice(ChoiceImpl.java:108)
   at mage.client.dialog.PickChoiceDialog.setChoice(PickChoiceDialog.java:111)
   at mage.client.dialog.PickChoiceDialog.btnOkActionPerformed(PickChoiceDialog.java:192)
   at mage.client.dialog.PickChoiceDialog.lambda$initComponents$2(PickChoiceDialog.java:143)
   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
   at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
   at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
   at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
   at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
   at java.awt.Component.processMouseEvent(Component.java:6533)
   at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
   at java.awt.Component.processEvent(Component.java:6298)
   at java.awt.Container.processEvent(Container.java:2236)
   at java.awt.Component.dispatchEventImpl(Component.java:4889)
   at java.awt.Container.dispatchEventImpl(Container.java:2294)
   at java.awt.Component.dispatchEvent(Component.java:4711)
   at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
   at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
   at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
   at java.awt.Container.dispatchEventImpl(Container.java:2280)
   at java.awt.Window.dispatchEventImpl(Window.java:2746)
   at java.awt.Component.dispatchEvent(Component.java:4711)
   at mage.client.dialog.MageDialog.startModal(MageDialog.java:136)
   at mage.client.dialog.MageDialog.show(MageDialog.java:82)
   at java.awt.Component.show(Component.java:1671)
   at java.awt.Component.setVisible(Component.java:1623)
   at javax.swing.JComponent.setVisible(JComponent.java:2644)
   at mage.client.dialog.MageDialog.setVisible(MageDialog.java:88)
   at mage.client.dialog.PickChoiceDialog.showDialog(PickChoiceDialog.java:91)
   at mage.client.game.GamePanel.getChoice(GamePanel.java:1284)
   at mage.client.remote.CallbackClientImpl.lambda$processCallback$1(CallbackClientImpl.java:247)
   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
   at java.awt.EventQueue.access$500(EventQueue.java:97)
   at java.awt.EventQueue$3.run(EventQueue.java:709)
   at java.awt.EventQueue$3.run(EventQueue.java:703)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
   at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

-- from forums

**Comment by drmDev** [comment]
Unable to duplicate. Was able to name card and it performed as intended. No errors logged.
