### ISSUE TITLE
Server race condition / endless loop ? 

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3374]
Ran into what appeared to be a server race condition where the client would mostly work but anything that involved server interaction failed.

mage.abilities.mana.AnyColorLandsProduceManaEffect getManaTypes
WARNING: needed to identify endless loop causing cards: Exotic Orchard

Please see attached server log. If someone knows how I can get the Xmage Server Console output I would love to know. I have tried to google it and tried everything I know how and I still can't get the text out into a new file.

-- from forums
[mageserver.txt](https://github.com/magefree/mage/files/998960/mageserver.txt)

**Comment by magenoxx** [comment]
Did you reproduce it locally?

Tried to add Exotic Orchard onto battlefield and it worked:
`
battlefield:Computer:Mountain:6
battlefield:Computer:Swamp:6
battlefield:Computer:Plains:6

battlefield:Human:Exotic Orchard:2
`

**Comment by magenoxx** [comment]
Could reproduce warning though (but able to play xmage game):
`
May 15, 2017 12:20:49 PM mage.abilities.mana.AnyColorLandsProduceManaEffect getManaTypes
WARNING: needed to identify endless loop causing cards: Exotic Orchard
`

**Comment by drmDev** [comment]
Might not be an issue. Haven't tried to duplicate it myself.

**Comment by magenoxx** [comment]
Looking into the code gave me an idea how to reproduce it. So in case both players have Exotic Orchard the loop is endless trying to determine what mana each of Orchards may produce.

It's 100% reproducible with exception:
`
Exception in thread "CALL main-68" java.lang.StackOverflowError
	at mage.abilities.mana.AnyColorLandsProduceManaEffect.getNetMana(AnyColorLandsProduceManaAbility.java:184)
	at mage.abilities.mana.AnyColorLandsProduceManaAbility.getNetMana(AnyColorLandsProduceManaAbility.java:72)
	at mage.abilities.mana.AnyColorLandsProduceManaEffect.getManaTypes(AnyColorLandsProduceManaAbility.java:173)
	at mage.abilities.mana.AnyColorLandsProduceManaEffect.getNetMana(AnyColorLandsProduceManaAbility.java:184)
	at mage.abilities.mana.AnyColorLandsProduceManaAbility.getNetMana(AnyColorLandsProduceManaAbility.java:72)
	at mage.abilities.mana.AnyColorLandsProduceManaEffect.getManaTypes(AnyColorLandsProduceManaAbility.java:173)
`

**Comment by magenoxx** [comment]
Not only it's difficult to fix but also to implement correct behavior when you have Swamp, Plains, Exotic Orchard and your opponent has only Exotic Orchard then your Orchard should also be able to produce B and W (so your opponent's Orchard akka reflecting your mana sources to you).

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
