### ISSUE TITLE
Deck generation fails with split cards from Amonkhet

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#3444]
Selected set was only Amonkhet + colour black.

java.lang.UnsupportedOperationException: Not supported yet.
	at mage.cards.mock.MockSplitCardHalf.setParentCard(MockSplitCardHalf.java:55)
	at mage.cards.SplitCard.<init>(SplitCard.java:66)
	at mage.cards.mock.MockSplitCard.<init>(MockSplitCard.java:64)
	at mage.cards.mock.MockSplitCard.copy(MockSplitCard.java:69)
	at mage.cards.mock.MockSplitCard.copy(MockSplitCard.java:17)
	at mage.client.deck.generator.DeckGenerator.generateSpells(DeckGenerator.java:230)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:192)
	at mage.client.deck.generator.DeckGenerator.buildDeck(DeckGenerator.java:112)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:78)
	at mage.client.table.NewPlayerPanel.generateDeck(NewPlayerPanel.java:95)
	at mage.client.table.NewPlayerPanel.btnGenerateActionPerformed(NewPlayerPanel.java:211)
	at mage.client.table.NewPlayerPanel.lambda$initComponents$1(NewPlayerPanel.java:157)

**Comment by Simown** [comment]
I'll have a look at it. Wonder if it's all split cards or just Amonket.
