### ISSUE TITLE
NPEs when connected to server in testMode

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3506]
With latest from master, when I connect to local-host (running server in test-mode), I get NPEs and never show up in the lobby. (However, I still am able to do Quick Match fine)

java.lang.NullPointerException
	at mage.server.MageServerImpl.handleException(MageServerImpl.java:1054)
	at mage.server.MageServerImpl.getTables(MageServerImpl.java:386)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	at com.sun.proxy.$Proxy8.getTables(Unknown Source)
	at mage.remote.SessionImpl.getTables(SessionImpl.java:731)
	at mage.client.SessionHandler.getTables(SessionHandler.java:289)
	at mage.client.table.UpdateTablesTask.doInBackground(TablesPanel.java:1420)
	at mage.client.table.UpdateTablesTask.doInBackground(TablesPanel.java:1402)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
FATAL 2017-06-17 13:54:42,198 Communication error                                                                        =>[SwingWorker-pool-4-thread-5] SessionImpl.handleThrowable 

and

java.lang.NullPointerException
	at mage.server.MageServerImpl.handleException(MageServerImpl.java:1054)
	at mage.server.MageServerImpl.getRoomUsers(MageServerImpl.java:417)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	at com.sun.proxy.$Proxy8.getRoomUsers(Unknown Source)
	at mage.remote.SessionImpl.getRoomUsers(SessionImpl.java:761)
	at mage.client.SessionHandler.getRoomUsers(SessionHandler.java:263)
	at mage.client.table.UpdatePlayersTask.doInBackground(TablesPanel.java:1467)
	at mage.client.table.UpdatePlayersTask.doInBackground(TablesPanel.java:1451)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
FATAL 2017-06-17 13:54:45,204 Communication error

**Comment by drmDev** [comment]
Others are not having this issue. Will re-test and debug later.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
