### ISSUE TITLE
No Subtype for Avatar

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3706]
```
GameImpl.playPriority
java.lang.IllegalArgumentException: no subtype for Avatar exists
    at mage.constants.SubType.byDescription(SubType.java:369)
    at mage.cards.k.KaronaFalseGodEffect.apply(KaronaFalseGod.java:168)
    at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
    at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:101)
    at mage.game.stack.StackAbility.resolve(StackAbility.java:100)
    at mage.game.GameImpl.resolve(GameImpl.java:1344)
    at mage.game.GameImpl.playPriority(GameImpl.java:1295)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:210)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:153)
    at mage.game.GameImpl.playTurn(GameImpl.java:822)
    at mage.game.GameImpl.play(GameImpl.java:731)
    at mage.game.GameImpl.start(GameImpl.java:695)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ingmargoudt** [comment]
Resolved in the next major release
