### ISSUE TITLE
NPE with MindsDesireCastFromExile

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3707]
```
GameImpl.playPriority
java.lang.NullPointerException
	at mage.cards.m.MindsDesireCastFromExileEffect.applies(MindsDesire.java:142)
	at mage.abilities.effects.ContinuousEffects.asThough(ContinuousEffects.java:506)
	at mage.abilities.effects.ContinuousEffects.asThough(ContinuousEffects.java:497)
	at mage.players.PlayerImpl.getUseableActivatedAbilitiesHalfImpl(PlayerImpl.java:1298)
	at mage.players.PlayerImpl.getUseableActivatedAbilities(PlayerImpl.java:1321)
	at mage.player.human.HumanPlayer.priority(HumanPlayer.java:766)
	at mage.game.GameImpl.playPriority(GameImpl.java:1274)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:822)
	at mage.game.GameImpl.play(GameImpl.java:731)
	at mage.game.GameImpl.start(GameImpl.java:695)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeffwadsworth** [comment]
Null check missing for player.
