### ISSUE TITLE
Annihilator effect - ConcurrentModificationException

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3709]
```
GameImpl.playPriority
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:324)
	at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:305)
	at mage.target.TargetPermanent.canChoose(TargetPermanent.java:162)
	at mage.abilities.keyword.AnnihilatorEffect.apply(AnnihilatorAbility.java:130)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:101)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:100)
	at mage.game.GameImpl.resolve(GameImpl.java:1344)
	at mage.game.GameImpl.playPriority(GameImpl.java:1295)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:822)
	at mage.game.GameImpl.play(GameImpl.java:731)
	at mage.game.GameImpl.start(GameImpl.java:695)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeffwadsworth** [comment]
The iteration was changed so let's close this for now.
