### ISSUE TITLE
ConcurrentModificationException on Past in Flames effect

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3710]
```
GameImpl.playPriority
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at mage.cards.p.PastInFlamesEffect.apply(PastInFlames.java:112)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:125)
	at mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:919)
	at mage.game.GameState.applyEffects(GameState.java:555)
	at mage.game.GameImpl.applyEffects(GameImpl.java:1420)
	at mage.game.GameImpl.playPriority(GameImpl.java:1279)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:822)
	at mage.game.GameImpl.play(GameImpl.java:731)
	at mage.game.GameImpl.start(GameImpl.java:695)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeffwadsworth** [comment]
Looks to be related to the iteration through the graveyard.  A refactor of it may help.  Testing.

**Comment by jeffwadsworth** [comment]
The iteration was changed so let's close this for now.
