### ISSUE TITLE
Linux: HeadlessException when executing launcher

### ISSUE THREAD

**Issue by Ketsuban** [magefree/mage#3776]
I put `XMageLauncher-0.3.8.jar` in `$HOME/.local` and created the following shell script in `$HOME/.local/bin/xmage` for ease of use.

```
#!/usr/bin/env sh
java -jar "$HOME/.local/XMageLauncher-0.3.8.jar"
```

When running it I get the following output.

```
[thomas@chansey ~]% xmage                            
INFO  2017-08-02 16:54:07,915 Detected screen DPI: 96                                                                    =>[main] Config.<clinit>
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at com.xmage.launcher.XMageConsole.<init>(XMageConsole.java:19)
	at com.xmage.launcher.XMageLauncher.<init>(XMageLauncher.java:102)
	at com.xmage.launcher.XMageLauncher.main(XMageLauncher.java:480)
```

Following is some diagnostic information about my system. It's Fedora 26, and I haven't done anything particularly special to it.

```
[thomas@chansey ~]% uname -a
Linux chansey 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[thomas@chansey ~]% java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)
[thomas@chansey ~]% echo $DISPLAY
:0
```

**Comment by Ketsuban** [comment]
Nevermind—turns out Fedora has a distinction between headless and non-headless Java, and I had to install the non-headless additions.
