### ISSUE TITLE
Removing of player objects in multiplayer games may only happen if no ability of the game resolves

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#3885]
In a multiplayer game, if a player leaves the game, his objects have to be removed only after the current ability/effect's resolving is finished.
Otherwise e.g. ConcurrentModificationException can happen.

FATAL 2017-08-27 00:17:55,397 Game exception gameId: ace1068a-f8e3-426a-a60c-17f6cfb72f12                                =>[GAME ace1068a-f8e3-426a-a60c-17f6cfb72f12] GameImpl.playPriority
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:324)
	at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:305)
	at mage.target.TargetPermanent.canChoose(TargetPermanent.java:162)
	at mage.abilities.effects.common.SacrificeEffect.apply(SacrificeEffect.java:90)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:101)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:99)
	at mage.game.GameImpl.resolve(GameImpl.java:1335)
	at mage.game.GameImpl.playPriority(GameImpl.java:1286)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)

**Comment by LevelX2** [comment]
DEBUG 2017-09-12 15:54:31,476 Player Vyrax concedes game c6d8fa2c-52a0-4994-9f31-680c5df3d196                            =>[CALL main-21758] GameImpl.concede
DEBUG 2017-09-12 15:54:31,476 Game over for player Id: 85ed5658-6552-414c-8c0a-a7ef1ac4e70d gameId c6d8fa2c-52a0-4994-9f31-680c5df3d196 =>[CALL main-21758] GameImpl.gameOver
DEBUG 2017-09-12 15:54:31,476 Start leave game: Vyrax                                                                    =>[CALL main-21758] GameImpl.leave
DEBUG 2017-09-12 15:54:31,477 Vyrax has lost gameId: c6d8fa2c-52a0-4994-9f31-680c5df3d196                                =>[CALL main-21758] PlayerImpl.lostForced
FATAL 2017-09-12 15:54:31,479 GameWorker general exception [c6d8fa2c-52a0-4994-9f31-680c5df3d196] null                   =>[GAME c6d8fa2c-52a0-4994-9f31-680c5df3d196] GameWorker.call
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
	at mage.game.permanent.Battlefield.endOfTurn(Battlefield.java:210)
	at mage.game.turn.CleanupStep.beginStep(CleanupStep.java:64)
	at mage.game.turn.EndPhase.playStep(EndPhase.java:59)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:804)
	at mage.game.GameImpl.play(GameImpl.java:713)
	at mage.game.GameImpl.start(GameImpl.java:677)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by LevelX2** [comment]
Should be fixed with last update.

Removing player objects is now always handled by the main game thread.
