### ISSUE TITLE
Null pointer exception at start of combat for AI

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#4058]
I have Ghostly Prison, Propaganda, and Sphere of Safety with 5 enchantments, meaning it costs 9 to attack me. The AI opponent has a 6/5 Dragon and 6 available mana. The AI wants to attack me. It is currently listed as the "begin combat" step.

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.26V6
mage.abilities.SpellAbility.spellCanBeActivatedRegularlyNow(SpellAbility.java:88)
mage.abilities.SpellAbility.canActivate(SpellAbility.java:95)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1174)
mage.player.ai.ComputerPlayer.activateAbility(ComputerPlayer.java:920)
mage.player.ai.ComputerPlayer6.act(ComputerPlayer6.java:289)
mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:108)
mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:82)
mage.game.GameImpl.playPriority(GameImpl.java:1277)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:816)
mage.game.GameImpl.play(GameImpl.java:725)
mage.game.GameImpl.start(GameImpl.java:689)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:748)

Here's the server log:

DEBUG 2017-09-24 22:16:30,372 End Check Expired                                                                          =>[pool-8-thread-1] UserManager.checkExpired
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:492)
	at mage.player.ai.ComputerPlayer7.calculatePreCombatActions(ComputerPlayer7.java:165)
	at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:106)
	at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:82)
	at mage.game.GameImpl.playPriority(GameImpl.java:1277)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:816)
	at mage.game.GameImpl.play(GameImpl.java:725)
	at mage.game.GameImpl.start(GameImpl.java:689)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at mage.abilities.SpellAbility.spellCanBeActivatedRegularlyNow(SpellAbility.java:88)
	at mage.abilities.SpellAbility.canActivate(SpellAbility.java:95)
	at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1174)
	at mage.player.ai.ComputerPlayer.activateAbility(ComputerPlayer.java:920)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:585)
	at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:317)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:482)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:479)
	... 4 more
FATAL 2017-09-24 22:16:34,964 Game exception gameId: 77a2abbc-d17f-4781-92e7-848e91521147                                =>[GAME 77a2abbc-d17f-4781-92e7-848e91521147] GameImpl.playPriority
java.lang.NullPointerException
	at mage.abilities.SpellAbility.spellCanBeActivatedRegularlyNow(SpellAbility.java:88)
	at mage.abilities.SpellAbility.canActivate(SpellAbility.java:95)
	at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1174)
	at mage.player.ai.ComputerPlayer.activateAbility(ComputerPlayer.java:920)
	at mage.player.ai.ComputerPlayer6.act(ComputerPlayer6.java:289)
	at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:108)
	at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:82)
	at mage.game.GameImpl.playPriority(GameImpl.java:1277)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:816)
	at mage.game.GameImpl.play(GameImpl.java:725)
	at mage.game.GameImpl.start(GameImpl.java:689)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:492)
	at mage.player.ai.ComputerPlayer7.calculatePreCombatActions(ComputerPlayer7.java:165)
	at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:106)
	at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:82)
	at mage.game.GameImpl.playPriority(GameImpl.java:1277)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:816)
	at mage.game.GameImpl.play(GameImpl.java:725)
	at mage.game.GameImpl.start(GameImpl.java:689)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at mage.cards.CardsImpl.getUniqueCards(CardsImpl.java:202)
	at mage.players.PlayerImpl.getPlayable(PlayerImpl.java:2652)
	at mage.player.ai.SimulatedPlayer2.simulateOptions(SimulatedPlayer2.java:124)
	at mage.player.ai.SimulatedPlayer2.simulatePriority(SimulatedPlayer2.java:94)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:569)
	at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:317)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:482)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:479)
	... 4 more

**Comment by SpikesCafe-google** [comment]
I see "activate ability" in the stack trace, but there's no permanents on the battlefield the computer could legally activate (besides tapping lands for mana), and I don't think there are any cards in the deck that can be activated from their hand, and their graveyard is empty. The one ability they could potentially activate is Spinerock Knoll, but they haven't met the requirements.

**Comment by theelk801** [comment]
What was the Dragon? Did it have any relevant text?

**Comment by SpikesCafe-google** [comment]
Hellkite Tyrant, nothing seems relevant to the stack trace. https://magiccards.info/c16/en/128.html

**Comment by theelk801** [comment]
Alright, I only asked because I thought maybe it was Territorial Hellkite.

**Comment by Zerrisx** [comment]
As this is an old exception report without enough additional information, closing as likely obsolete.
