### ISSUE TITLE
Image download not working correctly

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4148]
Getting several reports of people being unable to download images on the current client.

**Comment by emallson** [comment]
I'm having this issue. Fresh install. I tried downloading the images.zip from /r/xmage and placing it in the plugins/images directory and that did not fix the issue.

```Nov 06, 2017 3:54:54 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2017-11-06 15:54:54,623 Starting MAGE client version 1.4.26V8                                                      =>[main] MageFrame.main 
INFO  2017-11-06 15:54:54,626 Logging level: INFO                                                                        =>[main] MageFrame.main 
ERROR 2017-11-06 15:54:55,745 Couldn't rename mana symbols!                                                              =>[AWT-EventQueue-0] ManaSymbols.renameSymbols 
ERROR 2017-11-06 15:54:55,746 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,746 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,746 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,747 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,747 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,747 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,747 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,747 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,748 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,748 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,748 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,748 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,748 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,749 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,750 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,751 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,751 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,752 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,752 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,752 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,752 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,752 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,752 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,753 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,753 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,753 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,753 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,753 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,754 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,754 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,754 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,754 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,755 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,755 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,756 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,756 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,756 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,757 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,758 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,758 Error for symbol:E                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,758 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,759 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,759 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,759 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,759 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,759 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,759 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,760 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,760 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,760 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,760 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,760 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,760 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,760 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,761 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,761 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,761 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,761 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,762 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,762 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,762 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,762 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,762 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,763 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,763 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,763 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,763 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,763 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,763 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,763 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,764 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,764 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,764 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,764 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,764 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,764 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,764 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,765 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,765 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-11-06 15:54:55,765 Error for symbol:E                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
INFO  2017-11-06 15:54:56,164 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2017-11-06 15:54:56,203 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2017-11-06 15:54:56,211 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2017-11-06 15:54:57,671 Client start up time: 3 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2017-11-06 15:54:59,842 Trying to connect to XMAGE server at xmage.de:17171                                        =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2017-11-06 15:55:01,438 Connected to MAGE server at xmage.de:17171                                                 =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2017-11-06 15:55:01,439 Trying to log-in as emallson to XMAGE server at xmage.de:17171                             =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
INFO  2017-11-06 15:56:03,322 Logged-in as emallson to MAGE server at xmage.de:17171                                     =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
INFO  2017-11-06 15:56:17,205 Card was not selected: Sword of Dungeons and Dragons                                       =>[Thread-222] DownloadPictures.lambda$getNeededCards$4 
INFO  2017-11-06 15:56:17,244 Card was not selected: Grimlock, Dinobot Leader                                            =>[ForkJoinPool.commonPool-worker-3] DownloadPictures.lambda$getNeededCards$4 
INFO  2017-11-06 15:56:17,286 Card was not selected: Sword of Dungeons & Dragons                                         =>[ForkJoinPool.commonPool-worker-3] DownloadPictures.lambda$getNeededCards$4 
FATAL 2017-11-06 15:56:21,486 MAGE Client UI error                                                                       =>[Thread-222] EDTExceptionHandler.handle 
java.nio.file.InvalidPathException: Illegal char <"> at index 23: PTK.zip/PTK/Pang Tong, "Young Phoenix".full.jpg
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at net.java.truevfs.driver.file.FileController.checkAccess(FileController.java:99)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:181)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.checkAccess(FalsePositiveArchiveController.scala:74)
	at net.java.truevfs.access.TFile.exists(TFile.java:1670)
	at org.mage.plugins.card.images.DownloadPictures.lambda$getNeededCards$5(DownloadPictures.java:466)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: net.java.truevfs.kernel.impl.FalsePositiveArchiveException: java.nio.file.NoSuchFileException: PTK.zip
	Caused by: java.nio.file.NoSuchFileException: PTK.zip
		at net.java.truevfs.kernel.impl.TargetArchiveController.mount0(TargetArchiveController.scala:141)
		at net.java.truevfs.kernel.impl.TargetArchiveController.mount(TargetArchiveController.scala:109)
		at net.java.truevfs.kernel.impl.FileSystemArchiveController$ResetFileSystem.autoMount(FileSystemArchiveController.scala:70)
		at net.java.truevfs.kernel.impl.FileSystemArchiveController.autoMount(FileSystemArchiveController.scala:37)
		at net.java.truevfs.kernel.impl.BasicArchiveController.checkAccess(BasicArchiveController.scala:56)
		at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$SyncController$$super$checkAccess(DefaultManager.scala:158)
		at net.java.truevfs.kernel.impl.SyncController$$anonfun$checkAccess$1.apply$mcV$sp(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.SyncController$$anonfun$checkAccess$1.apply(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.SyncController$$anonfun$checkAccess$1.apply(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.SyncController$class.net$java$truevfs$kernel$impl$SyncController$$apply(SyncController.scala:129)
		at net.java.truevfs.kernel.impl.SyncController$class.checkAccess(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$LockController$$super$checkAccess(DefaultManager.scala:158)
		at net.java.truevfs.kernel.impl.LockController$$anonfun$checkAccess$1.apply$mcV$sp(LockController.scala:48)
		at net.java.truevfs.kernel.impl.LockController$$anonfun$checkAccess$1.apply(LockController.scala:48)
		at net.java.truevfs.kernel.impl.LockController$$anonfun$checkAccess$1.apply(LockController.scala:48)
		at net.java.truevfs.kernel.impl.LockingStrategy.apply(LockingStrategy.scala:84)
		at net.java.truevfs.kernel.impl.LockController$class.timedReadOrWriteLocked(LockController.scala:104)
		at net.java.truevfs.kernel.impl.LockController$class.checkAccess(LockController.scala:48)
		at net.java.truevfs.kernel.impl.DefaultManager$BackController.checkAccess(DefaultManager.scala:158)
		at net.java.truevfs.kernel.impl.ArchiveControllerAdapter.checkAccess(ArchiveControllerAdapter.scala:23)
		at net.java.truevfs.comp.zipdriver.AbstractKeyController.checkAccess(AbstractKeyController.java:105)
		at net.java.truevfs.kernel.spec.FsDecoratingController.checkAccess(FsDecoratingController.java:53)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$TryChild$.apply(FalsePositiveArchiveController.scala:195)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.checkAccess(FalsePositiveArchiveController.scala:74)
		at net.java.truevfs.access.TFile.exists(TFile.java:1670)
		at org.mage.plugins.card.images.DownloadPictures.lambda$getNeededCards$5(DownloadPictures.java:466)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
		at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
		at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```

**Comment by JayDi85** [comment]
Have the same error (see post above). Looked at images folder and do not found that error file **PTK.zip**. Download it from torrent and save to image folder. Now client work fine.

Also I can't download 10 images:
```
NFO  2017-11-10 00:46:27,725 Started download of 10 images from source: scryfall.com                                    =>[Thread-2178] DownloadPictures.run 
WARN  2017-11-10 00:46:28,830 Image download for Spitfire Bastion(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/173b?format=image =>[pool-7-thread-10] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,830 Image download for Adanto, the First Fort(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/22b?format=image =>[pool-7-thread-5] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,837 Image download for Itlimoc, Cradle of the Sun(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/191b?format=image =>[pool-7-thread-4] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,842 Image download for Treasure Cove(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/250b?format=image =>[pool-7-thread-9] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,845 Image download for Spires of Orazca(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/249b?format=image =>[pool-7-thread-8] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,847 Image download for Lost Vale(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/235b?format=image =>[pool-7-thread-3] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,861 Image download for Temple of Aclazotz(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/90b?format=image =>[pool-7-thread-1] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,867 Image download for Primal Wellspring(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/243b?format=image =>[pool-7-thread-6] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,881 Image download for Conqueror's Foothold(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/234b?format=image =>[pool-7-thread-2] DownloadPictures$DownloadTask.run 
WARN  2017-11-10 00:46:28,892 Image download for Azcanta, the Sunken Ruin(XLN) failed - responseCode: 404 url: https://api.scryfall.com/cards/xln/74b?format=image =>[pool-7-thread-7] DownloadPictures$DownloadTask.run 
INFO  2017-11-10 00:46:42,836 Started download of 10 images from source: WOTC Gatherer                                   =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,836 Image not available on WOTC Gatherer: Temple of Aclazotz (XLN)                             =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,837 Image not available on WOTC Gatherer: Conqueror's Foothold (XLN)                           =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,837 Image not available on WOTC Gatherer: Lost Vale (XLN)                                      =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,838 Image not available on WOTC Gatherer: Itlimoc, Cradle of the Sun (XLN)                     =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,838 Image not available on WOTC Gatherer: Adanto, the First Fort (XLN)                         =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,838 Image not available on WOTC Gatherer: Primal Wellspring (XLN)                              =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,839 Image not available on WOTC Gatherer: Azcanta, the Sunken Ruin (XLN)                       =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,839 Image not available on WOTC Gatherer: Spires of Orazca (XLN)                               =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,840 Image not available on WOTC Gatherer: Treasure Cove (XLN)                                  =>[Thread-2179] DownloadPictures.run 
INFO  2017-11-10 00:46:42,840 Image not available on WOTC Gatherer: Spitfire Bastion (XLN)                               =>[Thread-2179] DownloadPictures.run 

```

**Comment by JayDi85** [comment]
Error is in card names with " (Quotation Mark). You created wrong commit: 7ad481cc0e4fe2bfa870c73a822a1c8290c644ac month ago and broke old code.

If you search Kongming from repository -- you can find that card name use ' (Apostrophe) in other sets. But in PTK set it use " (Quotation Mark).

Try to fix it by add that code

> replace("\"", "")

in line:
https://github.com/magefree/mage/blob/c29787323a177641203205d27bf78192e2491b00/Mage.Client/src/main/java/org/mage/plugins/card/utils/CardImageUtils.java#L187

But you must test it.

**Comment by JayDi85** [comment]
Another one errors and warnings on symbols download. Logs from new version (see pull request #4159):
```
can't find set by code: ANB
early to download: RIX (Rivals of Ixalan), available after Fri Jan 05 00:00:00 SAMT 2018
early to download: DOM (Dominaria), available after Fri Apr 13 00:00:00 SAMT 2018
early to download: M19 (Core 2019), available after Fri Jul 06 00:00:00 SAMT 2018
founded duplicated code: V12
set is not configured: SUS (Super Series)
set is not configured: FNMP (Friday Night Magic)
set is not configured: H09 (Premium Deck Series: Slivers)
set is not configured: CP (Champs)
set is not configured: SWS (Star Wars)
set is not configured: H17 (HASCON Promo 2017)
set is not configured: CHR (Chronicles)
set is not configured: GPX (Grand Prix)
set is not configured: APAC (Asia Pacific Land Program)
set is not configured: MLP (Launch Party)
set is not configured: 9EB (Ninth Edition Box)
set is not configured: CLASH (Clash Pack)
set is not configured: S99 (Starter 1999)
set is not configured: GRC (WPN Gateway)
set is not configured: PD3 (Premium Deck Series: Graveborn)
set is not configured: PTC (Prerelease Events)
set is not configured: PD2 (Premium Deck Series: Fire and Lightning)
set is not configured: EURO (European Land Program)
set is not configured: UNH (Unhinged)
set is not configured: 8EB (EighthEditionBox)
set is not configured: V10 (From the Vault: Relics)
set is not configured: V11 (From the Vault: Legends)
set is not configured: V17 (From the Vault: Transform)
set is not configured: MPRP (Magic Player Rewards)
set is not configured: CM1 (Commander's Arsenal)
set is not configured: E02 (Explorers of Ixalan)
set is not configured: UGIN (Ugin's Fate)
set is not configured: GUR (Guru)
set is not configured: DPA (Duels of the Planeswalkers)
set is not configured: JR (Judge Promo)
set is not configured: DD3GVL (Duel Decks: Anthology, Garruk vs. Liliana)
set is not configured: MPS-AKH (Masterpiece Series Amonkhet)
set is not configured: M25 (Masters 25)
set is not configured: MBP (Media Inserts)
set is not configured: ARENA (Arena League)
set have rare cards, but don't download icon: DRB (From the Vault: Dragons)
set is not configured: UST (Unstable)
set is not configured: S00 (Starter 2000)
set is not configured: IMA (Iconic Masters)
set is not configured: DD2 (Duel Decks: Jace vs. Chandra)
set is not configured: EVG (Duel Decks: Elves vs. Goblins)
set is not configured: MGDC (Game Day)
set is not configured: DDC (Duel Decks: Divine vs. Demonic)
set is not configured: DDE (Duel Decks: Phyrexia vs. the Coalition)
set is not configured: DDD (Duel Decks: Garruk vs. Liliana)
set is not configured: DDT (Duel Decks: Merfolk vs. Goblins)
set is not configured: WMCQ (World Magic Cup Qualifier)
set is not configured: UGL (Unglued)
```
