### ISSUE TITLE
Xmage doesn't have access to audio resources/Xmage has exclusive access to audio resources

### ISSUE THREAD

**Issue by jottunn** [magefree/mage#4187]
If I have a browser with, say, youtube open and start Xmage, Xmage doesn't have sound.
If I have Xmage running, nothing else besides it can use my system's sound resources, neither inputs nor outputs.

I run Linux 4.13.12-1-ARCH x86_64 with PulseAudio.

**Comment by JayDi85** [comment]
Are there any log errors? Look at "..\xmage\mage-client\mageclient.log"

**Comment by jottunn** [comment]
no errors but some warning:

`WARN  2017-11-22 12:50:59,262 Failed to open line                                                                        =>[Util2] LinePool.lambda$playSound$1 
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:413)
	at mage.client.util.audio.LinePool.lambda$playSound$1(LinePool.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARN  2017-11-22 12:51:04,501 Failed to open line                                                                        =>[Util4] LinePool.lambda$playSound$1 
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:413)
	at mage.client.util.audio.LinePool.lambda$playSound$1(LinePool.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARN  2017-11-22 12:51:07,200 Failed to open line                                                                        =>[Util3] LinePool.lambda$playSound$1 
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:413)
	at mage.client.util.audio.LinePool.lambda$playSound$1(LinePool.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Zerrisx** [comment]
Resolved / Not a bug
