### ISSUE TITLE
Card Viewer freezes and displays "EMPTY STATS" - no longer works afterward

### ISSUE THREAD

**Issue by ttamnedlog** [magefree/mage#4235]
Short description:

- macOS 10.13.2
- xmage_1_4_26V9
- Card Viewer freezes on sets that have card file names containing both numbers and letters, such as Planeshift's `Ertai, the Corrupted.107a.full.jpg`

Detailed description:

I've encountered a reproducible, very specific bug that most people probably won't encounter unless they are thumbing through the Card Viewer and adding/editing image files. I will detail my experience in encountering and reproducing said bug.

I've started from a fresh install with no images and been going through each and every set and adding card images. When I get to a set that has a card name containing both a number and a letter, the Card Viewer freezes. I then close and re-open XMage, and the Card Viewer will not open at all. Clicking it makes the page opening sound effect, but nothing displays. I can then click and open the Deck Editor, and if I then click Exit, the Card Viewer is opened after all but displaying nothing but the words "EMPTY STATS".

Uninstalling and reinstalling XMage, strangely, did not solve the issue. Somehow, even on a fresh install, the Card Viewer was trying to start with the set where I had last froze as opposed to starting with "All Sets". I suspect this is macOS-related, however. More on that later.

This first happened when I got to the Planeshift set, and in the console I noticed a Java error about 107a. On a hunch, I checked the card numbers in the set and found Ertai the Corrupted, numbered 107a and 107b. After devising a workaround so that I could continue my card editing, I encountered the error again when I got to the Battle for Zendikar set. And immediately after at Oath of the Gatewatch set. As suspected, these sets also contained card names that had both a number and a letter (with lands this time). Here is the console error for Oath of the Gatewatch specifically (At first glance, I believe it prints the error twice back-to-back, but I didn't read it in depth to see if the second block says anything different than the first):

```
FATAL 2017-12-10 11:25:26,861 Error setting selected format
java.lang.NumberFormatException: For input string: "183a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at mage.client.deckeditor.collection.viewer.MageBook.updateCardStats(MageBook.java:467)
	at mage.client.deckeditor.collection.viewer.MageBook.showCardsOrTokens(MageBook.java:250)
	at mage.client.deckeditor.collection.viewer.MageBook.lambda$addSetTabs$2(MageBook.java:224)
	at mage.client.components.HoverButton.execute(HoverButton.java:291)
	at mage.client.deckeditor.collection.viewer.MageBook.updateDispayedSets(MageBook.java:632)
	at mage.client.deckeditor.collection.viewer.CollectionViewerPanel.lambda$initComponents$5(CollectionViewerPanel.java:161)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at mage.client.deckeditor.collection.viewer.CollectionViewerPanel.<init>(CollectionViewerPanel.java:67)
	at mage.client.deckeditor.collection.viewer.CollectionViewerPane.<init>(CollectionViewerPane.java:53)
	at mage.client.MageFrame.showCollectionViewer(MageFrame.java:1101)
	at mage.client.MageFrame.btnCollectionViewerActionPerformed(MageFrame.java:937)
	at mage.client.MageFrame.lambda$initComponents$8(MageFrame.java:838)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
FATAL 2017-12-10 11:25:26,885 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NumberFormatException: For input string: "183a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at mage.client.deckeditor.collection.viewer.MageBook.updateCardStats(MageBook.java:467)
	at mage.client.deckeditor.collection.viewer.MageBook.showCards(MageBook.java:263)
	at mage.client.deckeditor.collection.viewer.CollectionViewerPanel.showCards(CollectionViewerPanel.java:240)
	at mage.client.deckeditor.collection.viewer.CollectionViewerPane.setVisible(CollectionViewerPane.java:85)
	at mage.client.MageFrame.showCollectionViewer(MageFrame.java:1103)
	at mage.client.MageFrame.btnCollectionViewerActionPerformed(MageFrame.java:937)
	at mage.client.MageFrame.lambda$initComponents$8(MageFrame.java:838)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

As I mentioned, I had to devise a workaround so that I could continue my image editing; I installed `xmage_1_4_26V8` and worked from there. The strange part, and this is what I suspect is macOS-specific, is that even on a fresh install of a different XMage version in a different folder, the Card Viewer opened directly to the set that had frozen in `xmage_1_4_26V9` as opposed to "All Sets" as expected. Fortunately, it works both ways. Once I had finished with the troublesome set in `xmage_1_4_26V8`, I flipped to a set that did not have this problem, closed XMage, and opened `xmage_1_4_26V9`. The Card Viewer opened to the problem-free set I last opened in the other XMage version. If this is indeed macOS at work, it is ironically both the cause of and solution to this issue for me. It tries to save where I left off, opening the frozen set back to the frozen set, and since it doesn't freeze in the other XMage version, macOS allows me to circumvent it and then pick up where I left off in the first XMage. Make of this long paragraph what you will. I don't suspect it has anything to do with the root of the bug (but what do I know!).

**Comment by JayDi85** [comment]
Duplicate #4220 (bug with non standard card number in some sets).

You can wait next release or download [current developer version from here](https://yadi.sk/d/oLKb_rzG3PwE7n) (it's compatible with xmage.de and other servers -- [what's new in that version](https://github.com/magefree/mage/wiki/Features-and-fixes-not-released-yet)).
