### ISSUE TITLE
cancel action error v1.4.26v9

### ISSUE THREAD

**Issue by mindcloud69** [magefree/mage#4255]
version 1.4.26v9 on all systems
Client win 10 playing pebuilt sample commander deck "Wade into Battle" 
Server on my Linux Centos 7

playing "Boros Signet" on turn 2 , tapped a mountain and then tapped a Terramorphic expanse thinking to get a mana and then realized that she couldn't tap TE  for mana. When she then hit cancel the error below popped up and rolled back to the begining of the turn.

Error as it appeared on the Linux console.

FATAL 2017-12-15 19:27:34,506 Game exception gameId: fd95401b-e115-42cb-96be-5dfe82b1dbf7                                =>[GAME fd95401b-e115-42cb-96be-5dfe82b1dbf7] GameImpl.playPriority
java.lang.UnsupportedOperationException: It was not possible to do the requested undo operation (bookmark 1 does not exist) context:
        at mage.game.GameImpl.restoreState(GameImpl.java:671)
        at mage.players.PlayerImpl.restoreState(PlayerImpl.java:1158)
        at mage.players.PlayerImpl.cast(PlayerImpl.java:1025)
        at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1190)
        at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1511)
        at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1525)
        at mage.player.human.HumanPlayer.priority(HumanPlayer.java:831)
        at mage.game.GameImpl.playPriority(GameImpl.java:1317)
        at mage.game.turn.Step.priority(Step.java:87)
        at mage.game.turn.Phase.playStep(Phase.java:210)
        at mage.game.turn.Phase.play(Phase.java:115)
        at mage.game.turn.Turn.play(Turn.java:153)
        at mage.game.GameImpl.playTurn(GameImpl.java:856)
        at mage.game.GameImpl.play(GameImpl.java:765)
        at mage.game.GameImpl.start(GameImpl.java:729)
        at mage.server.game.GameWorker.call(GameWorker.java:60)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by mindcloud69** [comment]
looks like it is any cancel 

Game exception occurred: java.lang.UnsupportedOperationException: It was not possible to do the requested undo operation (bookmark 1 does not exist) context: {1}, {T}: Put a storage counter on {this}.
Server version: 1.4.26V9
mage.game.GameImpl.restoreState(GameImpl.java:671)
mage.players.PlayerImpl.restoreState(PlayerImpl.java:1158)
mage.players.PlayerImpl.playAbility(PlayerImpl.java:1122)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1194)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1511)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1544)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:831)
mage.game.GameImpl.playPriority(GameImpl.java:1317)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:856)
mage.game.GameImpl.play(GameImpl.java:765)
mage.game.GameImpl.start(GameImpl.java:729)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by mindcloud69** [comment]
using the same files to start a local server on my win 10 system does not cause a cancel to error out.

Centos 7: I am using java version 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

on windows I am using the downloaded copy that xmage downloaded. jre1.8.0_131

**Comment by mindcloud69** [comment]
Closing issue this is caused by me not reading the comments on the options and setting the following to true in the config.xml.
saveGameActivated="true"
