### ISSUE TITLE
Exception when trying to launch client

### ISSUE THREAD

**Issue by RaelCappra** [magefree/mage#4421]
Launcher version: 1.4.27V0
Java version: 1.8.0_131
Attempt to run the client causes the following exception:
`java.lang.NoSuchMethodError: org.apache.batik.dom.util.HashTableStack.put(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;`

**Comment by RaelCappra** [comment]
I should have mentioned that I'm on Linux. Also, it appears to be a java version error, as I copied the java folder from my install to you test directory and the same exception occurred.

**Comment by JayDi85** [comment]
Are you run from launcher? If you got that error with test version and start by launcher then report here your OS version and full errors list (from logs window or from log file in `..\xmage\mage-client\mageclient.log`). you can also send me error log file to email: jaydi85@gmail.com

**Comment by RaelCappra** [comment]
Yes, I am running from launcher. The full stack trace from the logs follows:

> `INFO  2018-01-15 20:02:35,476 Starting MAGE client version 1.4.27V0                                                      =>[main] MageFrame.main 
> INFO  2018-01-15 20:02:35,478 Logging level: INFO                                                                        =>[main] MageFrame.main 
> FATAL 2018-01-15 20:02:36,688 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
> java.lang.NoSuchMethodError: org.apache.batik.dom.util.HashTableStack.put(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
> 	at org.apache.batik.dom.svg.SAXSVGDocumentFactory.startDocument(SAXSVGDocumentFactory.java:274)
> 	at org.apache.xerces.parsers.AbstractSAXParser.startDocument(Unknown Source)
> 	at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
> 	at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
> 	at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
> 	at org.apache.xerces.impl.XMLEntityManager.startDocumentEntity(Unknown Source)
> 	at org.apache.xerces.impl.XMLDocumentScannerImpl.setInputSource(Unknown Source)
> 	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
> 	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
> 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
> 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(Unknown Source)
> 	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(Unknown Source)
> 	at org.apache.batik.dom.svg.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:183)
> 	at org.apache.batik.dom.svg.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:248)
> 	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:108)
> 	at org.mage.card.arcane.ManaSymbols.loadSVG(ManaSymbols.java:293)
> 	at org.mage.card.arcane.ManaSymbols.loadSymbolAsSVG(ManaSymbols.java:361)
> 	at org.mage.card.arcane.ManaSymbols.loadSymbolImages(ManaSymbols.java:429)
> 	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:89)
> 	at mage.client.MageFrame.<init>(MageFrame.java:226)
> 	at mage.client.MageFrame.lambda$main$16(MageFrame.java:1179)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Is there any way to increase logging level (without compiling from source)?

**Comment by JayDi85** [comment]
No need to new logging error -- it's an SVG library problem (some incompatibility with your environment). Report your OS version -- i will test it.

As workaround you can delete `svg` folder from `..\xmage\mage-client\plugins\images\symbols`

**Comment by RaelCappra** [comment]
Using Fedora 27 here.

**Comment by RaelCappra** [comment]
Renaming the svg directory worked (original version, NOT the test you sent). Could it be related to the pom.xml at Mage.Client? I see there is a dependency clause for batik-transcoder, but not batik-dom or batik-svg-dom modules. I don't know if that's intended.

**Comment by JayDi85** [comment]
Try this [new test version](https://yadi.sk/d/oLKb_rzG3PwE7n) (download, unzip to new folder, run, wait java downloaded, run client and report error if got it again).

**Comment by RaelCappra** [comment]
Just out of curiosity, where can those test versions and their respective sources be found? Are they from a particular branch? Your personal fork?

**Comment by JayDi85** [comment]
It's from my developer machine. If that's work then will be added to master.

**Comment by RaelCappra** [comment]
Same error with the new test. Also, when the exception occurs, the java process for the client keeps running forever untill I forcefully `kill` it. You might want to take a look on that as well.

**Comment by JayDi85** [comment]
I've installed Fedora 26, but can't reproduce your error with default xmage (downloading by launcher).

There are was only headless java error on first xmage launcher run. I've installed default java and error gone:
`yum install java`

XMage run:
`java -jar XMageLauncher-0.3.8.jar`

All works:
![shot_180116_033738](https://user-images.githubusercontent.com/8344157/34965594-9f330f8a-fa6e-11e7-9663-63844168de63.png)

**Comment by RaelCappra** [comment]
```
$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```
Could 32-bit/64-bit possibly be the issue here?

**Comment by JayDi85** [comment]
Don't known. Will test x64 later.

P.S. Even start from commands file works fine (from `mage-client` folder):
`bash startClient.command`
or
`bash startClient.sh`

**Comment by JayDi85** [comment]
Well, I've tested it on x64 fedora system and can confirm -- it's have issue with classpath on that systems (or something similar). It's can be run by launcher. Only by command line or script (see above). It's a weird.

**Comment by zorkmead** [comment]
I'm on Ubuntu 16.04.3 LTS with 4.13.0-26 generic kernel. Launcher fails. 

bash startClient.sh works with no issues.

Here is the console log from Launch Client from launcher. Note that this has /symbols/svg renamed.

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
INFO  2018-01-19 12:48:25,269 Starting MAGE client version 1.4.27V0                                                      =>[main] MageFrame.main 
INFO  2018-01-19 12:48:25,302 Logging level: INFO                                                                        =>[main] MageFrame.main 
FATAL 2018-01-19 12:48:35,813 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NoSuchMethodError: org.apache.batik.dom.util.HashTableStack.put(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at org.apache.batik.dom.svg.SAXSVGDocumentFactory.startDocument(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.startDocument(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.startDocumentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl.setInputSource(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:347)
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:276)
	at org.apache.batik.dom.svg.SAXSVGDocumentFactory.createDocument(Unknown Source)
	at org.apache.batik.dom.svg.SAXSVGDocumentFactory.createDocument(Unknown Source)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.mage.card.arcane.ManaSymbols.loadSVG(ManaSymbols.java:293)
	at org.mage.card.arcane.ManaSymbols.loadSymbolAsSVG(ManaSymbols.java:361)
	at org.mage.card.arcane.ManaSymbols.loadSymbolImages(ManaSymbols.java:429)
	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:89)
	at mage.client.MageFrame.<init>(MageFrame.java:226)
	at mage.client.MageFrame.lambda$main$16(MageFrame.java:1179)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by zorkmead** [comment]
Problem persists on Ubuntu 16.04 with xmage version 1.4.27V1 (2018-01-28).

**Comment by JayDi85** [comment]
x64 linux problem will be fixed with next release or you can download [current test version](https://yadi.sk/d/oLKb_rzG3PwE7n). If you update by launcher, then you must delete all files from `\xmage\mage-client\lib` and run update again.
