### ISSUE TITLE
Nothing in the command screen when trying to Launch client - Windows 10

### ISSUE THREAD

**Issue by hamitasgarov** [magefree/mage#4431]
Hi everyone,

XMage won't work on my Windows 10 computer. Updated Java and, when I click on Launch client, this is what I get. You can also see what happens when I try to update the client.

Help anyone?

Thank you :)

![imagen](https://user-images.githubusercontent.com/11925083/35165949-3d9a03aa-fd61-11e7-9f5e-d472276162e5.png)
![imagen](https://user-images.githubusercontent.com/11925083/35165967-503d8db0-fd61-11e7-91a8-43b06a1b4aaa.png)

**Comment by JayDi85** [comment]
You are using messed up old and test client files. Windows block your internet connection to download data files.

How to fix:
1. Simple try: download official launcher, copy it to any OTHER folder (e.g. disk C) and run -- it's will download all needed files.
2. Download [last test client](https://yadi.sk/d/oLKb_rzG3PwE7n), unzip it to any OTHER folder, run launcher and wait java to download (press update if you can't see window request).

If you can't download after that the report your error window/logs again.

**Comment by JayDi85** [comment]
Argth. Find out it was Program Files. DON'T use that dir. You need admin access or disabled UAC to work with it. Copy xmage files to another dir like disk D or C:\x\.

**Comment by hamitasgarov** [comment]
The solution you suggested has worked exactly once :( Copied the files to C:\Windows\Program Files\Xmage, and I managed to open it. Now I can't anymore.

**Comment by JayDi85** [comment]
DO NOT copy to program files... Use another folder for xmage. Create `c:\games\x\` folder, copy launcher to it and run.

**Comment by hamitasgarov** [comment]
Sorry, but still nothing. Here's the launch log, seems to be a problem with the placement of the Java folder. Sorry for my insistence :/

ERROR 2018-01-24 14:49:48,527 Error staring process                                                                      =>[AWT-EventQueue-0] Utilities.launchProcess
java.io.IOException: Cannot run program "C:\Games\xmage\java\jre1.8.0_131\bin\java" (in directory "C:\Games\xmage\xmage\mage-client"): CreateProcess error=2, Не удается найти указанный файл
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.xmage.launcher.Utilities.launchProcess(Utilities.java:150)
	at com.xmage.launcher.Utilities.launchClientProcess(Utilities.java:105)
	at com.xmage.launcher.XMageLauncher.handleClient(XMageLauncher.java:412)
	at com.xmage.launcher.XMageLauncher.access$300(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$4.actionPerformed(XMageLauncher.java:227)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, Не удается найти указанный файл
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 43 more

**Comment by JayDi85** [comment]
It's can't find java to launch. Did you have java folder in it?

Delete all files from games folder. Go to http://xmage.de/ and download launcher. Copy it to games folder and run. On launcher window update all files (java + xmage). Ensure that you have all files after update -- open games folder and check:
 - games\x\java\
 - games\x\xmage\
 - games\x\xmage\mage-client\

After that run client by launcher and report error here (if you get it).

**Comment by Zerrisx** [comment]
Looks like this was two years ago - has this been resolved?
