### ISSUE TITLE
On game end Revealed View can cause a NPE

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#444]
FATAL [2014-06-15 23:49 [10:467]] GameImpl[pool-2-thread-64]: Game exception 
java.lang.NullPointerException
    at mage.view.RevealedView.<init>(RevealedView.java:48)
    at mage.view.GameView.<init>(GameView.java:140)
    at mage.server.game.GameSession.getGameView(GameSession.java:243)
    at mage.server.game.GameWatcher.update(GameWatcher.java:76)
    at mage.server.game.GameController.updateGame(GameController.java:523)
    at mage.server.game.GameController.access$000(GameController.java:91)
    at mage.server.game.GameController$1.event(GameController.java:140)
    at mage.server.game.GameController$1.event(GameController.java:132)
    at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:56)
    at mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:66)
    at mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:1752)
    at mage.game.GameImpl.playPriority(GameImpl.java:1074)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:199)
    at mage.game.turn.Phase.play(Phase.java:112)
    at mage.game.turn.Turn.play(Turn.java:132)
    at mage.game.GameImpl.playTurn(GameImpl.java:654)
    at mage.game.GameImpl.play(GameImpl.java:620)
    at mage.game.GameImpl.start(GameImpl.java:589)
    at mage.game.GameImpl.start(GameImpl.java:574)
    at mage.server.game.GameWorker.call(GameWorker.java:59)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
INFO  [2014-06-15 23:49 [10:471]] GameImpl[pool-2-thread-64]: Game with gameId 1e16eb7e-28c9-40e3-8c30-e5f9c5850c82 ended.

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.
