### ISSUE TITLE
Exception while creating CubeFromDeck

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4449]
FATAL 2018-01-16 02:41:07,589 CubeFactory error                                                                          =>[WorkerThread#1648[24.217.143.17:52982]] CubeFactory.createDraftCube
java.lang.NoSuchMethodException: mage.tournament.cubes.CubeFromDeck.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at mage.server.draft.CubeFactory.createDraftCube(CubeFactory.java:56)
	at mage.server.tournament.TournamentFactory.createTournament(TournamentFactory.java:79)
	at mage.server.TableController.<init>(TableController.java:109)
	at mage.server.TableManager.createTournamentTable(TableManager.java:110)
	at mage.server.game.GamesRoomImpl.createTournamentTable(GamesRoomImpl.java:176)
	at mage.server.MageServerImpl$3.execute(MageServerImpl.java:260)
	at mage.server.MageServerImpl$3.execute(MageServerImpl.java:211)
	at mage.server.MageServerImpl.executeWithResult(MageServerImpl.java:1262)
	at mage.server.MageServerImpl.createTournamentTable(MageServerImpl.java:211)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.

**Comment by JayDi85** [comment]
All `NoSuchMethodException` related to different server/client version (e.g. user user outdated client). It's no more actual since version control became more strict.
