### ISSUE TITLE
To do: JSON game log 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4587]
- [x]  Add option to aktivate/deaktivate the log creating and writing

- [x] Write JSON logs to a sub folder

- [x]  java.lang.IllegalArgumentException: Access key cannot be null.
```
INFO  2018-03-08 23:00:13,941 Syncing C:\Users\user\Documents\NetBeansProjects\mage\Mage.Client\game-203cb05a-aa3e-40f5-88ab-9cb00307dc73.json to bucket: xmage-game-logs-dev with AWS Access Id: null =>[AWT-EventQueue-0] S3Uploader.upload 
FATAL 2018-03-08 23:00:13,943 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.IllegalArgumentException: Access key cannot be null.
	at com.amazonaws.auth.BasicAWSCredentials.<init>(BasicAWSCredentials.java:37)
	at mage.client.remote.S3Uploader.upload(S3Uploader.java:32)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$1(CallbackClientImpl.java:206)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by LevelX2** [comment]
Updated with b60522f9e4e328203313fca5e4d0217cd6d3c81a
