### ISSUE TITLE
nullpointer in serverlog

### ISSUE THREAD

**Issue by ingmargoudt** [magefree/mage#4645]
java.lang.NullPointerException
	at mage.cards.a.AdarkarValkyrieDelayedTriggeredAbility.checkTrigger(AdarkarValkyrie.java:146)
	at mage.abilities.DelayedTriggeredAbilities.checkTriggers(DelayedTriggeredAbilities.java:67)
	at mage.game.GameState.handleEvent(GameState.java:682)
	at mage.game.GameState.handleSimultaneousEvent(GameState.java:671)
	at mage.game.GameImpl.playPriority(GameImpl.java:1330)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:864)
	at mage.game.GameImpl.play(GameImpl.java:773)
	at mage.game.GameImpl.start(GameImpl.java:737)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
Looks like there needs to be a null check on the fixedTarget object.
