### ISSUE TITLE
IllegalStateException in server log

### ISSUE THREAD

**Issue by ingmargoudt** [magefree/mage#4646]
Game freezed in waitResponseOpen for user [XXX]     =>[CALL main-51459] HumanPlayer.waitResponseOpen
java.lang.IllegalStateException: Game freezed in waitResponseOpen for user [XXX]
	at mage.player.human.HumanPlayer.waitResponseOpen(HumanPlayer.java:160)
	at mage.player.human.HumanPlayer.setResponseBoolean(HumanPlayer.java:1777)
	at mage.server.game.GameSessionPlayer.sendPlayerBoolean(GameSessionPlayer.java:204)
	at mage.server.game.GameController.lambda$sendPlayerBoolean$10(GameController.java:733)
	at mage.server.game.GameController.sendMessage(GameController.java:977)
	at mage.server.game.GameController.sendPlayerBoolean(GameController.java:733)
	at mage.server.game.GameManager.sendPlayerBoolean(GameManager.java:106)
	at mage.server.User.sendPlayerBoolean(User.java:328)
	at mage.server.MageServerImpl.lambda$sendPlayerBoolean$16(MageServerImpl.java:757)
	at mage.server.MageServerImpl.lambda$execute$50(MageServerImpl.java:1236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
It's a disconnection problem (on user's lag or connection problem server can't process it correct and wait response) -- difficult to fix.

**Comment by ingmargoudt** [comment]
I understand that a disconnect problem from a user is difficult to fix, but is it possible to somehow catch this exception and do proper logging?

**Comment by JayDi85** [comment]
That's why exception's code was added -- for logging with stack. But today we don't need stack data any more -- all other freeze bugs was fixed, only connection problem last. 

Removed exception/stack from logs via ddc43d05f6b3bc51b386cb5e8bdfdd5d467f37f4

**Comment by ingmargoudt** [comment]
Thanks! That's exactly what I intended with this report :)
