### ISSUE TITLE
Java download is broken now

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4660]
Windows 7 x64, same with Windows 10

```
D:\Games\xmage>java.exe -jar XMageLauncher-0.3.8.jar
INFO  2018-03-24 20:14:58,604 Detected screen DPI: 96
 =>[main] Config.<clinit>
ERROR 2018-03-24 20:15:02,688 Error:
 =>[SwingWorker-pool-1-thread-2] DownloadTask.download
java.io.FileNotFoundException: http://download.oracle.com/otn-pub/?AuthParam=1521908242_7f24ad121c7d8ea29d8c766aae9edc2a

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at com.xmage.launcher.Downloader.connect(Downloader.java:38)
        at com.xmage.launcher.DownloadTask.download(DownloadTask.java:64)
        at com.xmage.launcher.XMageLauncher$UpdateTask.updateJava(XMageLauncher.java:735)
        at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:713)
        at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: http://download.oracle.com/otn-pub/?AuthParam=1521908242_7f24ad121c7d8ea29d8c7
66aae9edc2a
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at com.xmage.launcher.Downloader.connect(Downloader.java:27)
        ... 10 more
```

**Comment by JayDi85** [comment]
Works again.
