### ISSUE TITLE
Unable to launch Xmage

### ISSUE THREAD

**Issue by SirensLure** [magefree/mage#4667]
I can get to the launcher but launching it only causes this to appear in the console and nothing to happen.

INFO  2018-03-26 20:10:37,944 Starting MAGE client version 1.4.28V1                                                      =>[main] MageFrame.main 
INFO  2018-03-26 20:10:37,947 Logging level: INFO                                                                        =>[main] MageFrame.main 
FATAL 2018-03-26 20:10:38,427 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.InternalError: Could not bind shell folder to interface
	at sun.awt.shell.Win32ShellFolder2.initSpecial(Native Method)
	at sun.awt.shell.Win32ShellFolder2.access$300(Win32ShellFolder2.java:72)
	at sun.awt.shell.Win32ShellFolder2$1.call(Win32ShellFolder2.java:242)
	at sun.awt.shell.Win32ShellFolder2$1.call(Win32ShellFolder2.java:237)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Win32ShellFolderManager2.java:571)
	at sun.awt.shell.ShellFolder.invoke(ShellFolder.java:518)
	at sun.awt.shell.Win32ShellFolder2.<init>(Win32ShellFolder2.java:237)
	at sun.awt.shell.Win32ShellFolderManager2.getNetwork(Win32ShellFolderManager2.java:187)
	at sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:571)
	at sun.awt.shell.Win32ShellFolder2.access$400(Win32ShellFolder2.java:72)
	at sun.awt.shell.Win32ShellFolder2$10.call(Win32ShellFolder2.java:756)
	at sun.awt.shell.Win32ShellFolder2$10.call(Win32ShellFolder2.java:747)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Win32ShellFolderManager2.java:547)
	at java.lang.Thread.run(Thread.java:748)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0

**Comment by JayDi85** [comment]
Move launcher to other folder. Like `c:\games\xm\` and launch it from there.

**Comment by SirensLure** [comment]
Same errors still unable launch

**Comment by JayDi85** [comment]
Open launcher, settings menu, java tab and add new command to client:
 * `-Dswing.disableFileChooserSpeedFix=true`

Run client from launcher and report results. If you get same error then report OS version.

**Comment by SirensLure** [comment]
still not working I am running Windows 10 version 1709

**Comment by JayDi85** [comment]
Check your access to network computers from explorer. If not then enable it (you must see your computer in the list).

**Comment by SirensLure** [comment]
what do you mean?

**Comment by JayDi85** [comment]
Open explorer, select "network" from left menu -- it's must open network PCs list (if you don't have local network then it's show only your PC).

**Comment by SirensLure** [comment]
there is only my computer on the network...

**Comment by JayDi85** [comment]
Can't reproduce your errors. Try to research it by yourself, look at user access and admin settings.

**Comment by SirensLure** [comment]
I tried hence why I'm asking. I don't understand what is happening to fix, if I knew where or what it's shell folder was I could work to understanding why the path is broken or grant the permissions it neededs. I do know the last line is removed by clearing out the java code for window size. 


Could the issue be with in the bin or with the type of java it is trying to run?

**Comment by JayDi85** [comment]
If you download java from launcher and run app from launcher then all ok. It's access permission problem. [Read about bug here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4879395) (example and workaround).

**Comment by Zerrisx** [comment]
This appears to be a third party issue, and not an XMage bug.
