### ISSUE TITLE
XMage is broken plz help

### ISSUE THREAD

**Issue by MrPockety** [magefree/mage#4711]
ive reinstalled idk what else i can do here are some pic of what it says
![untitled](https://user-images.githubusercontent.com/38050572/38269352-4643278a-374e-11e8-9504-53b7b721d9b1.png)
![ujhfvjhv](https://user-images.githubusercontent.com/38050572/38269454-9065b350-374e-11e8-9317-6dc7af0c32c0.png)

**Comment by JayDi85** [comment]
Download symbols from main menu and restart app.

**Comment by JayDi85** [comment]
Restart your PC and go to disable auto-connect setting (see above post for instruction link). Servers are down and you can't connect now.

**Comment by MrPockety** [comment]
should i just wait for the servers to come back up and r all the servers down or just the us one and thx for helping

**Comment by JayDi85** [comment]
xmage.de is work fine now... Try to disable auto-connect and connect to it.

**Comment by MrPockety** [comment]
ok thx

**Comment by LevelX2** [comment]
Maybe we should remove the autoconnect option.

**Comment by mcappadonna** [comment]
Hi, same problem here. Yesterday evening, everything ok. This morning, software doesn't start. Version is the same as yesterday (1.4.28V1), I've already checked (and set to false) the autoconnect option, here the log:

`INFO  2018-04-11 09:48:16,253 Starting MAGE client version 1.4.28V1                                                      =>[main] MageFrame.main 
INFO  2018-04-11 09:48:16,255 Logging level: INFO                                                                        =>[main] MageFrame.main 
FATAL 2018-04-11 09:48:25,609 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.cards.repository.ExpansionRepository.getSetCodes(ExpansionRepository.java:75)
	at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:128)
	at mage.client.MageFrame.<init>(MageFrame.java:227)
	at mage.client.MageFrame.lambda$main$8(MageFrame.java:1205)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Any idea? Thanks

**Comment by spjspj** [comment]
@mcappadonna You have to download the symbols (the horse symbol in the main window at the top).  It's a bug in the current client if you don't have them (used in rendering the cards)

**Comment by JayDi85** [comment]
It's can be access denied by OS to xmage files. Move all your files to another folder like "c:\games\xm\" (or download another one launcher from xmage.de and place it to new folder). Find `db` folder and delete all files from it (`..\xmage\mage-client\db\*`). Start launcher and start client from it. Connect to any server.
