### ISSUE TITLE
AI hangs because of exception

### ISSUE THREAD

**Issue by magenoxx** [magefree/mage#475]
1) there is some bug in costs
2) AI shouldn't hang because of single NPE

Exception stack trace (see cause):
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:202)
    at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:440)
    at mage.player.ai.ComputerPlayer7.calculatePreCombatActions(ComputerPlayer7.java:175)
    at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:114)
    at mage.game.GameImpl.playPriority(GameImpl.java:1056)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:203)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:140)
    at mage.game.GameImpl.playTurn(GameImpl.java:634)
    at mage.game.GameImpl.play(GameImpl.java:600)
    at mage.game.GameImpl.start(GameImpl.java:569)
    at mage.game.GameImpl.start(GameImpl.java:554)
    at mage.server.game.GameWorker.call(GameWorker.java:58)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at java.util.ArrayList.addAll(ArrayList.java:559)
    at mage.abilities.costs.CostsImpl.getTargets(CostsImpl.java:159)
    at mage.players.PlayerImpl.addTargetOptions(PlayerImpl.java:2102)
    at mage.players.PlayerImpl.getPlayableOptions(PlayerImpl.java:2047)
    at mage.player.ai.SimulatedPlayer2.simulateOptions(SimulatedPlayer2.java:127)
    at mage.player.ai.SimulatedPlayer2.simulatePriority(SimulatedPlayer2.java:99)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:517)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:320)
    at mage.player.ai.ComputerPlayer6.minimaxAB(ComputerPlayer6.java:343)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:317)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:548)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:320)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:548)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:320)
    at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:548)
    at mage.player.ai.ComputerPlayer7.addActions(ComputerPlayer7.java:320)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:434)
    at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:431)
    ... 4 more

AI hand:
[INFO  [2014-07-24 20:33 [52:048]] ComputerPlayer6[pool-3-thread-15]: [computer], life = 19
INFO  [2014-07-24 20:33 [52:049]] ComputerPlayer6[pool-3-thread-15]: -> Hand: [Lightning Axe;Snapcaster Mage;Snapcaster Mage;Mana Leak;Mountain;Lightning Bolt;Life from the Loam;]
INFO  [2014-07-24 20:33 [52:049]] ComputerPlayer6[pool-3-thread-15]: -> Permanents: [Mountain;Mountain;Scalding Tarn;]
INFO  [2014-07-24 20:33 [52:050]] ComputerPlayer6[pool-3-thread-15]: [player], life = 17
INFO  [2014-07-24 20:33 [52:050]] ComputerPlayer6[pool-3-thread-15]: -> Hand: [Spell Pierce;Spell Snare;Mana Leak;Spell Snare;Mana Leak;]
INFO  [2014-07-24 20:33 [52:051]] ComputerPlayer6[pool-3-thread-15]: -> Permanents: [Steam Vents(tapped);Breeding Pool(tapped);Delver of Secrets(tapped);Island(tapped);Misty Rainforest;Vendilion Clique;]

Screenshot:
![image 24-07-14 at 20 38](https://cloud.githubusercontent.com/assets/1684275/3691299/03daf14a-1351-11e4-86b8-f34c6f4f9105.jpg)

**Comment by Zzooouhh** [comment]
Has this been fixed recently? Because I'm experiencing it as of version 1.4.28V1.
