### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by Darkninja0001** [magefree/mage#4810]
I updated my server like usual, but after I press launch server and tried to log in, an error message window popped up, telling me I don't have the latest server but currently have 1.28. Yet when I checked the version in the launch window, it told me that I have 1.29. I even forced an update but it still didn't work. 
![error1](https://user-images.githubusercontent.com/38542890/39020367-9a5856c0-43fa-11e8-97e1-92437f6e0803.JPG)
![error 2](https://user-images.githubusercontent.com/38542890/39020394-b5d9c4d8-43fa-11e8-919e-4e5281309839.JPG)

**Comment by jack-the-BOSS** [comment]
We should be on 1.4.29v1 now. I think it might just be time that fixes that one.

**Comment by LevelX2** [comment]
I first only updated the server with V1. There were no client bugs.

Now I also updated the launcher to be able to update the clients. But that's only important if you use your local server to play agains the AI.

**Comment by JayDi85** [comment]
@LevelX2 it's a files lock problem, not xmage. People run xmage from download folder and later got that errors on update, symbols or cards download. Replace files to new folder usually helps.

**Comment by Darkninja0001** [comment]
I restarted my computer and it did prompt me to update to 4.29V1, but then when I logged in, the error message reappeared, saying I have 4.28V1 instead of 4.29V1. Also tried moving the folder from download to desktop, but didn't work either. I really want to play Dominaria sealed early, thanks for helping everyone and let me know how to fix this.

**Comment by JayDi85** [comment]
@Darkninja0001 download new launcher file from xmage.de , place it to new folder and run.

**Comment by Darkninja0001** [comment]
@JayDi85 I tried that, the same problem occurred.

**Comment by JayDi85** [comment]
Search your computer for any `mage-client-1.4.28.jar` files. If you find it then delete that folders at all (e.g. if you find `c:\download\mage-client\lib\mage-client-1.4.28.jar` then delete `c:\download\mage-client\`.

After that use launcher to download all files.

**Comment by Darkninja0001** [comment]
@JayDi85 Huh, the same issue still occurs, thanks for your time anyways, I guess I'll try again tomorrow and hope that it'll work. This is really weird since I've been using xmage for half a year now and previous updates had no problem.

**Comment by JayDi85** [comment]
Search for server's files like `mage-1.4.28.jar` and delete that folders.

**Comment by Darkninja0001** [comment]
This? 

ERROR 2018-04-19 20:12:27,746 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] DownloadTask.download
javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.xmage.launcher.Downloader.connect(Downloader.java:27)
	at com.xmage.launcher.DownloadTask.download(DownloadTask.java:64)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:779)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by JayDi85** [comment]
You have https certificates problem. It's a very weird problem -- you can't download any data from https links (updates, symbols and cards from some sources).

Java re-install can help (java for your OS). If not help then It's too difficult to resolve -- you can read about [https fixes on linux in here](https://github.com/magefree/mage/issues/3419#issuecomment-354799527).

Fast solutions:
 * re-install java for OS;
 * run launcher by xmage java:
  * create file `run-launcher-by-xmage-java.cmd` in launcher folder;
  * insert command `.\java\jre1.8.0_172\bin\java.exe -jar XMageLauncher-0.3.8.jar`;
  * run launcher by that cmd file (or shell command) and try to update;
 * manually download and update client/server files:
  * use http://xmage.de/xmage/config.json to see current download link ([29v1](https://github.com/magefree/mage/releases/download/xmage_1.4.29V1/xmage_1.4.29V1.zip));
  * download zip and extract it to xmage folder with file replacements;
  * open `installed.properties` file from launcher folder and insert/edit line `xmage.version=1.4.29V1 (2018-04-20)`;
 * If not helped then use cacerts fixes manual from [here](https://github.com/magefree/mage/issues/3419#issuecomment-354799527);

**Comment by JayDi85** [comment]
Updated post above. Try to check/update java on your OS to 1.8

**Comment by Darkninja0001** [comment]
How do you check/update java?

**Comment by JayDi85** [comment]
Go to http://java.com/ and download latest version

**Comment by Darkninja0001** [comment]
Hmmm I think I do have the latest Java. Let me try the other steps.

**Comment by JayDi85** [comment]
Open `cmd` from search and enter `java --version` to see java version. Report it. And report your OS version too.

**Comment by Darkninja0001** [comment]
Report it here?

**Comment by JayDi85** [comment]
Yes

**Comment by Darkninja0001** [comment]
Oh, wait! Huh, I have version 1.7. I thought they auto update.

**Comment by Darkninja0001** [comment]
That's not good since this computer is borrowed from a college and I need admin permission to download most programs.

**Comment by JayDi85** [comment]
Run launcher by xmage java:
 * create `run-launcher-by-xmage-java.cmd` file in launcher folder;
 * insert command `.\java\jre1.8.0_172\bin\java.exe -jar XMageLauncher-0.3.8.jar`;
 * run launcher by that cmd file and try to update;

**Comment by Darkninja0001** [comment]
How do you run launcher from that cmd file? Do I just run launcher normally after I create the cmd file?

**Comment by JayDi85** [comment]
Run it by double click on cmd file.

**Comment by Darkninja0001** [comment]
I'm having trouble creating the cmd file, don't you just create a notepad file? I tried changing the file type but it won't let me.

**Comment by Darkninja0001** [comment]
nvm I got it

**Comment by Darkninja0001** [comment]
Once xmage opens up do I force update?

**Comment by JayDi85** [comment]
Yep, try it.

**Comment by Darkninja0001** [comment]
huh the update is not starting

**Comment by Darkninja0001** [comment]
The message in the console after I try launching client is: Error: could not open C:\Users\pfs7964\Desktop\XMAGE\java\jre1.8.0_172\lib\amd64\jvm.cfg

**Comment by JayDi85** [comment]
@Darkninja0001 Update java OS version to 1.8, wait update server to fixes or use that [full version](https://yadi.sk/d/oLKb_rzG3PwE7n) (download, unzip, run launcher and press update to inner java download).

**Comment by JayDi85** [comment]
@Darkninja0001 updater was fixed and you can download new version by launcher. Try it.

**Comment by Darkninja0001** [comment]
Hey, I was messing around yesterday and I fixed it! I download the 4.19 version and unzipped it to the xmage folder and it worked. Thanks!
