### ISSUE TITLE
command.Plane cannot be cast to command.Emblem

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4869]
From xmage.de server log 1.4.29V3
Can this be caused because of older client version?

java.lang.ClassCastException: mage.game.command.Plane cannot be cast to mage.game.command.Emblem
	at mage.game.GameImpl.leave(GameImpl.java:2572)
	at mage.game.GameImpl.checkConcede(GameImpl.java:611)
	at mage.player.human.HumanPlayer.waitForResponse(HumanPlayer.java:239)
	at mage.player.human.HumanPlayer.chooseTarget(HumanPlayer.java:532)
	at mage.target.TargetImpl.chooseTarget(TargetImpl.java:334)
	at mage.target.Targets.chooseTargets(Targets.java:99)
	at mage.abilities.AbilityImpl.activate(AbilityImpl.java:347)
	at mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:292)
	at mage.players.PlayerImpl.playAbility(PlayerImpl.java:1150)
	at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1227)
	at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1582)
	at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1596)
	at mage.player.human.HumanPlayer.priority(HumanPlayer.java:887)
	at mage.game.GameImpl.playPriority(GameImpl.java:1350)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:153)
	at mage.game.GameImpl.playTurn(GameImpl.java:880)
	at mage.game.GameImpl.playExtraTurns(GameImpl.java:834)
	at mage.game.GameImpl.play(GameImpl.java:793)
	at mage.game.GameImpl.start(GameImpl.java:753)
	at mage.server.game.GameWorker.call(GameWorker.java:60)

**Comment by spjspj** [comment]
#4704 << I'm incorrectly casting the plane to an emblem.  It should only be server side and occurrs when the controller of the Plane leaves the game.

**Comment by spjspj** [comment]
ef28106
