### ISSUE TITLE
Alliances card images with variations can't be downloaded from wizard source

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4871]
Alliances card images with variations can't be downloaded from wizard source

ERROR 2018-04-26 22:17:16,205 java.lang.NumberFormatException: For input string: "66a"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "66a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2018-04-26 22:17:16,212 java.lang.NumberFormatException: For input string: "66b"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "66b"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2018-04-26 22:17:16,214 java.lang.NumberFormatException: For input string: "55a"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "55a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2018-04-26 22:17:16,214 java.lang.NumberFormatException: For input string: "55b"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "55b"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2018-04-26 22:17:25,161 java.lang.NumberFormatException: For input string: "82a"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "82a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2018-04-26 22:17:25,162 java.lang.NumberFormatException: For input string: "82b"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "82b"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2018-04-26 22:17:25,162 java.lang.NumberFormatException: For input string: "84a"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "84a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)
ERROR 2018-04-26 22:17:25,162 java.lang.NumberFormatException: For input string: "84b"                                   =>[Thread-3862] DownloadPictures.run 
java.lang.NumberFormatException: For input string: "84b"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.mage.plugins.card.dl.sources.WizardCardsImageSource.generateURL(WizardCardsImageSource.java:515)
	at org.mage.plugins.card.images.DownloadPictures.run(DownloadPictures.java:607)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Gatherer images source was outdated after scryfall implementation. So not actual until someone return it to live again.
