### ISSUE TITLE
Spells can't target opposing creatures

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4984]
Apparently there's a bug being reported in several places claiming that spells can't target opposing creatures that they otherwise should be able to. I haven't been able to recreate this, so I'm hoping that whatever it is it'll go away with a server reboot/version update.

**Comment by janjuafarooq** [comment]
Can confirm it's happened to me today.

**Comment by felipefreitag** [comment]
I can confirm, it's happened to me while playing sealed with a friend. We couldn't target each other's creatures with spells like eviscerate and vicious offering, only our own.

**Comment by dhraskar** [comment]
I can confirm too, that happened to me with Path to Exile, during several modern matches, the instant just don't cast.

**Comment by BlaKDetH** [comment]
Moment of Craving is suffering the same

**Comment by Silex93** [comment]
Can also confirm, this has happened  against me in multiple matches, Firey Intervnetion, Fight With fire, Path to exile...

**Comment by LevelX2** [comment]
Looks a lot like a problem with a StaticFilter.

In this case FILTER_PERMANENT_CREATURE that is used from TargetCreaturePermanent.
The lock to the filter is set correctly in StaticFilters Class.

Hmm...

**Comment by janjuafarooq** [comment]
Still an issue.

**Comment by argonplatypus** [comment]
Can confirm, bug seems to be back, just happened to me in a standard game.

**Comment by jgalrito** [comment]
+1

**Comment by theelk801** [comment]
Whatever the issue is, it's not static filters, as there are reports of cards that don't use them.

**Comment by LevelX2** [comment]
**Affected cards:**
[Eviscerate](https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage.Sets/src/mage/cards/e/Eviscerate.java)
Path to Exile
[Fight with Fire](https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage.Sets/src/mage/cards/f/FightWithFire.java)
[Fiery Intervention](https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage.Sets/src/mage/cards/f/FieryIntervention.java)
[Ahn-Crop Champion](https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage.Sets/src/mage/cards/a/AhnCropChampion.java)
Abrade
Vizier of Many Faces
Goblin Barrage
Dismember
Backfire

**Comment by LevelX2** [comment]
> Whatever the issue is, it's not static filters, as there are reports of cards that don't use them.

Which card is an example not using new TargetCreaturePermanent() as target?

**Comment by theelk801** [comment]
Ahn-Crop Champion

**Comment by LevelX2** [comment]
> Ahn-Crop Champion

Seems like this card does not belong to the list. Seems to be a false bug report.
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=22239&sid=a41167c97ff2f8bef01a9353990e3294&start=30#p225393

It seems to me correct, that it's not possible to target opponent creatures with Ahn-Crop Champion.

**Comment by theelk801** [comment]
Oh, I see. I think they were referring to Ahn-Crop Crasher, which does belong on the list.

**Comment by theelk801** [comment]
Looks like there were subtype classes that could be modified even if locked. There's still something somewhere that's modifying these filters even when they shouldn't, though. Hopefully this change will help us catch it.

**Comment by LevelX2** [comment]
Did it happen again since update to V3?
Any feedbacks?

**Comment by LevelX2** [comment]
FATAL 2018-06-10 08:00:20,938 Error loading card: mage.cards.t.Topple (NEM)                                              =>[main] CardImpl.createCard
java.lang.UnsupportedOperationException: You may not modify a locked filter
	at mage.filter.FilterImpl.add(FilterImpl.java:46)
	at mage.cards.t.ToppleTargetCreature.<init>(Topple.java:47)
	at mage.cards.t.Topple.<init>(Topple.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:201)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:61)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:129)

**Comment by LevelX2** [comment]
Topple fixed with 984bc0871bdde4c7e006d6e0e56d41305f653329.
