### ISSUE TITLE
Java update problem

### ISSUE THREAD

**Issue by Stafy1** [magefree/mage#5205]
Xmage gave me a pop-up saying that a new version of Java was available (current was 172, new one was 181).

Updating through the launcher won't work, as it was mentioned before Oracle download is broken. I went to download it manually from Oracle, but there's no 181, only 172

**Comment by JayDi85** [comment]
Java update was fixed yesterday and it works fine. Open process explorer and close all running `java.exe` apps (it's possible xmage client  do not close correctly) or simply restart PC. And try again to update java by launcher. 

If you can't then report your latest logs from `xmage_launcher.log` file and describe your launcher running process (it's possible that's you run it by special script and uses xmage's java instead system).

```
ERROR 2018-08-07 12:18:51,861 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\api-ms-win-core-file-l1-2-0.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,886 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\api-ms-win-core-file-l2-1-0.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,911 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\api-ms-win-core-localization-l1-2-0.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,913 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\api-ms-win-core-processthreads-l1-1-1.dl
l =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,942 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\api-ms-win-core-timezone-l1-1-0.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,947 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\awt.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,947 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\dcpr.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,950 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\fontmanager.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,953 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\java.dll
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
ERROR 2018-08-07 12:18:51,953 Can't remove D:\Games\xmage\java\jre1.8.0_172\bin\java.exe
 =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.removeJavaFiles
```

**Comment by Stafy1** [comment]
I restarted and managed to update the Java version, but now the console is blank and xmage won't start.

Xmage log:
ERROR 2018-08-07 11:49:56,975 Error staring process                                                                      =>[AWT-EventQueue-0] Utilities.launchProcess
java.io.IOException: Cannot run program "D:\games\xmage\java\jre1.8.0_181\bin\java" (in directory "D:\games\xmage\xmage\mage-client"): CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.xmage.launcher.Utilities.launchProcess(Utilities.java:150)
	at com.xmage.launcher.Utilities.launchClientProcess(Utilities.java:105)
	at com.xmage.launcher.XMageLauncher.handleClient(XMageLauncher.java:412)
	at com.xmage.launcher.XMageLauncher.access$300(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$4.actionPerformed(XMageLauncher.java:227)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 43 more

**Comment by JayDi85** [comment]
XMage files mustb updated too. Close xmage, delete `xmage` subfolder with client files (`D:\games\xmage\xmage\`), open `installed.properties` and delete line with `xmage.version=...`. Run launcher and it's request to update client -- do it.

**Comment by Stafy1** [comment]
That worked. Thanks!
