### ISSUE TITLE
Image Download Error

### ISSUE THREAD

**Issue by elishacoad** [magefree/mage#5249]
When trying to download card images, it throws me this error.

```
ManaSymbols.lambda$loadSymbolImages$0 
INFO  2018-08-20 22:12:37,580 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2018-08-20 22:12:37,604 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2018-08-20 22:12:37,609 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2018-08-20 22:12:38,158 Client start up time: 14 seconds                                                           =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2018-08-20 22:12:49,630 Card was not selected: Grimlock, Dinobot Leader                                            =>[ForkJoinPool.commonPool-worker-0] DownloadPictures.lambda$getNeededCards$4 
INFO  2018-08-20 22:12:49,631 Card was not selected: Sword of Dungeons & Dragons                                         =>[ForkJoinPool.commonPool-worker-0] DownloadPictures.lambda$getNeededCards$4 
FATAL 2018-08-20 22:12:52,000 MAGE Client UI error                                                                       =>[Thread-333] EDTExceptionHandler.handle 
java.nio.file.InvalidPathException: Illegal char <?> at index 15: 4ED.zip/4ED/Jun?n Efreet.full.jpg
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at net.java.truevfs.driver.file.FileController.checkAccess(FileController.java:99)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$UseParent.apply(FalsePositiveArchiveController.scala:204)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:181)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.checkAccess(FalsePositiveArchiveController.scala:74)
	at net.java.truevfs.access.TFile.exists(TFile.java:1670)
	at org.mage.plugins.card.images.DownloadPictures.lambda$getNeededCards$5(DownloadPictures.java:469)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: net.java.truevfs.kernel.impl.FalsePositiveArchiveException: java.nio.file.NoSuchFileException: 4ED.zip
	Caused by: java.nio.file.NoSuchFileException: 4ED.zip
		at net.java.truevfs.kernel.impl.TargetArchiveController.mount0(TargetArchiveController.scala:141)
		at net.java.truevfs.kernel.impl.TargetArchiveController.mount(TargetArchiveController.scala:109)
		at net.java.truevfs.kernel.impl.FileSystemArchiveController$ResetFileSystem.autoMount(FileSystemArchiveController.scala:70)
		at net.java.truevfs.kernel.impl.FileSystemArchiveController.autoMount(FileSystemArchiveController.scala:37)
		at net.java.truevfs.kernel.impl.BasicArchiveController.checkAccess(BasicArchiveController.scala:56)
		at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$SyncController$$super$checkAccess(DefaultManager.scala:158)
		at net.java.truevfs.kernel.impl.SyncController$$anonfun$checkAccess$1.apply$mcV$sp(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.SyncController$$anonfun$checkAccess$1.apply(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.SyncController$$anonfun$checkAccess$1.apply(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.SyncController$class.net$java$truevfs$kernel$impl$SyncController$$apply(SyncController.scala:129)
		at net.java.truevfs.kernel.impl.SyncController$class.checkAccess(SyncController.scala:47)
		at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$LockController$$super$checkAccess(DefaultManager.scala:158)
		at net.java.truevfs.kernel.impl.LockController$$anonfun$checkAccess$1.apply$mcV$sp(LockController.scala:48)
		at net.java.truevfs.kernel.impl.LockController$$anonfun$checkAccess$1.apply(LockController.scala:48)
		at net.java.truevfs.kernel.impl.LockController$$anonfun$checkAccess$1.apply(LockController.scala:48)
		at net.java.truevfs.kernel.impl.LockingStrategy.apply(LockingStrategy.scala:84)
		at net.java.truevfs.kernel.impl.LockController$class.timedReadOrWriteLocked(LockController.scala:104)
		at net.java.truevfs.kernel.impl.LockController$class.checkAccess(LockController.scala:48)
		at net.java.truevfs.kernel.impl.DefaultManager$BackController.checkAccess(DefaultManager.scala:158)
		at net.java.truevfs.kernel.impl.ArchiveControllerAdapter.checkAccess(ArchiveControllerAdapter.scala:23)
		at net.java.truevfs.comp.zipdriver.AbstractKeyController.checkAccess(AbstractKeyController.java:105)
		at net.java.truevfs.kernel.spec.FsDecoratingController.checkAccess(FsDecoratingController.java:53)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$$anonfun$checkAccess$1.apply(FalsePositiveArchiveController.scala:74)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$TryChild$.apply(FalsePositiveArchiveController.scala:195)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
		at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.checkAccess(FalsePositiveArchiveController.scala:74)
		at net.java.truevfs.access.TFile.exists(TFile.java:1670)
		at org.mage.plugins.card.images.DownloadPictures.lambda$getNeededCards$5(DownloadPictures.java:469)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
		at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
		at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by JayDi85** [comment]
Wait next release with fixes. Or you can try [that workaround with restore previous version](https://www.reddit.com/r/XMage/comments/97v9eo/new_user_here_anyone_else_perpetually_stuck_on/e4f9fkg/).
