### ISSUE TITLE
Public Server - Random disconnects 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#537]
Far too often the client loses the connection to the server. Would be interesting what can be the reason. This issue is used to gather information about.

Is it a timing problem?
A bad internet connection?
Or a server bug?

Maybe it makes sens to adjust some timeouts of the XMage server/client JBoss Remoting  settings.

Here's what written to the client log as I lost connection during a draft:

```
INFO  2014-08-23 19:15:22,767 Tournament 92a79c02-80d1-4691-be28-83566ddeb276 started for player 7ea5624b-401c-4f49-a93c-5d08e3f5b244 =>[AWT-EventQueue-0] CallbackClientImpl.tournamentStarted 
INFO  2014-08-23 19:15:23,855 Draft 179d8703-1e73-4f0f-a107-577123df0d68 started for player 7ea5624b-401c-4f49-a93c-5d08e3f5b244 =>[AWT-EventQueue-0] CallbackClientImpl.draftStarted 
INFO  2014-08-23 19:30:24,845 connection to server lost - Could not connect to server!                                   =>[Thread-12715] SessionImpl$ClientConnectionListener.handleConnectionException 
INFO  2014-08-23 19:30:24,965 Disconnected ...                                                                           =>[Thread-12715] SessionImpl.disconnect 
FATAL 2014-08-23 19:30:31,440 Error disconnecting ...                                                                    =>[AWT-EventQueue-0] SessionImpl.disconnect 
java.lang.Exception: Can not remove callback listener as remoting client is not connected to server.
    at org.jboss.remoting.Client.removeListener(Client.java:1466)
    at mage.remote.SessionImpl.disconnect(SessionImpl.java:281)
    at mage.client.MageFrame$22.run(MageFrame.java:1240)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
FATAL 2014-08-23 19:30:40,969 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
INFO  2014-08-23 19:30:46,634 Connected as Bandit to MAGE server at 176.31.186.181:17171                                 =>[AWT-EventQueue-0] SessionImpl.connect 
INFO  2014-08-23 19:30:46,973 Disconnected ...                                                                           =>[pool-1-thread-1] SessionImpl.disconnect 
INFO  2014-08-23 19:30:59,023 Connected as Bandit to MAGE server at 176.31.186.181:17171                                 =>[SwingWorker-pool-4-thread-9] SessionImpl.connect 
INFO  2014-08-23 19:31:09,113 Showing tournament table 088f8e22-f795-474d-a5fe-934dd010d1e8
```

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
