### ISSUE TITLE
Cannot generate random deck for GRN

### ISSUE THREAD

**Issue by robertre2** [magefree/mage#5413]
Generating a random deck using the "Guilds of Ravnica" format, XX color, 40 cards,
with options Singleton, Artifacts, Non-basic lands
does not work. (Some other combinations for Guilds of Ravnica also appear to not work)

I am running
XMage version installed:  1.4.31V4 (2018-09-30)
Java version installed:  1.8.0_191

I get an error:
FATAL 2018-11-04 22:01:20,958 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:351)
	at mage.util.RandomUtil.nextInt(RandomUtil.java:23)
	at mage.client.deck.generator.DeckGenerator.getBasicLand(DeckGenerator.java:371)
	at mage.client.deck.generator.DeckGenerator.addBasicLands(DeckGenerator.java:353)
	at mage.client.deck.generator.DeckGenerator.generateLands(DeckGenerator.java:275)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:168)
	at mage.client.deck.generator.DeckGenerator.buildDeck(DeckGenerator.java:87)
	at mage.client.deck.generator.DeckGenerator.generateDeck(DeckGenerator.java:53)
	at mage.client.deckeditor.DeckEditorPanel.btnGenDeckActionPerformed(DeckEditorPanel.java:1055)
	at mage.client.deckeditor.DeckEditorPanel.lambda$initComponents$10(DeckEditorPanel.java:691)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by JayDi85** [comment]
Fixed via d78d818a667d383058ef5673fa1f4bc334f58d01
