### ISSUE TITLE
As Foretold - missing watcher error

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5510]
As Foretold card, error in AsForetoldAddAltCostEffect, watcher must be initialized with card creation or be global.

Server logs:
```
ERROR 2019-01-11 15:49:47,328 bafa8c42-9c54-4871-af37-278f4721b17eAsForetoldAltCostUsedWatcher not found in watchers     =>[GAME c35d5908-8dec-437f-b108-5a81bd45069c] Watchers.get
java.lang.Throwable
        at mage.watchers.Watchers.get(Watchers.java:51)
        at mage.watchers.Watchers.get(Watchers.java:43)
        at mage.game.GameState.getWatcher(GameState.java:544)
        at mage.cards.a.AsForetoldAddAltCostEffect.apply(AsForetold.java:163)
        at mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1009)
        at mage.game.GameState.applyEffects(GameState.java:573)
        at mage.game.GameImpl.applyEffects(GameImpl.java:1530)
        at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3547)
        at mage.players.PlayerImpl.moveCards(PlayerImpl.java:3493)
        at mage.game.stack.Spell.resolve(Spell.java:293)
        at mage.game.GameImpl.resolve(GameImpl.java:1404)
        at mage.game.GameImpl.playPriority(GameImpl.java:1354)
        at mage.game.turn.Step.priority(Step.java:61)
```

**Comment by jeffwadsworth** [comment]
This card was working perfectly fine not very long ago.  So, a recent change is to blame.

**Comment by JayDi85** [comment]
It's a new checks, not card. Last versions don't have that watcher checks and ignores missing watchers at all (e.g. that card don't wok for some situations or at all).

**Comment by LevelX2** [comment]
Switch to game instead of card watcher using sourceId.
Card watcher can always give problems in case of card copys or cloning actions.

**Comment by ingmargoudt** [comment]
This is a new error message. This error could have been there before but now it is logged in Watchers::51 . AsForeTold has not changed in functionality, only a rewrite from game.getState.getWatchers().get() to game.getState().getWatcher(). There are examples of other watchers that also log errors, like the CommanderInfoWatcher

**Comment by JayDi85** [comment]
All that errors must be fixed (cards lost their watcher or not initialize it). `As Foretold` generates watcher name with card id... but on copy that card's Id is changes, but watcher's copy uses old one. That's one of the the reason.

**Comment by ingmargoudt** [comment]
Ah that changed cardId is a very good reason. Indeed their copy method should handle this. Perhaps by a method called replaceWatcher in the gamestate? That removes the previous watcher and adds the new one with the new Id

**Comment by ingmargoudt** [comment]
VorinclexVoiceOfHungerTest - PlayLandWatcher not found in watchers

all commander tests: {id}CommanderInfoWatcher not found in watchers

**Comment by jeffwadsworth** [comment]
Watchers??  We don't need no stinking watchers!  Love that movie.  Fix tomorrow.
