### ISSUE TITLE
Game types not found Running Xmage Server

### ISSUE THREAD

**Issue by LordNex** [magefree/mage#5536]
I upgraded to the latest version V33 and when I fire up the server the log files show that the game types have not been found. When you logon to the server and attempt to start a new game the type of game drop down is blank. See attached log file

WARN  2019-01-17 18:31:08,298 Game type not found:mage-game-twoplayerduel-1.4.31.jar - check plugin folder               =>[main] Main.loadGameType
java.lang.ClassNotFoundException: mage.game.TwoPlayerDuelType
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at mage.server.util.PluginClassLoader.loadClass(PluginClassLoader.java:43)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at mage.server.Main.loadGameType(Main.java:391)
	at mage.server.Main.main(Main.java:144)

[service.log](https://github.com/magefree/mage/files/2771134/service.log)

**Comment by LordNex** [comment]
Well I was able to fix it but I had to completely blow out the entire xmage directory and start from scratch. Every time I try and move over the Users DB and then run the server the attached errors occur. 

If possible it would be nice to be able to just download the updated server files for us who run dedicated servers and run them as a windows service. Using the launcher is just not practical in a server environment. It would be nice if we could just backup the server messages, config.xml, and the user db, copy the new server dir over, then copy just those files back into the new version. Not sure if this is possible with this setup but is what I was doing in the past and never had this happen. 

Over all though the new update looks very nice and adds some great features. Kudos to the dev team!!!
