### ISSUE TITLE
Kess, Dissident Mage - NPE error with watcher

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5563]
NPE error on AI play:
```
 java.lang.NullPointerException
        at mage.cards.k.KessDissidentMageWatcher.watch(KessDissidentMage.java:182)
        at mage.watchers.Watchers.watch(Watchers.java:34)
        at mage.game.GameState.handleEvent(GameState.java:704)
        at mage.game.GameImpl.fireEvent(GameImpl.java:2682)
        at mage.players.PlayerImpl.cast(PlayerImpl.java:1097)
        at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1280)
        at mage.player.ai.ComputerPlayer.activateAbility(ComputerPlayer.java:1104)
        at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:468)
        at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:268)

```

**Comment by ingmargoudt** [comment]
fixed in 4be8cdc02
the check was missing parentheses around an or-statement.
