### ISSUE TITLE
Karn Liberated restart ability brokes commander games

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5575]
It's a rare error (maybe only `tiny leader` affected, search code: `new CommanderInfoWatcher`). 

Karn Liberated's restart ability do not full restore commander game settings and effects, as example: `CommanderInfoWatcher` is not restored. Connected fix: 678118c79da3db37cf5aa26df9083453fe77c6a4

Server log:
```
ERROR 2019-02-06 02:30:31,318 4c4c7432-bd22-4e2b-93f7-71d53d2de88bCommanderInfoWatcher not found in watchers             =>[pool-1-thread-1] Watchers.get
java.lang.Throwable
        at mage.watchers.Watchers.get(Watchers.java:51)
        at mage.watchers.Watchers.get(Watchers.java:43)
        at mage.game.GameState.getWatcher(GameState.java:544)
        at mage.game.GameCommanderImpl.checkStateBasedActions(GameCommanderImpl.java:170)
        at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1769)
        at mage.game.GameImpl.playPriority(GameImpl.java:1323)
        at mage.game.turn.Step.priority(Step.java:61)
        at mage.game.turn.Phase.playStep(Phase.java:184)
        at mage.game.turn.Phase.play(Phase.java:89)
        at mage.game.turn.Turn.play(Turn.java:127)
        at mage.game.GameImpl.playTurn(GameImpl.java:858)
        at mage.game.GameImpl.play(GameImpl.java:767)
        at mage.game.GameImpl.start(GameImpl.java:731)
        at mage.cards.k.KarnLiberatedEffect.apply(KarnLiberated.java:133)
        at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:171)
        at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:161)
        at mage.game.stack.StackAbility.resolve(StackAbility.java:84)
        at mage.player.ai.ComputerPlayer6.resolve(ComputerPlayer6.java:392)

```

**Comment by JayDi85** [comment]
No more actual
