### ISSUE TITLE
Connecting Issues

### ISSUE THREAD

**Issue by kayalareren** [magefree/mage#5583]
I can't connect any server nor download any images. It says unable to connect. Here is the mageclient.log: (And does vpn help this issue I am not installed a vpn) (New to github I hope I didn't anything wrong)

INFO  2019-02-09 23:15:53,834 Starting MAGE client version 1.4.33V3 (build: 2019-02-09 15:13)                            =>[main] MageFrame.main 
INFO  2019-02-09 23:15:53,837 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2019-02-09 23:15:56,178 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2019-02-09 23:15:58,196 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
WARN  2019-02-09 23:15:58,227 Symbols can't be load for size 15: SVG fails - 52, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
WARN  2019-02-09 23:15:58,230 Symbols can't be load for size 25: SVG fails - 52, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
WARN  2019-02-09 23:15:58,234 Symbols can't be load for size 50: SVG fails - 52, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
INFO  2019-02-09 23:15:58,276 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-02-09 23:15:58,400 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2019-02-09 23:15:58,420 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2019-02-09 23:15:58,434 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2019-02-09 23:15:58,435 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-02-09 23:16:00,552 Client start up time: 6 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2019-02-09 23:16:28,273 Trying to connect to XMAGE server at xmage.today:17171                                     =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2019-02-09 23:16:29,677 Connected to MAGE server at xmage.today:17171                                              =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2019-02-09 23:16:29,679 Trying to log-in as sfgdred to XMAGE server at xmage.today:17171                           =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
FATAL 2019-02-09 23:16:29,765                                                                                            =>[SwingWorker-pool-4-thread-2] SessionImpl.handleRemotingTaskExceptions 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy8.connectUser(Unknown Source)
	at mage.remote.SessionImpl$4.run(SessionImpl.java:204)
	at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:91)
	at mage.remote.SessionImpl.connect(SessionImpl.java:196)
	at mage.client.SessionHandler.connect(SessionHandler.java:52)
	at mage.client.MageFrame.connect(MageFrame.java:714)
	at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:547)
	at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:536)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.remoting.InvalidConfigurationException: Can not handle invocation request for subsystem 'MAGE.İNTERFACES.MAGESERVER' because there are no matching ServerInvocationHandlers registered. Please add via xml configuration or via the Connector's addInvocationHandler() method.
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:962)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	... 14 more
WARN  2019-02-09 23:16:49,802 No formats defined. Try connecting to a server first!                                      =>[Thread-65] DownloadPicturesService.prepareMissingCards 
FATAL 2019-02-09 23:16:59,566 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy8.ping(Unknown Source)
	at mage.remote.SessionImpl.ping(SessionImpl.java:1588)
	at mage.client.SessionHandler.ping(SessionHandler.java:35)
	at mage.client.MageFrame.lambda$new$1(MageFrame.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.remoting.InvalidConfigurationException: Can not handle invocation request for subsystem 'MAGE.İNTERFACES.MAGESERVER' because there are no matching ServerInvocationHandlers registered. Please add via xml configuration or via the Connector's addInvocationHandler() method.
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:962)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	... 11 more
FATAL 2019-02-09 23:17:59,564 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy8.ping(Unknown Source)
	at mage.remote.SessionImpl.ping(SessionImpl.java:1588)
	at mage.client.SessionHandler.ping(SessionHandler.java:35)
	at mage.client.MageFrame.lambda$new$1(MageFrame.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.remoting.InvalidConfigurationException: Can not handle invocation request for subsystem 'MAGE.İNTERFACES.MAGESERVER' because there are no matching ServerInvocationHandlers registered. Please add via xml configuration or via the Connector's addInvocationHandler() method.
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:962)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	... 11 more

**Comment by JayDi85** [comment]
Try connects to BETA server. Is that work?

**Comment by JayDi85** [comment]
Restart your machine and try again. If that not helps then you can download https://www.teamviewer.com/ run it and send me connect ID and password (email: jaydi85@gmail.com ) -- I'll connects to your machine and checks all settings.

**Comment by JayDi85** [comment]
I think it's ipv4 or proxy problem. Go here and [try apply that instructions](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/) (steps 1-8). If it's not helps or too complex then send me teamviewer connection (see above).

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to create a new one if this is still a problem.
