### ISSUE TITLE
PreventAllDamageToAllEffect cast error

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5584]
Server log:
```
java.lang.ClassCastException: mage.player.human.HumanPlayer cannot be cast to mage.game.permanent.Permanent
        at mage.filter.FilterPermanent.match(FilterPermanent.java:21)
        at mage.abilities.effects.common.PreventAllDamageToAllEffect.applies(PreventAllDamageToAllEffect.java:77)
        at mage.abilities.effects.ContinuousEffects.getApplicableReplacementEffects(ContinuousEffects.java:372)
        at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:748)
        at mage.game.GameState.replaceEvent(GameState.java:712)
        at mage.game.GameState.replaceEvent(GameState.java:705)
        at mage.game.GameImpl.replaceEvent(GameImpl.java:2687)
        at mage.players.PlayerImpl.doDamage(PlayerImpl.java:1957)
        at mage.players.PlayerImpl.damage(PlayerImpl.java:1943)
        at mage.game.combat.CombatGroup.defenderDamage(CombatGroup.java:570)
        at mage.game.combat.CombatGroup.unblockedDamage(CombatGroup.java:260)
        at mage.game.combat.CombatGroup.assignDamageToBlockers(CombatGroup.java:170)
        at mage.game.turn.CombatDamageStep.beginStep(CombatDamageStep.java:46)
        at mage.game.turn.Phase.prePriority(Phase.java:168)

```

**Comment by jeffwadsworth** [comment]
The filter in that class is for creatures only.

**Comment by jeffwadsworth** [comment]
Looks like this might be related to the card Endure.  I will check it out.
