### ISSUE TITLE
Teferi, Hero of Dominaria - NPE error in putCardOnTopXOfLibrary

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5601]
Server's logs:
```
Caused by: java.lang.NullPointerException
        at mage.players.PlayerImpl.putCardOnTopXOfLibrary(PlayerImpl.java:921)
        at mage.cards.t.TeferiHeroOfDominariaSecondEffect.apply(TeferiHeroOfDominaria.java:90)
        at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:176)
        at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:166)
        at mage.game.stack.StackAbility.resolve(StackAbility.java:85)
        at mage.player.ai.ComputerPlayer6.resolve(ComputerPlayer6.java:392)
        at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:233)
        at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:492)
        at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:269)
        at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:410)
        at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:407)

```

**Comment by jeffwadsworth** [comment]
We need a log of this game.

**Comment by jeffwadsworth** [comment]
Unless we have a log, this NPE makes no sense to me.
