### ISSUE TITLE
Riptide Chronologist - NPE error

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5602]
Server's logs:

```
Caused by: java.lang.NullPointerException
        at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:300)
        at mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:279)
        at mage.cards.r.RiptideChronologistEffect.apply(RiptideChronologist.java:75)
        at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:176)
        at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:166)
        at mage.game.stack.StackAbility.resolve(StackAbility.java:85)
        at mage.player.ai.ComputerPlayer6.resolve(ComputerPlayer6.java:392)
        at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:233)
        at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:492)

```

**Comment by ingmargoudt** [comment]
````java
Set<UUID> range = game.getPlayer(sourcePlayerId).getInRange();
            ```

probably getPlayer returned a null
