### ISSUE TITLE
 Gonti, Lord of Luxury - NPE error

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5748]
Server logs:
```
java.lang.NullPointerException
	at mage.cards.g.GontiLordOfLuxurySpendAnyManaEffect.applies(GontiLordOfLuxury.java:187)
	at mage.abilities.effects.AsThoughEffectImpl.applies(AsThoughEffectImpl.java:35)
	at mage.abilities.effects.ContinuousEffects.asThoughMana(ContinuousEffects.java:540)
	at mage.players.ManaPool.pay(ManaPool.java:145)
	at mage.abilities.costs.mana.ManaCostImpl.assignGeneric(ManaCostImpl.java:149)
	at mage.abilities.costs.mana.GenericManaCost.assignPayment(GenericManaCost.java:45)
	at mage.abilities.costs.mana.ManaCostsImpl.assignPayment(ManaCostsImpl.java:314)
	at mage.abilities.costs.mana.ManaCostsImpl.pay(ManaCostsImpl.java:128)
	at mage.abilities.AbilityImpl.activate(AbilityImpl.java:382)
	at mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:288)
	at mage.players.PlayerImpl.playManaAbility(PlayerImpl.java:1176)
	at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1273)
	at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1689)
```

**Comment by jeffwadsworth** [comment]
It would be good to know what the card being cast was.

**Comment by ingmargoudt** [comment]
``objectId = game.getCard(objectId).getMainCard().getId(); // for split cards``

getCard() could return null, and getMainCard() could return null (theoretically). Most likely getCard() returned a null.  I will add some nullchecks here.
