### ISSUE TITLE
Bolas's Citadel - NPE error

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5749]
Server logs:
```
java.lang.NullPointerException
	at mage.cards.b.BolassCitadelPlayTheTopCardEffect.applies(BolassCitadel.java:96)
	at mage.abilities.effects.ContinuousEffects.asThough(ContinuousEffects.java:507)
	at mage.players.PlayerImpl.getUseableActivatedAbilitiesHalfImpl(PlayerImpl.java:1413)
	at mage.players.PlayerImpl.getUseableActivatedAbilities(PlayerImpl.java:1453)
	at mage.player.human.HumanPlayer.priority(HumanPlayer.java:946)
	at mage.game.GameImpl.playPriority(GameImpl.java:1248)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:127)
```

**Comment by jeffwadsworth** [comment]
Fix coming.  Just testing.
