### ISSUE TITLE
Random Disconnects with 1.3.0dev2014-09-26v2

### ISSUE THREAD

**Issue by patrickstjohn** [magefree/mage#586]
Random disconnects occur after a few minutes of being connected. Requires complete shutdown of client in order to properly reconnect. Connection between myself and the server is ~110ms and I'm able to ping the entire time this is happening. Below is the stack trace. I'm on Mac OS X 10.9.5.

```
INFO  2014-09-30 21:39:20,227 Connected as patrickstj to MAGE server at 176.31.186.181:17171                             =>[SwingWorker-pool-3-thread-2] SessionImpl.connect 
INFO  2014-09-30 21:39:56,725 connection to server lost - Could not connect to server!                                   =>[Thread-509] SessionImpl$ClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
    at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
    at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
    at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
    at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
INFO  2014-09-30 21:39:56,727 RECONNECT - Connected: true                                                                =>[Thread-509] SessionImpl.reconnect 
INFO  2014-09-30 21:39:56,727 DISCONNECTED (NO Event Dispacth Thread)                                                    =>[Thread-509] MageFrame.disconnected 
FATAL 2014-09-30 21:40:00,037                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:592)
    at java.lang.Integer.parseInt(Integer.java:615)
    at mage.client.MageFrame.performConnect(MageFrame.java:698)
    at mage.client.MageFrame.access$2000(MageFrame.java:102)
    at mage.client.MageFrame$22.run(MageFrame.java:1250)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR 2014-09-30 21:40:15,046 Ping failed: patrickstj Session: 5c4o113-cf8yxz-i0ppkjym-1-i0ppkk0j-4 to MAGE server at 176.31.186.181:17171 =>[pool-1-thread-1] SessionImpl.ping 
FATAL 2014-09-30 21:40:15,048 Server error                                                                               =>[pool-1-thread-1] SessionImpl.handleMageException 
mage.MageException: Ping failed
    at mage.remote.SessionImpl.ping(SessionImpl.java:1363)
    at mage.client.MageFrame$2.run(MageFrame.java:215)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
