### ISSUE TITLE
Remote Task Error

### ISSUE THREAD

**Issue by KebbabBoi** [magefree/mage#5869]
INFO  2019-06-30 16:06:41,185 Disconnecting...                                                                           =>[SwingWorker-pool-6-thread-7] SessionImpl.disconnect 
INFO  2019-06-30 16:06:41,394 Disconnecting DONE                                                                         =>[SwingWorker-pool-6-thread-7] SessionImpl.disconnect 
INFO  2019-06-30 16:06:41,429 Disconnected from user mode                                                                =>[SwingWorker-pool-6-thread-7] MageFrame.disconnected 
INFO  2019-06-30 16:06:41,434 Connect: connecting to server xmage.de:17171                                               =>[SwingWorker-pool-6-thread-8] SessionImpl$5.work 
INFO  2019-06-30 16:06:42,022 Connect: DONE                                                                              =>[SwingWorker-pool-6-thread-8] SessionImpl$5.work 
INFO  2019-06-30 16:06:42,025 Registration: username kebbabboi for email atomicezeus@gmail.com                           =>[SwingWorker-pool-6-thread-9] SessionImpl$1.work 
FATAL 2019-06-30 16:06:42,097 Connect: unknown error                                                                     =>[SwingWorker-pool-6-thread-7] SessionImpl.doRemoteWorkAndHandleErrors 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy8.registerUser(Unknown Source)
	at mage.remote.SessionImpl$1.work(SessionImpl.java:190)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.remoting.InvalidConfigurationException: Can not handle invocation request for subsystem 'MAGE.İNTERFACES.MAGESERVER' because there are no matching ServerInvocationHandlers registered. Please add via xml configuration or via the Connector's addInvocationHandler() method.
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:962)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	... 10 more
INFO  2019-06-30 16:06:42,107 Disconnecting...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2019-06-30 16:06:42,301 Disconnecting DONE                                                                         =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2019-06-30 16:06:42,302 Disconnected from remote task                                                              =>[AWT-EventQueue-0] MageFrame.disconnected 

Whenever i try to register it says "Remote task eror" İ am able to connect to localhost but not to any other server. Please help

**Comment by JayDi85** [comment]
What's your client version? Its visible on startup in logs or in app's window caption.

Also use start - search "cmd" and enter command line: ping localhost
It's shows your computer name.

**Comment by KebbabBoi** [comment]
DESKTOP-SS9K2SR is the computer name. İ have xmage version 1.4.36V3

**Comment by JayDi85** [comment]
It's can be non english windows problem (like Turkish):
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16424

There aren't fixes for that bug. You can try connects to xmage by IP (run "ping xmage.de " in cmd like before to find out IP).

**Comment by KebbabBoi** [comment]
Thanks a lot :D

**Comment by JayDi85** [comment]
Are IP connect helped you?

**Comment by KebbabBoi** [comment]
no i changed the language of windows from turkish to english and the problem was solved immediately
Thanks for the help
