### ISSUE TITLE
MAGE server version 1.4.37V4 Throwing NPE

### ISSUE THREAD

**Issue by michaeldelgado1** [magefree/mage#5903]
I'm very new to Xmage, so sorry if this is an easily fixed issue. When staring up the xmage client, and server, the server caller throws a Null Pointer Exception during start up. The console log is below 

OS: macOS MoJave v10.14.5
Wifi Connection  

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
INFO  2019-07-15 21:08:13,516 Starting MAGE server version 1.4.37V4 (build: 2019-07-13 15:59)                            =>[main] Main.main
INFO  2019-07-15 21:08:13,518 Logging level: DEBUG                                                                       =>[main] Main.main
INFO  2019-07-15 21:08:13,720 Loading database...                                                                        =>[main] RepositoryUtil.bootstrapLocalDb
org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.SocketTimeoutException: connect timed out: 10.199.150.78:53894" [90067-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:451)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:364)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:266)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:187)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:397)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:383)
	at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:75)
	at mage.cards.repository.RepositoryUtil.isDatabaseObsolete(RepositoryUtil.java:32)
	at mage.cards.repository.ExpansionRepository.<init>(ExpansionRepository.java:47)
	at mage.cards.repository.ExpansionRepository.<clinit>(ExpansionRepository.java:26)
	at mage.cards.repository.RepositoryUtil.bootstrapLocalDb(RepositoryUtil.java:27)
	at mage.server.Main.main(Main.java:94)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:103)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:83)
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:114)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:447)
	... 16 more
ERROR 2019-07-15 21:08:25,879 Error creating card repository -                                                           =>[main] CardRepository.<init>
org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.SocketTimeoutException: connect timed out: 10.199.150.78:53894" [90067-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:451)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:364)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:266)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:187)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:397)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:383)
	at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:75)
	at mage.cards.repository.RepositoryUtil.isDatabaseObsolete(RepositoryUtil.java:32)
	at mage.cards.repository.CardRepository.<init>(CardRepository.java:51)
	at mage.cards.repository.CardRepository.<clinit>(CardRepository.java:29)
	at mage.cards.repository.RepositoryUtil.bootstrapLocalDb(RepositoryUtil.java:28)
	at mage.server.Main.main(Main.java:94)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:103)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:83)
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:114)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:447)
	... 16 more
INFO  2019-07-15 21:08:25,882 Done.                                                                                      =>[main] Main.main
INFO  2019-07-15 21:08:25,883 Loading extension packages...                                                              =>[main] Main.main
INFO  2019-07-15 21:08:25,883 Done.                                                                                      =>[main] Main.main
INFO  2019-07-15 21:08:25,884 Loading cards...                                                                           =>[main] Main.main
Exception in thread "main" java.lang.NullPointerException
	at mage.cards.repository.ExpansionRepository.getSetByCode(ExpansionRepository.java:171)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:35)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:135)

**Comment by michaeldelgado1** [comment]
Issue was worked around by re-installing. Feel free to close this if you are unable get useful information from this.

**Comment by JayDi85** [comment]
`org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.SocketTimeoutException: connect timed out: 10.199.150.78:53894" [90067-197]`

It's can be missing machine name for server's IP in `config.xml` settings (`serverAddress` must be looks up to real machine name/ip) or firewall access problem (put app to new folder helps to reset access settings).
