### ISSUE TITLE
Localhost CannotConnectException: Error setting up client lease upon performing connect.

### ISSUE THREAD

**Issue by Jakub41** [magefree/mage#5934]
Hello,

I'm using xMage on a Mac Mojave 10.14.6 and I'm unable to run localhost.
The error I'm getting in the log as following:
```
WARN  2019-08-12 15:24:00,567 Cannot connect                                                                             =>[SwingWorker-pool-5-thread-3] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:412)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://198.18.10.242:17171/?serializationtype=jboss]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
INFO  2019-08-12 15:24:00,583 Disconnecting DONE                                                                         =>[SwingWorker-pool-5-thread-3] SessionImpl.disconnect 
INFO  2019-08-12 15:24:00,584 Disconnected from user mode                                                                =>[SwingWorker-pool-5-thread-3] MageFrame.disconnected 

```

Please tell me what I can do to resolve this issue 
Thank you

**Comment by JayDi85** [comment]
You must run server from launcher. If it's run fine (server's logs shows "listening") then checks your IP/name settings.

198.18.10.242 -- is that your machine's IP?

**Comment by Jakub41** [comment]
I run from luncher and my IP is 192.168.1.73

**Comment by JayDi85** [comment]
1. Open server's config: `\xmage\mage-server\config\config.xml`
2. Check `serverAddress` -- it's must contains `0.0.0.0`:
![shot_190812_174544](https://user-images.githubusercontent.com/8344157/62869495-082d3500-bd29-11e9-8c42-bdd1a1975f43.png)
3. [Open](https://www.macworld.co.uk/how-to/mac/ping-test-mac-3524076/) `network utility` and try to ping `localhost` address:
![shot_190812_174829](https://user-images.githubusercontent.com/8344157/62869721-6bb76280-bd29-11e9-95a0-102dee882543.png)
4. If you see wrong IP then [edit](https://www.techjunkie.com/edit-hosts-file-mac-os-x/) `/etc/hosts` file and add `127.0.0.1 localhost`

**Comment by Jakub41** [comment]
I see this 
```
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.031 ms
```

**Comment by JayDi85** [comment]
1. Open `client -> preferences -> connection` and remove any proxy settings:
![shot_190812_180225](https://user-images.githubusercontent.com/8344157/62870855-64915400-bd2b-11e9-841f-2c5bd1c46d4f.png)
2. Restart xmage and try connect to `localhost` address (LOCAL button in connection dialog):
![shot_190812_180344](https://user-images.githubusercontent.com/8344157/62870928-8b4f8a80-bd2b-11e9-9320-60de0078fda5.png)

**Comment by Jakub41** [comment]
I have none in proxy and doing that is not working 
<img width="654" alt="Screenshot 2019-08-12 at 16 09 53" src="https://user-images.githubusercontent.com/8559542/62871382-b03c0180-bd1b-11e9-80d7-2e71f052d2de.png">

**Comment by JayDi85** [comment]
1. Close xmage;
2. Delete client logs file: `\xmage\mage-client\mageclient.log`
3. Delete server logs file: `\xmage\mage-server\mageserver.log`
4. Run luancher;
5. Run client and server from launcher;
6. Wait 1 minute and try connect to `localhost`;
7. If not works then close client and server and show me logs from that TWO files (you can upload it to https://pastebin.com/ :
   * Client: `\xmage\mage-client\mageclient.log`
   * Server: `\xmage\mage-server\mageserver.log`

**Comment by Jakub41** [comment]
Still not working and sharing the logs:
https://pastebin.com/MKLEyD2b
https://pastebin.com/8FXXwLrL

**Comment by JayDi85** [comment]
Server logs fine, clients logs shows unknown IP.

1. Can you connect to xmage.de or beta server?
2. Open network [utilities -> lookup](http://guide.hosting-advantage.com/Advanced/Ping_and_Nslookup_with_Mac_OS_X.htm) and check IP `198.18.10.242` -- what's it?

**Comment by Jakub41** [comment]
Yes I can but I cannot only localhost

This is the response
```
198.18.10.242 -> The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 2.)
```

**Comment by JayDi85** [comment]
1. Try connect to 127.0.0.1 instead localhost
2. Try connect to your local ip instead localhost

**Comment by Jakub41** [comment]
With 127.0.0.1 worked :D Thanks

**Comment by JayDi85** [comment]
The reason: file '/etc/hosts' contains wrong settings. You can open editor and delete line with wrong IP (replace it with 127.0.0.1 localhost):
https://www.techjunkie.com/edit-hosts-file-mac-os-x/

**Comment by Jakub41** [comment]
Thanks so much I didn't know about it. I will make the changes then as suggested :smile:
