### ISSUE TITLE
Can't launch Mage.Client through eclipse

### ISSUE THREAD

**Issue by adozaraz** [magefree/mage#6030]
Have problem with launching mage through eclipse. When i launch, this happens:
```
INFO  2019-11-05 21:20:12,666 Starting MAGE client version 1.4.39V0 (build: runtime)                                     =>[main] MageFrame.main 
INFO  2019-11-05 21:20:12,669 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2019-11-05 21:20:13,906 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2019-11-05 21:20:18,447 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2019-11-05 21:20:19,880 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-11-05 21:20:19,931 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2019-11-05 21:20:19,940 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2019-11-05 21:20:19,943 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2019-11-05 21:20:19,943 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
FATAL 2019-11-05 21:20:20,513 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.table.TablesPanel.setTableFilter(TablesPanel.java:805)
	at mage.client.table.TablesPanel.restoreFilters(TablesPanel.java:597)
	at mage.client.table.TablesPanel.<init>(TablesPanel.java:346)
	at mage.client.table.TablesPane.<init>(TablesPane.java:23)
	at mage.client.MageFrame.<init>(MageFrame.java:268)
	at mage.client.MageFrame.lambda$9(MageFrame.java:1303)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
System: Windows 10
Java: jdk1.8.0_231
This kind of problem also happens in NetBeans

**Comment by JayDi85** [comment]
There were missing code from Pioneer format implementation. Fixed it by 4ab598a7c906f32a1f6416b2d3f9af4935e9a802 You can update your source and rebuild -- all works fine now.
