### ISSUE TITLE
Connecting to a server with other card base brings up "unable to connect to server".

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#605]
Problem shpould be handled in another way, allowing to connect.

![carddatabase](https://cloud.githubusercontent.com/assets/2066790/4697126/a870668a-5821-11e4-96ce-bd34366bd7e3.jpg)

```
DEBUG 2014-10-20 08:21:19,563 connecting: None null 0                                                                    =>[AWT-EventQueue-0] ConnectDialog.btnConnectActionPerformed 
FATAL 2014-10-20 08:21:36,941 error                                                                                      =>[SwingWorker-pool-4-thread-7] RegularObjectPersister.writeSlotWithMethod 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithMethod(RegularObjectPersister.java:120)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:86)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ArrayPersister.saveObjectArray(ArrayPersister.java:110)
    at org.jboss.serial.persister.ArrayPersister.writeData(ArrayPersister.java:101)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.io.JBossObjectOutputStream.writeObjectOverride(JBossObjectOutputStream.java:181)
    at java.io.ObjectOutputStream.writeObject(Unknown Source)
    at org.jboss.remoting.serialization.impl.jboss.JBossSerializationManager.sendObject(JBossSerializationManager.java:133)
    at org.jboss.remoting.marshal.serializable.SerializableMarshaller.write(SerializableMarshaller.java:120)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.versionedWrite(MicroSocketClientInvoker.java:1347)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:885)
    at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
    at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
    at org.jboss.remoting.Client.invoke(Client.java:2084)
    at org.jboss.remoting.Client.invoke(Client.java:879)
    at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
    at com.sun.proxy.$Proxy10.getMissingCardsData(Unknown Source)
    at mage.remote.SessionImpl.updateDatabase(SessionImpl.java:326)
    at mage.remote.SessionImpl.connect(SessionImpl.java:289)
    at mage.remote.SessionImpl.connect(SessionImpl.java:131)
    at mage.client.MageFrame.connect(MageFrame.java:677)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:333)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:323)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(Unknown Source)
    at java.net.SocketOutputStream.write(Unknown Source)
    at org.jboss.remoting.transport.socket.TimedOutputStream.write(TimedOutputStream.java:122)
    at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
    at java.io.BufferedOutputStream.write(Unknown Source)
    at java.io.DataOutputStream.write(Unknown Source)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.write(DataContainer.java:226)
    at org.jboss.serial.util.StringUtil.saveString(StringUtil.java:86)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.saveImmutable(DataContainer.java:295)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:149)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ObjectOutputStreamProxy.writeObjectOverride(ObjectOutputStreamProxy.java:60)
    at java.io.ObjectOutputStream.writeObject(Unknown Source)
    at java.util.ArrayList.writeObject(Unknown Source)
    ... 47 more
FATAL 2014-10-20 08:21:36,957 Unable to connect to server -                                                              =>[SwingWorker-pool-4-thread-7] SessionImpl.connect 
java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy10.getMissingCardsData(Unknown Source)
    at mage.remote.SessionImpl.updateDatabase(SessionImpl.java:326)
    at mage.remote.SessionImpl.connect(SessionImpl.java:289)
    at mage.remote.SessionImpl.connect(SessionImpl.java:131)
    at mage.client.MageFrame.connect(MageFrame.java:677)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:333)
    at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:323)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.remoting.InvocationFailureException: Unable to perform invocation; nested exception is: 
    java.io.IOException
    at org.jboss.remoting.transport.socket.SocketClientInvoker.handleException(SocketClientInvoker.java:146)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.handleOtherException(MicroSocketClientInvoker.java:1104)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:966)
    at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
    at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
    at org.jboss.remoting.Client.invoke(Client.java:2084)
    at org.jboss.remoting.Client.invoke(Client.java:879)
    at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
    ... 13 more
Caused by: java.io.IOException
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithMethod(RegularObjectPersister.java:129)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:86)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ArrayPersister.saveObjectArray(ArrayPersister.java:110)
    at org.jboss.serial.persister.ArrayPersister.writeData(ArrayPersister.java:101)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithFields(RegularObjectPersister.java:182)
    at org.jboss.serial.persister.RegularObjectPersister.defaultWrite(RegularObjectPersister.java:90)
    at org.jboss.serial.persister.RegularObjectPersister.writeData(RegularObjectPersister.java:62)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:276)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.io.JBossObjectOutputStream.writeObjectOverride(JBossObjectOutputStream.java:181)
    at java.io.ObjectOutputStream.writeObject(Unknown Source)
    at org.jboss.remoting.serialization.impl.jboss.JBossSerializationManager.sendObject(JBossSerializationManager.java:133)
    at org.jboss.remoting.marshal.serializable.SerializableMarshaller.write(SerializableMarshaller.java:120)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.versionedWrite(MicroSocketClientInvoker.java:1347)
    at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:885)
    ... 18 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.jboss.serial.persister.RegularObjectPersister.writeSlotWithMethod(RegularObjectPersister.java:120)
    ... 42 more
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(Unknown Source)
    at java.net.SocketOutputStream.write(Unknown Source)
    at org.jboss.remoting.transport.socket.TimedOutputStream.write(TimedOutputStream.java:122)
    at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
    at java.io.BufferedOutputStream.write(Unknown Source)
    at java.io.DataOutputStream.write(Unknown Source)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.write(DataContainer.java:226)
    at org.jboss.serial.util.StringUtil.saveString(StringUtil.java:86)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.saveImmutable(DataContainer.java:295)
    at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.describeObject(ObjectDescriptorFactory.java:149)
    at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectOutput.writeObject(DataContainer.java:206)
    at org.jboss.serial.persister.ObjectOutputStreamProxy.writeObjectOverride(ObjectOutputStreamProxy.java:60)
    at java.io.ObjectOutputStream.writeObject(Unknown Source)
    at java.util.ArrayList.writeObject(Unknown Source)
    ... 47 more
INFO  2014-10-20 08:21:36,957 DISCONNECT still connected                                                                 =>[SwingWorker-pool-4-thread-7] SessionImpl.disconnect 
INFO  2014-10-20 08:21:55,452 Disconnected ...                                                                           =>[SwingWorker-pool-4-thread-7] SessionImpl.disconnect 
INFO  2014-10-20 08:21:55,452 DISCONNECTED (NO Event Dispacth Thread)      
```

A new connect try brings up this error:

```
INFO  2014-10-20 08:25:00,661 Found server: localhost -> connect to your local server (must be started):localhost:17171  =>[AWT-EventQueue-0] ConnectDialog.findPublicServerActionPerformed 
FATAL 2014-10-20 08:25:58,681 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.hash(Unknown Source)
    at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
    at mage.server.SessionManager.extendUserSession(SessionManager.java:212)
    at mage.server.MageServerImpl.ping(MageServerImpl.java:354)
    at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
    at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
    at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
    at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
    at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
    at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
    at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
    at org.jboss.remoting.Client.invoke(Client.java:2084)
    at org.jboss.remoting.Client.invoke(Client.java:879)
    at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
    at com.sun.proxy.$Proxy8.ping(Unknown Source)
    at mage.remote.SessionImpl.ping(SessionImpl.java:1364)
    at mage.client.MageFrame$2.run(MageFrame.java:215)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by JayDi85** [comment]
It's data reflection problem between different versions, not db (e.g. there were changes in sterilizable classes). Not actual any more.
