### ISSUE TITLE
Questing Beast - ClassCastException for GameEvent

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6116]
Questing Beast uses `PREVENT_DAMAGE` event, but it's simple event and haven't any info about Damage Event or combat info.
```
java.lang.ClassCastException: mage.game.events.GameEvent cannot be cast to mage.game.events.DamageEvent
        at mage.cards.q.QuestingBeastPreventionEffect.applies(QuestingBeast.java:104)
        at mage.abilities.effects.ContinuousEffects.preventedByRuleModification(ContinuousEffects.java:739)
        at mage.game.GameState.replaceEvent(GameState.java:714)
        at mage.game.GameState.replaceEvent(GameState.java:710)
        at mage.game.GameImpl.replaceEvent(GameImpl.java:2617)
        at mage.game.GameImpl.preventDamage(GameImpl.java:2642)
        at mage.abilities.effects.PreventionEffectImpl.preventDamageAction(PreventionEffectImpl.java:77)
        at mage.abilities.effects.PreventionEffectImpl.replaceEvent(PreventionEffectImpl.java:91)
        at mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:850)
        at mage.game.GameState.replaceEvent(GameState.java:717)
```

**Comment by JayDi85** [comment]
Fixed via 9cf1ee2f426ebd7ed83bf6c324f3b9cd03a0e16f
