### ISSUE TITLE
Adding OpenJDK 11 compatibility

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6197]
Hi,

After opening (and closing) #6185, I tried to see what classes need to be changed to be able to gain this.

So I run `jdeps` on all of the game JARs (both client and server) to find uses of deprecated/deleted JDK classes. (See command invocation at the bottom of this message.)

I found only one class in this situation:
- [ ] mage.watchers.Watcher (uses the deleted class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl)

The problematic commit is https://github.com/magefree/mage/commit/1a8723697ec547f4c9659dc61a0dc876f05dcf90

According to https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/, it could be that PrameterizedTypeImpl could be well replaced by its interface, ParameterizedType. Finally, according to [the official Migration Guide](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.javadoc/jdk/javadoc/doclet/package-summary.html#migration), the replacement for this class is javax.lang.model.type.DeclaredType.

@ingmargoudt Whereas I am not very experienced in this, the switch does not seem too dificult. I could try implementing the switch myself, if I can get some mentoring.

```
% jdeps --jdk-internals mage-1.4.42.jar
mage-1.4.42.jar -> java.base
   mage.watchers.Watcher                              -> sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl JDK internal API (java.base)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are
subject to be removed or changed incompatibly and could break your application.
Please modify your code to eliminate dependence on any JDK internal APIs.
For the most recent update on JDK internal API replacements, please check:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

JDK Internal API                         Suggested Replacement
----------------                         ---------------------
sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl Removed. See http://openjdk.java.net/jeps/260
```

**Comment by JayDi85** [comment]
There are must be another problems too. New watcher code was introduced month ago, but people can't run xmage under java 9+ many years.

**Comment by allentiak** [comment]
I'm sure this is not the only problem. I just suggested a starting point...

**Comment by JayDi85** [comment]
I came up with the idea that the old compatibility problem with java 9+ in different client/server java, not in code compatibility itself (well, except that watcher warning). Xmage uses object's binary serialization for client-server data transfer -- so it can fail on wrong java objects (e.g. server under java 8, but client under java 9). As example: if serialization fail then client can't receive data from server and user will see empty hand on game start.

**Comment by allentiak** [comment]
I am referring to a different thing: being able to run both the client and server under OpenJDK 11.
(Let's remember that XMage can currently run only on an old, unsupported Java 8 Oracle build...)

**Comment by allentiak** [comment]
#6830 has been merged! (It closes #6256.)

**Comment by allentiak** [comment]
@JayDi85, @Craigacp: After your comments, I came up with a migration roadmap towards achieving OpenJDK11+ compatibility. Could you please tell me your thoughts?

***********************************

I have been checking the dependencies from the project: they are... _arcane_. E.g. JBoss 4.2.2 GA is from... 2010!
So, in order to update everything, I think we will have to divide this process into (at least) three stages:

1. Update all XMage dependencies to their latest Oracle JDK8-supporting versions. As these updates would be non-breaking, they could be easily merged and released with future XMage versions.

2. Update all dependencies to their latest OpenJDK8-supporting versions + Allow the Launcher to use an already-insalled OpenJDK8 + OpenJFX8 installation (#6462).
Let's remember that, whereas JavaFX is bundled with Oracle JDK8, it is not with official OpenJDK builds. As an Oracle JDK8 drop-in replacement, maybe we could try using Zulu Community[1]? (An OpenJDK8 + OpenJFX8 build.)

3. (Only once all prior steps have been achieved!) Update the deps and refactor the code to be compatible with OpenJDK 11+.

***************

[1] Zulu Community claims to provide fully free OpenJDK8+OpenJFX8 binaries for all major XMage platforms:
- Windows 2008R2+,
- MacOS 10.13+,
- 64-bits GNU/Linux

https://www.azul.com/downloads/zulu-community/?version=java-8-lts&package=jdk-fx

**Comment by allentiak** [comment]
BTW: the only functionality that depends on JavaFX is the What's New dialog...
Maybe could it be modified so it does not use it anymore? This may allow to run the game under OpenJDK8...

**Comment by SpeedProg** [comment]
Please don't, it would make all my work on getting openjfx11 with webkit built for my system naught ;).
Is it really the only thing using javafx ? Like none of the GUI uses it?
Probably would be a good idea to get rid of it then.

**Comment by Craigacp** [comment]
One issue with OpenJFX8 is that no-one is maintaining it. I think OpenJFX 11 is the earliest version that is being actively maintained.

**Comment by allentiak** [comment]
Thanks for your comment, Adam!


On Mon, 4 May 2020 at 16:05, Adam Pocock wrote:

> One issue with OpenJFX8 is that no-one is maintaining it.
>

In the same way, Oracle JDK8 has been declared "unsupported" for non-Oracle
subscribers around two years ago, and not publicly available more than a
year ago -yet XMage still depends on it...



> I think OpenJFX 11 is the earliest version that is being actively
> maintained.
>
I agree. As I said, this is just a proposal for a roadmap towards full
OpenJFX + OpenJDK compatibility :-)

**Comment by Craigacp** [comment]
Upgrading the jboss dependencies is the core issue, and I don't think it will be possible without extensive code changes as the jboss remoting package is very different between v2 and v3. I couldn't find any documentation about the changes either, and the latest version is v5 which is basically considered as for internal use by Wildfly.

I'm fairly sure that the rest of the code will be fine on Java 11 once the jboss stuff is sorted, as it's not doing anything particularly fancy with class loading or serialization (which is what causes the jboss issues).

**Comment by allentiak** [comment]
@JayDi85 
Should we pin this issue, so it's visible? Perhaps that could be a way of getting more hands to help here...

**Comment by SpeedProg** [comment]
I am not sure if it is even needed to update jboss for jdk11. I have the server running under jdk11 and client with java 8 and everything works fine (like I can play against bot etc).
If I run the client on openjdk11 + openjfx11 (with some slight modifications like fixing the theme class name) it starts up fine but when I try to join a game the game view does not show up.

**Comment by Craigacp** [comment]
I get an exception thrown when I try to create a game, which comes out of the serialization infrastructure.

```FATAL 2020-05-01 22:38:45,210 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy11.getRoomChatId(Unknown Source)
	at mage.remote.SessionImpl.getRoomChatId(SessionImpl.java:650)
	at mage.client.SessionHandler.getRoomChatId(SessionHandler.java:278)
	at mage.client.table.TablesPanel.showTables(TablesPanel.java:699)
	at mage.client.table.TablesPane.showTables(TablesPane.java:51)
	at mage.client.MageFrame.prepareAndShowTablesPane(MageFrame.java:1140)
	at mage.client.dialog.ConnectDialog$ConnectTask.done(ConnectDialog.java:702)
<snip>
Caused by: org.jboss.remoting.InvocationFailureException: Unable to perform invocation; nested exception is: 
	org.jboss.serial.exception.SerializationException: Could not create instance of java.util.Optional - java.util.Optional
	at org.jboss.remoting.transport.socket.SocketClientInvoker.handleException(SocketClientInvoker.java:146)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.handleOtherException(MicroSocketClientInvoker.java:1104)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:966)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	... 35 more
Caused by: org.jboss.serial.exception.SerializationException: Could not create instance of java.util.Optional - java.util.Optional
	at org.jboss.serial.classmetamodel.ClassMetaData.newInstance(ClassMetaData.java:342)
	at org.jboss.serial.persister.RegularObjectPersister.readData(RegularObjectPersister.java:239)
	at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.readObjectDescriptionFromStreaming(ObjectDescriptorFactory.java:412)
	at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.objectFromDescription(ObjectDescriptorFactory.java:82)
	at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectInput.readObject(DataContainer.java:643)
	at org.jboss.serial.persister.RegularObjectPersister.readSlotWithFields(RegularObjectPersister.java:353)
	at org.jboss.serial.persister.RegularObjectPersister.defaultRead(RegularObjectPersister.java:273)
	at org.jboss.serial.persister.RegularObjectPersister.readData(RegularObjectPersister.java:241)
	at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.readObjectDescriptionFromStreaming(ObjectDescriptorFactory.java:412)
	at org.jboss.serial.objectmetamodel.ObjectDescriptorFactory.objectFromDescription(ObjectDescriptorFactory.java:82)
	at org.jboss.serial.objectmetamodel.DataContainer$DataContainerDirectInput.readObject(DataContainer.java:643)
	at org.jboss.serial.io.JBossObjectInputStream.readObjectOverride(JBossObjectInputStream.java:163)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:490)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:457)
	at org.jboss.remoting.serialization.impl.jboss.JBossSerializationManager.receiveObject(JBossSerializationManager.java:189)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.read(SerializableUnMarshaller.java:123)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.versionedRead(MicroSocketClientInvoker.java:1323)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:932)
	... 40 more
Caused by: java.lang.InstantiationException: java.util.Optional
	at java.base/java.lang.Class.newInstance(Class.java:598)
	at org.jboss.serial.classmetamodel.ClassMetaData.newInstance(ClassMetaData.java:334)
	... 57 more
Caused by: java.lang.NoSuchMethodException: java.util.Optional.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3427)
	at java.base/java.lang.Class.newInstance(Class.java:585)
	... 58 more```

**Comment by JayDi85** [comment]
EU, US and beta servers works on OpenJDK8 all the time -- it works fine with Oracle's and OpenJDK's clients. Also I tested jdk+jfx pack from [zulu source](https://www.azul.com/downloads/zulu-community/?version=java-8-lts&package=jdk-fx) -- it works fine too. But it needs some repack to support backward compatibility with oracle's jdk in xmage's launcher (as example: macos archive have different structure).

For next release I'll try to change default java from oracle to openjdk in launcher settings.

**Comment by allentiak** [comment]
On Thu, 7 May 2020 at 11:50, Oleg Agafonov <notifications@github.com> wrote:

> For next release I'll try to change default java from oracle to openjdk in
> launcher settings.


Cool!

**Comment by Craigacp** [comment]
One thing to note is that OpenJDK 8 and Oracle JDK 8 use different rendering pipelines. They were unified in Java 9 (https://openjdk.java.net/jeps/265).

**Comment by allentiak** [comment]
Thanks for that data, @Craigacp !
From what you say, I get that we either support _both_ Oracle's JDK 8 _and_ OpenJDK 8, or we settle with OpenJDK 11+?

**Comment by SpeedProg** [comment]
Optionals should never make it into serializations anyway, so if that is happening that's an other thing that would be good to get rid of :/

**Comment by Craigacp** [comment]
I assume it's a remote method call that returns an optional, hence it's serialised over the wire.

**Comment by allentiak** [comment]
Closes #6652

**Comment by JayDi85** [comment]
[Original problem](https://stackoverflow.com/a/53824670/1276632) of xml packages compile in missing `module-info.java` files -- new Java 9+ modules system. Project must be migrated to it.

**Comment by allentiak** [comment]
> Project must be migrated to it.

Eventually, yes.

For now, https://github.com/magefree/mage/commit/1764f13b96e64a8db8a553a037d65a3eabd72129 makes this work as-is.

**Comment by ldeluigi** [comment]
Done this:

> Update the Launcher so it does allow to use a local JDK/JRE, instead of an old, unsopported Oracle JDK8

Here: https://github.com/magefree/Launcher/pull/14

**Comment by JayDi85** [comment]
Current code base and release builds fully support any java version, see https://github.com/magefree/mage/issues/12768#issuecomment-2348667587 for run instructions and compatibility matrix. But there are some active TODOs (see starting comment) for better and simpler install/launch steps.

**Comment by xenohedron** [comment]
@JayDi85 
Given that the `--add-opens=java.base/java.io=ALL-UNNAMED` works for running client/server on java 21, what's actually stopping us from moving to a modern JDK?

**Comment by JayDi85** [comment]
See related issues and lists, compatibility problems with clients and launcher, netbeans and forms upgrade, jdk downloads, and many others.

**Comment by xenohedron** [comment]
That's not a good answer.
- Launcher - just need update to use system java and add-opens param
- Netbeans forms - not actually needed for functionality. while migrating to something else would maybe aid development of those dialog interfaces, I don't see how having ancient netbeans version actually helps, just needs to be reworked anyway
- Jdk downloads - these appear free on website either openjdk or oracle

**Comment by JayDi85** [comment]
Nope, xmage must use standard app lifecycle with stable and same java versions for better compatibility and support. Run under system's java is optional, not default.

**Comment by Jmlundeen** [comment]
from my own experimentation, JBoss is the only thing that seems to prevent the project from moving into a modern JDK. I haven't tried updating JBoss, but replacing it with web-sockets allowed me to use JDK 21+ for the client and server.
