### ISSUE TITLE
Crash on linux

### ISSUE THREAD

**Issue by andreacosta** [magefree/mage#6263]
I'm using xmage on Linux (Arch Linux) and from last update i have many crash, sometimes just after start it other times during a game. I checked CPU/RAM usage but i not see somethings strange (like spikes).
Anyone have the same issue?
The problem could be on Arch and not on xMage, i open this issue just to know if anyone has the same issue.

**Comment by JayDi85** [comment]
1. Delete logs `\xmage\mage-client\mageclient.log`
2. Run game until crashes;
3. Report game logs from that file.

**Comment by andreacosta** [comment]
`INFO  2020-02-06 13:22:40,786 Logging: DONE                                                                              =>[SwingWorker-pool-5-thread-2] SessionImpl$4.work
INFO  2020-02-06 13:22:40,787 Disconnecting...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect
INFO  2020-02-06 13:22:40,968 Disconnecting DONE                                                                         =>[AWT-EventQueue-0] SessionImpl.disconnect
INFO  2020-02-06 13:22:40,969 Disconnected from remote task                                                              =>[AWT-EventQueue-0] MageFrame.disconnected
INFO  2020-02-06 13:22:46,908 Game c0d44d33-9acb-43b5-a398-868c2007dcbc started for player c1f3b5b0-f224-4bfe-a430-29824b34ffdc =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted
FATAL 2020-02-06 13:23:03,247 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle
java.lang.NullPointerException
        at mage.client.table.TablesPanel.btnNewTableActionPerformed(TablesPanel.java:1645)
        at mage.client.table.TablesPanel.access$900(TablesPanel.java:62)
        at mage.client.table.TablesPanel$14.actionPerformed(TablesPanel.java:1014)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)`

**Comment by JayDi85** [comment]
There are must be more logs and errors before. Show me full log file. You can upload it to https://pastebin.com/ or send to my email: jaydi85@gmail.com

**Comment by andreacosta** [comment]
I send the log file to you

**Comment by JayDi85** [comment]
I don't see any problems in your logs. You've got that error message with `btnNewTableActionPerformed` -- cause not connected to server. I also research de-server logs and found info about frequent connection problem with your account. I recommend to check your network settings. Maybe it's VPN (xmage need stable connection and some VPN can broke it).

**Comment by andreacosta** [comment]
Yesterday we had some problems with modem and internet connection, maybe the problem could be this. In next days i'll check it.
Thanks for the support.

**Comment by Zerrisx** [comment]
Has this been resolved?
