### ISSUE TITLE
Non-Creature Tokens causing server crash against AI player on remote server, not on local.

### ISSUE THREAD

**Issue by rgthigpen** [magefree/mage#6331]
When playing in a game against the AI, I get the following exception anytime there is a non-creature token on the battlefield. Note that this only happens on my remote linux server, not on my local windows PC. 

This is likely due to the fact that Tokens are explicitly not setting a rarity as noted in Card.java, and then the code is force reading Rarity as part of getCardDefinitionScore()

```
FATAL 2020-03-05 15:21:17,337 Game exception gameId: 7e84be9f-f92b-4551-bbed-da7d9045283d                                =>[GAME 7e84be9f-f92b-4551-bbed-da7d9045283d] GameImpl.playPriority
java.lang.NullPointerException
        at mage.player.ai.ma.ArtificialScoringSystem.getCardDefinitionScore(ArtificialScoringSystem.java:46)
        at mage.player.ai.ma.ArtificialScoringSystem.getFixedPermanentScore(ArtificialScoringSystem.java:52)
        at mage.player.ai.GameStateEvaluator2.evaluatePermanent(GameStateEvaluator2.java:104)
        at mage.player.ai.ComputerPlayer6.printOutState(ComputerPlayer6.java:143)
        at mage.player.ai.ComputerPlayer6.printOutState(ComputerPlayer6.java:109)
        at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:73)
        at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
        at mage.game.GameImpl.playPriority(GameImpl.java:1292)
        at mage.game.turn.Step.priority(Step.java:61)
        at mage.game.turn.Phase.playStep(Phase.java:184)
        at mage.game.turn.Phase.play(Phase.java:89)
        at mage.game.turn.Turn.play(Turn.java:126)
        at mage.game.GameImpl.playTurn(GameImpl.java:889)
        at mage.game.GameImpl.play(GameImpl.java:798)
        at mage.game.GameImpl.start(GameImpl.java:762)
        at mage.server.game.GameWorker.call(GameWorker.java:34)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
FATAL 2020-03-05 15:21:17,337 Game exception                                                                             =>[GAME 7e84be9f-f92b-4551-bbed-da7d9045283d] GameImpl.playPriority
mage.MageException: Iterated player priority after game exception too often, game ends!
        at mage.game.GameImpl.playPriority(GameImpl.java:1336)
        at mage.game.turn.Step.priority(Step.java:61)
        at mage.game.turn.Phase.playStep(Phase.java:184)
        at mage.game.turn.Phase.play(Phase.java:89)
        at mage.game.turn.Turn.play(Turn.java:126)
        at mage.game.GameImpl.playTurn(GameImpl.java:889)
        at mage.game.GameImpl.play(GameImpl.java:798)
        at mage.game.GameImpl.start(GameImpl.java:762)
        at mage.server.game.GameWorker.call(GameWorker.java:34)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by rgthigpen** [comment]
Thank you kindly.
