### ISSUE TITLE
AI: NPE at mage.player.ai.ma.ArtificialScoringSystem.getCardDefinitionScore(ArtificialScoringSystem.java:46)

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#6357]
I did a test game to test a new self-hosted XMage server and got this error in a Commander match versus 3 AIs:

```
FATAL 2020-03-20 18:33:18,813 Game exception gameId: 20712cae-1d0f-455f-8e64-6f39161b7af6                                =>[GAME 20712cae-1d0f-455f-8e64-6f39161b7af6] GameImpl.playPriority 
java.lang.NullPointerException
	at mage.player.ai.ma.ArtificialScoringSystem.getCardDefinitionScore(ArtificialScoringSystem.java:46)
	at mage.player.ai.ma.ArtificialScoringSystem.getFixedPermanentScore(ArtificialScoringSystem.java:52)
	at mage.player.ai.GameStateEvaluator2.evaluatePermanent(GameStateEvaluator2.java:104)
	at mage.player.ai.ComputerPlayer6.printOutState(ComputerPlayer6.java:143)
	at mage.player.ai.ComputerPlayer6.printOutState(ComputerPlayer6.java:107)
	at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:73)
	at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
	at mage.game.GameImpl.playPriority(GameImpl.java:1292)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:126)
	at mage.game.GameImpl.playTurn(GameImpl.java:889)
	at mage.game.GameImpl.play(GameImpl.java:798)
	at mage.game.GameImpl.start(GameImpl.java:762)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This repeated some times, before the table got killed by the Server.

Full excerpt from the `mageserver.log`:
[game_crash.log.zip](https://github.com/magefree/mage/files/4361106/game_crash.log.zip)

If there is anything more I need provide, I’ll do so.

XMage version: 1.4.42V6

**Comment by JayDi85** [comment]
Was fixed in prev release by cb8d4dc340f06487a2eda83406e2cd671bba881f
