### ISSUE TITLE
Server saveGame: NotSerializableException for LondonMulligan

### ISSUE THREAD

**Issue by Elandril** [magefree/mage#6420]
Saving games on the server causes the following error to occur on games with the London Mulligan:

FATAL 2020-04-15 04:04:38,537 Cannot save game.
java.io.NotSerializableException: mage.game.mulligan.LondonMulligan
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at mage.server.game.GameController.saveGame(GameController.java:924)
        at mage.server.game.GameManager.saveGame(GameManager.java:162)
        at mage.server.TableController.endGameAndStartNextGame(TableController.java:768)
        at mage.server.TableManager.endGame(TableManager.java:293)
        at mage.server.game.GameController.endGame(GameController.java:719)
        at mage.server.game.GameController.gameResult(GameController.java:908)
        at mage.server.game.GameWorker.call(GameWorker.java:36)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed via 10348faaec492e2a31f00384a603111d0df1bf45
