### ISSUE TITLE
Server: Update the JBoss/Wildfly serialisation infrastructure (OpenJDK 11+ support)

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6514]
Copying relevant discussion threads from #6394 :

>[I]t seems like the jboss serialisation infrastructure isn't happy with Java 11, and probably all needs upgrading (as while the server and client could talk to each other, they immediately died when I tried to create a match).

_Originally posted by @Craigacp in https://github.com/magefree/mage/pull/6394#issuecomment-622653539_

>It looks like the jboss remoting v2 library isn't part of Wildfly which is the new open source project for jboss related things, and also that the jboss remoting v2 library has a completely different API to the jboss remoting v3 library which is in wildfly. I've never used any of these things so it would be good to get some help from someone who understands anything about this remoting stuff. I've built distributed Java systems before, but they used RMI & Jini/Apache River, not jboss.

_Originally posted by @Craigacp in https://github.com/magefree/mage/pull/6394#issuecomment-622656610_

>The newer version of jboss remoting is basically undocumented and doesn't support general purpose RPC calls except for EJB things.

_Originally posted by @Craigacp in https://github.com/magefree/mage/pull/6394#issuecomment-623135687_

>JBoss Remoting supports custom serialization engine. So jboss's serialization can be replaced by java's or other implementation. See docs on [5.5. Marshalling](https://docs.jboss.org/jbossremoting/2.5.3/html_single/#d0e2822).

_Originally posted by @JayDi85 in https://github.com/magefree/mage/pull/6394#issuecomment-623137617_

>I believe so. There might be a set of command line arguments that let the jboss serialisation engine into the java.base module, but that's not a sustainable solution. Currently I get an error message out of the serialisation infrastructure saying it can't call "Optional.\<init\>", i.e. the constructor of optional (which it shouldn't be doing as optional has private constructors). That might be mitigated by allowing the unnamed module (i.e. the regular classpath) to have reflective access into java.base.
>
>It does raise the question why an optional is being stored as a field, which I couldn't find apart from inside the SoftValuesLoadingCache, but that doesn't seem to be transmitted anywhere.

_Originally posted by @Craigacp in https://github.com/magefree/mage/pull/6394#issuecomment-623146587_

**Comment by SpeedProg** [comment]
So I looked into this and after changing the RPC to not use optionals. The communication seem to work quite fine, except for when the server uses callback to the client.
You get this:
`java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1535)
	at org.jboss.util.threadpool.BasicThreadPool.setMaximumPoolSize(BasicThreadPool.java:335)
	at org.jboss.remoting.ServerInvoker.getOnewayThreadPool(ServerInvoker.java:607)
	at org.jboss.remoting.ServerInvoker.handleOnewayInvocation(ServerInvoker.java:2164)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:937)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1535)
	at org.jboss.util.threadpool.BasicThreadPool.setMaximumPoolSize(BasicThreadPool.java:335)
	at org.jboss.remoting.ServerInvoker.getOnewayThreadPool(ServerInvoker.java:607)
	at org.jboss.remoting.ServerInvoker.handleOnewayInvocation(ServerInvoker.java:2164)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:937)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)`
Which you will only realize if you set jboss to trace mode (I had no idea how to do that) or step through a lot of deserialization xD.
But the messages and callbacks seem to arrive fine.

**Comment by SpeedProg** [comment]
Okay I found out why this happens. In java 11 they changed the implementation of setCorePoolSize to check if maxPoolSize is bigger or the same.
But the JBoss thing calls setCorePoolSize first and then setMaximumPoolSize

**Comment by SpeedProg** [comment]
I got it running by using a custom thread pool and configuring the invokator to use it instead.
I successfully played a bot game with it.
Server + Client openjdk11 + openjfx11.

I am going to need to clean this up through and them I am going to make a PR.
