### ISSUE TITLE
Trouble building a new clone

### ISSUE THREAD

**Issue by Alchus** [magefree/mage#667]
I have successfully built the project in the past- last week-, but I wiped out some of my source files (by mistake). 

I have re-cloned the repo to a new location on disk and added the project into NetBeans, but after running mage.server.Main.main(); I get a 
java.lang.NoClassDefFoundError: mage/utils/MageVersion
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)

Which I can't explain, because MageVersion is safely tucked in Common project; I haven't touched it.

Any information on how to fix this?

**Comment by emerald000** [comment]
Clean and rebuild the program. That should fix it.

**Comment by LevelX2** [comment]
emerald is right. Lokks for me too like a Clean and build "Mage Root" will fix it.
If not, reopen the issue.
