### ISSUE TITLE
Server Error: Card not found - [CARD NAME] - [SET] for deck - [DECK NAME]

### ISSUE THREAD

**Issue by IKEYMAN** [magefree/mage#669]
I can't play any game. Every format I play shows this error( no matter what deck i play). Even if I change the card version, another card will show up with the error. I did update the card images, the client, and the mana symbols. I even try uninstalling the program and re download it. Here's a pic of the issue

![error 1 6 15](https://cloud.githubusercontent.com/assets/10430839/5641477/b57442b2-95f6-11e4-907b-5018aca59b79.PNG)

**Comment by IKEYMAN** [comment]
Also cannot download 3 card imagess no matter what source I get it from

**Comment by LevelX2** [comment]
This is most probably a db resource problem that seems to happen if some server resources getting short or overloaded.
Looks like the h2 DB requests are no longer handled correctly causing this problem.
Normally after a XMage server restart the problem is gone.
As a workaround the XMage.info server 1 will now be restarted twice a day (07:00 + 19:00 CET) to reduce/minimize this kind of problems until the true causing reason is found and fixed.

And the three missing cards are not available on magiccards.info yet. As sonn as available you can download it.

**Comment by fireshoes** [comment]
I got this error message today on my local server after the card reorganization, so unsure if related. Here is the exception generated.


`FATAL 2016-10-05 13:20:15,950 Server error                                                                               =>[AWT-EventQueue-0] SessionImpl.handleMageException 
mage.MageException: Server error: Card not found - Sinister Concoction - SOI for deck - null
Possible reason is, that you use cards in your deck, that are only supported in newer versions of the server.
So it can help to use the same card from another set, that's already supported from this server.
	at mage.server.MageServerImpl.handleException(MageServerImpl.java:1040)
	at mage.server.MageServerImpl.executeWithResult(MageServerImpl.java:1272)
	at mage.server.MageServerImpl.joinTable(MageServerImpl.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	at com.sun.proxy.$Proxy8.joinTable(Unknown Source)
	at mage.remote.SessionImpl.joinTable(SessionImpl.java:678)
	at mage.client.SessionHandler.joinTable(SessionHandler.java:238)
	at mage.client.table.TablesPanel.btnQuickStartActionPerformed(TablesPanel.java:1289)
	at mage.client.table.TablesPanel.access$1100(TablesPanel.java:107)
	at mage.client.table.TablesPanel$28.actionPerformed(TablesPanel.java:1139)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by fireshoes** [comment]
It also causes a dead table to be created (Waiting for players: 0/2).
