### ISSUE TITLE
No longer able to connect to Local, AI (localhost) with local IntelliJ compile

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6807]
This is a recent change, as it was working before the Jul 7, 2020 code changes.  Likely caused by one of the version updates and/or d6ad722.  Bubba in Discord reported similar issues.

This is with Windows 10, running IntelliJ.

Old Behavior: connecting launches local sever.
New behavior: simply fails to connect.
![image](https://user-images.githubusercontent.com/59861365/86930428-9f973580-c0fc-11ea-99b7-91266e0b3869.png)

**Comment by 18ths** [comment]
Oops.

Caused by: java.lang.NoClassDefFoundError: gnu/trove/TObjectHashingStrategy
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.serial.util.ClassMetaConsts.<clinit>(ClassMetaConsts.java:41)
	at org.jboss.serial.io.JBossObjectInputStream.<clinit>(JBossObjectInputStream.java:56)
	at org.jboss.remoting.serialization.impl.jboss.JBossSerializationManager.createInput(JBossSerializationManager.java:64)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:75)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:58)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createInputStream(ClientSocketWrapper.java:206)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createStreams(ClientSocketWrapper.java:189)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.<init>(ClientSocketWrapper.java:67)
	... 22 more
Caused by: java.lang.ClassNotFoundException: gnu.trove.TObjectHashingStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

These are definitely problems with deps using other deps. Give me 20 minutes.

**Comment by 18ths** [comment]
I decided to revert the whole commit. The exception is saying that it cannot find a particular class in package that was removed, but reverting only those two trove packages didnt seem to make any difference. Strange. Anyway this fixed the issue on my side, let me know if it works on your side too.

**Comment by JayDi85** [comment]
I tested and it works fine in PR. BUT... all dependency changes must be checked on fresh setup from sources. What a fail.

After fresh install I can confirm that client broken. Media player also broken:
* `Couldn't load file: X:\x\xxx.mp3 javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input file`

So that's must be return with additional comments (what it needs for server connection and media player).

![shot_200708_192545](https://user-images.githubusercontent.com/8344157/86938156-28d85780-c151-11ea-928c-6001bb4995c6.png)
![shot_200708_192540](https://user-images.githubusercontent.com/8344157/86938166-2b3ab180-c151-11ea-8c8b-787a17825c17.png)

**Comment by Zerrisx** [comment]
My issue at least is resolved.  JayDi, is there further work that needs to be done here?

**Comment by jeffwadsworth** [comment]
I would assume something needs to be done about the "new" install aspect.  Might as well keep this open until that is resolved.  I would test that, but I don't have access to another system at the moment.

**Comment by JayDi85** [comment]
There's nothing else to do here. Removed libs were important for project so it was reverted. Just keep eye on dependency removes (compiled != works). Fresh "install" is when sources are imported to a new folder and the project is built from them.
