### ISSUE TITLE
Hamletback Goliath little issue

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6882]
this wasn't a issue on gameplay, just that I notice that in the server console there were a bunch of nullpointer exceptions, apparently caused by _Hamletback Goliath_, maybe caused because at one point I reanimated said card from the AI

```
INFO  2020-07-24 00:33:53,342 MATCH started [Game] 3d164b4b-cfee-4236-9b4a-cf5b1dc6eee0(copperfield)                     =>[CALL main-32] TableController.lambda$startMatch$4 
INFO  2020-07-24 00:33:53,979 GAME started 7949bc1f-05cf-4f90-89f4-73e7fdfeca08 [Game] copperfield - Computer 3 - Computer 4 - Computer 2 =>[CALL main-32] TableController.startGame 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:429)
	at mage.player.ai.ComputerPlayer7.calculateActions(ComputerPlayer7.java:113)
	at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:63)
	at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
	at mage.game.GameImpl.playPriority(GameImpl.java:1326)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:126)
	at mage.game.GameImpl.playTurn(GameImpl.java:869)
	at mage.game.GameImpl.play(GameImpl.java:783)
	at mage.game.GameImpl.start(GameImpl.java:768)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at mage.cards.h.HamletbackGoliathTriggeredAbility.checkTrigger(HamletbackGoliath.java:75)
	at mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
	at mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
	at mage.game.GameState.handleEvent(GameState.java:729)
	at mage.game.GameState.handleSimultaneousEvent(GameState.java:717)
	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1778)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:495)
	at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:278)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:501)
	at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:278)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:419)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:416)
	... 4 more
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:429)
	at mage.player.ai.ComputerPlayer7.calculateActions(ComputerPlayer7.java:113)
	at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:63)
	at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
	at mage.game.GameImpl.playPriority(GameImpl.java:1326)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:126)
	at mage.game.GameImpl.playTurn(GameImpl.java:869)
	at mage.game.GameImpl.play(GameImpl.java:783)
	at mage.game.GameImpl.start(GameImpl.java:768)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at mage.cards.h.HamletbackGoliathTriggeredAbility.checkTrigger(HamletbackGoliath.java:75)
	at mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
	at mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
	at mage.game.GameState.handleEvent(GameState.java:729)
	at mage.game.GameState.handleSimultaneousEvent(GameState.java:717)
	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1778)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:495)
	at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:278)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:501)
	at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:278)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:419)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:416)
	... 4 more
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at mage.player.ai.ComputerPlayer6.addActionsTimed(ComputerPlayer6.java:429)
	at mage.player.ai.ComputerPlayer7.calculateActions(ComputerPlayer7.java:113)
	at mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:63)
	at mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
	at mage.game.GameImpl.playPriority(GameImpl.java:1326)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:126)
	at mage.game.GameImpl.playTurn(GameImpl.java:869)
	at mage.game.GameImpl.play(GameImpl.java:783)
	at mage.game.GameImpl.start(GameImpl.java:768)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at mage.cards.h.HamletbackGoliathTriggeredAbility.checkTrigger(HamletbackGoliath.java:75)
	at mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
	at mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
	at mage.game.GameState.handleEvent(GameState.java:729)
	at mage.game.GameState.handleSimultaneousEvent(GameState.java:717)
	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1778)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:495)
	at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:278)
	at mage.player.ai.ComputerPlayer6.simulatePriority(ComputerPlayer6.java:501)
	at mage.player.ai.ComputerPlayer6.addActions(ComputerPlayer6.java:278)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:419)
	at mage.player.ai.ComputerPlayer6$1.call(ComputerPlayer6.java:416)
	... 4 more
INFO  2020-07-24 01:04:34,894 USER REMOVE - copperfield (Disconnected)  userId: 8be67092-7480-4984-a6d9-9ae0d5a63754 []  =>[CALL main-50] UserManager.lambda$null$1 

```

**Comment by JayDi85** [comment]
Fixed via dfaf09e76cff0c01e13c29fba3b7d2ffe07aa2f8
