### ISSUE TITLE
a couple of small issue with the deck editor

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6920]
there was no problem using the deck editor, but I notice the following in the client console:

```
FATAL 2020-07-31 18:32:36,077 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException: 220 >= 28
	at java.util.Vector.elementAt(Vector.java:477)
	at javax.swing.DefaultListModel.getElementAt(DefaultListModel.java:89)
	at mage.client.dialog.CheckBoxList$CheckBoxListModel.setChecked(CheckBoxList.java:483)
	at mage.client.dialog.CheckBoxList.setChecked(CheckBoxList.java:639)
	at mage.client.deckeditor.CardSelector.cbExpansionSetActionPerformed(CardSelector.java:1203)
	at mage.client.deckeditor.CardSelector.access$800(CardSelector.java:50)
	at mage.client.deckeditor.CardSelector$8.actionPerformed(CardSelector.java:654)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
	at mage.client.deckeditor.CardSelector.btnExpansionSearchActionPerformed(CardSelector.java:1401)
	at mage.client.deckeditor.CardSelector.access$1000(CardSelector.java:50)
	at mage.client.deckeditor.CardSelector$10.actionPerformed(CardSelector.java:679)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

and here is another in a different occasion 

```
ERROR 2020-08-01 01:32:33,691                                                                                            =>[Util4] ImageCache.loadImage 
java.lang.NullPointerException
	at java.awt.color.ICC_Profile.intFromBigEndian(ICC_Profile.java:1782)
	at java.awt.color.ICC_Profile.getNumComponents(ICC_Profile.java:1474)
	at sun.java2d.cmm.lcms.LCMSTransform.<init>(LCMSTransform.java:98)
	at sun.java2d.cmm.lcms.LCMS.createTransform(LCMS.java:173)
	at java.awt.color.ICC_ColorSpace.fromRGB(ICC_ColorSpace.java:230)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.setImageData(JPEGImageReader.java:705)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:620)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:492)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:613)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1070)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1050)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at org.mage.plugins.card.images.ImageCache.loadImage(ImageCache.java:489)
	at org.mage.plugins.card.images.ImageCache$1.makeThumbnailByFile(ImageCache.java:177)
	at org.mage.plugins.card.images.ImageCache$1.apply(ImageCache.java:147)
	at org.mage.plugins.card.images.ImageCache$1.apply(ImageCache.java:56)
	at mage.client.util.SoftValuesLoadingCache.lambda$from$0(SoftValuesLoadingCache.java:64)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.ForwardingLoadingCache.get(ForwardingLoadingCache.java:45)
	at mage.client.util.SoftValuesLoadingCache.getOrNull(SoftValuesLoadingCache.java:38)
	at org.mage.plugins.card.images.ImageCache.getImage(ImageCache.java:409)
	at org.mage.plugins.card.images.ImageCache.getThumbnail(ImageCache.java:386)
	at org.mage.card.arcane.CardPanelComponentImpl.lambda$updateArtImage$1(CardPanelComponentImpl.java:732)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by JayDi85** [comment]
For second error -- try to find and delete all zero size zip-files in images folder:
* `\xmage\mage-client\plugins\images`

**Comment by copperfield42** [comment]
I don't use the zip option for the images, use a personalize folder for the images, and just check just in case and there is no a single zip there

**Comment by JayDi85** [comment]
Then check zero size images files. I think some images file is broken so xmage can't load it.

**Comment by copperfield42** [comment]
there is none either, I'm trying to remember what I was doing to reproduce the error again, but nothing so far...
