### ISSUE TITLE
error No such child 17

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6985]
well this one a new one:
![No such child](https://user-images.githubusercontent.com/4504719/90549858-1cd2b300-e15d-11ea-80ca-ae7a8e0f0bc1.PNG)
I finish a game, and nothing out of the ordinary, I got one of the sound, FeedbackNeeded in particular, and the error show up

```
INFO  2020-08-18 11:25:56,371 Game dad20d2d-6d3a-42ef-9c1d-e2c6480af9e3 started for player 68ac96ab-03c6-4afa-b742-e04e27dc5846 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
INFO  2020-08-18 11:49:45,086 Aborting json log sync.                                                                    =>[AWT-EventQueue-0] S3Uploader.upload 
INFO  2020-08-18 11:49:53,186 Ending game...                                                                             =>[pool-9-thread-1] FeedbackPanel.lambda$endWithTimeout$0 
FATAL 2020-08-18 11:49:57,132 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.ArrayIndexOutOfBoundsException: No such child: 17
	at java.awt.Container.getComponent(Container.java:336)
	at javax.swing.JDesktopPane.getAllFrames(JDesktopPane.java:273)
	at javax.swing.JDesktopPane.getAllFrames(JDesktopPane.java:265)
	at mage.client.dialog.MageDialog.isModalDialogActivated(MageDialog.java:36)
	at mage.client.game.GamePanel.isUserImputActive(GamePanel.java:2391)
	at mage.client.game.GamePanel.access$1600(GamePanel.java:57)
	at mage.client.game.GamePanel$12.actionPerformed(GamePanel.java:1902)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:250)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.pumpApprovedKeyEvents(DefaultKeyboardFocusManager.java:921)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:639)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:174)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:89)
	at mage.client.dialog.GameEndDialog.showDialog(GameEndDialog.java:126)
	at mage.client.MageFrame.showGameEndDialog(MageFrame.java:751)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$1(CallbackClientImpl.java:281)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by JayDi85** [comment]
It's a random error, related to [race conditions in multithread app](https://stackoverflow.com/questions/10464233/exception-in-thread-awt-eventqueue-0-java-lang-arrayindexoutofboundsexception). Rare coincidence of circumstances -- F2 were pressed before game end and cause that error. 

I can't reproduce that bug but it can be possible in theory. So until it can be reproduce-able or until it will be raise too often for users -- that issue can be closed.
