### ISSUE TITLE
StackOverflowError 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#6994]
From todays XMage.de server log 

`FATAL 2020-08-23 05:41:21,342 GameWorker general error [635cb83c-998f-4532-a7bb-ac5fa7b151a5] java.lang.StackOverflowError =>[GAME 635cb83c-998f-4532-a7bb-ac5fa7b151a5] GameWorker.call
java.lang.StackOverflowError
	at java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:497)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at mage.abilities.dynamicvalue.common.DevotionCount.checkCost(DevotionCount.java:72)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:456)
	at java.util.stream.IntPipeline.sum(IntPipeline.java:414)
	at mage.abilities.dynamicvalue.common.DevotionCount.calculate(DevotionCount.java:59)
	at mage.cards.n.NykthosDynamicManaEffect.computeMana(NykthosShrineToNyx.java:127)
	at mage.cards.n.NykthosDynamicManaEffect.lambda$getNetMana$0(NykthosShrineToNyx.java:94)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at mage.cards.n.NykthosDynamicManaEffect.getNetMana(NykthosShrineToNyx.java:96)
	at mage.abilities.effects.mana.ManaEffect.getProducableManaTypes(ManaEffect.java:108)
	at mage.abilities.mana.ActivatedManaAbilityImpl.getProducableManaTypes(ActivatedManaAbilityImpl.java:128)
	at mage.MageObjectImpl.getFrameColor(MageObjectImpl.java:176)
	at mage.view.CardView.<init>(CardView.java:490)
	at mage.view.CardView.<init>(CardView.java:219)
	at mage.view.PermanentView.<init>(PermanentView.java:39)
	at mage.view.PlayerView.<init>(PlayerView.java:99)
	at mage.view.GameView.<init>(GameView.java:70)
	at mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:189)
	at mage.server.game.GameSessionWatcher.lambda$update$0(GameSessionWatcher.java:52)
	at java.util.Optional.ifPresent(Optional.java:159)
	at mage.server.game.GameSessionWatcher.update(GameSessionWatcher.java:52)
	at mage.server.game.GameController.updateGame(GameController.java:758)
	at mage.server.game.GameController.lambda$init$3aa0d15c$1(GameController.java:120)
	at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
	at mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:39)
	at mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:2502)
	at mage.players.PlayerImpl.lookAtCards(PlayerImpl.java:1683)
	at mage.abilities.effects.common.continuous.LookAtTopCardOfLibraryAnyTimeEffect.apply(LookAtTopCardOfLibraryAnyTimeEffect.java:45)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:102)
	at mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1116)
	at mage.game.GameState.applyEffects(GameState.java:595)
	at mage.game.GameImpl.applyEffects(GameImpl.java:1534)
	at mage.abilities.AbilityImpl.activate(AbilityImpl.java:228)
	at mage.game.GameImpl.addTriggeredAbility(GameImpl.java:1720)
	at mage.abilities.TriggeredAbilityImpl.trigger(TriggeredAbilityImpl.java:55)
	at mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:98)
	at mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
	at mage.game.GameState.handleEvent(GameState.java:733)
	at mage.game.GameImpl.fireEvent(GameImpl.java:2766)
	at mage.abilities.mana.ManaOptions.checkManaReplacementAndTriggeredMana(ManaOptions.java:135)
	at mage.abilities.mana.ManaOptions.addMana(ManaOptions.java:50)
	at mage.players.PlayerImpl.getManaAvailable(PlayerImpl.java:2949)
	at mage.players.PlayerImpl.getPlayable(PlayerImpl.java:3512)
	at mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:3662)
	at mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:192)
	at mage.server.game.GameSessionWatcher.lambda$update$0(GameSessionWatcher.java:52)
	at java.util.Optional.ifPresent(Optional.java:159)
	at mage.server.game.GameSessionWatcher.update(GameSessionWatcher.java:52)
	at mage.server.game.GameController.updateGame(GameController.java:758)
	at mage.server.game.GameController.lambda$init$3aa0d15c$1(GameController.java:120)
	at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
	at mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:39)
	at mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:2502)
	at mage.players.PlayerImpl.lookAtCards(PlayerImpl.java:1683)
	at mage.abilities.effects.common.continuous.LookAtTopCardOfLibraryAnyTimeEffect.apply(LookAtTopCardOfLibraryAnyTimeEffect.java:45)
...
	at mage.abilities.effects.common.continuous.LookAtTopCardOfLibraryAnyTimeEffect.apply(LookAtTopCardOfLibraryAnyTimeEffect.java:45)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:102)
	at mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1116)
	at mage.game.GameState.applyEffects(GameState.java:595)
	at mage.game.GameImpl.applyEffects(GameImpl.java:1534)
	at mage.abilities.AbilityImpl.activate(AbilityImpl.java:228)
	at mage.game.GameImpl.addTriggeredAbility(GameImpl.java:1720)
	at mage.abilities.TriggeredAbilityImpl.trigger(TriggeredAbilityImpl.java:55)
	at mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:98)
	at mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
	at mage.game.GameState.handleEvent(GameState.java:733)
	at mage.game.GameImpl.fireEvent(GameImpl.java:2766)
	at mage.abilities.mana.ManaOptions.checkManaReplacementAndTriggeredMana(ManaOptions.java:135)
	at mage.abilities.mana.ManaOptions.addMana(ManaOptions.java:50)
	at mage.players.PlayerImpl.getManaAvailable(PlayerImpl.java:2949)
	at mage.players.PlayerImpl.getPlayable(PlayerImpl.java:3512)
	at mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:3662)
	at mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:192)
	at mage.server.game.GameSessionWatcher.lambda$update$0(GameSessionWatcher.java:52)
	at java.util.Optional.ifPresent(Optional.java:159)
	at mage.server.game.GameSessionWatcher.update(GameSessionWatcher.java:52)
	at mage.server.game.GameController.updateGame(GameController.java:758)
	at mage.server.game.GameController.lambda$init$3aa0d15c$1(GameController.java:120)
	at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
	at mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:39)
	at mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:2502)
	at mage.players.PlayerImpl.lookAtCards(PlayerImpl.java:1683)
	at mage.abilities.effects.common.continuous.LookAtTopCardOfLibraryAnyTimeEffect.apply(LookAtTopCardOfLibraryAnyTimeEffect.java:45)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:102)`

**Comment by LevelX2** [comment]
> Found miss code related to `TAPPED_FOR_MANA` (search by `== GameEvent.EventType.TAPPED_FOR_MANA`). Don't know is that related to that bug or to #6698.

Seems ok to me.
That's intended because TapForManaAllTriggeredAbility is no mana abaility and so the "simulated" event have to be ignored. Mana abilities that trigger on the TAPPED_FOR_MANA event have to trigger because exactly that has to be calculated.
