### ISSUE TITLE
Cant connect to any server other than eu.today

### ISSUE THREAD

**Issue by Dingkey420** [magefree/mage#7097]
For tha last week i have been trying to get a game going on the de server, everytime I try to connect it just says Unable connect to server, server is likely offline, on mi launcher i get this log, dont know if that has anything to do 

```
INFO  2020-09-30 16:24:46,682 Connect: connecting to server xmage.de:17171                                               =>[SwingWorker-pool-6-thread-9] SessionImpl$5.work 
WARN  2020-09-30 16:25:07,758 Cannot connect                                                                             =>[SwingWorker-pool-6-thread-8] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:412)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://xmage.de:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=jboss]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
INFO  2020-09-30 16:25:07,900 Disconnecting DONE                                                                         =>[SwingWorker-pool-6-thread-8] SessionImpl.disconnect 
INFO  2020-09-30 16:25:07,901 Disconnected from user mode                                                                =>[SwingWorker-pool-6-thread-8] MageFrame.disconnected 
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
```

**Comment by JayDi85** [comment]
De server works fine, us server restarted and works too. Try to close all `java.exe` apps and run xmage again.

If not help then disable all firewall, antimalware and antivirus software. If you would be able to connect then it's a wrong settings in your apps.
