### ISSUE TITLE
GUI: too much memory usage by deck editor - GC overhead limit exceeded

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#7177]
Steps to reproduce:
* change launcher settings -> java -> client to `-Xmx700m ` or `-Xmx500m` (remove all other settings);
* run launcher -> deck editor
* press search button, wait loading cursor (repeat few times until error in logs).

One of the possible error (real reason of overhead usage can be in another place):
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at mage.constants.SubType.values(SubType.java:10)
	at mage.constants.SubType.fromString(SubType.java:528)
	at mage.cards.repository.CardInfo.getSubTypes(CardInfo.java:376)
	at mage.cards.mock.MockCard.<init>(MockCard.java:45)
	at mage.cards.repository.CardInfo.getMockCard(CardInfo.java:262)
	at mage.client.deckeditor.CardSelector.filterCards(CardSelector.java:435)
	at mage.client.deckeditor.CardSelector.jButtonSearchActionPerformed(CardSelector.java:1308)
	at mage.client.deckeditor.CardSelector.access$3500(CardSelector.java:49)
	at mage.client.deckeditor.CardSelector$38.actionPerformed(CardSelector.java:1090)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

P.S. It's not a critical error and can be fixed by memory increase (2GB works fine), but it can be useful for low spec computers.

**Comment by JayDi85** [comment]
Fixed in #7515, read [details in that comment](https://github.com/magefree/mage/issues/7515#issuecomment-778370060).
