### ISSUE TITLE
Rollback in the beta - ConcurrentModificationException

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7231]
Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.47V0-beta3 (build: 2020-11-30 02:35)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.effects.ContinuousEffects.getApplicableReplacementEffects(ContinuousEffects.java:347)
mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:848)
mage.game.GameState.replaceEvent(GameState.java:772)
mage.game.GameState.replaceEvent(GameState.java:765)
mage.game.GameImpl.replaceEvent(GameImpl.java:2793)
mage.actions.MageDrawAction.drawCard(MageDrawAction.java:82)
mage.actions.MageDrawAction.doAction(MageDrawAction.java:54)
mage.game.GameImpl.doAction(GameImpl.java:3121)
mage.players.PlayerImpl.drawCards(PlayerImpl.java:652)
mage.abilities.effects.common.DrawCardSourceControllerEffect.apply(DrawCardSourceControllerEffect.java:56)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:179)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:163)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:81)
mage.game.stack.StackAbility.resolve(StackAbility.java:86)
mage.game.GameImpl.resolve(GameImpl.java:1427)
mage.game.GameImpl.playPriority(GameImpl.java:1374)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:893)
mage.game.GameImpl.play(GameImpl.java:805)
mage.game.GameImpl.start(GameImpl.java:790)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
ConcurrentModificationException is very rare bug, maybe related to slow server's performance (game freeze can cause the CPU usage to 100%). So it can't be fixed until bug will be reproduceable.

Another error example:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:275)
	at mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:373)
	at mage.abilities.effects.common.continuous.GainAbilityAllEffect.apply(GainAbilityAllEffect.java:112)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:102)
	at mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1058)
	at mage.game.GameState.applyEffects(GameState.java:599)
	at mage.game.GameImpl.applyEffects(GameImpl.java:1556)
	at mage.game.GameImpl.playPriority(GameImpl.java:1358)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:126)
	at mage.game.GameImpl.playTurn(GameImpl.java:893)
	at mage.game.GameImpl.play(GameImpl.java:805)
```

**Comment by LevelX2** [comment]
Duplicate of #7170.
