### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#7507]
from the client console 
```
FATAL 2021-02-05 11:47:53,008 MAGE Client UI error                                                                       =>[mouseResetTimer] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at org.mage.card.arcane.CardPanel$1.run(CardPanel.java:628)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FATAL 2021-02-05 11:50:02,648 MAGE Client UI error                                                                       =>[mouseResetTimer] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at org.mage.card.arcane.CardPanel$1.run(CardPanel.java:628)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FATAL 2021-02-05 11:50:04,488 MAGE Client UI error                                                                       =>[mouseResetTimer] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at org.mage.card.arcane.CardPanel$1.run(CardPanel.java:628)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FATAL 2021-02-05 12:02:40,689 MAGE Client UI error                                                                       =>[mouseResetTimer] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at org.mage.card.arcane.CardPanel$1.run(CardPanel.java:628)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FATAL 2021-02-05 12:03:10,570 MAGE Client UI error                                                                       =>[mouseResetTimer] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at org.mage.card.arcane.CardPanel$1.run(CardPanel.java:628)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FATAL 2021-02-05 12:03:48,089 MAGE Client UI error                                                                       =>[mouseResetTimer] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at org.mage.card.arcane.CardPanel$1.run(CardPanel.java:628)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
INFO  2021-02-05 12:12:32,038 Ending game...                                                                             =>[pool-9-thread-1] FeedbackPanel.lambda$endWithTimeout$0 
```

version: 1.4.48.dev_2021-02-04_16-54

**Comment by JayDi85** [comment]
I think it can be related to card clicks while dialogs are closing (example: game end or drafting end). Must be fixed with c256aa59f7fa25daa4141f2bed000805c66f0327
