### ISSUE TITLE
Error loading cards UrborgTombOfYawgmoth and YavimayaCradleOfGrowth

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#7892]
I'm getting the following errors logged to the console after commit ac04c27133f78949865c5ac8cbae54e9a415a61a

Not sure what's causing it at first glance:

```
FATAL 2021-06-05 13:57:48,283 Error loading card: mage.cards.u.UrborgTombOfYawgmoth (UMA)                                =>[main] CardImpl.createCard 
java.lang.NoClassDefFoundError: org/junit/Assert
	at mage.abilities.effects.common.continuous.AddBasicLandTypeAllLandsEffect.<init>(AddBasicLandTypeAllLandsEffect.java:24)
	at mage.cards.u.UrborgTombOfYawgmoth.<init>(UrborgTombOfYawgmoth.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:174)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:57)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:150)
Caused by: java.lang.ClassNotFoundException: org.junit.Assert
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 10 more
FATAL 2021-06-05 13:57:48,726 Error loading card: mage.cards.u.UrborgTombOfYawgmoth (V12)                                =>[main] CardImpl.createCard 
java.lang.NoClassDefFoundError: org/junit/Assert
	at mage.abilities.effects.common.continuous.AddBasicLandTypeAllLandsEffect.<init>(AddBasicLandTypeAllLandsEffect.java:24)
	at mage.cards.u.UrborgTombOfYawgmoth.<init>(UrborgTombOfYawgmoth.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:174)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:57)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:150)
FATAL 2021-06-05 13:57:52,501 Error loading card: mage.cards.u.UrborgTombOfYawgmoth (TSR)                                =>[main] CardImpl.createCard 
java.lang.NoClassDefFoundError: org/junit/Assert
	at mage.abilities.effects.common.continuous.AddBasicLandTypeAllLandsEffect.<init>(AddBasicLandTypeAllLandsEffect.java:24)
	at mage.cards.u.UrborgTombOfYawgmoth.<init>(UrborgTombOfYawgmoth.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:174)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:57)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:150)
FATAL 2021-06-05 13:57:52,887 Error loading card: mage.cards.u.UrborgTombOfYawgmoth (PLC)                                =>[main] CardImpl.createCard 
java.lang.NoClassDefFoundError: org/junit/Assert
	at mage.abilities.effects.common.continuous.AddBasicLandTypeAllLandsEffect.<init>(AddBasicLandTypeAllLandsEffect.java:24)
	at mage.cards.u.UrborgTombOfYawgmoth.<init>(UrborgTombOfYawgmoth.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:174)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:57)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:150)
FATAL 2021-06-05 13:57:53,379 Error loading card: mage.cards.y.YavimayaCradleOfGrowth (MH2)                              =>[main] CardImpl.createCard 
java.lang.NoClassDefFoundError: org/junit/Assert
	at mage.abilities.effects.common.continuous.AddBasicLandTypeAllLandsEffect.<init>(AddBasicLandTypeAllLandsEffect.java:24)
	at mage.cards.y.YavimayaCradleOfGrowth.<init>(YavimayaCradleOfGrowth.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:174)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:57)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:150)
FATAL 2021-06-05 13:57:54,648 Error loading card: mage.cards.u.UrborgTombOfYawgmoth (PUMA)                               =>[main] CardImpl.createCard 
java.lang.NoClassDefFoundError: org/junit/Assert
	at mage.abilities.effects.common.continuous.AddBasicLandTypeAllLandsEffect.<init>(AddBasicLandTypeAllLandsEffect.java:24)
	at mage.cards.u.UrborgTombOfYawgmoth.<init>(UrborgTombOfYawgmoth.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:174)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:57)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:150)
FATAL 2021-06-05 13:57:55,721 Error loading card: mage.cards.u.UrborgTombOfYawgmoth (M15)                                =>[main] CardImpl.createCard 
java.lang.NoClassDefFoundError: org/junit/Assert
	at mage.abilities.effects.common.continuous.AddBasicLandTypeAllLandsEffect.<init>(AddBasicLandTypeAllLandsEffect.java:24)
	at mage.cards.u.UrborgTombOfYawgmoth.<init>(UrborgTombOfYawgmoth.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mage.cards.CardImpl.createCard(CardImpl.java:174)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:57)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.server.Main.main(Main.java:150)
```

**Comment by JayDi85** [comment]
New assert code. Use it in tests, not in production code.

**Comment by weirddan455** [comment]
I see.  I didn't write that code so I'm not sure why that assert is there.  It looks like the error is triggered on database rebuild so you'll need to delete the .db files if you want to reproduce.

**Comment by JayDi85** [comment]
Real reason: junit dependency in pom.xml file. Old code was in cards package (Mage.Sets) and it's have junit in pom. But new code moved to Mage package and it doesn't have junit dependency in pom. You can fix it by adding missing dependency in pom or remove assert code.

**Comment by JayDi85** [comment]
BTW I can see a good build from current sources. Github uses clean setup (e.g. db files creates on tests running), so all dependencies are fine now. Try to check your pom files or call maven re-import to fix your local build error.

**Comment by weirddan455** [comment]
It's not a build error.  The error happens at runtime when the database gets rebuilt.  I don't think the online builds test for that.

**Comment by JayDi85** [comment]
Game tests (95% of all unit tests) call "scanner" to check and re-create database. So any unit test on first call will create new database. For database creating xmage calls a card's constructor (and all related abilities/effects from that constructor too). So if card code have some error then it will be shown in the logs like your:
https://travis-ci.org/github/magefree/mage/builds/773599720

![shot_210605_235530](https://user-images.githubusercontent.com/8344157/120903852-b110f680-c659-11eb-9f9e-3018cc18aa3a.png)

**Comment by JayDi85** [comment]
All game tests are server side only (not client/server). There are only few tests for real client/server communications and games (example: LoadTest.java).

**Comment by weirddan455** [comment]
Right, the tests are running fine for me locally though and aren't throwing errors when rebuilding the db.

```
INFO  2021-06-05 15:05:22,485 DB: need to add 443 new sets                                                               =>[main] ExpansionRepository.lambda$saveSets$0 
INFO  2021-06-05 15:05:33,555 DB: need to add 53470 new cards                                                            =>[main] CardRepository.lambda$saveCards$0 
```
What I'm saying is that the error only happens when the real client (and server) programs run.  Test framework seems to be unaffected.

**Comment by JayDi85** [comment]
Ok, I've got it now. Open `Mage.Client\pom.xml` and remove `<scope>test</scope>` line for junit dependency. It will enable junit in client's production. It's only a workaround to fix a problem (same fix already made for Mage package).

P.S. I think assert code in production must be refactored to throw exception instead assert call. Someday.

**Comment by theelk801** [comment]
yeah sorry about that, we can just remove the assertion completely since it’s not that important
