### ISSUE TITLE
Foretell can apply cost for land (?) card and raise rollback error (ForetellAddCostEffect)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#8044]
Rare error.

It's NPE error and can be fixed by null check on `card.getSpellAbility()` BUT there are must a real use case to repeat that error. Cause there are many places in foretell with same code style (without `getSpellAbility()` null check).

Possible reason: `ForetellAddCostEffect` somehow targeting land card or MDFC with land part.

```
java.lang.NullPointerException
	at mage.abilities.keyword.ForetellAbility$ForetellAddCostEffect.apply(ForetellAbility.java:273)
	at mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
	at mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1091)
	at mage.game.GameState.applyEffects(GameState.java:641)
	at mage.game.GameImpl.applyEffects(GameImpl.java:1633)
	at mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:229)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:178)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:120)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:90)
	at mage.game.GameImpl.resolve(GameImpl.java:1504)
	at mage.game.GameImpl.playPriority(GameImpl.java:1450)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:128)
	at mage.game.GameImpl.playTurn(GameImpl.java:966)
	at mage.game.GameImpl.play(GameImpl.java:876)
	at mage.game.GameImpl.start(GameImpl.java:852)
```

https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage/src/main/java/mage/abilities/keyword/ForetellAbility.java#L270-L275

**Comment by jeffwadsworth** [comment]
[[Dream Devourer]]
