### ISSUE TITLE
Failing to connect to server

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#857]
I am able to ping the server just fine, but when I try to connect I get the following error. I've changed the port on the server, and other remote clients connect just fine. But several remote clients also get this error.

No proxy is being used in the environment.

Mageclient.log
-----------------------------------------------------------------------------
FATAL 2015-03-30 16:24:48,891 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at mage.server.SessionManager.extendUserSession(SessionManager.java:213)
	at mage.server.MageServerImpl.ping(MageServerImpl.java:355)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
	at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
	at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:798)
	at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
	at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
	at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:218)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.invoke(Client.java:879)
	at org.jboss.remoting.transporter.TransporterClient.invoke(TransporterClient.java:475)
	at com.sun.proxy.$Proxy8.ping(Unknown Source)
	at mage.remote.SessionImpl.ping(SessionImpl.java:1415)
	at mage.client.MageFrame$2.run(MageFrame.java:218)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
-----------------------------------------------------------------------------

Any suggestions?

**Comment by Greeneye0** [comment]
This is some kind of environmental issue. I'm able to see the packets come in to the server from the client, but the client never connects.  

The environment is a bit strange in that there is some crazy stuff with the router going on. 

Anyhow, on a similar note, I did find a strange connection issue where I could ping by host name and get some strange connect then an imeddiate disconnect message when I used the hostname of a machine to connect to a machine in the domain. Once I changed it to connect to the FQDN it didn't have any issues. This tells me that the FQDN of the server is some how used even if the client is connecting via hostname or IP address.

**Comment by LevelX2** [comment]
I guess you talk about connecting to xmage.info server 1?

It seems to be some problems with the server by the host net/hardware/managing.
I didn't changed anything on the server itself but starting with Monday 0:00 CET things are different.
I can see it in different munin graphs.
![tcpsyncookies-week](https://cloud.githubusercontent.com/assets/2066790/6904844/0115f5d0-d724-11e4-86d0-8dbd87a6e726.png)

**Comment by Greeneye0** [comment]
No, this was connecting to a local server. The wireshark trace I ran was from the server itself.
