### ISSUE TITLE
Cannot build server on M1 Mac due to sqlite-jdbc being too old

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8581]
When I setup the server to run from IntelliJ I get the following error:
```
INFO  2022-01-22 10:00:08,902 Starting MAGE server version 1.4.50-V2 (build: runtime)                                    =>[main] Main.main 
INFO  2022-01-22 10:00:08,903 Logging level: INFO                                                                        =>[main] Main.main 
INFO  2022-01-22 10:00:08,903 Default charset: UTF-8                                                                     =>[main] Main.main 
INFO  2022-01-22 10:00:08,905 Reading configuration from path=config/config.xml                                          =>[main] Main.main 
INFO  2022-01-22 10:00:08,968 Loading database...                                                                        =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2022-01-22 10:00:09,441 Done.                                                                                      =>[main] Main.main 
INFO  2022-01-22 10:00:09,441 Loading extension packages...                                                              =>[main] Main.main 
INFO  2022-01-22 10:00:09,441 Done.                                                                                      =>[main] Main.main 
INFO  2022-01-22 10:00:09,441 Loading cards...                                                                           =>[main] Main.main 
INFO  2022-01-22 10:00:16,069 DB: need to add 450 new sets                                                               =>[main] ExpansionRepository.lambda$saveSets$0 
INFO  2022-01-22 10:00:23,417 DB: need to add 56499 new cards                                                            =>[main] CardRepository.lambda$saveCards$0 
INFO  2022-01-22 10:00:27,431 Done.                                                                                      =>[main] Main.main 
INFO  2022-01-22 10:00:27,431 Updating user stats DB...                                                                  =>[main] Main.main 
ERROR 2022-01-22 10:00:27,457 Error creating user_stats repository -                                                     =>[main] UserStatsRepository.<init> 
java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:139)
	at com.j256.ormlite.jdbc.BaseJdbcConnectionSource.getReadWriteConnection(BaseJdbcConnectionSource.java:154)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:370)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:357)
	at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:75)
	at mage.cards.repository.RepositoryUtil.isDatabaseObsolete(RepositoryUtil.java:32)
	at mage.server.record.UserStatsRepository.<init>(UserStatsRepository.java:39)
	at mage.server.record.UserStatsRepository.<clinit>(UserStatsRepository.java:23)
	at mage.server.Main.main(Main.java:169)
Caused by: java.lang.Exception: No native library found for os.name=Mac, os.arch=aarch64, paths=[/Users/alex/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
	... 16 more
```

I was able to get the server running (though I cannot join it locally, idk the issue for that yet) by changing the following line:
https://github.com/magefree/mage/blob/c4a0a18066c8ab5a8ea189f9f0f3d8c352775ccb/Mage.Server/pom.xml#L265

to `<version>3.36.0.2</version>`. This version (the newest) has arm support for Mac.

**Comment by jimga150** [comment]
Same here. on macOS 14.2.1, M1. Changing to latest version as of now (3.44.1.0) did not fix, now did 3.42.0.0 or 3.36.0.2

**Comment by jimga150** [comment]
Workaround found: make changes found here:
#11163 
Then use the latest version of sqlite-jbc (currently 3.45.1.0)
If you use IntelliJ IDEA then make sure you run pom file sync/import after lib version changed (by right click on server’s pom file or by popup icon in the editor)
Then run an mvm clean install and run the server.

**Comment by JayDi85** [comment]
fixed in c272a825c012ccaee138453bde018919abb7b47e
