### ISSUE TITLE
Client launcher issue (No toolkit found)

### ISSUE THREAD

**Issue by capt-pyro** [magefree/mage#8597]
When launching the client from the launcher, the following error message is printed out

```
INFO  2022-01-26 13:58:09,565 Starting MAGE client version 1.4.51-V3-beta2 (build: 2021-12-31 16:27)                     =>[main] MageFrame.main 
INFO  2022-01-26 13:58:09,567 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2022-01-26 13:58:09,567 Default charset: UTF-8                                                                     =>[main] MageFrame.main 
INFO  2022-01-26 13:58:10,294 Using GUI theme: Default                                                                   =>[AWT-EventQueue-0] PreferencesDialog.getCurrentTheme 
INFO  2022-01-26 13:58:10,301 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2022-01-26 13:58:10,523 Images: search broken files...                                                             =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2022-01-26 13:58:10,654 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
WARN  2022-01-26 13:58:10,659 Symbols can't be load for size 15: SVG fails - 52, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
WARN  2022-01-26 13:58:10,659 Symbols can't be load for size 25: SVG fails - 48, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
WARN  2022-01-26 13:58:10,661 Symbols can't be load for size 50: SVG fails - 49, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
INFO  2022-01-26 13:58:10,798 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2022-01-26 13:58:10,818 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2022-01-26 13:58:10,822 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2022-01-26 13:58:10,823 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2022-01-26 13:58:10,823 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:248)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
	at javafx.embed.swing.JFXPanel.lambda$initFx$2(JFXPanel.java:232)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
FATAL 2022-01-26 13:58:10,937 Critical error on start up, app will be closed: No toolkit found                           =>[AWT-EventQueue-0] MageFrame.lambda$main$9 
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
	at javafx.embed.swing.JFXPanel.lambda$initFx$2(JFXPanel.java:232)
	at java.lang.Thread.run(Thread.java:748)
```

I'm running this on Arch Linux and running launcher version 0.3.8

**Comment by JayDi85** [comment]
Some graphic library is missing from the system like GTK. Try [that instructions](https://stackoverflow.com/a/21203726/1276632)

P.S. You can set java app params from the launcher - settings - java - client: `-Dprism.verbose=true`

**Comment by everettttt** [comment]
I also got this error (EndeavourOS), tried a few things (`yay java-openjfx`, `yay java8-openjfx` => could not build), and gave up.

**Comment by Alex-Vasile** [comment]
> I also got this error (EndeavourOS), tried a few things (`yay java-openjfx`, `yay java8-openjfx` => could not build), and gave up.

Have you tried building the newest version from source? The JavaFX dependancy was recently removed, but the change has not yet shown up on the beta.

**Comment by everettttt** [comment]
>Have you tried building the newest version from source?

I'm not sure how to do that. No Makefile or anything I'm familiar with in the repo. And I can't find a clue in the docs/wiki/etc. What's the build command?

**Comment by Alex-Vasile** [comment]
> > Have you tried building the newest version from source?
> 
> I'm not sure how to do that. No Makefile or anything I'm familiar with in the repo. And I can't find a clue in the docs/wiki/etc. What's the build command?

See https://github.com/magefree/mage/issues/8756

There's a perl script in the source files `Utils/build-and-package.pl` to build and package.
