### ISSUE TITLE
[NEO] Replication Specalist throwing exception in DB creation

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#8643]
I'll take a look at this in a little bit.

```
INFO  2022-02-04 11:51:59,182 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2022-02-04 11:51:59,543 DB: creating cards database (it can take few minutes)...                                   =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2022-02-04 11:52:06,800 DB: need to add 451 new sets                                                               =>[AWT-EventQueue-0] ExpansionRepository.lambda$saveSets$0 
ERROR 2022-02-04 11:52:15,650 Exception in rules generation for card: Replication Specialist                             =>[AWT-EventQueue-0] CardUtil.getCardRulesWithAdditionalInfo 
java.lang.UnsupportedOperationException: Using default rule generation of target effect without having a target object
	at mage.abilities.effects.common.CreateTokenCopyTargetEffect.getText(CreateTokenCopyTargetEffect.java:270)
	at mage.abilities.effects.Effects.getText(Effects.java:45)
	at mage.abilities.effects.common.DoIfCostPaid.getText(DoIfCostPaid.java:158)
	at mage.abilities.effects.Effects.getText(Effects.java:45)
	at mage.abilities.Modes.getText(Modes.java:464)
	at mage.abilities.AbilityImpl.getRule(AbilityImpl.java:803)
	at mage.abilities.TriggeredAbilityImpl.getRule(TriggeredAbilityImpl.java:151)
	at mage.abilities.common.EntersBattlefieldAllTriggeredAbility.getRule(EntersBattlefieldAllTriggeredAbility.java:111)
	at mage.abilities.AbilitiesImpl.getRules(AbilitiesImpl.java:56)
	at mage.abilities.AbilitiesImpl.getRules(AbilitiesImpl.java:44)
	at mage.util.CardUtil.getCardRulesWithAdditionalInfo(CardUtil.java:1099)
	at mage.util.CardUtil.getCardRulesWithAdditionalInfo(CardUtil.java:1087)
	at mage.cards.CardImpl.getRules(CardImpl.java:216)
	at mage.cards.repository.CardInfo.<init>(CardInfo.java:215)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:71)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
	at mage.client.MageFrame.<init>(MageFrame.java:243)
	at mage.client.MageFrame.lambda$main$9(MageFrame.java:1338)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by weirddan455** [comment]
It's using a target pointer so it's throwing the exception here.  Not sure the best way to fix it (maybe just give it static text) but I think @theelk801 usually does some text clean-up stuff once the set is done so probably not a big deal for now.

https://github.com/magefree/mage/blob/93f14cdf614b6310cc2689b1d6e522dfa502215a/Mage/src/main/java/mage/abilities/effects/common/CreateTokenCopyTargetEffect.java#L267-L271

**Comment by theelk801** [comment]
I’ll handle it when I’m off work
