### ISSUE TITLE
"Choose a card name" dialogue client lock ups

### ISSUE THREAD

**Issue by ghost** [magefree/mage#8671]
Didn't see anything in the closed bugs about this so just going to explain it.  When the "choose a card name" dialogue pops up (lets say with pithing needle, but really anything that calls this dialogue) if you type out the card name, hit backspace a million times (figuratively) and do that a couple times over again the client will just freeze after about 20 seconds of doing this and the only way to progress is process kill (on windows at least) and start the client again rejoining the disconnected game.  This tends to happen as I always type out the card name and change my mind often and maybe change it again and at some point it just freezes up.  Can recreate on demand, for years.

**Comment by Alex-Vasile** [comment]
I'm trying to reproduce this, but I'm not getting any freezes. I've been on the pithing needle dialog, deleting and rewriting things and I haven't gotten it to freeze.

Which version are you getting this happening on?

**Comment by peter-thoenen** [comment]
I've had that with every version of xmage since I started years ago including the current.  It's with literally every search dialogue, not just pithing needle.  And I've rebuild computers, etc so it's not a clean reinstall issue.  I can recreate on demand and I know from conversations in xmage chat others get it too.  It doesn't kick an error in the Java console so not sure how to report it.

**Comment by Alex-Vasile** [comment]
> I've had that with every version of xmage since I started years ago including the current.  It's with literally every search dialogue, not just pithing needle.  And I've rebuild computers, etc so it's not a clean reinstall issue.  I can recreate on demand and I know from conversations in xmage chat others get it too.  It doesn't kick an error in the Java console so not sure how to report it.

Can you do a screen recording of exactly what you're doing? I haven't been able to get it to freeze.

**Comment by Alex-Vasile** [comment]
Do you play against AI when this happens?

How much ram are you giving the server that you play one?

**Comment by peter-thoenen** [comment]
No and none, I only play using the DE server.  I'm taking a pause for xmage until out of beta, just an FYI as I won't be able to recreate.

**Comment by JayDi85** [comment]
I can confirm GUI freeze on search text deleting by backspace (it's freeze forever).

Maybe related stack trace after freeze:
```
"AWT-EventQueue-0@1254" prio=6 tid=0x16 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.lang.Object.notifyAll(Object.java:-1)
	  at javax.swing.text.AbstractDocument.writeUnlock(AbstractDocument.java:1364)
	  - locked <0x1c12> (a javax.swing.plaf.basic.BasicHTML$BasicDocument)
	  at javax.swing.text.DefaultStyledDocument.create(DefaultStyledDocument.java:161)
	  at javax.swing.text.html.HTMLDocument.create(HTMLDocument.java:469)
	  at javax.swing.text.html.HTMLDocument$HTMLReader.flushBuffer(HTMLDocument.java:3736)
	  at javax.swing.text.html.HTMLDocument$HTMLReader.flush(HTMLDocument.java:2538)
	  at javax.swing.text.html.HTMLEditorKit.read(HTMLEditorKit.java:262)
	  at javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:62)
	  at javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:207)
	  at javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:481)
	  at javax.swing.plaf.synth.SynthLabelUI.propertyChange(SynthLabelUI.java:296)
	  at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	  at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	  at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	  at java.awt.Component.firePropertyChange(Component.java:8434)
	  at javax.swing.DefaultListCellRenderer.firePropertyChange(DefaultListCellRenderer.java:261)
	  at javax.swing.JLabel.setText(JLabel.java:330)
	  at javax.swing.DefaultListCellRenderer.getListCellRendererComponent(DefaultListCellRenderer.java:151)
	  at javax.swing.plaf.synth.SynthListUI$SynthListCellRenderer.getListCellRendererComponent(SynthListUI.java:221)
	  at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	  at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	  at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2623)
	  at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	  at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	  at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	  at javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:632)
	  at javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2581)
	  at javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:148)
	  at javax.swing.DefaultListModel.addElement(DefaultListModel.java:367)
	  at mage.client.dialog.PickChoiceDialog.loadData(PickChoiceDialog.java:378)
	  at mage.client.dialog.PickChoiceDialog.access$100(PickChoiceDialog.java:31)
	  at mage.client.dialog.PickChoiceDialog$1.removeUpdate(PickChoiceDialog.java:153)
	  at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:259)
	  at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:622)
	  at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:590)
	  at javax.swing.text.DefaultEditorKit$DeletePrevCharAction.actionPerformed(DefaultEditorKit.java:1071)
	  at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	  at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	  at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	  at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	  at java.awt.Component.processEvent(Component.java:6316)
	  at java.awt.Container.processEvent(Container.java:2239)
	  at java.awt.Component.dispatchEventImpl(Component.java:4889)
	  at java.awt.Container.dispatchEventImpl(Container.java:2297)
	  at java.awt.Component.dispatchEvent(Component.java:4711)
	  at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	  at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	  at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	  at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	  at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	  at java.awt.Component.dispatchEventImpl(Component.java:4760)
	  at java.awt.Container.dispatchEventImpl(Container.java:2297)
	  at java.awt.Window.dispatchEventImpl(Window.java:2746)
	  at java.awt.Component.dispatchEvent(Component.java:4711)
	  at mage.client.dialog.MageDialog.startModal(MageDialog.java:200)
```
