### ISSUE TITLE
Patron of the Akki causes null pointer exception when attempting to offer a token

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8724]
Server error log:
`INFO  2022-02-24 21:07:15,657 
Stack before error 1: 
Cast Patron of the Akki
                                           =>[GAME d22d311b-ab2d-43d8-8e97-468ab05b741e] GameImpl.playPriority 
FATAL 2022-02-24 21:08:21,480 Game exception gameId: d22d311b-ab2d-43d8-8e97-468ab05b741e                                =>[GAME d22d311b-ab2d-43d8-8e97-468ab05b741e] GameImpl.playPriority 
java.lang.NullPointerException
	at mage.abilities.keyword.OfferingCostReductionEffect.apply(OfferingAbility.java:228)
	at mage.abilities.effects.ContinuousEffects.costModification(ContinuousEffects.java:741)
	at mage.abilities.AbilityImpl.activate(AbilityImpl.java:392)
	at mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:259)
	at mage.game.stack.Spell.activate(Spell.java:139)
	at mage.players.PlayerImpl.cast(PlayerImpl.java:1236)
	at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1492)
	at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2083)
	at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2106)
	at mage.player.human.HumanPlayer.priority(HumanPlayer.java:1191)
	at mage.game.GameImpl.playPriority(GameImpl.java:1535)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:132)
	at mage.game.GameImpl.playTurn(GameImpl.java:1060)
	at mage.game.GameImpl.play(GameImpl.java:970)
	at mage.game.GameImpl.start(GameImpl.java:946)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by Alex-Vasile** [comment]
[[Patron of the Akki]]
