### ISSUE TITLE
Trying to Connect to LocalHost on Xmage. I have tried reading through the guides on here, but can't get it to work. Server Launches, Client, can't connect to it.

### ISSUE THREAD

**Issue by Flexerhh** [magefree/mage#8975]
WARN  2022-05-19 19:44:05,886 Cannot connect                                                                             =>[SwingWorker-pool-6-thread-8] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:415)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://192.168.0.10:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=jboss]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
INFO  2022-05-19 19:44:05,891 Disconnecting DONE                                                                         =>[SwingWorker-pool-6-thread-8] SessionImpl.disconnect 
INFO  2022-05-19 19:44:05,891 Disconnected from user mode                                                                =>[SwingWorker-pool-6-thread-8] MageFrame.disconnected 

Server says listening to 0.0.0.0:17171

**Comment by Alex-Vasile** [comment]
What OS?

What version of XMage?

What version of Java (including subversion)?

**Comment by Alex-Vasile** [comment]
Hmm. I've had issues with the firewall blocking even local connections before. But other than that I'm not sure.

Do you have an antivirus program running?

**Comment by Flexerhh** [comment]
Yes, I have AVG and also the natural windows firewall

**Comment by Flexerhh** [comment]
Hi I disabled my AVG and it worked... Do you mind me asking how you knew it was my firewall?

**Comment by Alex-Vasile** [comment]
> Hi I disabled my AVG and it worked... Do you mind me asking how you knew it was my firewall?

You don't have to disable to whole firewall, just add XMage to the whitelist.

As to how I know. It's one of the few applications that affect incoming/outgoing connections.

**Comment by Flexerhh** [comment]
Hi Alex,

I really wanted to figure out how to add Xmage to the whitelist, the issue is, its not as simple as just adding the app xmage to the whitelist and I dont have time to be able to figure it out. I am unsure which things I need to be enabling in my rules, could you possibly assist?

- I am a novice when it comes to this stuff if I haven't screamed that already.

**Comment by Alex-Vasile** [comment]
> Hi Alex,
> 
> 
> 
> I really wanted to figure out how to add Xmage to the whitelist, the issue is, its not as simple as just adding the app xmage to the whitelist and I dont have time to be able to figure it out. I am unsure which things I need to be enabling in my rules, could you possibly assist?
> 
> 
> 
> - I am a novice when it comes to this stuff if I haven't screamed that already.

I don't know how to do it for your antivirus, you'll have to look that one up online

**Comment by Flexerhh** [comment]
Hi  Alex,

I didn't think it would be so straightforward haha.

I appreciate you lending me a hand regardless.

Many thanks
