### ISSUE TITLE
What's New Dialog causes freezes on macOS when resizing window

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9050]
When running the beta if you try to use any sort of window management software (e.g. snap XMage to left half of screen) while the  "Connect to server" window is open, the entire application will freeze. Digging into it some more, it's cause by the what's new dialog.

When running from source on my M1 Mac, the what's new dialog does not work at all, since the JDK can't find a arm version `libjfxwebkit.dylib`. (The issue of the UI hanging still happens even when building from source.

Error:
```
java.lang.UnsatisfiedLinkError: /Users/alex/Library/Java/JavaVirtualMachines/liberica-1.8.0_332/jre/lib/libjfxwebkit.dylib: dlopen(/Users/alex/Library/Java/JavaVirtualMachines/liberica-1.8.0_332/jre/lib/libjfxwebkit.dylib, 0x0001): tried: '/Users/alex/Library/Java/JavaVirtualMachines/liberica-1.8.0_332/jre/lib/libjfxwebkit.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
	at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.webkit.WebPage.<clinit>(WebPage.java:132)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:889)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:876)
	at javafx.scene.web.WebView.<init>(WebView.java:273)
	at mage.client.dialog.WhatsNewDialog$3.run(WhatsNewDialog.java:264)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by JayDi85** [comment]
1. Popup dialogs can be freeze on macos with any third party window or text tools like contexts, magent, etc -- see #4920 for more details. I research it old days and found possible reason in old java's gui lib (AWT) -- maybe will be fixed after migrate to java 11+

2. Miss javafx must be ignored by app and continue to work without any freezes. I'll try to test and find the workaround for macos later.

**Comment by JayDi85** [comment]
You can test popup freeze with search language/flag dialog (from connection).

**Comment by Alex-Vasile** [comment]
> You can test popup freeze with search language/flag dialog (from connection).

See https://github.com/magefree/mage/issues/4920#issuecomment-1144070833
