### ISSUE TITLE
Computer can play Valorous Stance with No Target, Throwing a NPE

### ISSUE THREAD

**Issue by DeepCrimson** [magefree/mage#9157]
While running `TestPlayRandomGame`, a computer player tried to cast [[Valorous Stance]] with no targets, resulting in the following exception being thrown:

```
FATAL 2022-06-25 00:59:47,178 Game exception gameId: ddf35b27-d8f4-4840-a71f-70d99748e7c5                                =>[main] GameImpl.playPriority 
java.lang.NullPointerException
	at mage.abilities.AbilityImpl.<init>(AbilityImpl.java:133)
	at mage.abilities.TriggeredAbilityImpl.<init>(TriggeredAbilityImpl.java:52)
	at mage.abilities.decorator.ConditionalInterveningIfTriggeredAbility.<init>(ConditionalInterveningIfTriggeredAbility.java:49)
	at mage.abilities.decorator.ConditionalInterveningIfTriggeredAbility.copy(ConditionalInterveningIfTriggeredAbility.java:62)
	at mage.abilities.decorator.ConditionalInterveningIfTriggeredAbility.copy(ConditionalInterveningIfTriggeredAbility.java:23)
	at mage.abilities.TriggeredAbilities.<init>(TriggeredAbilities.java:35)
	at mage.abilities.TriggeredAbilities.copy(TriggeredAbilities.java:165)
	at mage.game.GameState.<init>(GameState.java:167)
	at mage.game.GameState.copy(GameState.java:299)
	at mage.game.GameStates.save(GameStates.java:24)
	at mage.game.GameImpl.saveState(GameImpl.java:746)
	at mage.game.GameImpl.bookmarkState(GameImpl.java:843)
	at mage.players.PlayerImpl.cast(PlayerImpl.java:1197)
	at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1494)
	at org.mage.test.player.RandomPlayer.priority(RandomPlayer.java:77)
	at mage.game.GameImpl.playPriority(GameImpl.java:1523)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:132)
	at mage.game.GameImpl.playTurn(GameImpl.java:1042)
	at mage.game.GameImpl.play(GameImpl.java:952)
	at mage.game.GameImpl.start(GameImpl.java:928)
	at org.mage.test.serverside.TestPlayRandomGame.playOneGame(TestPlayRandomGame.java:73)
	at org.mage.test.serverside.TestPlayRandomGame.playGames(TestPlayRandomGame.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by Alex-Vasile** [comment]
`AbilityImpl.java:133` is `this.hints.add(hint.copy());` with a NPE, means that `hint` is null.
Based on the stack, it's a `ConditionalInterveningIfTriggeredAbility` that's causing it.

So some card with a `ConditionalInterveningIfTriggeredAbility` is not setting it's hint properly.

**Comment by DeepCrimson** [comment]
I'm not sure what else was on the battlefield and I tried to replicate the situation with [this test](https://github.com/magefree/mage/pull/9176) but the issue isn't passing, so I'm closing this issue out as nonreproducible.
