### ISSUE TITLE
Undo can cause Game exception (missing bookmark data)

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#925]
```
FATAL 2015-04-19 19:26:17,874 Game exception gameId: 65a32bf4-2856-4857-a994-fe217080347c                                =>[GAME 65a32bf4-2856-4857-a994-fe217080347c] GameImpl.playPriority
java.lang.UnsupportedOperationException: It was not possible to do the requested undo operation (bookmark 4 does not exist) context: choose two &mdash;<br>&bull  Prevent all damage target instant or sorcery spell would deal until end of turn.<br>&bull  Target player sacrifices an enchantment.<br>&bull  Put a +1/+1 counter on target creature.<br>&bull  Target creature you control fights target creature you don't control.<br>
    at mage.game.GameImpl.restoreState(GameImpl.java:553)
    at mage.players.PlayerImpl.cast(PlayerImpl.java:938)
    at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1088)
    at mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1017)
    at mage.player.human.HumanPlayer.priority(HumanPlayer.java:573)
    at mage.game.GameImpl.playPriority(GameImpl.java:1133)
    at mage.game.turn.Step.priority(Step.java:87)
    at mage.game.turn.Phase.playStep(Phase.java:203)
    at mage.game.turn.Phase.play(Phase.java:115)
    at mage.game.turn.Turn.play(Turn.java:140)
    at mage.game.GameImpl.playTurn(GameImpl.java:724)
    at mage.game.GameImpl.play(GameImpl.java:647)
    at mage.game.GameImpl.start(GameImpl.java:614)
    at mage.game.GameImpl.start(GameImpl.java:599)
    at mage.server.game.GameWorker.call(GameWorker.java:60)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.

**Comment by JayDi85** [comment]
That's error type still actual in server's logs with missing bookmark data.

Example 1:
ERROR 2020-07-16 01:12:12,036 It was not possible to do the requested undo operation (bookmark 2 does not exist) context: scry 1. <i>(Look at the top card of your library. You may put that card on the bottom of your library.)</i> Draw a card. =>[GAME cfec0e4d-3f43-4c86-a847-c83fc7036e71] GameImpl.restoreState
INFO  2020-07-16 01:12:12,037 Saved states: [0, 1]                                                                       =>[GAME cfec0e4d-3f43-4c86-a847-c83fc7036e71] GameImpl.restoreState

Example 2:
ERROR 2020-07-16 02:17:45,829 It was not possible to do the requested undo operation (bookmark 3 does not exist) context: draw three cards. =>[GAME 40f31ea5-8a0f-43fa-913d-8c5733dc74d3] GameImpl.restoreState
INFO  2020-07-16 02:17:45,830 Saved states: [0, 1, 2]                                                                    =>[GAME 40f31ea5-8a0f-43fa-913d-8c5733dc74d3] GameImpl.restoreState

Example 3:
ERROR 2020-07-17 19:17:41,167 It was not possible to do the requested undo operation (bookmark 2 does not exist) context:  =>[GAME 30cc9d1d-4e7f-481d-8e35-6fbfa66c5763] GameImpl.restoreState
INFO  2020-07-17 19:17:41,167 Saved states: [0, 1]                                                                       =>[GAME 30cc9d1d-4e7f-481d-8e35-6fbfa66c5763] GameImpl.restoreState

**Comment by JayDi85** [comment]
Error logs above related to #6937 (some cards or actions tries to disable cancel button but can broke player's bookmark). I think it fixed now.
