### ISSUE TITLE
Games room update exception

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#926]
```
FATAL 2015-04-19 22:39:58,740 Games room update exception! java.lang.IllegalArgumentException: Comparison method violates its general contract! =>[pool-7-thread-1] GamesRoomImpl$1.run
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(TimSort.java:773)
    at java.util.TimSort.mergeAt(TimSort.java:510)
    at java.util.TimSort.mergeCollapse(TimSort.java:437)
    at java.util.TimSort.sort(TimSort.java:241)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.ArrayList.sort(ArrayList.java:1454)
    at java.util.Collections.sort(Collections.java:175)
    at mage.server.game.GamesRoomImpl.update(GamesRoomImpl.java:99)
    at mage.server.game.GamesRoomImpl.access$000(GamesRoomImpl.java:65)
    at mage.server.game.GamesRoomImpl$1.run(GamesRoomImpl.java:81)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zerrisx** [comment]
@JayDi85 @LevelX2 

What should we do with old exception reports like this?  Are they worth keeping around for future investigation, or is there some time after which the software has changed enough that they're effectively obsolete?

**Comment by JayDi85** [comment]
Yes, code can be changes by years. So if old report (1+ years old) contains only exception error without use case description then it useless and can be closed.

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.

**Comment by JayDi85** [comment]
BTW all actual exception errors visible in server's logs. So literally no needs to report it without situation description.
