### ISSUE TITLE
Putting 100s of abilities on the stack at once will crash the server

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9302]
Reported a few times on the beta already.

Easiest way to reproduce, add 10-30 [[Sharding Sphinx]] to your board and a Platinum Angel to the AI so they won't lose the game.

When damage is deal this will put a few hundred triggers from the Sharing Sphinx on the board. This will cause the server to lock up a large amount of RAM (20 Sphinxes will lock up ~450MB of ram). This ram can't be CG'ed away until the stack empties.

Same effect can be seen, but easier to recreate, by filling the board up with many copies of a creature with landfall.

**Comment by Alex-Vasile** [comment]
From the log:
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1774)
	at java.util.HashMap.putVal(HashMap.java:632)
	at java.util.HashMap.put(HashMap.java:613)
	at mage.abilities.effects.EffectImpl.<init>(EffectImpl.java:46)
	at mage.abilities.effects.OneShotEffect.<init>(OneShotEffect.java:20)
	at mage.abilities.effects.common.CreateTokenEffect.<init>(CreateTokenEffect.java:60)
	at mage.abilities.effects.common.CreateTokenEffect.copy(CreateTokenEffect.java:71)
	at mage.abilities.effects.common.CreateTokenEffect.copy(CreateTokenEffect.java:25)
	at mage.abilities.effects.Effects.<init>(Effects.java:23)
	at mage.abilities.effects.Effects.copy(Effects.java:28)
	at mage.abilities.Mode.<init>(Mode.java:33)
	at mage.abilities.Mode.copy(Mode.java:42)
	at mage.abilities.Modes.<init>(Modes.java:58)
	at mage.abilities.Modes.copy(Modes.java:87)
	at mage.abilities.AbilityImpl.<init>(AbilityImpl.java:121)
	at mage.abilities.TriggeredAbilityImpl.<init>(TriggeredAbilityImpl.java:52)
	at mage.abilities.common.DealsDamageToAPlayerAllTriggeredAbility.<init>(DealsDamageToAPlayerAllTriggeredAbility.java:49)
	at mage.abilities.common.DealsDamageToAPlayerAllTriggeredAbility.copy(DealsDamageToAPlayerAllTriggeredAbility.java:59)
	at mage.abilities.common.DealsDamageToAPlayerAllTriggeredAbility.copy(DealsDamageToAPlayerAllTriggeredAbility.java:19)
	at mage.game.stack.StackAbility.<init>(StackAbility.java:70)
	at mage.game.stack.StackAbility.copy(StackAbility.java:379)
	at mage.game.stack.StackAbility.copy(StackAbility.java:45)
	at mage.game.stack.SpellStack.<init>(SpellStack.java:31)
	at mage.game.stack.SpellStack.copy(SpellStack.java:134)
	at mage.game.GameState.<init>(GameState.java:152)
	at mage.game.GameState.copy(GameState.java:299)
	at mage.game.GameStates.save(GameStates.java:24)
	at mage.game.GameImpl.saveState(GameImpl.java:746)
	at mage.game.GameImpl.bookmarkState(GameImpl.java:843)
	at mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:1524)
	at mage.game.GameImpl.checkTriggered(GameImpl.java:2051)
	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2005)
```

**Comment by Alex-Vasile** [comment]
So the memory issue is cased by two things:
1. Each time an ability is put on the stack, it's rules text is re-generated.
    - This puts a lot of pressure on the memory as hundreds of strings are created and recreated. Much of this unnecessary and can be cached since the ability rules do not change.
2. Before each ability is put on the stack, the entire game state is saved using bookmarking. This, combined with keeping an independent copy of each ability in memory results in the majority of the retained memory system.
    - I have no looked into the bookmark and rollback system yet, but this seems very inefficient (especially for when it is multiple copies of the same ability).

The simplest approach would be to only bookmark before putting the first ability on the stack. This will not address the memory used by the abilities on the stack (a different approach might be needed there, perhaps deduplicating abilities and only allocating memory for each copy when it reaches the top of the stack, or is interacted with), but it would remove the memory used by the save states (which is something like 60% of the retained memory). The downside of this approach is that if an error occurs while resolving the stack, the game will rollback to the full stack.

I personally see this as a worthwhile tradeoff (any error being raised is a bug that needs fixing anyway) but the current approach can cause the whole server to grind to a halt or crash due to a single game.

**Comment by JayDi85** [comment]
Test use case, also see unit test in `GameStatePerformanceTest`:
```
[init]
battlefield:Human:Forest:5
battlefield:Human:Plains:5
battlefield:Human:Mountain:5
battlefield:Human:Swamp:5
battlefield:Human:Island:5
hand:Human:Lightning Bolt:2

[test memory overflow]
@init
battlefield:Human:Sharding Sphinx:30
battlefield:Computer:Platinum Angel:30
hand:Human:Order // Chaos:1
```

Real reason of memory overflow -- wrong game state cleaning code on bookmark usage (xmage saves game state before resolve and must delete it on good resolve and restore on bad, but it don't - so each new resolve generates +1 game state and +2 Mb memory).

xxx must fix follow problems:
* big memory usage and performance in long games;
* big memory usage and server restarts on too much stack objects at once;

But there is still a game logic problem with too much triggers and logs/updates (500+ tokens creates one by one with users inform after each token -- it's slow, but works):
![shot_231014_153801](https://github.com/magefree/mage/assets/8344157/87f96263-9ca5-415c-b04d-d6f5fadbe99c)

Also I don't check/fix another usage of `bookmarkState` and `removeBookmark`, like mana payment. It can be affected too, but need code research and manual testing. See TODO in `removeBookmark_v2`.

**Comment by Alex-Vasile** [comment]
The original problem is that putting all of the triggers on the stack would use up a lot of ram.

While the code change fixes a bug and stops ram leakage, it does not resolve the original problem.

Even if the bookmark states are properly cleared after resolution, they still consume excessive ram in instances like this before resolution.

**Comment by JayDi85** [comment]
Yes, it fixed memory usage, not leak. Before fix 500 triggers used up to 1000 Mb memory. Now it uses 2 Mb.

**Comment by Alex-Vasile** [comment]
> Yes, it fixed memory usage, not leak. Before fix 500 triggers used up to 1000 Mb memory. Now it uses 2 Mb. Trigger instance takes only few know as normal java object. 

Ahh. My mistake, I misunderstood your message above. I thought that the commit was only about removeBookmark rather than also about significantly shrinking the memory usage of bookmarkState.
