### ISSUE TITLE
Xmage individual draft crash

### ISSUE THREAD

**Issue by radiasian** [magefree/mage#9314]
Hello!

This is radiasian from the XDHS server, we're the people who keep bugging you about old limited cards that no one else plays lmao.

We've had two separate people on separate days have an odd glitch where they start a draft, it works for everyone else but they only see the draft screen with no cards populated. They are unable to make picks, and their timer will run to zero and then nothing happens. While this is happening, the rest of the table is drafting as normal.

After we did drafting on a separate website, the two were able to log onto xmage and then play through a limited tournament with imported decks with no problems.

We tried restarting the first draft 3 times with no luck, and the next day twice for the second guy, also with no luck. The second guy received a "server error, Nullpointerexception".

We were drafting triple XLN, and the only other similarity was that both of the folks with problems installed xmage within the last 3 days from the time of this post and had never done a draft with us before.

Please let me know if there's any more information you want to grab, or any tests you'd like us to try running- as our server is dedicated to drafting we're eager to get this resolved.

Thanks in advance!

**Comment by Alex-Vasile** [comment]
Are you running the stable (xmage.de) or the beta (xmage.today)?

What else did the error say beyond Nullpointerexception? What was in the log?

**Comment by radiasian** [comment]
It's the beta client. Here are three logs from one of the players- the person didn't tell me what else was in the error, unfortuantely.


[mageclient-log-3.txt](https://github.com/magefree/mage/files/9176919/mageclient-log-3.txt)
[mageclient-log-2.txt](https://github.com/magefree/mage/files/9176920/mageclient-log-2.txt)
[mageclient-log-1.txt](https://github.com/magefree/mage/files/9176921/mageclient-log-1.txt)

**Comment by radiasian** [comment]
And here's a log from the other person with the problem
[mageclient-log-second.txt](https://github.com/magefree/mage/files/9185331/mageclient-log-second.txt)
:

**Comment by Alex-Vasile** [comment]
> And here's a log from the other person with the problem
> [mageclient-log-second.txt](https://github.com/magefree/mage/files/9185331/mageclient-log-second.txt)
> :

This one looks different. It looks like they're using the beta. Is mtg.pizza running a beta server?

**Comment by radiasian** [comment]
mtg.pizza is a currently runnign beta server. I'm uncertain why the log looks super different

**Comment by Alex-Vasile** [comment]
All three of the client files are variations on the following 3 errors:
```
Error 1:
FATAL 2022-07-24 11:47:26,607 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at javax.swing.text.html.ImageView.updateImageSize(Unknown Source)
	at javax.swing.text.html.ImageView.refreshImage(Unknown Source)
	at javax.swing.text.html.ImageView.sync(Unknown Source)
	at javax.swing.text.html.ImageView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.ParagraphView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.TableView$CellView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.TableView.checkSingleColumnCell(Unknown Source)
	at javax.swing.text.html.TableView.calculateColumnRequirements(Unknown Source)
	at javax.swing.text.html.TableView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getPreferredSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getPreferredSpan(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML$Renderer.<init>(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML.createHTMLView(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML.updateRenderer(Unknown Source)
	at javax.swing.plaf.basic.BasicLabelUI.propertyChange(Unknown Source)
	at javax.swing.plaf.synth.SynthLabelUI.propertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at javax.swing.JLabel.setText(Unknown Source)
	at mage.client.util.gui.GuiDisplayUtil.getDescription(GuiDisplayUtil.java:100)
	at mage.client.plugins.adapters.MageActionCallback.displayCardInfo(MageActionCallback.java:726)
	at mage.client.plugins.adapters.MageActionCallback.updateCardHints(MageActionCallback.java:502)
	at mage.client.plugins.adapters.MageActionCallback.mouseMoved(MageActionCallback.java:314)
	at org.mage.card.arcane.CardPanel.mouseMoved(CardPanel.java:728)
	at java.awt.Component.processMouseMotionEvent(Unknown Source)
	at javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Error 2:
FATAL 2022-07-24 11:49:40,600 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at javax.swing.text.html.ImageView.updateImageSize(Unknown Source)
	at javax.swing.text.html.ImageView.refreshImage(Unknown Source)
	at javax.swing.text.html.ImageView.sync(Unknown Source)
	at javax.swing.text.html.ImageView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.ParagraphView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.TableView$CellView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.TableView.checkSingleColumnCell(Unknown Source)
	at javax.swing.text.html.TableView.calculateColumnRequirements(Unknown Source)
	at javax.swing.text.html.TableView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getPreferredSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getPreferredSpan(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML$Renderer.<init>(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML.createHTMLView(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML.updateRenderer(Unknown Source)
	at javax.swing.plaf.basic.BasicLabelUI.propertyChange(Unknown Source)
	at javax.swing.plaf.synth.SynthLabelUI.propertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at javax.swing.JLabel.setText(Unknown Source)
	at mage.client.util.gui.GuiDisplayUtil.getDescription(GuiDisplayUtil.java:100)
	at mage.client.plugins.adapters.MageActionCallback.displayCardInfo(MageActionCallback.java:726)
	at mage.client.plugins.adapters.MageActionCallback.updateCardHints(MageActionCallback.java:502)
	at mage.client.plugins.adapters.MageActionCallback.mouseMoved(MageActionCallback.java:314)
	at org.mage.card.arcane.CardPanel.mouseMoved(CardPanel.java:728)
	at java.awt.Component.processMouseMotionEvent(Unknown Source)
	at javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Error 3:
java.lang.NullPointerException
	at javax.swing.text.html.ImageView.updateImageSize(Unknown Source)
	at javax.swing.text.html.ImageView.refreshImage(Unknown Source)
	at javax.swing.text.html.ImageView.sync(Unknown Source)
	at javax.swing.text.html.ImageView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(Unknown Source)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.ParagraphView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.TableView$CellView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.TableView.checkSingleColumnCell(Unknown Source)
	at javax.swing.text.html.TableView.calculateColumnRequirements(Unknown Source)
	at javax.swing.text.html.TableView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
	at javax.swing.text.BoxView.checkRequests(Unknown Source)
	at javax.swing.text.BoxView.getPreferredSpan(Unknown Source)
	at javax.swing.text.html.BlockView.getPreferredSpan(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML$Renderer.<init>(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML.createHTMLView(Unknown Source)
	at javax.swing.plaf.basic.BasicHTML.updateRenderer(Unknown Source)
	at javax.swing.plaf.basic.BasicLabelUI.propertyChange(Unknown Source)
	at javax.swing.plaf.synth.SynthLabelUI.propertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at javax.swing.JLabel.setText(Unknown Source)
	at mage.client.util.gui.GuiDisplayUtil.getDescription(GuiDisplayUtil.java:100)
	at mage.client.plugins.adapters.MageActionCallback.displayCardInfo(MageActionCallback.java:726)
	at mage.client.plugins.adapters.MageActionCallback.updateCardHints(MageActionCallback.java:502)
	at mage.client.plugins.adapters.MageActionCallback.mouseMoved(MageActionCallback.java:314)
	at org.mage.card.arcane.CardPanel.mouseMoved(CardPanel.java:728)
	at java.awt.AWTEventMulticaster.mouseMoved(Unknown Source)
	at java.awt.Component.processMouseMotionEvent(Unknown Source)
	at javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Alex-Vasile** [comment]
Based on your description it sounds like the draft starts without them, perhaps #9435 might help with this. 

I don't see anything in the logs that tell me WHY those UI errors are occurring or why they're not in the draft. next time this happens, It would be really helpful if you could get a hold of the server log from around the time issue occurs. Maybe that will have more info.

**Comment by radiasian** [comment]
will do next time, thanks!

**Comment by sprangg** [comment]
At least one of the players was running the client through the .bat file when the issue happened, and the issue stopped happening when they ran their client through the launcher. So this might have something to do with it. The used java version is probably not the same when running with the different methods.

**Comment by JayDi85** [comment]
* stream, serializable -- that's errors related to wrong client/server version;
* empty cards list, empty battlefield, empty draft and "random" NPE errors from a client side -- it's all related to wrong client/server data too;

If users used a beta client, but custom server deploys from a source code then all that problems are possible.

```
Caused by: java.io.StreamCorruptedException: invalid stream header: 6A627331
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at org.jboss.remoting.loading.ObjectInputStreamWithClassLoader.<init>(ObjectInputStreamWithClassLoader.java:100)
	at org.jboss.remoting.serialization.impl.java.JavaSerializationManager.createInput(JavaSerializationManager.java:54)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:75)
	at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.getMarshallingStream(SerializableUnMarshaller.java:58)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createInputStream(ClientSocketWrapper.java:206)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.createStreams(ClientSocketWrapper.java:189)
	at org.jboss.remoting.transport.socket.ClientSocketWrapper.<init>(ClientSocketWrapper.java:67)
```
