### ISSUE TITLE
Unable to connect to any server

### ISSUE THREAD

**Issue by gcaliber** [magefree/mage#9318]
Tried getting this working on linux. Launching server and client with java8.

Server
```
INFO  2022-07-25 10:00:16,947 Starting MAGE server version 1.4.50-V2 (build: 2021-09-05 18:59)                           =>[main] Main.main 
INFO  2022-07-25 10:00:16,948 Logging level: INFO                                                                        =>[main] Main.main 
INFO  2022-07-25 10:00:16,948 Default charset: UTF-8                                                                     =>[main] Main.main 
INFO  2022-07-25 10:00:16,949 Reading configuration from path=config/config.xml                                          =>[main] Main.main 
INFO  2022-07-25 10:00:17,072 Loading database...                                                                        =>[main] RepositoryUtil.bootstrapLocalDb 
INFO  2022-07-25 10:00:17,254 Done.                                                                                      =>[main] Main.main 
INFO  2022-07-25 10:00:17,254 Loading extension packages...                                                              =>[main] Main.main 
INFO  2022-07-25 10:00:17,254 Done.                                                                                      =>[main] Main.main 
INFO  2022-07-25 10:00:17,255 Loading cards...                                                                           =>[main] Main.main 
INFO  2022-07-25 10:00:22,710 Done.                                                                                      =>[main] Main.main 
INFO  2022-07-25 10:00:22,711 Updating user stats DB...                                                                  =>[main] Main.main 
INFO  2022-07-25 10:00:22,771 Done.                                                                                      =>[main] Main.main 
INFO  2022-07-25 10:00:22,882 Config - max seconds idle: 600                                                             =>[main] Main.main 
INFO  2022-07-25 10:00:22,882 Config - max game threads: 10                                                              =>[main] Main.main 
INFO  2022-07-25 10:00:22,882 Config - max AI opponents: 15                                                              =>[main] Main.main 
INFO  2022-07-25 10:00:22,882 Config - min usr name le.: 3                                                               =>[main] Main.main 
INFO  2022-07-25 10:00:22,883 Config - max usr name le.: 14                                                              =>[main] Main.main 
INFO  2022-07-25 10:00:22,883 Config - min pswrd length: 8                                                               =>[main] Main.main 
INFO  2022-07-25 10:00:22,883 Config - max pswrd length: 100                                                             =>[main] Main.main 
INFO  2022-07-25 10:00:22,884 Config - inv.usr name pat: [^a-z0-9_]                                                      =>[main] Main.main 
INFO  2022-07-25 10:00:22,884 Config - save game active: false                                                           =>[main] Main.main 
INFO  2022-07-25 10:00:22,884 Config - backlog size    : 200                                                             =>[main] Main.main 
INFO  2022-07-25 10:00:22,884 Config - lease period    : 5000                                                            =>[main] Main.main 
INFO  2022-07-25 10:00:22,884 Config - sock wrt timeout: 10000                                                           =>[main] Main.main 
INFO  2022-07-25 10:00:22,884 Config - max pool size   : 300                                                             =>[main] Main.main 
INFO  2022-07-25 10:00:22,885 Config - num accp.threads: 2                                                               =>[main] Main.main 
INFO  2022-07-25 10:00:22,885 Config - second.bind port: -1                                                              =>[main] Main.main 
INFO  2022-07-25 10:00:22,885 Config - auth. activated : false                                                           =>[main] Main.main 
INFO  2022-07-25 10:00:22,885 Config - mailgun api key :                                                                 =>[main] Main.main 
INFO  2022-07-25 10:00:22,885 Config - mailgun domain  :                                                                 =>[main] Main.main 
INFO  2022-07-25 10:00:22,885 Config - mail smtp Host  :                                                                 =>[main] Main.main 
INFO  2022-07-25 10:00:22,885 Config - mail smtpPort   :                                                                 =>[main] Main.main 
INFO  2022-07-25 10:00:22,886 Config - mail user       :                                                                 =>[main] Main.main 
INFO  2022-07-25 10:00:22,886 Config - mail passw. len.: 0                                                               =>[main] Main.main 
INFO  2022-07-25 10:00:22,886 Config - mail from addre.:                                                                 =>[main] Main.main 
INFO  2022-07-25 10:00:22,886 Config - google account  :                                                                 =>[main] Main.main 
INFO  2022-07-25 10:00:22,886 Loaded game types: 16, tourneys: 17, players: 3, cubes: 46, decks: 51                      =>[main] Main.main 
INFO  2022-07-25 10:00:23,021 Started MAGE server - listening on 0.0.0.0:17171/?serializationtype=jboss&maxPoolSize=300  =>[main] Main.main
```

Client
```
INFO  2022-07-25 10:15:36,941 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2022-07-25 10:15:36,941 Default charset: UTF-8                                                                     =>[main] MageFrame.main 
INFO  2022-07-25 10:15:37,593 Using GUI theme: Default                                                                   =>[AWT-EventQueue-0] PreferencesDialog.getCurrentTheme 
INFO  2022-07-25 10:15:37,600 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2022-07-25 10:15:37,810 Images: search broken files...                                                             =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2022-07-25 10:15:37,975 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2022-07-25 10:15:38,233 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2022-07-25 10:15:38,255 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2022-07-25 10:15:38,300 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2022-07-25 10:15:38,301 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2022-07-25 10:15:38,301 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 

(java:12252): Gtk-WARNING **: 10:15:38.458: Unable to locate theme engine in module_path: "adwaita",
INFO  2022-07-25 10:15:38,715 Client start up time: 1 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2022-07-25 10:16:07,960 Connect: connecting to server localhost:17171                                              =>[SwingWorker-pool-5-thread-4] SessionImpl$5.work 
WARN  2022-07-25 10:16:38,045 Cannot connect                                                                             =>[SwingWorker-pool-5-thread-3] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
        at org.jboss.remoting.Client.connect(Client.java:1928)
        at org.jboss.remoting.Client.connect(Client.java:737)
        at mage.remote.SessionImpl$5.work(SessionImpl.java:415)
        at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
        at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.Exception: Error setting up client lease
        at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
        at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
        at org.jboss.remoting.Client.connect(Client.java:1924)
        ... 10 more
Caused by: org.jboss.remoting.InvocationFailureException: Socket timed out.  Waited 29991 milliseconds for response while calling on InvokerLocator [bisocket://192.168.1.20:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=jboss]; nested exception is: 
        java.net.SocketTimeoutException: Read timed out
        at org.jboss.remoting.transport.socket.SocketClientInvoker.handleException(SocketClientInvoker.java:137)
        at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.handleOtherException(MicroSocketClientInvoker.java:1104)
        at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:966)
        at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
        at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
        at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
        ... 12 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.jboss.serial.io.JBossObjectInputStream.read(JBossObjectInputStream.java:193)
        at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.readVersion(MicroSocketClientInvoker.java:1366)
        at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:920)
        ... 15 more
INFO  2022-07-25 10:16:38,065 Disconnecting DONE                                                                         =>[SwingWorker-pool-5-thread-3] SessionImpl.disconnect 
INFO  2022-07-25 10:16:38,067 Disconnected from user mode                                                                =>[SwingWorker-pool-5-thread-3] MageFrame.disconnected 

```

**Comment by Alex-Vasile** [comment]
Try the beta. The stable hasn't been updated in a long time and should be ignored until it is updated

**Comment by gcaliber** [comment]
Thanks @Alex-Vasile
