### ISSUE TITLE
Program freezes....was working fine

### ISSUE THREAD

**Issue by EmblemMan** [magefree/mage#948]
I downloaded this today and got the hang of it and went to eat dinner got back on and itll open a window with a half loaded blue screen and freeze and not respond. Just want to know if this is my fault and/or how to fix it.

**Comment by LevelX2** [comment]
I guess you striggeling with this problem:

Since the woogerworks server moved to a new server 2 or 3 weeks ago, it happens often that starting sometime during the day it's no longer possible to connect to the server. As the XMage server is restarted at 10:00 CET (or manually restarted) it starts to work again.

The problem is caused from a specific behaviour of the woogerworks server, that causes the XMage server to hang while trying to connect to the server. I'm investigating this and will fix the client behaviour if possible with a next update so he shows a "Cannot connect" message after a timeout and you can connect to another server in this situation.

What can you do meanwhile:
Set the "Automatically connect to this server next time" to off. (You can do it after disconnecting from a successful connection to a server and calling again connect or by changing it in the java prefs (windows registry). So you have the chance to connect to another server after canceling the XMage client and restarting it again.

**Comment by LevelX2** [comment]
The error message the problem produces.
```
INFO  2015-05-03 23:16:23,305 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2015-05-03 23:16:23,358 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2015-05-03 23:16:23,363 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2015-05-03 23:16:23,739 Client start up time: 1 seconds                                                            =>[AWT-EventQueue-0] MageFrame$6.run 
INFO  2015-05-03 23:17:14,614 Connect was canceled                                                                       =>[AWT-EventQueue-0] ConnectDialog$ConnectTask.done 
FATAL 2015-05-03 23:17:23,582 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
FATAL 2015-05-03 23:21:31,331                                                                                            =>[SwingWorker-pool-4-thread-2] SessionImpl.connect 
org.jboss.remoting.InvocationFailureException: Unable to perform invocation; nested exception is: 
	java.io.EOFException: end of file
	at org.jboss.remoting.transport.socket.SocketClientInvoker.handleException(SocketClientInvoker.java:146)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:981)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.addCallbackListener(Client.java:2153)
	at org.jboss.remoting.Client.addListener(Client.java:1258)
	at org.jboss.remoting.Client.addListener(Client.java:1144)
	at org.jboss.remoting.Client.addListener(Client.java:1127)
	at mage.remote.SessionImpl.connect(SessionImpl.java:265)
	at mage.remote.SessionImpl.connect(SessionImpl.java:134)
	at mage.client.MageFrame.connect(MageFrame.java:686)
	at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:357)
	at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:347)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException: end of file
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:923)
	... 18 more
INFO  2015-05-03 23:21:31,337 DISCONNECT (still connected)                                                               =>[pool-1-thread-1] SessionImpl.disconnect 
INFO  2015-05-03 23:21:32,681 Disconnected ...                                                                           =>[pool-1-thread-1] SessionImpl.disconnect 
INFO  2015-05-03 23:21:32,683 DISCONNECTED (NO Event Dispatch Thread)                                                    =>[pool-1-thread-1] MageFrame.disconnected
```
