### ISSUE TITLE
TargetDefender.canTarget => java.lang.NullPointerException

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#951]
FATAL 2015-05-03 08:01:17,181 GameWorker general exception [a0e352ef-291c-4baf-9017-2533a22131c7]null                    =>[GAME a0e352ef-291c-4baf-9017-2533a22131c7] GameWorker.call
java.lang.NullPointerException
	at mage.target.common.TargetDefender.canTarget(TargetDefender.java:201)
	at mage.target.common.TargetDefender.canTarget(TargetDefender.java:217)
	at mage.player.human.HumanPlayer.chooseTarget(HumanPlayer.java:323)
	at mage.game.combat.Combat.checkAttackRequirements(Combat.java:264)
	at mage.game.combat.Combat.selectAttackers(Combat.java:212)
	at mage.game.turn.DeclareAttackersStep.beginStep(DeclareAttackersStep.java:62)
	at mage.game.turn.Phase.prePriority(Phase.java:187)
	at mage.game.turn.Phase.playStep(Phase.java:201)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:140)
	at mage.game.GameImpl.playTurn(GameImpl.java:738)
	at mage.game.GameImpl.play(GameImpl.java:661)
	at mage.game.GameImpl.start(GameImpl.java:628)
	at mage.game.GameImpl.start(GameImpl.java:613)
	at mage.server.game.GameWorker.call(GameWorker.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by LevelX2** [comment]
Fixed.

**Comment by LevelX2** [comment]
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&p=178391#p178391

But why can the source now null?

**Comment by TheFirecat** [comment]
The nullpointerexception issue also occurs when ones cursor hovers over a card during play. Keep seeing people suggesting messing with the cmd consol, but the only way to get to it is upon startup of the program?
