### ISSUE TITLE
[NEO] Explosive Singularity NPE

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9618]
AI tried to play [[Explosive Singularity]] from a randomly generated deck.

```
java.lang.NullPointerException
at mage.cards.e.ExplosiveSingularityEffect.apply(ExplosiveSingularity.java:74)
at mage.abilities.effects.ContinuousEffects.costModification(ContinuousEffects.java:741)
at mage.abilities.AbilityImpl.activate(AbilityImpl.java:394)
at mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:257)
at mage.game.stack.Spell.activate(Spell.java:142)
at mage.players.PlayerImpl.cast(PlayerImpl.java:1236)
at mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1494)
```

**Comment by awjackson** [comment]
The way this card's cost modifier has been implemented cannot possibly work. It uses the "tappedPermanents" value which is set in `TapTargetCost.pay`, but costs are not paid (`pay` is not called) until *after* cost modifications have been applied. It needs to be refactored to work like other cards with similar optional costs.
