### ISSUE TITLE
[Linux] Sound fails when another application is playing sound

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#9713]
I just caught this error in the Client logs when starting the game while I was watching a YouTube video in Firefox.  Closing Firefox and then restarting XMage resolved the issue.  Also (strangely) if I start XMage first, XMage sound works but then Firefox refuses to start playing videos in YouTube.

I think this issue could be fixed by supporting PulseAudio as a sound backend.  I think currently it's using ALSA directly since XMage does not show up in my PulseAudio sound mixer.  Using ALSA directly can have this issue where applications fight over usage of the sound card.  I'll look into this a bit further.

```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:412)
	at mage.client.util.audio.LinePool.lambda$playSound$1(LinePool.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

EDIT: Reproduced with mpv (a video player) as well so it's not just Firefox.

**Comment by weirddan455** [comment]
Well I found the easy solution.  I was missing a package `pulseaudio-alsa` on Arch Linux that forces ALSA applications to go through Pulse instead of getting exclusive access to the sound card.  Installing that lets sound work concurrently with other applications.

I think it would still be beneficial to have a PulseAudio backend on Linux but I looked at the audio code and XMage is just using Java's sound API.  There may be a way to configure Java to use pulse by editing sound.properties (located at /etc/java-8-openjdk/sound.properties on my machine) but results I found from searching were outdated (referencing IcedTea packages that aren't usually installed by distros anymore).

So I guess this may be "not an XMage bug" unless we want to use some other library for sound support which is probably more trouble than it's worth.
