### ISSUE TITLE
Deck with only Double Faced Lands Causes random NPE

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9742]
"I am playing decks with no lands and only double face land cards like belcher"

"It happens randomly." Sometimes they can play a full game before it shows up.

Top of the error:
```
FATAL 2022-11-04 13:13:59,689 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.NullPointerException
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$0(CallbackClientImpl.java:230)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:172)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at mage.client.dialog.MageDialog.setVisible(MageDialog.java:89)
	at mage.client.dialog.UserRequestDialog.showDialog(UserRequestDialog.java:78)
	at mage.client.MageFrame.showUserRequestDialog(MageFrame.java:1241)
	at mage.client.MageFrame.showError(MageFrame.java:1515)
	at mage.client.remote.CallbackClientImpl.handleException(CallbackClientImpl.java:633)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$0(CallbackClientImpl.java:444)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at mage.client.dialog.MageDialog.startModal(MageDialog.java:172)
	at mage.client.dialog.MageDialog.show(MageDialog.java:83)
```

Full error file: [npe.txt](https://github.com/magefree/mage/files/9947586/npe.txt)

Two decks that cause the issue to occur:
[1-LAND_TWIDDLE_STORM.txt](https://github.com/magefree/mage/files/9947587/1-LAND_TWIDDLE_STORM.txt)
[BELCHER.txt](https://github.com/magefree/mage/files/9947588/BELCHER.txt)

**Comment by Alex-Vasile** [comment]
"The problem is usually caused by [[Recross the Paths]] and [[Goblin Charbelcher]]"

"then if i quit the match and start another one it suddenly appears the NullPointerException before I draw the initial 7"

**Comment by Susucre** [comment]
Recross the Path's issue was a MageObject being sent in a client-side message during resolution, which could not be deserialized client side. Goblin Charbelcher may have a similar issue.

**Comment by JayDi85** [comment]
Not actual in current master. Client side gets only xxxView and some simple/shared classes, not a real game objects. There are verify tests to check it too (if some server side data return to the client).
