### ISSUE TITLE
[BRO] Slagstone Refinery is bugged.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#9755]
[[Slagstone Refinery]] is quite buggy in its first implementation:

- Does not trigger on other non-token artifacts, but does trigger a token artifact (I would have add that missing `!` myself as a PR if that was the only issue)
- On sacrificing a token artifact, there is immediatly a new trigger in the stack, which creates a new powerstone. Leading to an infinite trigger + powerstone creation.
- Passing the turn with the Refinery in play leads to a breaking game error:
```
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.52-V1-beta9 (build: 2022-11-12 06:32)
mage.game.GameImpl.playPriority(GameImpl.java:1591)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Comment by Susucre** [comment]
```
GameImpl.playPriority 
java.lang.NullPointerException
	at mage.cards.s.SlagstoneRefineryTriggeredAbility.checkTrigger(SlagstoneRefinery.java:65)
	at mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
	at mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:55)
	at mage.game.GameState.handleEvent(GameState.java:815)
	at mage.game.GameState.handleSimultaneousEvent(GameState.java:788)
	at mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2018)
	at mage.game.GameImpl.playPriority(GameImpl.java:1530)
	at mage.game.turn.Step.priority(Step.java:61)
	at mage.game.turn.Phase.playStep(Phase.java:184)
	at mage.game.turn.Phase.play(Phase.java:89)
	at mage.game.turn.Turn.play(Turn.java:132)
	at mage.game.GameImpl.playTurn(GameImpl.java:1056)
	at mage.game.GameImpl.play(GameImpl.java:966)
	at mage.game.GameImpl.start(GameImpl.java:942)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
should be more helpful for the game error issue.

**Comment by theelk801** [comment]
no idea what's causing the weird loop but I'll at least fix the nontoken clause for now

**Comment by weirddan455** [comment]
Parenthesis is wrong in that `checkTrigger` function I think.  I believe everything after the final `&&` needs to be enclosed in an additional set of parens.

**Comment by Susucre** [comment]
Indeed, all the weird behavior I did observe could be because of calling `.getTarget()` (or that `.getTarget()` is null) on unrelated events.

Will test the change locally, and come back with a PR if that fixes the issue.
